### ISSUE TITLE
computeExpr_antagonist     error 

### ISSUE THREAD

**Issue by tuqiang2014** [sqjin/CellChat#1]
CellChat/R/modeling.R  file  372 line 
computeExpr_antagonist  function   
```
 data.antagonist = matrix(1, nrow = 1, ncol = length(group))   
```
should be ? 

```
  data.antagonist = matrix(1, nrow = 1, ncol = length(unique(group)))
```

When I  use `Seurat`  packages  data `pbmc3k.final`  to  run  `CellChat ` in  linux .  The process of debug  as  follow: 

https://www.jianshu.com/p/da145cff3d41

Thanks  for  your great  jobs.

**Comment by sqjin** [comment]
@tuqiang2014 Thanks for reporting this bug. Your solution is totally correct! The code has been updated now.
