### ISSUE TITLE
A question about function of netvisual_bubble

### ISSUE THREAD

**Issue by MMriran** [sqjin/CellChat#10]
Hi,  thanks for developing this user-friendly tool. When I used the netvisual_bubble function to draw the communication pairs, I had some questions about the parameters of this functions. what do the “from” and
"to" mean? Should it be a cell type name？Moreover, how can I set a proper  vertex.receiver for  hierarchy plot？
（ps：I think the function of vertex.receive is to provide a fancier layout of the hierarchy plot？ ）

**Comment by sqjin** [comment]
Hi @MMriran, you can check the documentation of this function. Currently it only supports a numerical vector giving the index of source or target cell groups (based on the order of cell group defined in cellchat@identity). So you cannot input the cell type names. For the vertex.receiver, I usually set it based on the biological questions to address. For example, if you want to study the interactions between dermal and epidermal cells, then I will put all dermal subpopulations as vertex.receiver (i.e., on one side). Such special group order allows to easily check the interactions from dermal to epidermal cells and vice verse.

**Comment by MMriran** [comment]
thank you for your kind reply. So can I run the netvisual_bubble as follows：
netVisual_bubble(
  cellchat, ###the object name of cellchat
  from=7,   ########does it mean that I just need to input  a numer？
  to=8,
  pairLR.use0 = NULL,
  color.heatmap = viridis::viridis(50),
  thresh = 0.05
)

**Comment by sqjin** [comment]
@MMriran You need to run `cellchat <- rankNetPairwise(cellchat)` before calling `netVisual_bubble`. Yes, from/to can be a single number or a numerical vector.

**Comment by MMriran** [comment]
thank you for your reply!  CellChat was a really useful package！

**Comment by MMriran** [comment]
Hi, sqjin, I'm sorry for disturbing you again. I had another questions about the cellchat. how can I draw a picture like that ？
<img width="327" alt="67493d048bbc340e964268d6eed5ae9" src="https://user-images.githubusercontent.com/51091889/89122459-dd1f9080-d4f9-11ea-83a8-64770bc94886.png">

Is there some code that I can directly used to draw the circle  plot like that? Or how can I get the detailed information about  interaction pairs(including the pairs and their strength) between each cell group so that I can draw circle plot？

**Comment by sqjin** [comment]
Hi @MMriran , CellChat does not support such circle plot. However, the bubble plot in CellChat provides similar information as in such circle plot. Thus you can get some useful information from the code of netVisual_bubble function. Here are some key information: `pairwiseLR <- object@net$pairwiseRank
pairwiseLR_ij <- pairwiseLR[[from[i]]][[to[j]]]
pval_ij <- pairwiseLR_ij$pval
prob_ij <- pairwiseLR_ij$prob`

prob is the communication strength and pval is the p-value. Please check the codes for details.

**Comment by MMriran** [comment]
Thanks your answer.  And I had another question about the netVisual_bubble function. I noticed that the bubble plot in 
netVisual_bubble function only showed the 'to' cell goups in X axis.  Is there any resolutions that  I  can draw a bubble plot that show the “from” cell groups in X axis？ Just like the following picture shown:

![image](https://user-images.githubusercontent.com/51091889/89191475-90a98300-d5d5-11ea-89ae-bda1f4816ba9.png)

**Comment by sqjin** [comment]
@MMriran I just find that the current code only can work well for a single cell group defined in 'from' and I will update the code later.

**Comment by MMriran** [comment]
@sqjin , thank you for your reply. I am looking forward to the new “CellChat”.

**Comment by sqjin** [comment]
@MMriran The netVisual_bubble function has been updated. Moreover, it supports the input of both numerical vector and char vector with cell group names.

**Comment by MMriran** [comment]
@sqjin . thank you for your work. however, I found if I used the new function of netvisual bubble, I got a blank plot like this：
![image](https://user-images.githubusercontent.com/51091889/89726684-d17b1f00-da4f-11ea-9ff0-7b70b51f8aeb.png)




 and The  warning message was ：Warning message:
In max(prob + 1) : no non-missing arguments to max; returning -Inf.  How can solve this problems？ Need I to run the cellchat from  create the cellchat object？

**Comment by sqjin** [comment]
@MMriran Most likely you have not run `object <- rankNetPairwise(object)`. I have added a message in the code to remind such a run.

**Comment by ruohuchengxhe** [comment]
> @sqjin Hi, this tool is awesome!  Is it possible to plot multiple groups of 'to' cells? I can only plot one now.
Besides, I can only use numerical vector as input but not char vector (I'm using 0.0.1, I suppose this is the new one?)
Thanks in advance!

**Comment by sqjin** [comment]
@ruohuchengxhe Yes! I updated the function for bubble plot to make it more flexible two hours ago. You might can re-install the package. You can do it as `netVisual_bubble(cellchat, from = c(1,2), to = c(3,4))` or `netVisual_bubble(cellchat, from = c("FIB-A","FIB-B"), to = c("FIB-C","FIB-D"))`.

**Comment by ruohuchengxhe** [comment]
> @ruohuchengxhe Yes! I updated the function for bubble plot to make it more flexible two hours ago. You might can re-install the package. You can generate the bubble plot using `netVisual_bubble(cellchat, from = c(1,2), to = c(3,4))` or `netVisual_bubble(cellchat, from = c("FIB-A","FIB-B"), to = c("FIB-C","FIB-D"))`.

I tried to re-install, I can use char for single groups now.  But it looks like the 'from' and 'to' must have the same length and the 'to' cannot have more than one cell group. So I'm back to 1 vs 1.
Here's what happened:

`netVisual_bubble(cellchat, from =c(1,2), to =(3))`
`Error in netVisual_bubble(cellchat.lig, from = c(1, 2), to = (3)) : 
  The length of 'from' and 'to' must be the same!`

`netVisual_bubble(cellchat, from =c(1,2), to =(3,4))`
`Error: unexpected ',' in "netVisual_bubble(cellchat, from =c(1,2), to =(3,"`

**Comment by sqjin** [comment]
@ruohuchengxhe You made a mistake! It is `to = c(3,4)`, NOT `to = (3,4)`

**Comment by ruohuchengxhe** [comment]
> @ruohuchengxhe You made a mistake! It is `to = c(3,4)`, NOT `to = (3,4)`

True!!Stupid me! Thanks!!

**Comment by MMriran** [comment]
thank you for your patience and great work！！！！！！

**Comment by whcarson** [comment]
Is there a way for me to change the organization of the x-axis on the bubble plot in order to more clearly distinguish the major inputs to a cell type? Since the x-axis is organized as 1->1, 1->2, 1->3 in adjacent columns, it makes it easy to visually assess the major outputs of cell type 1, but less easy to assess the major inputs to a given cell class. In other words, I'd like to generate a plot that shows 1->1, 2->1, 3->1, adjacent to each other. Thank you!

**Comment by sqjin** [comment]
@whcarson Currently it does not support such setting. Can you help to implement such functionality?

**Comment by wanglu2014** [comment]
> Thanks your answer. And I had another question about the netVisual_bubble function. I noticed that the bubble plot in netVisual_bubble function only showed the 'to' cell goups in X axis. Is there any resolutions that I can draw a bubble plot that show the “from” cell groups in X axis？ Just like the following picture shown:
> 
> ![image](https://user-images.githubusercontent.com/51091889/89191475-90a98300-d5d5-11ea-89ae-bda1f4816ba9.png)

How to group the Tumer with vertical line, and change the color of labels.
