### ISSUE TITLE
How can we specificly visualize one ligand-receptor pair in one pathway?

### ISSUE THREAD

**Issue by l-magnificence** [sqjin/CellChat#101]
When we run netVisual_individual in a specific pathway , because of too many ligand-receptor pair are in it, the figure margins are too large to be visualized. So how can we subset a one ligand-receptor pair to be visualized via circle or hierarchy plot?

**Comment by sqjin** [comment]
Hi @l-magnificence , please check our new tutorial on how to do it using network_visual_individual

**Comment by l-magnificence** [comment]
excellent work！
