### ISSUE TITLE
Question about the rankNet function

### ISSUE THREAD

**Issue by charlesgwellem** [sqjin/CellChat#103]
Can the rankNet() function be made to produce graphs where one can see differences in interaction pathways per cell type and across conditions? if not, is there any such possibility where one can visualise pathway differences per cell type and across two conditions?

**Comment by sqjin** [comment]
Hi @charlesgwellem , I have created a function fro such analysis and will update the Github in next two days. A significantly enhanced tutorial on the comparison analysis will be included. Please stayed tuned.

**Comment by charlesgwellem** [comment]
Wow. Am anxiously looking forward to that. Will the updates be here or you make a separate tutorial?

Sent from Yahoo Mail on Android 
 
  On Mon, 4 Jan 2021 at 18:35, sqjin<notifications@github.com> wrote:   


Hi @charlesgwellem , I have created a function fro such analysis and will update the Github in next two days. A significantly enhanced tutorial on the comparison analysis will be included. Please stayed tuned.

**Comment by sqjin** [comment]
@charlesgwellem Tutorial has been updated now!
