### ISSUE TITLE
How to draw Figure 5g n your paper?

### ISSUE THREAD

**Issue by zhang0818k** [sqjin/CellChat#104]
Hi,
Thank you for developing CellChat, it's a great work.
I'm interested in Figure 5g   in your paper (show below), but I can't find the method to achieve it both in Methods and Vignettes (tutorials). Is it generated by CellChat or other tools? Could you please tell me how to draw it?
Thanks again!
![image](https://user-images.githubusercontent.com/75205193/103596888-e7770800-4f39-11eb-91f1-ed96b487aa91.png)

**Comment by sqjin** [comment]
@zhang0818k It is created by `rankNet` function. We will release a new version of CellChat as well as full tutorials in next two days. Please stay tuned.

**Comment by zhang0818k** [comment]
@sqjin Got it, thank you!
