### ISSUE TITLE
namespace 'circlize' 0.4.11 is already loaded, but >= 0.4.12 is required

### ISSUE THREAD

**Issue by lxwang326** [sqjin/CellChat#106]
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace 'circlize' 0.4.11 is already loaded, but >= 0.4.12 is required
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
停止执行
ERROR: lazy loading failed for package 'CellChat'
* removing 'C:/Users/Nano/Documents/R/win-library/4.0/CellChat'
Warning in install.packages :
  installation of package ‘C:/Users/Nano/Desktop/CellChat_0.5.0.tar.gz’ had non-zero exit status

i check the CRAN  there is no 0.4.12 available. the latest is 0.4.11

**Comment by sqjin** [comment]
@lxwang326 I just change the requirement of the version. But I suggest to use 0.4.12 and please see README file
