### ISSUE TITLE
Error in createCellChat object

### ISSUE THREAD

**Issue by lyuguol** [sqjin/CellChat#108]
Dear CellChat developers,

I am following your tutorial to do cell-cell communication analysis with my Seurat(V3) data. However, I encountered an error at the first step, and did not figure out why and how to solve it.

Here is how I prepare the data:

data.input <- GetAssayData(scRNA, assay = "RNA", slot = "data")
labels <- Idents(scRNA)
meta <- data.frame(group = labels, row.names = names(labels))
cellchat <- createCellChat(object = data.input, meta = meta, group.by = "labels")

Create a CellChat object from a data matrix
Error in createCellChat(object = data.input, meta = meta, group.by = "labels") : 
  The 'group.by' is not a column name in the `meta`, which will be used for cell grouping.

Could you show me how to fix this problem?

Many thanks and best,

Guoliang

**Comment by sqjin** [comment]
Hi @lyuguol , you should do `meta <- data.frame(labels = labels, row.names = names(labels))`. You can also directly pass a Seurat object to `createCellChat` by setting 'group.by = "ident"'. please check the example given in this function.

**Comment by lyuguol** [comment]
> Hi @lyuguol , you should do `meta <- data.frame(labels = labels, row.names = names(labels))`. You can also directly pass a Seurat object to `createCellChat` by setting 'group.by = "ident"'. please check the example given in this function.

Many thanks for the quick reply!!!!!
Indeed, solved my problem!!

Best,

Guoliang
