### ISSUE TITLE
Problem plotting

### ISSUE THREAD

**Issue by MeiShuhao** [sqjin/CellChat#109]
Dear Dr. Jin

Thanks a lot for your useful tools. I ran into a problem using CellChat 5.0.  when I used netVisual_aggregate to draw the Hierarchy plot, the edge weights were not proportional to the interaction strength. Their width were the same. This problem also can be seen in your tutorial.
![image](https://user-images.githubusercontent.com/77151495/104009413-f550b580-51e5-11eb-9f87-b50f77c8944f.png)
While it works well in circle plot and netVisual_individual.
Thanks a lot for your help.

**Comment by sqjin** [comment]
@MeiShuhao It should be fixed now.
