### ISSUE TITLE
Issue with truncated cell type labels when running subsetCommunication at the pathway level

### ISSUE THREAD

**Issue by jv-20** [sqjin/CellChat#112]
Hi Suoqin, 

Many thanks for the updated version and tutorial. I tried to run `subsetCommunication` function both at the LR level and pathway level. It works fine at the LR level, but however at the pathway level, I have two issues. 

1. The source and target names are truncated
2. There is one single value 0.56 in the p.value column for all the rows

My celltype labels have the following format in the names (01_CT1_FIB, 02_CT2_DC1,03_CT2_DC3).  It seems the source column has the first text before the delimiter "_" and target column has the second text after the delimiter "_". I attach a sample of my result table below for reference. 

It would be really great, if you could please advise what could be the reason for truncated names in the source and target columns and single p.value for all the pathways.

`subsetCommunication(object,thresh=0.05,slot.name = "netP") `

![image](https://user-images.githubusercontent.com/68548237/104208311-7a2b1180-5428-11eb-9c8f-ed6803742a22.png)

Thank you

**Comment by sqjin** [comment]
Hi @jv-20 , the bugs are fixed and it should works for your case now.

**Comment by jv-20** [comment]
Many thanks for fixing this so quickly Suoqin. You are amazing! Thanks a lot, it is working properly now

**Comment by jv-20** [comment]
Hi @sqjin , One other small request. Is it possible to have scientific notation in p-value column. Some of the p-values are small and it is reported as 0. I think this could be because of the formatting applied in the p-value column. Thank you.

**Comment by sqjin** [comment]
@jv-20 The p-value is directly computed from 100 permutations. Thus we do not have a scientific notation. Lots of pvalues are zeros.

**Comment by jv-20** [comment]
Hi @sqjin, that's grand. Thank you
