### ISSUE TITLE
L-R pair Contribution: netAnalysis_contribution "1" in LR.contribution$name

### ISSUE THREAD

**Issue by GildasLepennetier** [sqjin/CellChat#113]
Dear cellChat devel.

I want to sort the contribution be relative importance.
I have a weird name when running the netAnalysis_contribution: "1" with 0.000 as relative contribution.

[https://i.postimg.cc/VLQnJk32/Capture.jpg](https://i.postimg.cc/VLQnJk32/Capture.jpg)

The figure displayed is good though: [https://i.postimg.cc/DyrsLKh0/Capture2.jpg](https://i.postimg.cc/DyrsLKh0/Capture2.jpg)

What I want ultimately is just to reorder this way: [https://i.postimg.cc/RZvtTbCR/Capture3.jpg](https://i.postimg.cc/RZvtTbCR/Capture3.jpg)

I can indeed remove it, but wanted to ask if this "1" is there on purpose.

Best!

**Comment by sqjin** [comment]
Hi @GildasLepennetier , the row with contribution being zero is a fake data that is created for plotting (to produce a suitable bar width). The updated codes now return a data frame without these fake data.  The L-R pairs are also sorted based on their contribution now.

**Comment by GildasLepennetier** [comment]
Amazing! I think it improve the display thit way. Thanks to be so reactive.

**Comment by sqjin** [comment]
@GildasLepennetier It is now updated in Github.

**Comment by GildasLepennetier** [comment]
Hi, thanks.
The ordering is actually not working. Did you order the values of the contribution?
ggplot is actually taking the order of the name (factors) so I am doing as follow to have ggplot understand what I want:

`SIGNALING=cellchat@netP$pathways
CONTRIB=netAnalysis_contribution(cellchat,signaling=SIGNALING,thresh=0.05,return.data=T,font.size=12)
CONTRIB$LR.contribution$name = factor(CONTRIB$LR.contribution$name,levels=CONTRIB$LR.contribution$name[order(CONTRIB$LR.contribution$contribution)])`

(this factor ordering assume that the names are unique, which is true here)
