### ISSUE TITLE
Absence of interaction strength

### ISSUE THREAD

**Issue by charlesgwellem** [sqjin/CellChat#115]
Thanks a lot for your wonderful and helpful tool. Could there be a reason why my interaction strength value is 0, when comparing the interactions in two data sets?

```

gg1 <- compareInteractions(cellchat, show.legend = F, group = c(1,2))
gg2 <- compareInteractions(cellchat, show.legend = F, group = c(1,2), 
                           measure = "weight")

gg1 + gg2
```

![grafik](https://user-images.githubusercontent.com/10155881/104440166-4cfa7280-5592-11eb-8c71-10596b0a135f.png)

**Comment by sqjin** [comment]
@charlesgwellem ，can you check cellchat[[1]]@net$weight to see if you have the data? Note that you should update you CellChat object if you have not done.

**Comment by charlesgwellem** [comment]
@sqjin I get the error: 

```
saline_chat[[1]]@net$weight
>Error in saline_chat[[1]] : this S4 class is not subsettable
```
I did reinstall with `devtools::install_github("sqjin/CellChat")` and I am able to load it.

**Comment by charlesgwellem** [comment]
@sqjin  I think I found the problem. Inside the _compareInteractions_ function, this part of code: `df[, 1] <- round(df[, 1], 1)` will round the weight values to 1 decimal place. If the values are much smaller, e.g. 0.002, the weights will be rounded to 0 and that was my problem. I do not know if it will make any sense to make a possibility for a user to be able to chose the number of decimal places for this function.

**Comment by siqi-zZ** [comment]
hi,like this question, if I have not cellchat[[1]]@net$weight in merger cellchat, how can I redo to got 'weight' ? Thank you

**Comment by sqjin** [comment]
@siqi-zZ You can simply rerun the function `aggregateNet`

**Comment by RuiyuRayWang** [comment]
@charlesgwellem Hi, I have the same problem.
In my `cellchat` object, almost all slots in `cellchat@net$weight` are values close to zero, which doesn't make sense.
I'm doubting whether this could be a but or not, see #165 

I also re-run `computeCommunProb()` with `population.size = FALSE` but the issue persisted. Have you resolved your issue? @sqjin Could you help us find out what might have happened? Thanks!

**Comment by sqjin** [comment]
@RuiyuRayWang No need to care about the absolute values in the cellchat. Indeed, most of values in cellchatt are very small, but you can still compare the signaling.

**Comment by liucong-epi** [comment]
@charlesgwellem  Hi, what kind of data was used to calculate the interactions in each data sets? counts? or normalized data? Maybe normalized data is correct.
