### ISSUE TITLE
Graph labellig from the ranknet function

### ISSUE THREAD

**Issue by charlesgwellem** [sqjin/CellChat#116]
I am comparing two data sets and I made a plot with the ranknet function. I noticed that the colouring of the labels on the vertical axes is not what I expect. For example the Spp1 signalling pathway is only present in the bleomycin condition, but it is labelled in green colour on the vertical axis. The green colour should represent the other treatment group (nint).  Is there a hint on how I can solve this problem?

![grafik](https://user-images.githubusercontent.com/10155881/104452256-08c39e00-55a3-11eb-98e5-d8ea5c9a7595.png)

**Comment by sqjin** [comment]
@charlesgwellem Please re-install the package. This issue should be solved.

**Comment by charlesgwellem** [comment]
@sqjin  Yes I did reinstall it. It now works. Thanks.
