### ISSUE TITLE
Issues with the label colours from the rnaknet function.

### ISSUE THREAD

**Issue by charlesgwellem** [sqjin/CellChat#117]
I am comparing two data sets and I made a plot with the ranknet function. I noticed that the colouring of the labels on the vertical axes is not what I expect. Taking one example the Spp1 signalling pathway is only present in the bleomycin condition, but it is labelled in green colour on the vertical axis. The green colour should represent the other treatment group (nint).  Also the two graphs do not have the same magnitude for the same terms. Is there a hint on how I can solve these problems?

![grafik](https://user-images.githubusercontent.com/10155881/104452256-08c39e00-55a3-11eb-98e5-d8ea5c9a7595.png)

**Comment by sqjin** [comment]
Please re-install the package.

**Comment by charlesgwellem** [comment]
@sqjin  I have reinstalled the package but think the problem persisits.
