### ISSUE TITLE
object 'cellchat' not found

### ISSUE THREAD

**Issue by bandry257** [sqjin/CellChat#118]
Hello @sqjin 
Thanks a lot for your wonderful and helpful work. I am following your new tutorial. Here is my problem:
> netVisual_individual(cellchat_M, sources.use = c(1:12,14,17,19), targets.use = c(13,14,17), signaling = "CCL", pairLR.use = "CCL5_CCR1", layout = "hierarchy")
Error in levels(object@idents) : object 'object' not found
> cellchat_M
Error in (new("standardGeneric", .Data = function (object)  : 
  object 'cellchat' not found

Could you please show me how to fix this problem?

Thanks a lot for your help.

**Comment by sqjin** [comment]
@bandry257 I am sorry I have no idea on this error. Is there any error if you run `netVisual_individual(cellchat_M, sources.use = c(1:12,14,17,19), targets.use = c(13,14,17), signaling = "CCL")`?

**Comment by bandry257** [comment]
Yes, there is the same error:
netVisual_individual(cellchat_M, sources.use = c(1:12,14,17,19), targets.use = c(13,14,17), signaling = "CCL")
Error in levels(object@idents) : object 'object' not found

Thank you very much.

**Comment by sqjin** [comment]
@bandry257 If you did not have any issue to run our example data, I suggest to check your each step. This is the first time I heard about this issue and I have no idea about it. Sorry!

**Comment by bandry257** [comment]
OK, I‘ll check my each step. Thanks a lot for your help!
