### ISSUE TITLE
about visualize the conserved and context-specific signaling pathways

### ISSUE THREAD

**Issue by Isaac861105** [sqjin/CellChat#119]
Hi,
 I have a question about visualize the conserved and context-specific signaling pathways in multiple datasets analysis. 
 In the Compare the overall information flow of each signaling pathway section  (rankNet code section), can we extract only some specific cluster to draw the rankNet graph (for example only compare in fibroblast group) ? 
 Thank you!

Best,
Isaac

**Comment by sqjin** [comment]
@Isaac861105 You can do it by defining the `sources.use` and `targets.use`

**Comment by Isaac861105** [comment]
Hi @sqjin :
 I have try it~but it's show unused argument, have any other's suggestion? 
 Thank you!
![擷取](https://user-images.githubusercontent.com/67620171/104835175-c7532b80-58df-11eb-8515-3948f5ce668d.PNG)

**Comment by sqjin** [comment]
@Isaac861105 I guess you need to re-install the latest version.

**Comment by Isaac861105** [comment]
Hi @sqjin 
 Thanks for quickly reply. My cellchat version is ver 0.50.
 Beside, the rankNet graph that i need to visualize is some specific cluster instead of overall cluster between two samples. i have view the description of rankNet, there is no argument of sources.use and targets.use =).
 thank you.
 
![image](https://user-images.githubusercontent.com/67620171/104836534-73e5db00-58e9-11eb-82e9-28a2f8639b10.png)

**Comment by sqjin** [comment]
If you can go ahead to reinstall the package, your issues will be resolved.

**Comment by Isaac861105** [comment]
Hi, 
 Thank you for your inform and it's work now.
