### ISSUE TITLE
issue with merging objects

### ISSUE THREAD

**Issue by ruohuchengxhe** [sqjin/CellChat#12]
Hi,
I have created two objects (ctrl and dis) following the instructions, then I was trying to merge those two using 
`cellchat <- mergeCellChat(list(cellchat.ctrl, cellchat.dis), add.names = c("ctrl","dis"))`,
but it looks like the combined dataset has no information in it.
Here's a screenshot: 
![image](https://user-images.githubusercontent.com/43062204/89564844-8a094e80-d815-11ea-99d0-d8db5f9b2094.png)
Please kindly advice. Thanks!

**Comment by sqjin** [comment]
Hi @ruohuchengxhe , there is no issue of this function!  This function only keep the network info, and does not combine the data matrix. Please go head to run the downstream analysis.

**Comment by ruohuchengxhe** [comment]
> Hi @ruohuchengxhe , there is no issue of this function! This function only keep the network info, and does not combine the data matrix. Please go head to run the downstream analysis.

Thanks for your quick reply!Good to know!
