### ISSUE TITLE
Error in computeNetSimilarity

### ISSUE THREAD

**Issue by lazappi** [sqjin/CellChat#120]
I am getting the following error when I run `computeNetSimiliarity()` with `type = "structural"`.

```r
> cellchat <- computeNetSimilarity(cellchat, type = "structural")
Error in shortest.paths(g, algorithm = c("unweighted")) : 
  could not find function "shortest.paths"
```

I think it is coming from this line: https://github.com/sqjin/CellChat/blob/9d688b120832b4af0046784bfc42d012f20224a8/R/analysis.R#L1314

Should be easy to fix by specifying `igraph::shortest.paths(...)`.

**Comment by sqjin** [comment]
@lazappi Thanks for pointing it out! However, I suggest to explicitly load `igraph` when loading `CellChat` as there are several other palaces where I did not specify the igraph package. There are some conflict functions between igraph and other packages.

**Comment by lazappi** [comment]
Thanks for the response! I think specifying the packages everywhere using `::` would make things a bit easier for users than having to remember to load other packages. It's generally good practice anyway and would be required if you ever want to submit to CRAN/Bioconductor.

If you don't want to do that maybe it would be worth add **igraph** to `Depends:` in `DESCRIPTION`? That way it would be loaded whenever the user does `library(CellChat)` which would also avoid these kinds of problems.

Congratulations on **CellChat** by the way 🎉 ! Overall it's a great package.

**Comment by sqjin** [comment]
@lazappi Thanks so much for your kind suggestion.
