### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by s849** [sqjin/CellChat#121]
Hi,

I updated my R to version 4 and now I cannot install the package. I get this error:

> devtools::install_github("sqjin/CellChat")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 403.
  API rate limit exceeded for 128.195.70.144. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

  Rate limit remaining: 0/60
  Rate limit reset at: 2021-01-17 23:33:18 UTC

  To increase your GitHub API rate limit
  - Use `usethis::browse_github_pat()` to create a Personal Access Token.
  - Use `usethis::edit_r_environ()` and add the token as `GITHUB_PAT`.
  
Solutions?

**Comment by sqjin** [comment]
@s849 I am sorry I have no idea on it. Have you fix it?
