### ISSUE TITLE
Question about the parameter top

### ISSUE THREAD

**Issue by kangkc16** [sqjin/CellChat#122]
I find a question when I run `netVisual_diffInteraction()` with `top < 1`.
We can get the difference between the two samples by `net.diff <- obj2 - obj1`, and then filter it through `top < 1`. But there are negative numbers in `net.diff`, these decreased values will be filtered first.
I think it is more rigorous to use **absolute value** for filtering.

**Comment by sqjin** [comment]
@kangkc16 It is fixed now.
