### ISSUE TITLE
netAnalysis_signalingRole_heatmap Error: You should have at least two distinct break values

### ISSUE THREAD

**Issue by jv-20** [sqjin/CellChat#124]
Hi @sqjin  

Quick question in `netAnalysis_signalingRole_heatmap` function. I am trying to examine the outgoing signaling patterns of pathways. For one particular pathway, I have only one cell type that is expressed (value 0.5) and the rest of the celltypes have zero values ( `cellchat@netP$centr$pathway$outdeg`)

When I try to generate outgoing signaling pattern for this pathway using `netAnalysis_signalingRole_heatmap` function 
`ht1 <- netAnalysis_signalingRole_heatmap(cellchat, signaling = pathways.show.[i],pattern = "outgoing")`

I receive the following error message `Error: You should have at least two distinct break values.`

It would be great if you could give some advice on this?

Thank you

**Comment by gt7901b** [comment]
Hi, sqjin:

Maybe related netAnalysis_signalingRole_heatmap question. I can run incoming but when I ran outgoing. I got the error message below.

thanks for your time

netAnalysis_signalingRole_heatmap(cellchat, pattern = "outgoing",width = 16, height = 10, font.size = 8)

ERROR while rich displaying an object: Error: Relative strength: cannot map colors to some of the levels: 0

Traceback:
1. FUN(X[[i]], ...)
2. tryCatch(withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr)) 
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr)) 
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler), error = outer_handler)
3. tryCatchList(expr, classes, parentenv, handlers)
4. tryCatchOne(expr, names, parentenv, handlers[[1L]])
5. doTryCatch(return(expr), name, parentenv, handler)
6. withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr)) 
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr)) 
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler)
7. repr::mime2repr[[mime]](obj)
8. repr_text.default(obj)
9. paste(capture.output(print(obj)), collapse = "\n")
10. capture.output(print(obj))
11. evalVis(expr)
12. withVisible(eval(expr, pf))
13. eval(expr, pf)
14. eval(expr, pf)
15. print(obj)
16. print.default(obj)
17. (new("standardGeneric", .Data = function (object) 
  . standardGeneric("show"), generic = structure("show", package = "methods"), 
  .     package = "methods", group = list(), valueClass = character(0), 
  .     signature = structure("object", simpleOnly = TRUE), default = new("derivedDefaultMethod", 
  .         .Data = function (object) 
  .         showDefault(object), target = new("signature", .Data = "ANY", 
  .             names = "object", package = "methods"), defined = new("signature", 
  .             .Data = "ANY", names = "object", package = "methods"), 
  .         generic = structure("show", package = "methods")), skeleton = (new("derivedDefaultMethod", 
  .         .Data = function (object) 
  .         showDefault(object), target = new("signature", .Data = "ANY", 
  .             names = "object", package = "methods"), defined = new("signature", 
  .             .Data = "ANY", names = "object", package = "methods"), 
  .         generic = structure("show", package = "methods")))(object)))(new("HeatmapList", 
  .     ht_list = list(`Relative strength` = new("Heatmap", name = "Relative strength", 
  .         matrix = structure(c(0.175096032030705, 0.541413923427967, 
  .         0.512820765338683, 1, NA, NA, 1, NA, NA, NA, NA, 1, 0.075542470367976, 
  .         0.285967559930877, NA, NA, 0.210762431041145, NA, 0.824853608009167, 
  .         NA, NA, NA, 0.682653861463069, 0.445324315399188, NA, 
  .         0.81920246176321, 1, NA, 1, 0.811192713696738, 0.609210275101821, 
  .         0.41086260142087, NA, 0.419297194932914, 0.796099363700415, 
  .         NA, 0.448060539892992, 0.133135520468313, NA, NA, 1, 
  .         NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 0.210482859031316, 
  .         NA, 0.105126658277001, NA, NA, NA, 0.54059962015761, 
  .         0.22171285352986, NA, 0.178390121514442, 0.309130078096112, 
  .         0.335681348018737, 0.681485724474637, 0.664141910761381, 
  .         0.500760679256452, 0.191165549470494, NA, 0.329561789649403, 
  .         0.370730335277487, NA, 1, 1, NA, NA, NA, NA, NA, NA, 
  .         NA, 1, 0.165637000110108, 1, 1, NA, NA, NA, NA, 1, NA, 
  .         NA, NA, 1, 1, NA, 1, 0.833202186618906, 1, 0.759659583185771, 
  .         1, 1, 0.0205123806470227, NA, 1, 1, 0.31196601305365, 
  .         0.0696219148311043, 0.0267017818799157, NA, NA, NA, NA, 
  .         NA, 1, 1, NA, NA, NA, 0.0230586018742343, 1, NA, 0.12737275082242, 
  .         NA, 0.0953247222864712, 1, NA, NA, 0.0722904172621872, 
  .         0.0376614918432507, 1, 3.13045281504327e-05, 0.0195163330002719, 
  .         0.25509301888648, 0.25089721976414, NA, 0.114151943211053, 
  .         0.424213922573344, NA, 0.012831662701221, 0.00288756800283882, 
  .         NA, 0.0567057495803645, 0.17755376105725, NA, NA, NA, 
  .         NA, NA, NA, NA, NA, NA, NA, NA, NA, 1, NA, NA, 0.0421126819348583, 
  .         NA, 1, 1, 0.278822771130954, 0.181836170356371, NA, 0.000394859319861524, 
  .         0.0570488300590923, NA, 0.00925597411722491, NA, 0.313824888469301, 
  .         1, NA, NA, NA, NA, 0.0742115265187448, 0.0520567664181636, 
  .         0.326242420908236, NA, NA, 0.328637680232078, NA, NA, 
  .         NA, NA, 0.385337321092302, NA, 0.162991147201158, NA, 
  .         NA, NA, NA, 0.432072905190497, NA, NA, NA, 0.213721700113957, 
  .         0.103690020661211, NA, 0.246201082486926, 0.123659056659915, 
  .         0.245310388493737, 0.490026489799789, 0.121493621849456, 
  .         0.178611871551506, 0.0287430935215476, NA, 0.320046877439311, 
  .         0.173274893418948, 1, 0.351684016635656, 0.199704392705142, 
  .         0.429179898695421, 1, NA, 0.888402746979648, 1, NA, NA, 
  .         NA, 0.346626729030629, 0.0197829968269833, 0.0160566773590197, 
  .         0.0966254954709739, 0.709984479488006, 1, 1, 0.26173515695103, 
  .         NA, NA, NA, 0.257979760363936, 0.115390710298277, NA, 
  .         0.355669618322795, 0.373084500510496, 0.0340179257424638, 
  .         0.42327740104763, 0.392194585703733, 0.246158359743831, 
  .         0.327831565609614, 1, 0.0939145104705005, 0.755364057096385
  .         ), .Dim = c(35L, 7L), .Dimnames = list(c("CXCL", "MIF", 
  .         "IL16", "IFN-II", "TNF", "LT", "FASLG", "CD70", "APRIL", 
  .         "BAFF", "CD40", "PARs", "FLT3", "ANNEXIN", "GALECTIN", 
  .         "BTLA", "BAG", "COLLAGEN", "ADGRE5", "APP", "CD22", "CD23", 
  .         "CD45", "CD48", "CD86", "CD99", "CLEC", "ICAM", "ITGB2", 
  .         "LCK", "MHC-I", "MHC-II", "PECAM1", "SELPLG", "SEMA4"
  .         ), c("CD8 T", "CD4 Treg", "CD4 T", "Myel", "B", "NK", 
  .         "Prolif. CD8T"))), matrix_param = list(row_km = 1, row_km_repeats = 1, 
  .             row_gap = structure(1, unit = 7L, class = c("simpleUnit", 
  .             "unit", "unit_v2")), column_km = 1, column_km_repeats = 1, 
  .             column_gap = structure(1, unit = 7L, class = c("simpleUnit", 
  .             "unit", "unit_v2")), jitter = FALSE, gp = structure(list(
  .                 col = NA, lineheight = 0.9), class = "gpar"), 
  .             border = NA, border_gp = structure(list(col = "black"), class = "gpar"), 
  .             width = structure(16, unit = 1L, class = c("simpleUnit", 
  .             "unit", "unit_v2")), height = structure(10, unit = 1L, class = c("simpleUnit", 
  .             "unit", "unit_v2"))), matrix_color_mapping = new("ColorMapping", 
  .             colors = structure(c("#F7FCFDFF", "#F5FBFCFF", "#F4FAFCFF", 
  .             "#F2FAFCFF", "#F1F9FBFF", "#EFF9FBFF", "#EEF8FBFF", 
  .             "#ECF8FAFF", "#EBF7FAFF", "#E9F6FAFF", "#E8F6F9FF", 
  .             "#E7F5F9FF", "#E5F5F9FF", "#E3F4F8FF", "#E1F3F6FF", 
  .             "#DFF3F4FF", "#DDF2F3FF", "#DBF1F1FF", "#D9F0F0FF", 
  .             "#D7F0EEFF", "#D5EFEDFF", "#D3EEEBFF", "#D1EEEAFF", 
  .             "#CFEDE8FF", "#CDECE7FF", "#CAEBE5FF", "#C6E9E3FF", 
  .             "#C2E8E0FF", "#BEE6DEFF", "#BAE5DCFF", "#B6E3D9FF", 
  .             "#B2E1D7FF", "#AEE0D5FF", "#AADED2FF", "#A5DDD0FF", 
  .             "#A1DBCDFF", "#9DD9CBFF", "#99D8C9FF", "#95D6C6FF", 
  .             "#91D4C3FF", "#8DD2C0FF", "#89D1BDFF", "#84CFBAFF", 
  .             "#80CDB7FF", "#7CCBB4FF", "#78CAB1FF", "#74C8AEFF", 
  .             "#70C6ABFF", "#6CC4A8FF", "#68C2A5FF", "#64C1A2FF", 
  .             "#61BF9EFF", "#5EBD9AFF", "#5BBC96FF", "#58BA93FF", 
  .             "#55B98FFF", "#52B78BFF", "#4FB588FF", "#4CB484FF", 
  .             "#49B280FF", "#46B17CFF", "#43AF79FF", "#40AD75FF", 
  .             "#3EAA71FF", "#3BA76DFF", "#39A569FF", "#36A265FF", 
  .             "#349F61FF", "#329C5DFF", "#2F9959FF", "#2D9755FF", 
  .             "#2A9451FF", "#28914DFF", "#268E49FF", "#238B45FF", 
  .             "#208943FF", "#1E8641FF", "#1B843FFF", "#18813DFF", 
  .             "#157F3BFF", "#127D39FF", "#0F7A37FF", "#0D7835FF", 
  .             "#0A7533FF", "#077331FF", "#04702FFF", "#016E2DFF", 
  .             "#006B2BFF", "#00682AFF", "#006528FF", "#006127FF", 
  .             "#005E25FF", "#005B24FF", "#005723FF", "#005421FF", 
  .             "#005120FF", "#004D1FFF", "#004A1DFF", "#00471CFF", 
  .             "#00441BFF"), .Names = c("3.13045281504327e-05", 
  .             "0.000394859319861524", "0.00288756800283882", "0.00925597411722491", 
  .             "0.012831662701221", "0.0160566773590197", "0.0195163330002719", 
  .             "0.0197829968269833", "0.0205123806470227", "0.0230586018742343", 
  .             "0.0267017818799157", "0.0287430935215476", "0.0340179257424638", 
  .             "0.0376614918432507", "0.0421126819348583", "0.0520567664181636", 
  .             "0.0567057495803645", "0.0570488300590923", "0.0696219148311043", 
  .             "0.0722904172621872", "0.0742115265187448", "0.075542470367976", 
  .             "0.0939145104705005", "0.0953247222864712", "0.0966254954709739", 
  .             "0.103690020661211", "0.105126658277001", "0.114151943211053", 
  .             "0.115390710298277", "0.121493621849456", "0.123659056659915", 
  .             "0.12737275082242", "0.133135520468313", "0.162991147201158", 
  .             "0.165637000110108", "0.173274893418948", "0.175096032030705", 
  .             "0.17755376105725", "0.178390121514442", "0.178611871551506", 
  .             "0.181836170356371", "0.191165549470494", "0.199704392705142", 
  .             "0.210482859031316", "0.210762431041145", "0.213721700113957", 
  .             "0.22171285352986", "0.245310388493737", "0.246158359743831", 
  .             "0.246201082486926", "0.25089721976414", "0.25509301888648", 
  .             "0.257979760363936", "0.26173515695103", "0.278822771130954", 
  .             "0.285967559930877", "0.309130078096112", "0.31196601305365", 
  .             "0.313824888469301", "0.320046877439311", "0.326242420908236", 
  .             "0.327831565609614", "0.328637680232078", "0.329561789649403", 
  .             "0.335681348018737", "0.346626729030629", "0.351684016635656", 
  .             "0.355669618322795", "0.370730335277487", "0.373084500510496", 
  .             "0.385337321092302", "0.392194585703733", "0.41086260142087", 
  .             "0.419297194932914", "0.42327740104763", "0.424213922573344", 
  .             "0.429179898695421", "0.432072905190497", "0.445324315399188", 
  .             "0.448060539892992", "0.490026489799789", "0.500760679256452", 
  .             "0.512820765338683", "0.54059962015761", "0.541413923427967", 
  .             "0.609210275101821", "0.664141910761381", "0.681485724474637", 
  .             "0.682653861463069", "0.709984479488006", "0.755364057096385", 
  .             "0.759659583185771", "0.796099363700415", "0.811192713696738", 
  .             "0.81920246176321", "0.824853608009167", "0.833202186618906", 
  .             "0.888402746979648", "1", NA)), levels = c("3.13045281504327e-05", 
  .             "0.000394859319861524", "0.00288756800283882", "0.00925597411722491", 
  .             "0.012831662701221", "0.0160566773590197", "0.0195163330002719", 
  .             "0.0197829968269833", "0.0205123806470227", "0.0230586018742343", 
  .             "0.0267017818799157", "0.0287430935215476", "0.0340179257424638", 
  .             "0.0376614918432507", "0.0421126819348583", "0.0520567664181636", 
  .             "0.0567057495803645", "0.0570488300590923", "0.0696219148311043", 
  .             "0.0722904172621872", "0.0742115265187448", "0.075542470367976", 
  .             "0.0939145104705005", "0.0953247222864712", "0.0966254954709739", 
  .             "0.103690020661211", "0.105126658277001", "0.114151943211053", 
  .             "0.115390710298277", "0.121493621849456", "0.123659056659915", 
  .             "0.12737275082242", "0.133135520468313", "0.162991147201158", 
  .             "0.165637000110108", "0.173274893418948", "0.175096032030705", 
  .             "0.17755376105725", "0.178390121514442", "0.178611871551506", 
  .             "0.181836170356371", "0.191165549470494", "0.199704392705142", 
  .             "0.210482859031316", "0.210762431041145", "0.213721700113957", 
  .             "0.22171285352986", "0.245310388493737", "0.246158359743831", 
  .             "0.246201082486926", "0.25089721976414", "0.25509301888648", 
  .             "0.257979760363936", "0.26173515695103", "0.278822771130954", 
  .             "0.285967559930877", "0.309130078096112", "0.31196601305365", 
  .             "0.313824888469301", "0.320046877439311", "0.326242420908236", 
  .             "0.327831565609614", "0.328637680232078", "0.329561789649403", 
  .             "0.335681348018737", "0.346626729030629", "0.351684016635656", 
  .             "0.355669618322795", "0.370730335277487", "0.373084500510496", 
  .             "0.385337321092302", "0.392194585703733", "0.41086260142087", 
  .             "0.419297194932914", "0.42327740104763", "0.424213922573344", 
  .             "0.429179898695421", "0.432072905190497", "0.445324315399188", 
  .             "0.448060539892992", "0.490026489799789", "0.500760679256452", 
  .             "0.512820765338683", "0.54059962015761", "0.541413923427967", 
  .             "0.609210275101821", "0.664141910761381", "0.681485724474637", 
  .             "0.682653861463069", "0.709984479488006", "0.755364057096385", 
  .             "0.759659583185771", "0.796099363700415", "0.811192713696738", 
  .             "0.81920246176321", "0.824853608009167", "0.833202186618906", 
  .             "0.888402746979648", "1", NA), col_fun = function () 
  .             NULL, type = "discrete", name = "Relative strength", 
  .             na_col = "#FFFFFFFF", full_col = character(0)), matrix_legend_param = list(
  .             title = "Relative strength", title_gp = structure(list(
  .                 fontsize = 8, fontface = "plain", font = c(plain = 1L)), class = "gpar"), 
  .             title_position = "leftcenter-rot", border = NA, at = c(0, 
  .             1), legend_height = structure(20, unit = 7L, class = c("simpleUnit", 
  .             "unit", "unit_v2")), labels_gp = structure(list(fontsize = 8), class = "gpar"), 
  .             grid_width = structure(2, unit = 7L, class = c("simpleUnit", 
  .             "unit", "unit_v2"))), row_title = character(0), row_title_param = list(
  .             rot = 90, side = "left", gp = structure(list(fontsize = 13.2, 
  .                 lineheight = 0.9), class = "gpar"), just = c(0.5, 
  .             0)), column_title = "Outgoing signaling patterns", 
  .         column_title_param = list(rot = 0, side = "top", gp = structure(list(
  .             fontsize = 10, lineheight = 0.9), class = "gpar"), 
  .             just = c(0.5, 0)), row_dend_list = list(), row_dend_slice = NULL, 
  .         row_dend_param = list(cluster = FALSE, distance = "euclidean", 
  .             method = "complete", side = "left", width = structure(0.5, unit = 7L, class = c("simpleUnit", 
  .             "unit", "unit_v2")), show = FALSE, gp = structure(list(
  .                 lineheight = 0.9), class = "gpar"), reorder = TRUE, 
  .             cluster_slices = TRUE), row_order_list = list(), 
  .         row_order = 1:35, column_dend_list = list(), column_dend_slice = NULL, 
  .         column_dend_param = list(cluster = FALSE, distance = "euclidean", 
  .             method = "complete", side = "top", height = structure(0.5, unit = 7L, class = c("simpleUnit", 
  .             "unit", "unit_v2")), show = FALSE, gp = structure(list(
  .                 lineheight = 0.9), class = "gpar"), reorder = TRUE, 
  .             cluster_slices = TRUE), column_order_list = list(), 
  .         column_order = 1:7, row_names_param = list(labels = c("CXCL", 
  .         "MIF", "IL16", "IFN-II", "TNF", "LT", "FASLG", "CD70", 
  .         "APRIL", "BAFF", "CD40", "PARs", "FLT3", "ANNEXIN", "GALECTIN", 
  .         "BTLA", "BAG", "COLLAGEN", "ADGRE5", "APP", "CD22", "CD23", 
  .         "CD45", "CD48", "CD86", "CD99", "CLEC", "ICAM", "ITGB2", 
  .         "LCK", "MHC-I", "MHC-II", "PECAM1", "SELPLG", "SEMA4"
  .         ), side = "left", show = TRUE, gp = structure(list(fontsize = 8, 
  .             lineheight = 0.9), class = "gpar"), rot = 0, centered = FALSE, 
  .             max_width = structure(list(list(1, structure(list(
  .                 list(6, NULL, 1L), list(2, NULL, 7L)), class = c("unit", 
  .             "unit_v2")), 201L)), class = c("unit", "unit_v2")), 
  .             anno = new("AnnotationFunction", which = "row", fun_name = "anno_text", 
  .                 width = structure(15.2851555555556, unit = 7L, class = c("simpleUnit", 
  .                 "unit", "unit_v2")), height = structure(1, unit = 0L, class = c("simpleUnit", 
  .                 "unit", "unit_v2")), n = 35L, var_env = <environment>, 
  .                 fun = function (index, k = 1, n = 1) 
  .                 {
  .                   n = length(index)
  .                   gp = subset_gp(gp, index)
  .                   gp2 = gp
  .                   if ("border" %in% names(gp2)) 
  .                     gp2$col = gp2$border
  .                   if ("fill" %in% names(gp2)) {
  .                     if (!"border" %in% names(gp2)) 
  .                       gp2$col = gp2$fill
  .                   }
  .                   if (any(c("border", "fill") %in% names(gp2))) {
  .                     grid.rect(y = (n - seq_along(index) + 0.5)/n, 
  .                       height = 1/n, gp = gp2)
  .                   }
  .                   grid.text(value[index], location, (n - seq_along(index) + 
  .                     0.5)/n, gp = gp, just = just, rot = rot)
  .                 }, subset_rule = list(value = function (x, i) 
  .                 x[i], gp = function (gp, i) 
  .                 {
  .                   gp = lapply(gp, function(x) {
  .                     if (length(x) == 1) 
  .                       x
  .                     else x[i]
  .                   })
  .                   class(gp) = "gpar"
  .                   return(gp)
  .                 }), subsetable = TRUE, data_scale = c(0, 1), 
  .                 extended = structure(c(0, 0, 0, 0), unit = 7L, class = c("simpleUnit", 
  .                 "unit", "unit_v2")), show_name = FALSE)), column_names_param = list(
  .             labels = c("CD8 T", "CD4 Treg", "CD4 T", "Myel", 
  .             "B", "NK", "Prolif. CD8T"), side = "bottom", show = TRUE, 
  .             gp = structure(list(fontsize = 8, lineheight = 0.9), class = "gpar"), 
  .             rot = 90, centered = FALSE, max_height = structure(list(
  .                 list(1, structure(list(list(6, NULL, 1L), list(
  .                   2, NULL, 7L)), class = c("unit", "unit_v2")), 
  .                   201L)), class = c("unit", "unit_v2")), anno = new("AnnotationFunction", 
  .                 which = "column", fun_name = "anno_text", width = structure(1, unit = 0L, class = c("simpleUnit", 
  .                 "unit", "unit_v2")), height = structure(15.2823333333333, unit = 7L, class = c("simpleUnit", 
  .                 "unit", "unit_v2")), n = 7L, var_env = <environment>, 
  .                 fun = function (index, k = NULL, N = NULL, vp_name = NULL) 
  .                 {
  .                   n = length(index)
  .                   gp = subset_gp(gp, index)
  .                   gp2 = gp
  .                   if ("border" %in% names(gp2)) 
  .                     gp2$col = gp2$border
  .                   if ("fill" %in% names(gp2)) {
  .                     if (!"border" %in% names(gp2)) 
  .                       gp2$col = gp2$fill
  .                   }
  .                   if (any(c("border", "fill") %in% names(gp2))) {
  .                     grid.rect(x = (seq_along(index) - 0.5)/n, 
  .                       width = 1/n, gp = gp2)
  .                   }
  .                   grid.text(value[index], (seq_along(index) - 
  .                     0.5)/n, location, gp = gp, just = just, rot = rot)
  .                 }, subset_rule = list(value = function (x, i) 
  .                 x[i], gp = function (gp, i) 
  .                 {
  .                   gp = lapply(gp, function(x) {
  .                     if (length(x) == 1) 
  .                       x
  .                     else x[i]
  .                   })
  .                   class(gp) = "gpar"
  .                   return(gp)
  .                 }), subsetable = TRUE, data_scale = c(0, 1), 
  .                 extended = structure(c(0, 0, 0, 0), unit = 7L, class = c("simpleUnit", 
  .                 "unit", "unit_v2")), show_name = FALSE)), top_annotation = new("HeatmapAnnotation", 
  .             name = "heatmap_annotation_8", anno_list = list(Strength = new("SingleAnnotation", 
  .                 name = "Strength", label = "Strength", color_mapping = NULL, 
  .                 legend_param = NULL, fun = new("AnnotationFunction", 
  .                   which = "column", fun_name = "anno_barplot", 
  .                   width = structure(1, unit = 0L, class = c("simpleUnit", 
  .                   "unit", "unit_v2")), height = structure(10, unit = 7L, class = c("simpleUnit", 
  .                   "unit", "unit_v2")), n = 7L, var_env = <environment>, 
  .                   fun = function (index, k = 1, N = 1) 
  .                   {
  .                     n = length(index)
  .                     if (axis_param$direction == "reverse") {
  .                       value_origin = value
  .                       value = data_scale[2] - value + data_scale[1]
  .                       baseline = data_scale[2] - baseline + data_scale[1]
  .                     }

**Comment by jv-20** [comment]
Hi @sqjin 

There is another error associated with `netAnalysis_contribution` function for one pathway. This is the code I use `netAnalysis_contribution(cellchat, signaling = pathways.show[i])`. The following error occurs for only one pathway
```
Error in `levels<-`(`*tmp*`, value = as.character(levels)) : 
  factor level [36] is duplicated
```
Would you or anyone know how to solve this? Thank you

**Comment by sqjin** [comment]
@jv-20 Do you have this issue for other pathways or just this particular one?  Is this a merged CellChat object?

**Comment by sqjin** [comment]
@jv-20 @gt7901b I just updated the function netAnalysis_signalingRole_heatmap. Please let me know if the issue still exists.

**Comment by jv-20** [comment]
Thank you @sqjin I will run the `netAnalysis_signalingRole_heatmap` and update you. 

For your question
 **Do you have this issue for other pathways or just this particular one? Is this a merged CellChat object?**

the error I receive for function `netAnalysis_contribution` is for only one pathway so far. Thank you

**Comment by jv-20** [comment]
Hi @sqjin update on the `netAnalysis_signalingRole_heatmap`.  I receive another error message now like this for a pathway
```
Error in seq.default(min(matrix, na.rm = TRUE), max(matrix, na.rm = TRUE),  : 
  'from' must be a finite number
```

The code I am using is on a cellchat object obtained from single dataset
`netAnalysis_signalingRole_heatmap(cellchat, pattern = "outgoing", signaling = pathways.show)`

Thank you in advance

**Comment by sqjin** [comment]
@jv-20 I have made another change on the Github. If you still have the error, can you please share me your object?

**Comment by jv-20** [comment]
Hi @sqjin thanks a lot for looking into this. I re-installed the package and I still receive the error `netAnalysis_signalingRole_heatmap Error: You should have at least two distinct break values`. Confidentiality agreement prevents us from sharing the data, is there any other way to resolve this. If you can please advise me which subsections of the data to look at, I can get that information. Thank you

**Comment by gt7901b** [comment]
thanks, sqjin, it works for me.

**Comment by sqjin** [comment]
@jv-20 Please run the source codes of this function to figure out the issue.

**Comment by jv-20** [comment]
Thank you @sqjin, The issue I am having is for one pathway. I excluded that pathway and generating figures for the rest. I will update you if I find a solution. The pathway I am having the issue has multiple ligands and multiple receptors. I was wondering, if there is any limit set for the number of ligands to be in a pathway? Thank you for all your comments and replies.

**Comment by Jeayz** [comment]
![图片](https://user-images.githubusercontent.com/88371107/179346961-e0e40554-c11f-4925-af40-1ccbf406633a.png)
Hi, sqjin:

I meet a problem about the function `netAnalysis_signalingRole_heatmap question` too. I can run incoming and all but when I ran outgoing. I got the error.

Thanks for your kindness

`netAnalysis_signalingRole_heatmap(cellchat, pattern = "outgoing")`
ERROR while rich displaying an object: Error: Relative strength: cannot map colors to some of the levels: 0

**Comment by sqjin** [comment]
@Jeayz I have no idea on this error. You need to run the source codes line by line and figure out the reason. If you want to share your object, I can also take a look.

**Comment by notguigao** [comment]
> @jv-20 

Same error here when using function `netAnalysis_contribution()`
```R
Error in `levels<-`(`*tmp*`, value = as.character(levels)) : 
  factor level [7] is duplicated
```

Here's what I've found: 
In CellChatDB.human, the column `interaction_name_2` of pair **PLG_F2R** is **_PLG - F2RL3_** (it should be _PLG_F2R_), which leads to  the duplication problem between **PLG_F2R** and **PLG_F2RL3** when using `factor()` in following line 
```R
df$name <- factor(df$name, levels = df$name[order(df$contribution, decreasing = TRUE)])
```
of function `netAnalysis_contribution()`.

Solution: 
1. ```nb20@DB$interaction["PLG_F2R","interaction_name_2"] <- "PLG - F2R" ``` nb20 is the name of my cellchat object
2.  set the parameter `vertex.receiver` (rather than the default NULL) and this leads to another `if` branch of the source code

My code is:
```R
for (i in 1:length(pathways.show.all)) {
  netVisual(nb20, signaling = pathways.show.all[i], 
            vertex.receiver = vertex.receiver, layout = "hierarchy",out.format = c("png","pdf"))
  gg <- netAnalysis_contribution(nb20, signaling = pathways.show.all[i])
  ggsave(filename=paste0('./test',pathways.show.all[i], "_L-R_contribution.pdf"), 
         plot=gg, width = 6, height = 2, units = 'in', dpi = 300)
}
```

**Comment by Ryeeeeeeeeee** [comment]
> ![图片](https://user-images.githubusercontent.com/88371107/179346961-e0e40554-c11f-4925-af40-1ccbf406633a.png) Hi, sqjin:
> 
> I meet a problem about the function `netAnalysis_signalingRole_heatmap question` too. I can run incoming and all but when I ran outgoing. I got the error.
> 
> Thanks for your kindness
> 
> `netAnalysis_signalingRole_heatmap(cellchat, pattern = "outgoing")` ERROR while rich displaying an object: Error: Relative strength: cannot map colors to some of the levels: 0

Hi, I also met the same problem, there was only an error when I ran "incoming", for "outgoing" and "overall" everything was ok. I tried to change the color but it still didn't work. Do you have some solution for this? Thank you in advanced.

**Comment by zfy10086** [comment]
> @Jeayz I have no idea on this error. You need to run the source codes line by line and figure out the reason. If you want to share your object, I can also take a look.

Same error here as notguigao. I‘ve found in CellChatDB.human that the column interaction_name of pair CD99_PILRB2 is CD99 - PILRA. It was duplicated with CD99_PILRA pair. And this pair has the same problem:  "CD55B_ADGRE5" ->"CD55 - ADGRE5"

**Comment by bijuissacch224610** [comment]
I have gotten same error for this function, netAnalysis_signalingRole_heatmap. Is there a solution to this question available?
ht1 <- netAnalysis_signalingRole_heatmap(X, pattern = "outgoing")
Error: You should have at least two distinct break values.

**Comment by sqjin** [comment]
@bijuissacch224610 This is because all values in the `object@netP$centr` are the same. In this case, you may not need to show the results using this function.
