### ISSUE TITLE
extract ligands, receptors and cofactors associated with list of pathways

### ISSUE THREAD

**Issue by jv-20** [sqjin/CellChat#125]
Hi @sqjin Quick question. Is there a function to extract the underlying gene names for ligands, receptors and cofactors associated with a list of pathway names? 

For example, when I use `df.net <- subsetCommunication(cellchat, signaling = c("ACTIVIN","ADM")).` It returns the interactions nicely. But some of the ligands in the LR database are not gene names (e.g Activin AB is given as a ligand name and refers to cofactor table). Is it possible to extract the underlying gene names of ligands, receptors and cofactors for a particular pathway?   

Thank you

**Comment by sqjin** [comment]
@jv-20 You can do it by `extractGeneSubsetFromPair`. But this only return ligands/receptors.

**Comment by jv-20** [comment]
Hi @sqjin , this is very helpful. Thank you
