### ISSUE TITLE
Extracting pathways that are present in same cluster vs different cluster from a merged cellchat object

### ISSUE THREAD

**Issue by jv-20** [sqjin/CellChat#126]
Hi @sqjin, 

Question on extracting pathways based on functional or structural similarity on a merged cellchat object

Based on functional or structural similarity, I would like to extract pathways from two datasets that are present in same cluster vs different cluster from a merged cellchat object.

For example if I am looking at cluster 1, within this cluster

1. I want to know which pathways that cluster together from both the datasets. 
2. I also want to find those pathways that are unique to one dataset that are present within this cluster

I try to use this code `cellchat.merge_object@netP$similarity$functional$dr` , but the dataset name is not available. The row names are duplicated and appended with ".1".  I tried to use first set of row names without the extension as first dataset and those rownames with this extension as second dataset. However for pathways that are unique to one set of data, this method gives me incorrect results. 

Is it possible to add the dataset name to the results of this  `cellchat.merge_object@netP$similarity$functional$dr` . Or is there a way to obtain the information on the dataset labels. Please advise, thank you

**Comment by sqjin** [comment]
@jv-20 cellchat.merge_object@netP$similarity$functional$dr is a list and should have the dataset names as the list names.

**Comment by jv-20** [comment]
Hi @sqjin `cellchat.merge_object@netP$similarity$functional$dr` returns me a list. However the name is given as `"1-2"`.
  
I tried another way, based on the number of pathways detected in each individual dataset. With this, I am able to extract the information for each dataset from the merged cellchat object. For example, if the number of pathways detected in dataset 1 is 250 and dataset 2 is 130. 

I subset the results of  `cellchat.merge_object@netP$similarity$functional$dr` assuming the first 250 rows are associated with dataset 1 and the rest for dataset 2. Is this correct?

Thanks

**Comment by sqjin** [comment]
@jv-20 Yes, it is correct.
