### ISSUE TITLE
Normalization and merging objects

### ISSUE THREAD

**Issue by s849** [sqjin/CellChat#127]
In the new version, I noticed that you can normalize two data sets together and then extract each (for example normal versus condition) and then analyze and compare in parallel. This is with the assumption that they are both sharing cell types.

In the case that both have different cell types, you suggest to process independently and then merge, with the option to "lift up". Since they are processed separately, does this affect the analysis and identification of interactions since they are not normalized together?

**Comment by sqjin** [comment]
@s849 For any comparison analysis, CellChat always first analyze each dataset independently and then merge them together.   For your case, if both the input data of the two conditions are normalized in the same way, for example log-transformation, it is OK to run it. At least, I have not found any clear issues using such approach so far.
