### ISSUE TITLE
What is the difference between total interaction strength and number of interactions ？ 

### ISSUE THREAD

**Issue by BeyondMyPast228** [sqjin/CellChat#128]
Hi，
Thanks for developing this user-friendly tool. Could you please tell me what's the difference between total interaction strength and number of interactions ? I have some confusion about that two terms.

**Comment by sqjin** [comment]
@BeyondMyPast228 The interaction strength means the interaction weights. Thus the total interaction strength is the sum of interaction weights. The number of interactions means how many interactions.
