### ISSUE TITLE
about output exact ligand-receptor data of cellchat data 

### ISSUE THREAD

**Issue by tn00992786** [sqjin/CellChat#13]
Dear author, 

May I realize how to output exact ligand-receptor list of specific data of pathway? For example, wnt signaling pathway including different ligands  participating in signaling transduction, ctgf, dkk2, igfbp4, etc, and receptor of wnt signalling pathway including fzd2, fzd7, lgr5 and lrp6. 
Thanks for kind attention.

dentistZ

**Comment by sqjin** [comment]
Hi @tn00992786 , all the database information is available at CellChatDB.mouse or CellChatDB.human. CellChat provides a function to extract the L-R pairs of particular signaling pathway via `pairLR <- searchPair(signaling = "WNT", pairLR.use = CellChatDB$interaction, key = "pathway_name", matching.exact = T, pair.only = F)`.
