### ISSUE TITLE
Error when run netVisual_heatmap

### ISSUE THREAD

**Issue by gt7901b** [sqjin/CellChat#130]
Hi, Sqjin:

When I run this part of code from the tutorial with my object, I got the error: Error in if (all(abs(as.numeric(labels_y) - as.numeric(y)) < 1e-04)) {: missing value where TRUE/FALSE needed

thanks for your time

`pathways.show <- c("CXCL") 
par(mfrow = c(1,2), xpd=TRUE)
ht <- list()
for (i in 1:length(object.list)) {
  ht[[i]] <- netVisual_heatmap(object.list[[i]], signaling = pathways.show, 
                               color.heatmap = "Reds",title.name = paste(pathways.show, "signaling ",names(object.list)[i]))
}
ComplexHeatmap::draw(ht[[1]] + ht[[2]], ht_gap = unit(0.5, "cm"))`

Do heatmap based on a single object 

Do heatmap based on a single object 

Error in if (all(abs(as.numeric(labels_y) - as.numeric(y)) < 1e-04)) {: missing value where TRUE/FALSE needed
Traceback:

1. ComplexHeatmap::draw(ht[[1]] + ht[[2]], ht_gap = unit(0.5, "cm"))
2. ComplexHeatmap::draw(ht[[1]] + ht[[2]], ht_gap = unit(0.5, "cm"))
3. .local(object, ...)
4. make_layout(object, row_title = row_title, row_title_side = row_title_side, 
 .     row_title_gp = row_title_gp, column_title = column_title, 
 .     column_title_side = column_title_side, column_title_gp = column_title_gp, 
 .     heatmap_legend_side = heatmap_legend_side, merge_legends = merge_legends, 
 .     show_heatmap_legend = show_heatmap_legend, heatmap_legend_list = heatmap_legend_list, 
 .     annotation_legend_side = annotation_legend_side, show_annotation_legend = show_annotation_legend, 
 .     annotation_legend_list = annotation_legend_list, align_heatmap_legend = align_heatmap_legend, 
 .     align_annotation_legend = align_annotation_legend, legend_grouping = legend_grouping, 
 .     ht_gap = ht_gap, main_heatmap = main_heatmap, padding = padding, 
 .     auto_adjust = auto_adjust, row_dend_side = row_dend_side, 
 .     row_sub_title_side = row_sub_title_side, column_dend_side = column_dend_side, 
 .     column_sub_title_side = column_sub_title_side, row_gap = row_gap, 
 .     cluster_rows = cluster_rows, cluster_row_slices = cluster_row_slices, 
 .     clustering_distance_rows = clustering_distance_rows, clustering_method_rows = clustering_method_rows, 
 .     row_dend_width = row_dend_width, show_row_dend = show_row_dend, 
 .     row_dend_reorder = row_dend_reorder, row_dend_gp = row_dend_gp, 
 .     row_order = row_order, row_km = row_km, row_km_repeats = row_km_repeats, 
 .     row_split = row_split, height = height, heatmap_height = heatmap_height, 
 .     column_gap = column_gap, cluster_columns = cluster_columns, 
 .     cluster_column_slices = cluster_column_slices, clustering_distance_columns = clustering_distance_columns, 
 .     clustering_method_columns = clustering_method_columns, column_dend_width = column_dend_width, 
 .     show_column_dend = show_column_dend, column_dend_reorder = column_dend_reorder, 
 .     column_dend_gp = column_dend_gp, column_order = column_order, 
 .     column_km = column_km, column_km_repeats = column_km_repeats, 
 .     column_split = column_split, width = width, heatmap_width = heatmap_width, 
 .     use_raster = use_raster, raster_device = raster_device, raster_quality = raster_quality, 
 .     raster_device_param = raster_device_param, raster_resize = raster_resize)
5. make_layout(object, row_title = row_title, row_title_side = row_title_side, 
 .     row_title_gp = row_title_gp, column_title = column_title, 
 .     column_title_side = column_title_side, column_title_gp = column_title_gp, 
 .     heatmap_legend_side = heatmap_legend_side, merge_legends = merge_legends, 
 .     show_heatmap_legend = show_heatmap_legend, heatmap_legend_list = heatmap_legend_list, 
 .     annotation_legend_side = annotation_legend_side, show_annotation_legend = show_annotation_legend, 
 .     annotation_legend_list = annotation_legend_list, align_heatmap_legend = align_heatmap_legend, 
 .     align_annotation_legend = align_annotation_legend, legend_grouping = legend_grouping, 
 .     ht_gap = ht_gap, main_heatmap = main_heatmap, padding = padding, 
 .     auto_adjust = auto_adjust, row_dend_side = row_dend_side, 
 .     row_sub_title_side = row_sub_title_side, column_dend_side = column_dend_side, 
 .     column_sub_title_side = column_sub_title_side, row_gap = row_gap, 
 .     cluster_rows = cluster_rows, cluster_row_slices = cluster_row_slices, 
 .     clustering_distance_rows = clustering_distance_rows, clustering_method_rows = clustering_method_rows, 
 .     row_dend_width = row_dend_width, show_row_dend = show_row_dend, 
 .     row_dend_reorder = row_dend_reorder, row_dend_gp = row_dend_gp, 
 .     row_order = row_order, row_km = row_km, row_km_repeats = row_km_repeats, 
 .     row_split = row_split, height = height, heatmap_height = heatmap_height, 
 .     column_gap = column_gap, cluster_columns = cluster_columns, 
 .     cluster_column_slices = cluster_column_slices, clustering_distance_columns = clustering_distance_columns, 
 .     clustering_method_columns = clustering_method_columns, column_dend_width = column_dend_width, 
 .     show_column_dend = show_column_dend, column_dend_reorder = column_dend_reorder, 
 .     column_dend_gp = column_dend_gp, column_order = column_order, 
 .     column_km = column_km, column_km_repeats = column_km_repeats, 
 .     column_split = column_split, width = width, heatmap_width = heatmap_width, 
 .     use_raster = use_raster, raster_device = raster_device, raster_quality = raster_quality, 
 .     raster_device_param = raster_device_param, raster_resize = raster_resize)
6. .local(object, ...)
7. heatmap_legend_size(object, legend_list = heatmap_legend_list, 
 .     max_height = calc_legends_max_height(object, page_size))
8. heatmap_legend_size(object, legend_list = heatmap_legend_list, 
 .     max_height = calc_legends_max_height(object, page_size))
9. .local(object, ...)
10. draw_legend(ColorMappingList, ColorMappingParamList, side = side, 
  .     plot = FALSE, legend_list = legend_list, padding = padding, 
  .     ...)
11. lapply(seq_along(ColorMappingList2), function(i) color_mapping_legend(ColorMappingList2[[i]], 
  .     param = ColorMappingParamList2[[i]], plot = FALSE, ...))
12. FUN(X[[i]], ...)
13. color_mapping_legend(ColorMappingList2[[i]], param = ColorMappingParamList2[[i]], 
  .     plot = FALSE, ...)
14. color_mapping_legend(ColorMappingList2[[i]], param = ColorMappingParamList2[[i]], 
  .     plot = FALSE, ...)
15. .local(object, ...)
16. Legend(at = at, labels = labels, name = object@name, col_fun = object@col_fun, 
  .     title = title, title_gp = title_gp, grid_height = grid_height, 
  .     grid_width = grid_width, border = border, labels_gp = labels_gp, 
  .     labels_rot = labels_rot, direction = legend_direction, legend_width = legend_width, 
  .     legend_height = legend_height, title_position = title_position, 
  .     by_row = by_row, break_dist = break_dist)
17. vertical_continuous_legend_body(at = at, labels = labels, col_fun = col_fun, 
  .     break_dist = break_dist, grid_height = grid_height, grid_width = grid_widt

**Comment by sqjin** [comment]
@gt7901b Looks like it is an internal issue in the ComplexHeatmap package. Can you run the source codes of `netVisual_heatmap` to see if you can find the issue?

**Comment by l-magnificence** [comment]
I met the same error when I directly run netVisual_heatmap(object.list[[1]], signaling = pathways.show, color.heatmap = "Reds",  title.name = paste(pathways.show, "signaling ",names(object.list)[1]))
Do you konw how to deal with it? Thanks you!

**Comment by sqjin** [comment]
@l-magnificence Can you please let me know the pathway name?

**Comment by l-magnificence** [comment]
each pathway in my data can not be visualized by netVisual_heatmap
I extract the  communication probability matrix related with "TGFb" pathway and send you an email
Code:
TGFb <- slot(object.list[[1]], "netP")$prob[,,"TGFb"]
saveRDS(TGFb,file = "~/TGFb.rds")

**Comment by l-magnificence** [comment]
this is the communication probability matrix related with TGFb.
Thank you.













At 2021-02-06 23:42:04, "sqjin" <notifications@github.com> wrote:

@l-magnificence Can you please let me know the pathway name?

**Comment by sqjin** [comment]
@l-magnificence I did not received your data. Can you send the file to cellchat.package@gmail.com ?

**Comment by l-magnificence** [comment]
I have resend the file to your email.

**Comment by RAEjarq** [comment]
Hello,
Have you been able to address the issue? I am encountering it for some of my pathways but not others.
Thank you!

**Comment by sqjin** [comment]
@RAEjarq i think the issues has been fixed. Can you try the latest version?

**Comment by RAEjarq** [comment]
I have just forced the reinstallation of the package from devtools::install_github("sqjin/CellChat") and tried again with the same result.
I have emailed you the files

**Comment by sqjin** [comment]
@RAEjarq This issue should be fixed now. Please re-install it.

**Comment by RAEjarq** [comment]
Yes, the issue has been fixed but I have encountered another one for another of my pathways. 

"Error: You should have at least two distinct break values."

I think the problem comes from only one interaction being significant. I have sent you the object.

**Comment by sqjin** [comment]
@RAEjarq Fixed it!

**Comment by RAEjarq** [comment]
It works perfectly now, thanks!

**Comment by wdg118** [comment]
@sqjin I don't think this issue has been fixed. Heatmaps in cellchat do not work for me at all.
