### ISSUE TITLE
Further Information about Resource/DB

### ISSUE THREAD

**Issue by dbdimitrov** [sqjin/CellChat#132]
Hi, 

First, I would like to say congrats for the excellent package and for the well-written publication.

However, I think further information about the CellChatDB/resource should be provided.
I can see that there is a [page](https://htmlpreview.github.io/?https://github.com/sqjin/CellChat/blob/master/tutorial/Update-CellChatDB.html) that shows how you can contribute to the DB and how to add single entries.
Yet, it is quite challenging to substitute it with another DB or extend it on a larger scale than manually adding entries.

I completely understand that it is a complex resource, but some information about the fields/column and how the different lists are connected would go a long way in enabling reproducibility and future benchmarking of your tool/resource!

Any response would be much appreciated.

Kindest regards,

Daniel

**Comment by sqjin** [comment]
Hi @dbdimitrov , for a large scale update, there are two key columns in CellChatDB$interaction: ligand and receptor. If the new added ligands/receptors are complex, then you have to define the genes in this complex in another list called  `CellChatDB$complex`.  I think it is feasible to do this with some pieces of codes.  For some other columns in the key list 'CellChatDB$interaction', you should define 'interaction_name'.  It is clearly that columns such as 'pathway_name', 'agonist' and 'co_A_receptor' can only be defined manually. However, you can simply leave them empty if you do not have such information.

**Comment by dbdimitrov** [comment]
Hi @sqjin,

Thank you for the prompt response. I think I managed to deduct the information that you shared. 
Perhaps, a few words about agonist, co_A_receptor, and interaction_name_2 would be much appreciated.

**Comment by sqjin** [comment]
@dbdimitrov interaction_name_2 is just alternative name of interaction_name, which is better to show in the figure.  co-stimulatory (co_A_receptor) and co- inhibitory (co_I_receptor) membrane-bound receptors are capable of modulating signaling via the control of receptor activation. The extracellular agonists and antagonists from both sender and receiver cells are able to directly or indirectly modulate the ligand-receptor interaction.   Our paper will be officially out in Nature Communications in this late month and contains more details about the database compared to our preprint.  But please let me know if you have any other questions.

**Comment by dbdimitrov** [comment]
@sqjin, thank you so much for your response. I look forward to reading the published manuscript
