### ISSUE TITLE
install CellChat via devtools

### ISSUE THREAD

**Issue by liuzhe93** [sqjin/CellChat#134]
Thanks for reading this message.

Hello, I want to explore the cell-cell communication between 2 sub-cell populations in my scRNA-seq data. And I realized that CellChat is the R package that I needed. However, I encounter a problem when I install this package:
> devtools::install_github("sqjin/CellChat")
Error:  ‘igraph’ package is constructed by R version 4.0.3.
Stop execute
ERROR: lazy loading failed for package ‘CellChat’

And the version of my igraph R package is 1.2.6. My R version is R4.0.2.
 > packageVersion('igraph')
[1] ‘1.2.6’

Could you help me figure out what can I do to install this R package? Thank you so much for your kind help.

Best wishes,
Zhe

**Comment by sqjin** [comment]
Hi @liuzhe93 , it looks like ‘igraph’ package is not compatible with your R version. Can you try to install the igraph using the old version 1.2.5

**Comment by liuzhe93** [comment]
> Hi @liuzhe93 , it looks like ‘igraph’ package is not compatible with your R version. Can you try to install the igraph using the old version 1.2.5

Thank you so much for your reply and kind help. I will try. Thank you.
