### ISSUE TITLE
Chord diagram

### ISSUE THREAD

**Issue by l-magnificence** [sqjin/CellChat#135]
When I draw the Chord diagram in my datasets, It is too small to be observed because the name of ident is too long.
How can I control the size of the Chord diagram to make the labels small and circle big like you draw in  tutorial without changing the name of ident? 
Thank you！
![image](https://user-images.githubusercontent.com/68798288/107138252-5935dd80-694e-11eb-9e17-4bb1f0db39ad.png)
![image](https://user-images.githubusercontent.com/68798288/107137897-b4b29c00-694b-11eb-82d0-944d544ea760.png)

**Comment by sqjin** [comment]
@l-magnificence You can modify the values of 'lab.cex' when using this function. You can also save it as PDF file by adjusting the height and width.

**Comment by l-magnificence** [comment]
modify the values of 'lab.cex' and save it as PDF file by adjusting the height and width only change the size of words and  increase the size of canvas but not the size of the circle.

**Comment by sqjin** [comment]
@l-magnificence Did you save the figure using R codes? You should do it via 'pdf(....),  ...., dev.off()'

**Comment by l-magnificence** [comment]
Thank you!
I know how to do it.
