### ISSUE TITLE
Some questions about install CellChat

### ISSUE THREAD

**Issue by liuzhe93** [sqjin/CellChat#136]
Hello, I am LIU Zhe.

Thanks for reading this message. I encountered a question when I installed your CellChat R package.
My code is that: install CellChat by using devtools
**> devtools::install_github("sqjin/CellChat")**
However, there are some error messages when I try to install it:
Downloading GitHub repo sqjin/CellChat@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/sqjin/CellChat/tarball/HEAD' failed
Could you give me some advice for solving?
Thank you so much.

Best wishes,
Zhe

**Comment by sqjin** [comment]
@liuzhe93 Are you installing it on the linux system? If so, please check #131

**Comment by liuzhe93** [comment]
> @liuzhe93 Are you installing it on the linux system? If so, please check #131

Yes~~ thank you so much for your quick reply and message.  OK, I will follow the solution from yancylau. Thank you so much.

**Comment by BinDuan** [comment]
> Hello, I am LIU Zhe.
> 
> Thanks for reading this message. I encountered a question when I installed your CellChat R package.
> My code is that: install CellChat by using devtools
> **> devtools::install_github("sqjin/CellChat")**
> However, there are some error messages when I try to install it:
> Downloading GitHub repo sqjin/CellChat@HEAD
> Error in utils::download.file(url, path, method = method, quiet = quiet, :
> download from 'https://api.github.com/repos/sqjin/CellChat/tarball/HEAD' failed
> Could you give me some advice for solving?
> Thank you so much.
> 
> Best wishes,
> Zhe

I have the same error when I tried to install this package, have you solved it and how?

**Comment by sqjin** [comment]
@BinDuan Have you checked the issue #131 ? You need to  "Finally I have make it by locally installing, but the *.so and *.o files in the src directory should be removed before installing ."

**Comment by Richard3110** [comment]
I have the same error when I tried to install this package on M1 macbook,  how can i solve it ?
