### ISSUE TITLE
CellChat applied to bulk RNAseq of separated cells?

### ISSUE THREAD

**Issue by Zhuang-Bio** [sqjin/CellChat#137]
Dear sqjin,

Thanks for your amazing CellChat package. I wonder if it can be applied to the bulk RNA-seq of separated cells, like I have bulk RNA-seq data of keratinocytes and fibroblasts from the same patients, can I analyze the cell-cell interaction or communication using the CellChat? The pipeline is similar to the single cell RNA-seq?
Looking forward to hearing from you.

Best,
Zhuang

**Comment by sqjin** [comment]
@Zhuang-Bio Hi, yes, it can be used to analyze the bulk data using the same pipeline. Please use `cellchat <- computeCommunProb(cellchat, raw.use = TRUE)` to infer cell-cell communication.
