### ISSUE TITLE
computeCommunProb  no 'dimnames' attribute for array

### ISSUE THREAD

**Issue by cnhaines01** [sqjin/CellChat#138]
Hi! 

I'm new to CellChat. I'm trying to get started from a Seurat object. I'm able to get the cellchat object set up but when I try to compute communication probability I keep getting an error that I have no dimnames. When I look at  cellchat@data I have Dimnames. I'm assuming it's a capitalization issue (Dimnames instead of dimnames). Is there something else I'm missing or is there a way to work around this? Any help would be much appreciated! I've included my code and the output below:

Code:
library(CellChat)
cellchat <- createCellChat(object = Met1.integrated, group.by = "seurat_clusters")
CellChatDB <- CellChatDB.mouse # use CellChatDB.human if running on human data
CellChatDB.use <- CellChatDB
cellchat@DB <- CellChatDB.use
cellchat <- computeCommunProb(cellchat, raw.use = TRUE, population.size = TRUE)
 
Output:
Create a CellChat object from a Seurat object
The `data` slot in the `RNA` assay is used 
The `meta.data` slot in the Seurat object is used as cell meta information 
Set cell identities for the new CellChat object
The cell groups used for CellChat analysis are  0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 
no non-missing arguments to max; returning -InfError in data.use[geneL[index.singleL], ] : 
  no 'dimnames' attribute for array

Thanks so much!!

**Comment by sqjin** [comment]
Hi, can you modify your labels starting from 1,2,3,..., 23? There might be issues if it starts from 0.  Please run `cellchat <- subsetData(cellchat) ` before inferring cell-cell communication.

**Comment by cnhaines01** [comment]
Thank you so much for getting back to me. I re-named my labels and ran subsetData before inferring cell-cell communication. When I ran cellchat <- computeCommunProb(cellchat, raw.use = TRUE, population.size = TRUE) I got this error:

Error in matrix(nrow = nLR, ncol = nC) : non-numeric matrix extent

Thank you for your help!

**Comment by sqjin** [comment]
@cnhaines01 Can you please make sure there is no clear issue of the following three parts: 1) Please check cellchat@data; 2) Please check cellchat@data.signaling; 3) cellchat@idents
