### ISSUE TITLE
Error in h(simpleError(msg, call)): error in evaluating the argument 'x' in selecting a method for function 'rowSums': subscript out of bounds

### ISSUE THREAD

**Issue by cartal** [sqjin/CellChat#139]
Hi, 

I'm having some issues running `cellchat`. 

After successfully transforming my `anndata` into a `cellchat` object, check it and I get this: 

```
An object of class CellChat created from a single dataset 
 33538 genes.
 75000 cells.
```

But when I try to proceed with the workflow by processing the gene expression matrix like this: 

```
cellchat <- identifyOverExpressedGenes(cellchat)
cellchat <- identifyOverExpressedInteractions(cellchat)
cellchat <- projectData(cellchat, PPI.human)
```

I get the following error:

```
Error in h(simpleError(msg, call)): error in evaluating the argument 'x' in selecting a method for function 'rowSums': subscript out of bounds
Traceback:

1. identifyOverExpressedGenes(cellchat)
2. rowSums(data.use[features, cell.use1, drop = FALSE] > thresh.min)
3. .handleSimpleError(function (cond) 
 . .Internal(C_tryCatchHelper(addr, 1L, cond)), "subscript out of bounds", 
 .     base::quote(data.use[features, cell.use1, drop = FALSE]))
4. h(simpleError(msg, call))
```

Do you think you could help me figure out what's causing this? 

Tahnk you!

**Comment by sqjin** [comment]
@cartal Can you please make sure there is no clear issue of the following three parts: 1) Please check `cellchat@data`; 2) Please check `cellchat@data.signaling`; 3) `cellchat@idents`

**Comment by cartal** [comment]
Hi, 

So this is how `head(cellchat@data)` looks: 

```
   [[ suppressing 34 column names ‘AAACGAAGTGAGACCA-1-H0015_apex’, ‘AAACGAATCACCCATC-1-H0015_apex’, ‘AAACGAATCGGCTATA-1-H0015_apex’ ... ]]

6 x 75000 sparse Matrix of class "dgCMatrix"
                                                                               
MIR1302-2HG . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
FAM138A     . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
OR4F5       . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
AL627309.1  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
AL627309.3  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
AL627309.2  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
                  
MIR1302-2HG ......
FAM138A     ......
OR4F5       ......
AL627309.1  ......
AL627309.3  ......
AL627309.2  ......

 .....suppressing 74966 columns in show(); maybe adjust 'options(max.print= *, width = *)'
 ..............................
```

and this is how `head(cellchat@idents)` looks:

```
vCM2 vCM2 vCM2 PC4_CMC-like vCM1 Adip2
```
but `cellchat@data.signaling` is empty.

**Comment by sqjin** [comment]
@cartal You should run `cellchat <- subsetData(cellchat)`. If you want to keep all features, you can provide the feature names.

**Comment by cartal** [comment]
That worked! Thank you very much!

**Comment by rosana08** [comment]
Hi, Thanks for the wonderful tool. Could you please help with an error in merging cellchat object?

> cellchat.UCI 
An object of class CellChat created from a single dataset 
 45068 genes.
 2297 cells.
> cellchat.CCI
An object of class CellChat created from a single dataset 
 45068 genes.
 2125 cells.
> object.list <- list(UCI = cellchat.UCI, CCI = cellchat.CCI)
> object.list
$UCI
An object of class CellChat created from a single dataset 
 45068 genes.
 2297 cells.
$CCI
An object of class CellChat created from a single dataset 
 45068 genes.
 2125 cells.
> cellchat <- mergeCellChat(object.list, add.names = names(object.list))
Error in `[.data.frame`(object.list[[i]]@meta, , meta.use, drop = FALSE) : 
  undefined columns selected

Looking forward for your valuable response!

**Comment by sqjin** [comment]
@rosana08 Can you check the meta data of your two cellchat object and make sure they have the same column names?

**Comment by rosana08** [comment]
Hi Suoqin Jin,

Many thanks for your response. The issue was because of NA columns in metadata, I could merge it by adding labels back to cellchat object using addMeta(). This is really an amazing tool! 

Kind regards,
Rosana

**Comment by Mo7tafa** [comment]
I am running R from VS code and I get the same error! 

Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'boxplot': undefined columns selected

**Comment by FlyingFa** [comment]
I am running monocle3 and get the same error
plot_cells(cds,
+            genes = "APOB",
+            label_cell_groups = FALSE,
+            show_trajectory_graph = FALSE,
+            min_expr = 3)
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 't': attempt to set an attribute on NULL

can anybody helps?
