### ISSUE TITLE
Future Error when running "netAnalysis_compute"

### ISSUE THREAD

**Issue by rlorenzc** [sqjin/CellChat#140]
Hi, 

I'm currently running into issues when I try to run the "netAnalysis_compute" function and it may have something to do with parallel processing. Any help to fix this problem would be great... 

This is the error that I get:
`UNRELIABLE VALUE: Future (‘future_sapply-1’) unexpectedly generated random numbers without specifying argument 'future.seed'. There is a risk that those random numbers are not statistically sound and the overall results might be invalid. To fix this, specify 'future.seed=TRUE'. This ensures that proper, parallel-safe random numbers are produced via the L'Ecuyer-CMRG method. To disable this check, use 'future.seed=NULL', or set option 'future.rng.onMisuse' to "ignore".UNRELIABLE VALUE: Future (‘future_sapply-2’) unexpectedly generated random numbers without specifying argument 'future.seed'. There is a risk that those random numbers are not statistically sound and the overall results might be invalid. To fix this, specify 'future.seed=TRUE'. This ensures that proper, parallel-safe random numbers are produced via the L'Ecuyer-CMRG method. To disable this check, use 'future.seed=NULL', or set option 'future.rng.onMisuse' to "ignore".UNRELIABLE VALUE: Future (‘future_sapply-3’) unexpectedly generated random numbers without specifying argument 'future.seed'. There is a risk that those random numbers are not statistically sound and the overall results might be invalid. To fix this, specify 'future.seed=TRUE'. This ensures that proper, parallel-safe random numbers are produced via the L'Ecuyer-CMRG method. To disable this check, use 'future.seed=NULL', or set option 'future.rng.onMisuse' to "ignore".UNRELIABLE VALUE: Future (‘future_sapply-4’) unexpectedly generated random numbers without specifying argument 'future.seed'. There is a risk that those random numbers are not statistically sound and the overall results might be invalid. To fix this, specify 'future.seed=TRUE'. This ensures that proper, parallel-safe random numbers are produced via the L'Ecuyer-CMRG method. To disable this check, use 'future.seed=NULL', or set option 'future.rng.onMisuse' to "ignore".UNRELIABLE VALUE: Future (‘future_sapply-5’) unexpectedly generated random numbers without specifying argument 'future.seed'. There is a risk that those random numbers are not statistically sound and the overall results might be invalid. To fix this, specify 'future.seed=TRUE'. This ensures that proper, parallel-safe random numbers are produced via the L'Ecuyer-CMRG method. To disable this check, use 'future.seed=NULL', or set option 'future.rng.onMisuse' to "ignore".UNRELIABLE VALUE: Future (‘future_sapply-6’) unexpectedly generated random numbers without specifying argument 'future.seed'. There is a risk that those random numbers are not statistically sound and the overall results might be invalid. To fix this, specify 'future.seed=TRUE'. This ensures that proper, parallel-safe random numbers are produced via the L'Ecuyer-CMRG method. To disable this check, use 'future.seed=NULL', or set option 'future.rng.onMisuse' to "ignore".UNRELIABLE VALUE: Future (‘future_sapply-7’) unexpectedly generated random numbers without specifying argument 'future.seed'. There is a risk that those random numbers are not statistically sound and the overall results might be invalid. To fix this, specify 'future.seed=TRUE'. This ensures that proper, parallel-safe random numbers are produced via the L'Ecuyer-CMRG method. To disable this check, use 'future.seed=NULL', or set option 'future.rng.onMisuse' to "ignore".UNRELIABLE VALUE: Future (‘future_sapply-8’) unexpectedly generated random numbers without specifying argument 'future.seed'. There is a risk that those random numbers are not statistically sound and the overall results might be invalid. To fix this, specify 'future.seed=TRUE'. This ensures that proper, parallel-safe random numbers are produced via the L'Ecuyer-CMRG method. To disable this check, use 'future.seed=NULL', or set option 'future.rng.onMisuse' to "ignore".`

**Comment by rlorenzc** [comment]
I reinstalled packages and this issue disappeared.

**Comment by sqjin** [comment]
@rlorenzc Please try the solution here (https://github.com/HenrikBengtsson/future/issues/624#issuecomment-1131916204)

**Comment by RuiyuRayWang** [comment]
@sqjin Hi, thanks for the prompt response!

I tried the solution but the issue persisted.
```
> suppressPackageStartupMessages({
+   library(CellChat)
+   library(future)
+ })
> cellchat <- readRDS("../data/cellchat.rds")
> plan(multisession, workers = 8) # do parallel
> options(parallelly.makeNodePSOCK.validate = (packageVersion("parallelly") > "1.31.1"))  # https://github.com/HenrikBengtsson/future/issues/624
> cellchat <- netAnalysis_computeCentrality(cellchat, slot.name = "netP") # the slot 'netP' means the inferred intercellular communication network of signaling pathways
Warning messages:
1: UNRELIABLE VALUE: One of the ‘future.apply’ iterations (‘future_sapply-1’) unexpectedly generated random numbers without declaring so. There is a risk that those random numbers are not statistically sound and the overall results might be invalid. To fix this, specify 'future.seed=TRUE'. This ensures that proper, parallel-safe random numbers are produced via the L'Ecuyer-CMRG method. To disable this check, use 'future.seed = NULL', or set option 'future.rng.onMisuse' to "ignore". 
2: UNRELIABLE VALUE: One of the ‘future.apply’ iterations (‘future_sapply-2’) unexpectedly generated random numbers without declaring so. There is a risk that those random numbers are not statistically sound and the overall results might be invalid. To fix this, specify 'future.seed=TRUE'. This ensures that proper, parallel-safe random numbers are produced via the L'Ecuyer-CMRG method. To disable this check, use 'future.seed = NULL', or set option 'future.rng.onMisuse' to "ignore". 
3: UNRELIABLE VALUE: One of the ‘future.apply’ iterations (‘future_sapply-3’) unexpectedly generated random numbers without declaring so. There is a risk that those random numbers are not statistically sound and the overall results might be invalid. To fix this, specify 'future.seed=TRUE'. This ensures that proper, parallel-safe random numbers are produced via the L'Ecuyer-CMRG method. To disable this check, use 'future.seed = NULL', or set option 'future.rng.onMisuse' to "ignore". 
4: UNRELIABLE VALUE: One of the ‘future.apply’ iterations (‘future_sapply-4’) unexpectedly generated random numbers without declaring so. There is a risk that those random numbers are not statistically sound and the overall results might be invalid. To fix this, specify 'future.seed=TRUE'. This ensures that proper, parallel-safe random numbers are produced via the L'Ecuyer-CMRG method. To disable this check, use 'future.seed = NULL', or set option 'future.rng.onMisuse' to "ignore". 
5: UNRELIABLE VALUE: One of the ‘future.apply’ iterations (‘future_sapply-5’) unexpectedly generated random numbers without declaring so. There is a risk that those random numbers are not statistically sound and the overall results might be invalid. To fix this, specify 'future.seed=TRUE'. This ensures that proper, parallel-safe random numbers are produced via the L'Ecuyer-CMRG method. To disable this check, use 'future.seed = NULL', or set option 'future.rng.onMisuse' to "ignore". 
6: UNRELIABLE VALUE: One of the ‘future.apply’ iterations (‘future_sapply-6’) unexpectedly generated random numbers without declaring so. There is a risk that those random numbers are not statistically sound and the overall results might be invalid. To fix this, specify 'future.seed=TRUE'. This ensures that proper, parallel-safe random numbers are produced via the L'Ecuyer-CMRG method. To disable this check, use 'future.seed = NULL', or set option 'future.rng.onMisuse' to "ignore". 
7: UNRELIABLE VALUE: One of the ‘future.apply’ iterations (‘future_sapply-7’) unexpectedly generated random numbers without declaring so. There is a risk that those random numbers are not statistically sound and the overall results might be invalid. To fix this, specify 'future.seed=TRUE'. This ensures that proper, parallel-safe random numbers are produced via the L'Ecuyer-CMRG method. To disable this check, use 'future.seed = NULL', or set option 'future.rng.onMisuse' to "ignore". 
8: UNRELIABLE VALUE: One of the ‘future.apply’ iterations (‘future_sapply-8’) unexpectedly generated random numbers without declaring so. There is a risk that those random numbers are not statistically sound and the overall results might be invalid. To fix this, specify 'future.seed=TRUE'. This ensures that proper, parallel-safe random numbers are produced via the L'Ecuyer-CMRG method. To disable this check, use 'future.seed = NULL', or set option 'future.rng.onMisuse' to "ignore". 
```
It seems that the issues is unrelated to the link you posted b.c. I never used `zn_CN` as my language setting.

Instead, I find a workaround simply by restarting R and not attaching to the `future` library, hence not using parallel computing feature before calling the `netAnalysis_computeCentrality` function:
```
> suppressPackageStartupMessages({
+   library(CellChat)
+ })
> cellchat <- readRDS("../data/cellchat.rds")
> cellchat <- netAnalysis_computeCentrality(cellchat, slot.name = "netP") # the slot 'netP' means the inferred intercellular communication network of signaling pathways
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=01s
```

Thanks!
Ray

**Comment by HenrikBengtsson** [comment]
This is because the future framework detects that one of your `future_sapply()` calls code that relies on the random number generator (RNG) in R, but you did not declare argument `future.seed = TRUE` in your call to `future_sapply()`.  This suggests you might get insufficient random numbers, which might bias your results.

This is something that needs to be fixed in **CellChat**.  To fix it, make sure to do:

```r
y <- future_sapply(..., future.seed = TRUE)
```

for the `future_sapply()` that triggers this warning.  To find which one it is, set `options(warn = 2L)` and then use `traceback()`.

**Comment by sqjin** [comment]
@HenrikBengtsson Do you have any idea how to add 'future.seed' in the cellchat codes below

    my.sapply <- ifelse(
      test = future::nbrOfWorkers() == 1,
      yes = pbapply::pbsapply,
      no = future.apply::future_sapply
    )
    centr.all = my.sapply(
      X = 1:nrun,
      FUN = function(x) {
        net0 <- net[ , , x]
        return(computeCentralityLocal(net0))
      },
      simplify = FALSE
    )

**Comment by HenrikBengtsson** [comment]
See https://github.com/sqjin/CellChat/issues/424, where I suggest dropping the yes/no thing and just use future.apply. In the long run, the easiest to maintain + you get progress updates everywhere.

Otherwise,

```r
my.sapply <- ifelse(
  test = future::nbrOfWorkers() == 1,
  yes = function(..., future.seed = FALSE) pbapply::pbsapply(...),
  no = future.apply::future_sapply
)
```

and pass as `my.sapply(..., future.seed = TRUE)`.

**Comment by sqjin** [comment]
@HenrikBengtsson Thanks. I will simply use the future.apply. 

By the way, is the performance of future::plan("multiprocess", workers = 4) the same as future::plan("multisession", workers = 4)?  I cannot remember clearly, but I think I have tried both last year and found that the running time is longer when using "multisession".  The parallel in CellChat is heavily dependent on the future package. 

Another thing confused me is the performance of different number of 'workers'. I found the running time is less when use 'workers = 4' compared to workers = 6 or 8.  I do not know why, but I found the 4 workers exhibit the least running time.

**Comment by HenrikBengtsson** [comment]
> By the way, is the performance of future::plan("multiprocess", workers = 4) the same as future::plan("multisession", workers = 4)?

'multiprocess' is deprecated and soon to be removed, so please forget about that one.  What it was, was that it was an alias to 'multicore' on Linux and macOS and 'multisession' on MS Windows.  I, and several others, concluded that this caused confusion and uncertainty, so, we decided to remove it. 

> I cannot remember clearly, ...

Which confirms why it's a good idea to remove it

> but I think I have tried both last year and found that the running time is longer when using "multisession"

So, if you tested on Linux or macOS, then you most likely effectively compared 'multicore' vs 'multisession'.  They are different parallel backends (of the **parallel** package) - see the docs.  'multicore' is not supported on MS Windows, it's unstable in the RStudio Console and other environments, so we recommend to use 'multisession'.  See <https://parallelly.futureverse.org/reference/supportsMulticore.html> and the links there-in for details.

> Another thing confused me is the performance of different number of 'workers'. I found the running time is less when use 'workers = 4' compared to workers = 6 or 8. I do not know why, but I found the 4 workers exhibit the least running time.

This is a FAQ in all parallel processing in all programming languages.  It simply depends on a lot of things and what code you're parallelizing.  There's always a point when the overhead of having more parallel workers becomes larger than the performance gain.

**Comment by jessicook** [comment]
Hello,

I'm having this same issue and can't figure out how to fix it. should running 
```
y <- future_sapply(..., future.seed = TRUE)
```

fix the issue? or do I need to add this to the function? I have limited experience in R so I'm a little confused about what the fix above is

**Comment by kpbradsh** [comment]
Hello, I'm struggling with the same error when I compute centrality in the CellChat tutorial. any help would be appreciated! Thank you.

**Warning messages:**
"1: UNRELIABLE VALUE: One of the ‘future.apply’ iterations (‘future_sapply-1’) unexpectedly generated random numbers without declaring so. There is a risk that those random numbers are not statistically sound and the overall results might be invalid. To fix this, specify 'future.seed=TRUE'. This ensures that proper, parallel-safe random numbers are produced via the L'Ecuyer-CMRG method. To disable this check, use 'future.seed = NULL', or set option 'future.rng.onMisuse' to "ignore". 

**Below is my code:**

library(CellChat)
library(patchwork)
options(stringsAsFactors = FALSE)
library(dplyr)
library(Matrix)
library(data.table)
library(ggplot2)
library(cowplot)
library(tidyr)
library(Seurat)

Raw_data <- Read10X(data.dir = 'matrix_files_all_mouse_gene')
metadata <- read.csv('metadata_allcells_mouse_gene_removed_pericytes_unknown.csv')
rownames(metadata) <- metadata$barcode
rownames(metadata)

data.input = Raw_data
meta = metadata
cell.use = rownames(meta)[meta$treatmentage == "young_sham"]

data.input = data.input[, cell.use]
meta = meta[cell.use, ]
unique(meta$labeledcelltype) 

cellchat <- createCellChat(object = data.input, meta = meta, group.by = "labeledcelltype")
cellchat <- addMeta(cellchat, meta = meta)
cellchat <- setIdent(cellchat, ident.use = "labeledcelltype")
levels(cellchat@idents) 
groupSize <- as.numeric(table(cellchat@idents)) # number of cells in each cell group

CellChatDB <- CellChatDB.mouse # use CellChatDB.mouse if running on mouse data
showDatabaseCategory(CellChatDB)

dplyr::glimpse(CellChatDB$interaction)

CellChatDB.use <- CellChatDB #use all
cellchat@DB <- CellChatDB.use
cellchat <- subsetData(cellchat)
future::plan("multisession", workers = 4) # do parallel

cellchat <- identifyOverExpressedGenes(cellchat)
cellchat <- identifyOverExpressedInteractions(cellchat)
cellchat <- computeCommunProb(cellchat, type = "truncatedMean", trim = 0.05) #added truncated mean and trim to 0.05 to allow more cells 
cellchat <- filterCommunication(cellchat, min.cells = 10)
df.net <- subsetCommunication(cellchat)
cellchat <- computeCommunProbPathway(cellchat)
cellchat <- aggregateNet(cellchat)
cellchat <- netAnalysis_computeCentrality(cellchat)
