### ISSUE TITLE
could not find function "netAnalysis_signalingRole"

### ISSUE THREAD

**Issue by DawnEve** [sqjin/CellChat#141]
Version 0.5.5 on R 3.6.3

the others functions are function, but can't find this function:

> library(CellChat)
> netAnalysis_signalingRole()
Error in netAnalysis_signalingRole() : 
  could not find function "netAnalysis_signalingRole"

**Comment by sqjin** [comment]
@DawnEve We replaced this function by `netAnalysis_computeCentrality`

**Comment by DawnEve** [comment]
OK, I have found the hind in the code, not the F1:

#' NB: This function was previously named as `netAnalysis_signalingRole`.  The previous function `netVisual_signalingRole` is now named as `netAnalysis_signalingRole_network`.
netAnalysis_computeCentrality <- function(object, slot.name = "netP", net = NULL, net.name = NULL) {
