### ISSUE TITLE
netAnalysis_signalingRole   Error in dimnames(net)[[3]]: subscript out of bounds

### ISSUE THREAD

**Issue by lvzenglei** [sqjin/CellChat#142]
Hi, 
 Thanks for developing this user-friendly tool. I have problem when I run the code follow: 
cellchat <- netAnalysis_signalingRole(cellchat, slot.name = "netP")

I got an error occurs: Error in dimnames(net)[[3]]: subscript out of bounds. The receptor and ligand of this pathway are in the same cluster. 

Can you help me with this problem? Thank you very much!

**Comment by sqjin** [comment]
@lvzenglei From version 0.5.5,  this function is replaced by `netAnalysis_computeCentrality`. Please check the tutorial on Compute and visualize the network centrality scores
