### ISSUE TITLE
0 signaling genes

### ISSUE THREAD

**Issue by aperl0401** [sqjin/CellChat#143]
Hi there, 

I am using CellChat to look at two different (mouse) samples, and get the following result:  

An object of class CellChat created from a merged object with multiple datasets   0 signaling genes.  8092 cells.

Explanation for why 0 signaling genes?

Many thanks!

**Comment by sqjin** [comment]
@aperl0401 Can you check `cellchat@data.signaling` to see if you have the combined data matrix?

**Comment by aperl0401** [comment]
cellchat@data.signaling looks fine when I run through the tutorial with a single sample, but returns a 0 x 6887 matrix when I try to merge two of cellChat objects (which worked fine as individual analyses).

**Comment by sqjin** [comment]
@aperl0401 Can you please run the source codes line by line to figure out the reason?  I have no idea on this issue without testing.

**Comment by lxwang326** [comment]
I have the same problem  with my own data from seurat

**Comment by sqjin** [comment]
@lxwang326 Are the meta slot have the same column names in the two object?  For such issues, the best practice is to run the sources codes line by line. I am sorry I cannot give any correct suggestions except that I can run your data and replicate the error.

**Comment by lxwang326** [comment]
> @lxwang326 Are the meta slot have the same column names in the two object? For such issues, the best practice is to run the sources codes line by line. I am sorry I cannot give any correct suggestions except that I can run your data and replicate the error.

than you .I have solved the problem by mergeing the rds

**Comment by Chestnusaur** [comment]
I was having the same problem earlier the day. Then I realized that I didn't ran full analysis for each dataset before merging them together. When I merge the objects after I ran full analysis for each dataset, everything works out

**Comment by reza2026131** [comment]
Could you please explain what you mean by "full analysis"? When I want to run cellchat <- subsetData(cellchat) on each dataset, I got the following error and it did not allow me to do other codes:
Error in UseMethod("select") : 
  no applicable method for 'select' applied to an object of class "NULL"

Thanks.
