### ISSUE TITLE
Problem with defining colours for chord plot with netVisual_aggregate

### ISSUE THREAD

**Issue by maddemaddi** [sqjin/CellChat#144]
Hi! I am using netVisual_aggregate for visualizing my data with both the "circle" and the "chord" layouts. I want to define the colours to match the ones I have used previously in my analysis and I managed to do so by defining the _color.use_ parameter.  However, this only seems to work for the circle plot and not for the chord plot. When using the colour parameter for the chord plot, only group labels are showing and no interactions. Should I define the colour parameter in a different manner with the "chord"-option or could this be a bug? I am confused because it is the same function after all. Thanks for the help:)

Here is my code:

> # Circle plot
> 
> par(mfrow=c(1,1))
> netVisual_aggregate(cellchat1, signaling = pathways.show, layout = "circle", color.use = colours_all)
> 
> # Chord plot
> 
> par(mfrow=c(1,1))
> netVisual_aggregate(cellchat1, signaling = pathways.show, layout = "chord", color.use = colours_all)
> 

Here is my session info:

> R version 4.0.3 (2020-10-10)
> Platform: x86_64-apple-darwin17.0 (64-bit)
> Running under: macOS Catalina 10.15.7
> 
> Matrix products: default
> BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
> LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] ggalluvial_0.12.3    NMF_0.23.0           cluster_2.1.0        rngtools_1.5         pkgmaker_0.32.2      registry_0.5-1       CellChat_0.5.5      
>  [8] igraph_1.2.6         GO.db_3.12.1         AnnotationDbi_1.52.0 IRanges_2.24.1       S4Vectors_0.28.1     Biobase_2.50.0       BiocGenerics_0.36.0 
> [15] umap_0.2.7.0         writexl_1.3.1        stringr_1.4.0        tibble_3.0.6         gapminder_0.3.0      patchwork_1.1.1      dplyr_1.0.4         
> [22] ggplot2_3.3.3        SeuratObject_4.0.0   Seurat_4.0.0        
> 
> loaded via a namespace (and not attached):
>   [1] utf8_1.1.4           reticulate_1.18      tidyselect_1.1.0     RSQLite_2.2.3        htmlwidgets_1.5.3    grid_4.0.3           Rtsne_0.15          
>   [8] devtools_2.3.2       munsell_0.5.0        codetools_0.2-16     ica_1.0-2            future_1.21.0        miniUI_0.1.1.1       withr_2.4.1         
>  [15] colorspace_2.0-0     rstudioapi_0.13      ROCR_1.0-11          tensor_1.5           listenv_0.8.0        labeling_0.4.2       polyclip_1.10-0     
>  [22] bit64_4.0.5          farver_2.0.3         rprojroot_2.0.2      coda_0.19-4          parallelly_1.23.0    vctrs_0.3.6          generics_0.1.0      
>  [29] xfun_0.20            R6_2.5.0             doParallel_1.0.16    clue_0.3-58          gg.gap_1.3           spatstat.utils_2.0-0 cachem_1.0.3        
>  [36] assertthat_0.2.1     promises_1.1.1       scales_1.1.1         gtable_0.3.0         Cairo_1.5-12.2       globals_0.14.0       processx_3.4.5      
>  [43] goftest_1.2-2        rlang_0.4.10         systemfonts_1.0.0    GlobalOptions_0.1.2  splines_4.0.3        lazyeval_0.2.2       BiocManager_1.30.10 
>  [50] reshape2_1.4.4       abind_1.4-5          httpuv_1.5.5         tools_4.0.3          usethis_2.0.0        gridBase_0.4-7       statnet.common_4.4.1
>  [57] ellipsis_0.3.1       RColorBrewer_1.1-2   sessioninfo_1.1.1    ggridges_0.5.3       Rcpp_1.0.6           plyr_1.8.6           purrr_0.3.4         
>  [64] ps_1.5.0             prettyunits_1.1.1    rpart_4.1-15         openssl_1.4.3        deldir_0.2-9         pbapply_1.4-3        GetoptLong_1.0.5    
>  [71] cowplot_1.1.1        zoo_1.8-8            ggrepel_0.9.1        fs_1.5.0             tinytex_0.29         magrittr_2.0.1       data.table_1.13.6   
>  [78] RSpectra_0.16-0      sna_2.6              scattermore_0.7      circlize_0.4.12      lmtest_0.9-38        RANN_2.6.1           fitdistrplus_1.1-3  
>  [85] matrixStats_0.58.0   pkgload_1.1.0        mime_0.9             xtable_1.8-4         gridExtra_2.3        shape_1.4.5          testthat_3.0.1      
>  [92] compiler_4.0.3       KernSmooth_2.23-18   crayon_1.4.1         htmltools_0.5.1.1    mgcv_1.8-33          later_1.1.0.1        tidyr_1.1.2         
>  [99] DBI_1.1.1            ComplexHeatmap_2.6.2 MASS_7.3-53          Matrix_1.2-18        cli_2.3.0            forcats_0.5.1        pkgconfig_2.0.3     
> [106] plotly_4.9.3         foreach_1.5.1        svglite_1.2.3.2      webshot_0.5.2        callr_3.5.1          digest_0.6.27        sctransform_0.3.2   
> [113] RcppAnnoy_0.0.18     rle_0.9.2            spatstat.data_1.7-0  leiden_0.3.7         uwot_0.1.10          gdtools_0.2.3        shiny_1.6.0         
> [120] rjson_0.2.20         lifecycle_0.2.0      nlme_3.1-149         jsonlite_1.7.2       network_1.16.1       fansi_0.4.2          desc_1.2.0          
> [127] viridisLite_0.3.0    askpass_1.1          pillar_1.4.7         lattice_0.20-41      fastmap_1.1.0        httr_1.4.2           pkgbuild_1.2.0      
> [134] survival_3.2-7       glue_1.4.2           remotes_2.2.0        FNN_1.1.3            spatstat_1.64-1      png_0.1-7            iterators_1.0.13    
> [141] bit_4.0.4            stringi_1.5.3        blob_1.2.1           memoise_2.0.0        irlba_2.3.3          future.apply_1.7.0  

**EDIT: The same thing is relevant for the netVisual_individual function**

**Comment by sqjin** [comment]
@maddemaddi The bug should be fixed. Can you please re-install the package and see if it works?

**Comment by maddemaddi** [comment]
Hi, thanks for the quick reply. I re-installed and it works perfectly now:) Thanks a lot!

Br,
Madeleine
