### ISSUE TITLE
Customized database

### ISSUE THREAD

**Issue by wyxwyx96** [sqjin/CellChat#145]
Hi,

Can I customize the database? I have interaction and geneInfo files, but don't have complex and cofactor files. Can I just upload the interaction and geneInfo files and leave the other two blank?

**Comment by sqjin** [comment]
@wyxwyx96 Yes, you can just update the interaction file and do not need to change the other two files.

**Comment by wyxwyx96** [comment]
> @wyxwyx96 Yes, you can just update the interaction file and do not need to change the other two files.

Thank you for the reply. What if I only use my upload interactions? Do I still need to keep the complex and cofactor files as default?

**Comment by sqjin** [comment]
@wyxwyx96 In such case, you can leave the columns of related cofactors empty. If there is no complex, it will be use the complex file.
