### ISSUE TITLE
error for CellChat installation

### ISSUE THREAD

**Issue by biohubx** [sqjin/CellChat#146]
Hi,
   when I used `devtools::install_github("sqjin/CellChat")` to install CellChat in **OS: RedHat 7 x86_64**, I got this error:

Error: package or namespace load failed for ‘svglite’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/nas/longleaf/home/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-svglite/00new/svglite/libs/svglite.so':
  /nas/longleaf/apps/gcc/6.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /nas/longleaf/home/hubenxia/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-svglite/00new/svglite/libs/svglite.so)
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/nas/longleaf/home/R/x86_64-pc-linux-gnu-library/3.6/svglite’
Error: Failed to install 'CellChat' from GitHub:
  (converted from warning) installation of package ‘svglite’ had non-zero exit status

Do you have any comments to solve this problem?
Best,

**Comment by sqjin** [comment]
@biohubx Have you checked the instruction of installing package on the linux systems in the README file?

**Comment by biohubx** [comment]
yes, I followed the Installation on Windows, Linux and Centos: Please check the solution for Windows and Linux, I can not find the resolution related to the error I got

**Comment by sqjin** [comment]
@biohubx  Can you try to explicitly install `svglite`?

**Comment by nawazahid** [comment]
Hi Sqjin, I tried installing on Windows, however gives an error

Error: (converted from warning) package 'dplyr' was built under R version 4.0.4
Execution halted
ERROR: lazy loading failed for package 'CellChat'
* removing 'C:/Users/nawazz/Documents/R/win-library/4.0/CellChat'
Error: Failed to install 'CellChat' from GitHub:
  (converted from warning) installation of package ‘C:/Users/nawazz/AppData/Local/Temp/RtmpKkewYC/fileb4d072f841f4/CellChat_1.0.0.tar.gz’ had non-zero exit status

**Comment by sqjin** [comment]
@nawazahid You might can try to re-install a lower version of dplyr

**Comment by weikekaifa** [comment]
Dear, 
when I used devtools::install_github("sqjin/CellChat") to install CellChat in R 4.0.2 version in windows 10. I  got a ERROR: lazy loading failed for package 'CellChat'
* removing 'C:/Users/qizha/Documents/R/win-library/4.0/CellChat'
错误: Failed to install 'CellChat' from GitHub:
  (由警告转换成)installation of package ‘C:/Users/qizha/AppData/Local/Temp/RtmpU56A9A/file586459837ebb/CellChat_1.0.0.tar.gz’ had non-zero exit status.

Do you have any comments to solve this problem? 
Or, i would like install it from local package. How can i install it? 
Best,

**Comment by weikekaifa** [comment]
Dear,
when I used devtools::install_github("sqjin/CellChat") to install CellChat in R 4.0.2 version in windows 10. I got a ERROR: lazy loading failed for package 'CellChat'

removing 'C:/Users/ Documents/R/win-library/4.0/CellChat'
错误: Failed to install 'CellChat' from GitHub:
(由警告转换成)installation of package ‘C:/Users/qizha/AppData/Local/Temp/RtmpU56A9A/file586459837ebb/CellChat_1.0.0.tar.gz’ had non-zero exit status.
Do you have any comments to solve this problem?
Or, i would like install it from local package. How can i install it?
Best,

**Comment by weikekaifa** [comment]
亲爱的，
When i used the command "devtools :: install_github（“ sqjin / CellChat”）" in R 4.0.4 version or 4.0.2 version in windows 10，I got  errors：

C:/rtools40/mingw64/bin/g++ -std=gnu++11 -shared -s -static-libgcc -o CellChat.dll tmp.def CellChat_Rcpp.o RcppExports.o -LE:/R-4.0.2/bin/x64 -lR
installing to C:/Users/Documents/R/win-library/4.0/00LOCK-CellChat/00new/CellChat/libs/x64
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
错误: (由警告转换成)程辑包'dplyr'是用R版本4.0.4 来建造的
停止执行
ERROR: lazy loading failed for package 'CellChat'
* removing 'C:/Users/qizha/Documents/R/win-library/4.0/CellChat'
错误: Failed to install 'CellChat' from GitHub:
  (由警告转换成)installation of package ‘C:/Users/qizha/AppData/Local/Temp/RtmpU56A9A/file586439997399/CellChat_1.0.0.tar.gz’ had non-zero exit status

Do you have any suggestion? Or , can i install in local package?
Best,

**Comment by weikekaifa** [comment]
> Hi Sqjin, I tried installing on Windows, however gives an error
> 
> Error: (converted from warning) package 'dplyr' was built under R version 4.0.4
> Execution halted
> ERROR: lazy loading failed for package 'CellChat'
> 
> * removing 'C:/Users/nawazz/Documents/R/win-library/4.0/CellChat'
>   Error: Failed to install 'CellChat' from GitHub:
>   (converted from warning) installation of package ‘C:/Users/nawazz/AppData/Local/Temp/RtmpKkewYC/fileb4d072f841f4/CellChat_1.0.0.tar.gz’ had non-zero exit status

Have you solved it? I met the same error.

**Comment by sqjin** [comment]
@weikekaifa Have you checked the solution [here](https://github.com/sqjin/CellChat/issues/5)?  If you want to install it locally, you can download the source codes and then type 
`install.packages(path_to_file, type = 'source', rep = NULL) # The path_to_file would represent the full path and file name`

**Comment by vishnums007** [comment]
> > Hi Sqjin, I tried installing on Windows, however gives an error
> > Error: (converted from warning) package 'dplyr' was built under R version 4.0.4
> > Execution halted
> > ERROR: lazy loading failed for package 'CellChat'
> > 
> > * removing 'C:/Users/nawazz/Documents/R/win-library/4.0/CellChat'
> >   Error: Failed to install 'CellChat' from GitHub:
> >   (converted from warning) installation of package ‘C:/Users/nawazz/AppData/Local/Temp/RtmpKkewYC/fileb4d072f841f4/CellChat_1.0.0.tar.gz’ had non-zero exit status
> 
> Have you solved it? I met the same error.

Did you solve the error? I am having the same issue. I don't understand the solution @sqjin is suggesting.

**Comment by vishnums007** [comment]
Ohk, I tried different dplyr versions.
Finally it worked when I installed the following version.  

  | dplyr_1.0.2.tar.gz

**Comment by Hi-ZSY** [comment]
Hi Sqjin, I tried to install CellChat by 

> devtools::install_github("sqjin/CellChat")

 , however gives an error: 
Error in readRDS(nsInfoFilePath) : error reading from connection
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace -> readRDS
Execution halted
ERROR: lazy loading failed for package ‘CellChat’
* removing ‘/home/haohe/R/x86_64-pc-linux-gnu-library/4.1/CellChat’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/Rtmpiz8nxf/file3b5c7a28239b/CellChat_1.6.1.tar.gz’ had non-zero exit status

I have download the newest version of 'NMF'(0.26) and 'circlize'(0.4.15). 
Do you have any comments to solve this problem?
Best,
