### ISSUE TITLE
Comparison analysis of multiple datasets using CellChat

### ISSUE THREAD

**Issue by zhangqi234** [sqjin/CellChat#148]
Hi,
Thanks for developing this user-friendly tool.
I have problem when I run the code follow:
Problem1:
object.list <- list(N = Normal, C = PrimaryCancer,M=MetastasisCancer)
cellchat <- mergeCellChat(object.list, add.names = names(object.list))
Can I do that?

Problem2:
gg1 <- compareInteractions(cellchat, show.legend = F, group = c(1,2,3)),and this code is right?

Problem3:
netVisual_diffInteraction(cellchat, weight.scale = T),how to show the specific interaction in Normal,Primary Cancer and Metastasis Cancer.

Thanks.

**Comment by sqjin** [comment]
@zhangqi234 Your first two questions look good. For your third question, you can see the tutorial on '### Compare the overall information flow of each signaling pathway'  and '# Part III: Identify the upgulated and down-regulated signaling ligand-receptor pairs'

**Comment by apal6** [comment]
Hi Suoqin,
<img width="530" alt="Screenshot 2023-07-31 at 1 17 34 PM" src="https://github.com/sqjin/CellChat/assets/127814354/e62658e0-d245-4cf1-8d5b-7f60422032ce">

I have merged 3 cellchat objects (based on conditions) and and when I am trying to run the analysis from "Identify the upgulated and down-regulated signaling ligand-receptor pairs", I see only two conditions getting plotted. Not sure why is that happening even if the compareInteraction function shows all three conditions. Could you help? 

Best,
Aastha
