### ISSUE TITLE
How to reorder cells for visualization in late analysis

### ISSUE THREAD

**Issue by wjzacharias** [sqjin/CellChat#149]
Hello, I would like to manually reorder my cell populations after running cellchat to match orders from other visualizations. It seems I should be able to do this by adding metadata and then changing idents. I used the example you provided for changing names after analysis, but was unable to change the full set of cell identities this way. Is there a reasonable way to reorder the cell groups once the analysis has occurred? Thanks!

**Comment by sqjin** [comment]
@wjzacharias Currently CellChat does not support this function.  Can you try the function below

#' Set the default identity of cells
#' @param object CellChat object
#' @param ident.use the name of the variable in object.meta;
#' @param levels set the levels of factor
#' @return
#' @export
#'
#' @examples
setIdent <- function(object, ident.use = NULL, levels = NULL){
  object@idents <- as.factor(object@meta[[ident.use]])
  if (!is.null(levels)) {
    object@idents <- factor(object@idents, levels = levels)
  }
  if (length(object@net) > 0) {
    if (all(dimnames(object@net$prob)[[1]] %in% levels(object@idents) )) {
      message("Reorder cell groups! ")
      idx <- match(dimnames(object@net$prob)[[1]], levels(object@idents))
      object@net$prob <- object@net$prob[idx, idx, ]
      object@net$pval <- object@net$pval[idx, idx, ]
      cat("The cell group order after reordering is ", dimnames(object@net$prob)[[1]],'\n')
    } else {
      message("Rename cell groups but do not change the order! ")
      cat("The cell group order before renaming is ", dimnames(object@net$prob)[[1]],'\n')
      dimnames(object@net$prob) <- list(levels(object@idents), levels(object@idents), dimnames(object@net$prob)[[3]])
      dimnames(object@net$pval) <- dimnames(object@net$prob)
      cat("The cell group order after renaming is ", dimnames(object@net$prob)[[1]],'\n')
    }

  }
  return(object)
}

**Comment by wjzacharias** [comment]
@sqjin - thanks for making this great tool and for your rapid response to questions!

The function you made successfully reordered my cells.  

The code I used was:

#stash cell labels in scRNA object metadata
object$cellgroup <- Idents(object)

# Add cell labels to cellchat metadata
identity = data.frame(group = object$cellgroup, row.names = names(object$cellgroup)) 
unique(identity$group)
cellchat <- addMeta(cellchat, meta = identity, meta.name = "cell_type")
levels(cellchat@idents) #check idents are correct

#Reorder cells
cellchat <- setIdent(cellchat, ident.use = "cell_type") # set "cell_type" as default cell identity
levels(cellchat@idents)

This successfully reordered my cell groups in the order I had established in my scRNA object for other visualization.

**Comment by sqjin** [comment]
@wjzacharias Have you re-run `computeCommunProbPathway` , `cellchat <- aggregateNet(cellchat)`, `cellchat <- netAnalysis_computeCentrality(cellchat, slot.name = "netP") `. 

All the calculations after `computeCommunProb` should be re-run!

**Comment by wjzacharias** [comment]
@sqjin - you are right, I forgot to rerun the later analyses steps! Once I have re-run those calculations, the reordering is consistent with all visualizations. Thanks for your help!

**Comment by gt7901b** [comment]
Hi, @sqjin 
a somewhat related question, I have two seurat object with the same cell types, but when I ran 
cellchat <- setIdent(cellchat, ident.use = "labels")
two cellchat objects have different orders of the same cell types, the subsequent circle plot shows different color for the same cell type. 
Do I need to run this modified setIdent() to avoid this situation?
just do cellchat <- setIdent(cellchat) on both objects or just one?

thanks

**Comment by sqjin** [comment]
@gt7901b You can simply address this issue by defining the factor levels in your labels.  `object1@meta$labels = factor(object1@meta$labels, levels = labels.levels)` and `object2@meta$labels = factor(object2@meta$labels, levels = labels.levels)`

**Comment by gt7901b** [comment]
@sqjin, thanks for your reply. I tried the command, but it says object 'labels.levels' not found

**Comment by sqjin** [comment]
@gt7901b You need to define 'labels.levels'  by yourself.

**Comment by sqjin** [comment]
@gt7901b I think this is due to your incorrect use of factor() function. You should check unique(object2@meta$labels) and figure out how to use factor function.

**Comment by BatLaB-cell** [comment]
@sqjin Dear sqjin, I think this is an important code you should add to your beautiful vignette/tutorial because it would be broadly used by a lot of cellchat users. 

I don't exactly understand when we must use this reordering code in the cellchat process. 

Could you clarify please at which step we should use this code?

Just after createCellChat function for instance?

Thank you for your help



> @wjzacharias Currently CellChat does not support this function. Can you try the function below
> 
> #' Set the default identity of cells #' @param object CellChat object #' @param ident.use the name of the variable in object.meta; #' @param levels set the levels of factor #' @return #' @export #' #' @examples setIdent <- function(object, ident.use = NULL, levels = NULL){ object@idents <- as.factor(object@meta[[ident.use]]) if (!is.null(levels)) { object@idents <- factor(object@idents, levels = levels) } if (length(object@net) > 0) { if (all(dimnames(object@net$prob)[[1]] %in% levels(object@idents) )) { message("Reorder cell groups! ") idx <- match(dimnames(object@net$prob)[[1]], levels(object@idents)) object@net$prob <- object@net$prob[idx, idx, ] object@net$pval <- object@net$pval[idx, idx, ] cat("The cell group order after reordering is ", dimnames(object@net$prob)[[1]],'\n') } else { message("Rename cell groups but do not change the order! ") cat("The cell group order before renaming is ", dimnames(object@net$prob)[[1]],'\n') dimnames(object@net$prob) <- list(levels(object@idents), levels(object@idents), dimnames(object@net$prob)[[3]]) dimnames(object@net$pval) <- dimnames(object@net$prob) cat("The cell group order after renaming is ", dimnames(object@net$prob)[[1]],'\n') }
> 
> } return(object) }

**Comment by sqjin** [comment]
@BatLaB-cell Please check `updateClusterLabels` to update cell cluster labels without re-running the time-consuming function computeCommunProb.

**Comment by mesposit** [comment]
Dear @sqjin, 

Thank you very much for creating this awesome tool!

I also have a question concerning this issue: I want to compare two time points in my data and to make sure that the visualizations are easy to read, I want to set the order of the cell types using `updateClusterLabels`. Here is my code:

``` R
# import both CellChat objects that were pre-processed independently
cellchat.00wks <- readRDS("cellchatobject_p0700wks.rds")
cellchat.06wks <- readRDS("cellchatobject_p0706wks.rds")
# make sure they are both the most recent version
cellchat.00wks <- updateCellChat(cellchat.00wks)
cellchat.06wks <- updateCellChat(cellchat.06wks)
# make sure both objects use same order of cell type labels
updateClusterLabels(cellchat.00wks, new.order = c("T", "CD14 Mono", "NK", 
                                                  "Intermediate Mono", "B memory & intermediate", 
                                                  "CD16 Mono", "Conventional DC", "B naive", "Plasmacytoid DC"))
updateClusterLabels(cellchat.06wks, new.order = c("T", "CD14 Mono", "NK", 
                                                  "Intermediate Mono", "B memory & intermediate", 
                                                  "CD16 Mono", "Conventional DC", "B naive", "Plasmacytoid DC"))
# merge the two objects
object.list <- list(baseline = cellchat.00wks, week6 = cellchat.06wks)
cellchat <- mergeCellChat(object.list, add.names = names(object.list))
```
This seems to work fine, but when I do the two separate circle plots according to your vignette, the cell type labels show up in different positions and are shown in different colors. Please find below my code as well as a screenshot of the resulting figure:

``` R
weight.max <- getMaxWeight(object.list, attribute = c("idents","count"))
par(mfrow = c(1,2), xpd=TRUE)
for (i in 1:length(object.list)) {
  netVisual_circle(object.list[[i]]@net$count, weight.scale = T, label.edge= F, edge.weight.max = weight.max[2], edge.width.max = 12, title.name = paste0("Number of interactions - ", names(object.list)[i]))
}
```

![grafik](https://github.com/sqjin/CellChat/assets/137409427/391ea790-9ea4-4f25-885b-220e9b19f363)


Do you have any idea what might be the issue here? Thanks a lot in advance!

**Comment by PraiseGithub** [comment]
@mesposit 

Hello, I think the 'updateClusterLabels' has to be performed after the 'computeCommunProb' function.

........
cellchat@DB <- CellChatDB.use
cellchat <- subsetData(cellchat)
cellchat <- identifyOverExpressedGenes(cellchat)
cellchat <- identifyOverExpressedInteractions(cellchat)
cellchat <- projectData(cellchat, PPI.mouse)
cellchat <- computeCommunProb(cellchat, raw.use = FALSE)


cellchat <- updateClusterLabels(cellchat, new.order = c("Celltype1", "Celltype2", "Celltype3"))


cellchat <- filterCommunication(cellchat, min.cells = 10)
cellchat <- computeCommunProbPathway(cellchat)
cellchat <- aggregateNet(cellchat)
cellchat <- netAnalysis_computeCentrality(cellchat, slot.name = "netP")
....

Thats what was stated, hope it works for you as well
