### ISSUE TITLE
mergeCellChat and "names do not match previous names"

### ISSUE THREAD

**Issue by sanjeevRJMU1** [sqjin/CellChat#151]
Hi,

Thanks for making this tool and making the tutorial so detailed!!

I'm able to take a seurat object and run thru the standard workflow just fine. I then broke up my seurat object into 2 objects (WT and KO), converted to 2 separate cellchat objects, and ran both in cellchat until the aggregateNet step. I then tried to merge the 2 cellchat objects and am running into this error:

object.list <- list(WT = WT_cellchat, KO = KO_cellchat)
> head(names(object.list))
[1] "WT" "KO"

cellchat <- mergeCellChat(object.list, add.names = names(object.list))
Error in match.names(clabs, names(xi)) : 
  names do not match previous names

The only thing I can see in that the @net slot has different values between the 2 objects for prob and pval but otherwise I don't see what could be wrong. Any help would be greatly appreciated!!

**Comment by sqjin** [comment]
@sanjeevRJMU1 Sorry, this is the first time I heard about this error. Can you please run the source code of the function `mergeCellChat` to figure out the reason?

**Comment by khomicsk** [comment]
Wonderful tool.

I had the an identical problem as above.

**Comment by sqjin** [comment]
@sanjeevRJMU1 @khomicsk Can you check if you have different column names in object.list[[i]]@meta between the two objects?

**Comment by sanjeevRJMU1** [comment]
@sqjin , I have absolutely no idea why but I re-tried the command today (having re-started Rstudio) and I do not get the same error....everything is working just fine with the standard commands.... ??? Sorry I could not be more helpful but for me, the issue is resolved (somehow!). Thanks again for this package -- its really fantastic!

**Comment by khomicsk** [comment]
**@sqjin**  found the problem in the object.list[[i]]@meta. Thanks a lot!

**Comment by NeoLucy** [comment]
I have the same error when I merge two cellchat objects. After that, I run the code as suggested.
a <- object.list[[1]]@meta
View(a)

b <- object.list[[2]]@meta
View(b)

Here is the image I captured.
<img width="416" alt="a" src="https://user-images.githubusercontent.com/73898181/174760121-a3d8d847-96ea-4567-a969-577524f54e48.png">
<img width="469" alt="b" src="https://user-images.githubusercontent.com/73898181/174760139-2e0d8a3c-f311-4843-ad20-ab0a071312d2.png">

**Comment by sqjin** [comment]
@NeoLucy You should have the same column names in object.list[[i]]@meta between the two objects.

**Comment by maqingyue** [comment]
Hello, I also have the same problem. I ran object.list [[i]]@meta on the tutorial data and my data respectively. The data in the tutorial are different prefixes, and my data are also different prefixes. Why does my data have this error? Figure 1 is the data in the tutorial, and Figure 2 is my data.

fig.1
![图1](https://user-images.githubusercontent.com/113956599/223599026-056afe49-0f0b-4e9a-a3c8-324bcb0274f1.png)

fig.2
![图2](https://user-images.githubusercontent.com/113956599/223599051-b3d700c9-0769-46db-b585-3d8d3dcf6a8f.png)
