### ISSUE TITLE
Warning with identifyOverExpressedGenes on merged object

### ISSUE THREAD

**Issue by jv-20** [sqjin/CellChat#152]
Hi @sqjin

Congratulations on the official publication of cellchat paper. Very nice work

I am trying to identify UP and DOWN regulated LR pairs and followed the tutorial on comparing two datasets # Part III: Identify the up-regulated and down-regulated signaling ligand-receptor pairs. I am receiving the following warning message. I was wondering if you would be able to give some advice on this.  Thank you

```
cellchat <- identifyOverExpressedGenes(cellchat.merged, group.dataset = "datasets", pos.dataset = pos.dataset, features.name = features.name, only.pos = FALSE)

There were 50 or more warnings (use warnings() to see the first 50)
 warnings()
Warning messages:
1: In wilcox.test.default(data1[x, ], data2[x, ]) :
  cannot compute exact p-value with ties
```

**Comment by sqjin** [comment]
@jv-20 You can just ignore such warnings. The warning happens depending on the data
