### ISSUE TITLE
Verbose Option for ComputeCommunProb

### ISSUE THREAD

**Issue by wht10** [sqjin/CellChat#153]
Hello @sqjin 

Thanks for developing such a useful tool!

I am in the process of going through the tutorial for the first time and have been getting stuck at the `ComputeCommunProb()`  function for some time. I have 16GB of RAM and  and haven't had issues with handling large Seurat objects previously. 

The `@data.signaling` object is 719 x 5995. 

Would it be possible to add a verbose = T option for some of the longer computations to allow for printing of a progress bar in the console? 

It is currently hard for me to know if the calculation will finish or if it needs to be terminated.

**Comment by sqjin** [comment]
@wht10 Thanks for your nice suggestion. I will look into it. How long does it take eventually?

**Comment by wht10** [comment]
@sqjin On my system, `computeCommunProb()` takes about 45min.-1hr when the `@data.signaling` object is between 719x5789 - 719 x 5995. 

```
> future::plan("multiprocess", workers = 4) # do parallel
> cc.WT <- identifyOverExpressedGenes(cc.WT)
> cc.WT <- identifyOverExpressedInteractions(cc.WT)
> tic()
> cc.WT <- computeCommunProb(cc.WT, raw.use = T,population.size = T)
> toc()
2634.6 sec elapsed

> sessionInfo()
R version 4.0.4 (2021-02-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

> detectCores()
[1] 4

> Sys.meminfo()
Totalram:  15.887 GiB 
Freeram:    5.647 GiB 
```

**Comment by sqjin** [comment]
@wht10 Thanks! Can you please let me know how many cell types in yr data?

**Comment by wht10** [comment]
Thank you for continuing to look into it!

There are 17. 

```
> levels(cc.KO@idents)
 [1] "Apoe+ TAM"     "DC-like TAM"   "Nos2+ TAM"     "Microglia"     "cMono"         "non-cMono"     "Neut"         
 [8] "Baso"          "DC1"           "DC2"           "DC3"           "pDC"           "B Cell"        "NK Cell"      
[15] "CD8 TIL"       "CD4 TIL"       "Stem-Like TIL"
```
