### ISSUE TITLE
sources.use in netVisual_aggregate not working

### ISSUE THREAD

**Issue by vravik** [sqjin/CellChat#154]
Dear sqjin, thank you for making this wonderful package available to the research community. 
I'm facing a small issue with visualizing the pathway interaction map between cell types. 
I have about 10 cell types in my dataset, and I'd like to visualize the interactions happening only between a subset of them for a specific pathway. 

When I try to set the sources.use parameter, I keep getting this error message:

Error in polygon(p[1, ], p[2, ], border = color, lwd = width, lty = lty) : 
  invalid value specified for graphical parameter "lwd"

Could you please tell me what I'm doing wrong and how to fix it?

Here is my function call: netVisual_aggregate(cellchat, signaling = "THY1", 
                    layout = "circle", sources.use = c(3,5,6,7))

Thank you,

**Comment by vravik** [comment]
Dear sqjin, could i please get your email ID to share the data matrix with you?
Thank you

**Comment by sqjin** [comment]
@vravik Have you fixed this issue? I remember you shared me a dropbox link of your data. But somehow I cannot find it now. Can you share me again? You can also find the email address in the README file.

**Comment by vravik** [comment]
Dear sqjin, 
no i haven't had any luck fixing it. All i could do was repeat the analysis excluding specific cell types i don't want to visualize, but this is obviously not a solution. I shared a box folder with your uci email id, with my R object and my analysis script. I'm sharing it again with cellchat.package@gmail.com.

**Comment by sqjin** [comment]
@vravik Can you re-install the package? The issue should be fixed.

**Comment by vravik** [comment]
Dear sqjin,

it works perfectly now. Thank you so much for your help!
