### ISSUE TITLE
Options in "netVisual_embedding" and Summary of CellChat?

### ISSUE THREAD

**Issue by phoebee-h** [sqjin/CellChat#155]
Hi,
Thanks for such an amazing CellChat package! I wonder:

(1) Is there an option (eg. set.seed) for the UMAP plot of "Structural" or "Functional" network estimation, so that the results could be the same in each computation? (As below, even though they are mathematically the same...)
![image](https://user-images.githubusercontent.com/28743573/110761677-fb691e00-828a-11eb-88e7-4632ad7539e6.png)

(2) Is there a chart for summarizing the results (eg. p-value or something for sorting), since I could get plenty of cell-cell communication possibilities?

Thank you, 
Phoebe.

**Comment by sqjin** [comment]
@phoebee-h Thanks for bringing it out. I will look into this issue next week. For your second question, I am not quite understanding it. Can you check `subsetCommunication` function to see if it provides results you need?

**Comment by phoebee-h** [comment]
Hi, 
I've checked the function `subsetCommunication`, which indeed helps! However, I'm not quite sure about the pval colum:
(1) Why it only contains values under 0.05? But in the slot `net`, I can see far more than that?
(2) Why the p-values are not that continuous, which means they seem to categorize in certain intervals?

`net <- subsetCommunication(cellchat, slot.name="net")`

![image](https://user-images.githubusercontent.com/28743573/112783475-fe814e00-9081-11eb-864e-2fbfd1977e56.png)
![image](https://user-images.githubusercontent.com/28743573/112783539-207ad080-9082-11eb-8fdf-08c0e146d0b1.png)
![image](https://user-images.githubusercontent.com/28743573/112783269-887ce700-9081-11eb-811c-7fcc59c98cb2.png)


Thank you,
Phoebe.

**Comment by sqjin** [comment]
@phoebee-h Sorry, I missed your questions. (1) You can set thresh parameter to include more interactions; (2) We use a simple permutation test, where you can find it in our method section in the paper. This method will produce values like what you were showing.

**Comment by phoebee-h** [comment]
I see.
Thank you very much.
