### ISSUE TITLE
Error with subsetted Seurat object 

### ISSUE THREAD

**Issue by leawenger** [sqjin/CellChat#156]
Hello @sqjin, 

Thanks for such an amazing tool and for the detailed tutorial! 

I have managed to run the entire pipeline on particular data I loaded from Seurat, but only in very specific conditions and I can't seem to figure out why...

When I load the whole object data slot in, computeCommunProb() works. However, when I subset my data to remove a cell type or a condition, it only works for particular subsets. When the subsetting works (eg removing a condition from a merged object) I don't get any errors. However if I for instance try to remove a cell type from the analysis by subsetting my Seurat object to include all but that cell type, I get the following error: 

cellchat2 <- computeCommunProb(cellchat2, raw.use = TRUE)
Error in Prob[, , i] <- Pnull : 
  number of items to replace is not a multiple of replacement length

I have 4 conditions merged in one object (without batch correction as sequenced together). I have also received this error when subsetting to one of my conditions but not the other, although I cannot tell the difference between them. 

Many thanks in advance for your help!! 

Kind regards, 

Léa

This is my object: str(cellchat2)
Formal class 'CellChat' [package "CellChat"] with 14 slots
  ..@ data.raw      : num[0 , 0 ] 
  ..@ data          :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. ..@ i       : int [1:144476533] 9 16 20 23 28 38 40 42 43 44 ...
  .. .. ..@ p       : int [1:43154] 0 4578 6712 9546 12295 15332 17369 24417 27494 31769 ...
  .. .. ..@ Dim     : int [1:2] 24557 43153
  .. .. ..@ Dimnames:List of 2
  .. .. .. ..$ : chr [1:24557] "RP11-34P13.7" "RP11-34P13.8" "FO538757.3" "FO538757.2" ...
  .. .. .. ..$ : chr [1:43153] "CS29A_AAACCCAAGAGCAGCT-1" "CS29A_AAACCCAAGGGTACGT-1" "CS29A_AAACCCAAGTAAACGT-1" "CS29A_AAACCCAAGTTCATCG-1" ...
  .. .. ..@ x       : num [1:144476533] 0.57 0.57 1.97 0.57 0.57 ...
  .. .. ..@ factors : list()
  ..@ data.signaling:Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. ..@ i       : int [1:2814112] 0 16 18 25 38 45 47 62 66 75 ...
  .. .. ..@ p       : int [1:43154] 0 114 148 196 239 294 330 449 521 585 ...
  .. .. ..@ Dim     : int [1:2] 831 43153
  .. .. ..@ Dimnames:List of 2
  .. .. .. ..$ : chr [1:831] "AGRN" "TNFRSF4" "TNFRSF14" "TNFRSF25" ...
  .. .. .. ..$ : chr [1:43153] "CS29A_AAACCCAAGAGCAGCT-1" "CS29A_AAACCCAAGGGTACGT-1" "CS29A_AAACCCAAGTAAACGT-1" "CS29A_AAACCCAAGTTCATCG-1" ...
  .. .. ..@ x       : num [1:2814112] 0.57 0.57 0.93 0.93 0.57 ...
  .. .. ..@ factors : list()
  ..@ data.scale    : num[0 , 0 ] 
  ..@ data.project  : num [1:831, 1:43153] 0.569643 0 0.000129 0 0 ...
  .. ..- attr(*, "dimnames")=List of 2
  .. .. ..$ : chr [1:831] "AGRN" "TNFRSF4" "TNFRSF14" "TNFRSF25" ...
  .. .. ..$ : chr [1:43153] "CS29A_AAACCCAAGAGCAGCT-1" "CS29A_AAACCCAAGGGTACGT-1" "CS29A_AAACCCAAGTAAACGT-1" "CS29A_AAACCCAAGTTCATCG-1" ...
  ..@ net           : list()
  ..@ netP          : list()
  ..@ meta          :'data.frame':	43153 obs. of  10 variables:
  .. ..$ orig.ident     : chr [1:43153] "SeuratProject" "SeuratProject" "SeuratProject" "SeuratProject" ...
  .. ..$ nCount_RNA     : num [1:43153] 13027 3614 5481 6710 6471 ...
  .. ..$ nFeature_RNA   : int [1:43153] 4578 2134 2834 2749 3037 2037 7048 3077 4275 5612 ...
  .. ..$ percent.mt     : num [1:43153] 2.46 1.13 1.88 3.03 1.07 ...
  .. ..$ RNA_snn_res.0.4: Factor w/ 15 levels "0","1","2","3",..: 3 1 4 10 4 1 9 13 4 2 ...
  .. ..$ seurat_clusters: Factor w/ 15 levels "0","1","2","3",..: 3 1 4 10 4 1 9 13 4 2 ...
  .. ..$ stim           : chr [1:43153] "CS29_A" "CS29_A" "CS29_A" "CS29_A" ...
  .. ..$ sub_cluster    : chr [1:43153] "2" "0" "3" "9" ...
  .. ..$ Identity       : Factor w/ 15 levels "Astrocytes 1",..: 1 5 15 8 15 5 4 2 15 9 ...
  .. ..$ IDstim         : chr [1:43153] "Astrocytes 1_CS29_A" "Immature neurons_CS29_A" "Upper Layer neurons_CS29_A" "Interneurons_CS29_A" ...
  ..@ idents        : Factor w/ 15 levels "Astrocytes 1",..: 1 5 15 8 15 5 4 2 15 9 ...
  ..@ DB            :List of 4
  .. ..$ interaction:'data.frame':	1939 obs. of  11 variables:
  .. .. ..$ interaction_name  : chr [1:1939] "TGFB1_TGFBR1_TGFBR2" "TGFB2_TGFBR1_TGFBR2" "TGFB3_TGFBR1_TGFBR2" "TGFB1_ACVR1B_TGFBR2" ...
  .. .. ..$ pathway_name      : chr [1:1939] "TGFb" "TGFb" "TGFb" "TGFb" ...
  .. .. ..$ ligand            : chr [1:1939] "TGFB1" "TGFB2" "TGFB3" "TGFB1" ...
  .. .. ..$ receptor          : chr [1:1939] "TGFbR1_R2" "TGFbR1_R2" "TGFbR1_R2" "ACVR1B_TGFbR2" ...
  .. .. ..$ agonist           : chr [1:1939] "TGFb agonist" "TGFb agonist" "TGFb agonist" "TGFb agonist" ...
  .. .. ..$ antagonist        : chr [1:1939] "TGFb antagonist" "TGFb antagonist" "TGFb antagonist" "TGFb antagonist" ...
  .. .. ..$ co_A_receptor     : chr [1:1939] "" "" "" "" ...
  .. .. ..$ co_I_receptor     : chr [1:1939] "TGFb inhibition receptor" "TGFb inhibition receptor" "TGFb inhibition receptor" "TGFb inhibition receptor" ...
  .. .. ..$ evidence          : chr [1:1939] "KEGG: hsa04350" "KEGG: hsa04350" "KEGG: hsa04350" "PMID: 27449815" ...
  .. .. ..$ annotation        : chr [1:1939] "Secreted Signaling" "Secreted Signaling" "Secreted Signaling" "Secreted Signaling" ...
  .. .. ..$ interaction_name_2: chr [1:1939] "TGFB1 - (TGFBR1+TGFBR2)" "TGFB2 - (TGFBR1+TGFBR2)" "TGFB3 - (TGFBR1+TGFBR2)" "TGFB1 - (ACVR1B+TGFBR2)" ...
  .. ..$ complex    :'data.frame':	157 obs. of  4 variables:
  .. .. ..$ subunit_1: chr [1:157] "INHBA" "INHA" "INHA" "IL12A" ...
  .. .. ..$ subunit_2: chr [1:157] "INHBB" "INHBA" "INHBB" "IL12B" ...
  .. .. ..$ subunit_3: chr [1:157] "" "" "" "" ...
  .. .. ..$ subunit_4: chr [1:157] "" "" "" "" ...
  .. ..$ cofactor   :'data.frame':	31 obs. of  16 variables:
  .. .. ..$ cofactor1 : chr [1:31] "FST" "BAMBI" "TIE1" "PTPRB" ...
  .. .. ..$ cofactor2 : chr [1:31] "" "" "" "" ...
  .. .. ..$ cofactor3 : chr [1:31] "" "" "" "" ...
  .. .. ..$ cofactor4 : chr [1:31] "" "" "" "" ...
  .. .. ..$ cofactor5 : chr [1:31] "" "" "" "" ...
  .. .. ..$ cofactor6 : chr [1:31] "" "" "" "" ...
  .. .. ..$ cofactor7 : chr [1:31] "" "" "" "" ...
  .. .. ..$ cofactor8 : chr [1:31] "" "" "" "" ...
  .. .. ..$ cofactor9 : chr [1:31] "" "" "" "" ...
  .. .. ..$ cofactor10: chr [1:31] "" "" "" "" ...
  .. .. ..$ cofactor11: chr [1:31] "" "" "" "" ...
  .. .. ..$ cofactor12: chr [1:31] "" "" "" "" ...
  .. .. ..$ cofactor13: chr [1:31] "" "" "" "" ...
  .. .. ..$ cofactor14: chr [1:31] "" "" "" "" ...
  .. .. ..$ cofactor15: chr [1:31] "" "" "" "" ...
  .. .. ..$ cofactor16: chr [1:31] "" "" "" "" ...
  .. ..$ geneInfo   :'data.frame':	41787 obs. of  6 variables:
  .. .. ..$ Symbol         : chr [1:41787] "A1BG" "A1BG-AS1" "A1CF" "A2M" ...
  .. .. ..$ Name           : chr [1:41787] "alpha-1-B glycoprotein" "A1BG antisense RNA 1" "APOBEC1 complementation factor" "alpha-2-macroglobulin" ...
  .. .. ..$ EntrezGene.ID  : int [1:41787] 1 503538 29974 2 144571 144568 NA NA 3 127550 ...
  .. .. ..$ Ensembl.Gene.ID: chr [1:41787] "ENSG00000121410" "ENSG00000268895" "ENSG00000148584" "ENSG00000175899" ...
  .. .. ..$ MGI.ID         : chr [1:41787] "MGI:2152878" "" "MGI:1917115" "MGI:2449119" ...
  .. .. ..$ Gene.group.name: chr [1:41787] "Immunoglobulin like domain containing" "Antisense RNAs" "RNA binding motif containing" "C3 and PZP like, alpha-2-macroglobulin domain containing" ...
  ..@ LR            :List of 1
  .. ..$ LRsig:'data.frame':	1486 obs. of  11 variables:
  .. .. ..$ interaction_name  : chr [1:1486] "TGFB1_TGFBR1_TGFBR2" "TGFB2_TGFBR1_TGFBR2" "TGFB3_TGFBR1_TGFBR2" "TGFB1_ACVR1B_TGFBR2" ...
  .. .. ..$ pathway_name      : chr [1:1486] "TGFb" "TGFb" "TGFb" "TGFb" ...
  .. .. ..$ ligand            : chr [1:1486] "TGFB1" "TGFB2" "TGFB3" "TGFB1" ...
  .. .. ..$ receptor          : chr [1:1486] "TGFbR1_R2" "TGFbR1_R2" "TGFbR1_R2" "ACVR1B_TGFbR2" ...
  .. .. ..$ agonist           : chr [1:1486] "TGFb agonist" "TGFb agonist" "TGFb agonist" "TGFb agonist" ...
  .. .. ..$ antagonist        : chr [1:1486] "TGFb antagonist" "TGFb antagonist" "TGFb antagonist" "TGFb antagonist" ...
  .. .. ..$ co_A_receptor     : chr [1:1486] "" "" "" "" ...
  .. .. ..$ co_I_receptor     : chr [1:1486] "TGFb inhibition receptor" "TGFb inhibition receptor" "TGFb inhibition receptor" "TGFb inhibition receptor" ...
  .. .. ..$ evidence          : chr [1:1486] "KEGG: hsa04350" "KEGG: hsa04350" "KEGG: hsa04350" "PMID: 27449815" ...
  .. .. ..$ annotation        : chr [1:1486] "Secreted Signaling" "Secreted Signaling" "Secreted Signaling" "Secreted Signaling" ...
  .. .. ..$ interaction_name_2: chr [1:1486] "TGFB1 - (TGFBR1+TGFBR2)" "TGFB2 - (TGFBR1+TGFBR2)" "TGFB3 - (TGFBR1+TGFBR2)" "TGFB1 - (ACVR1B+TGFBR2)" ...
  ..@ var.features  :List of 2
  .. ..$ features     : chr [1:2564] "PTN" "SFRP1" "PTPRZ1" "TNC" ...
  .. ..$ features.info:'data.frame':	2564 obs. of  6 variables:
  .. .. ..$ clusters: chr [1:2564] "Astrocytes 1" "Astrocytes 1" "Astrocytes 1" "Astrocytes 1" ...
  .. .. ..$ features: chr [1:2564] "PTN" "SFRP1" "PTPRZ1" "TNC" ...
  .. .. ..$ pvalues : num [1:2564] 0 0 0 0 0 0 0 0 0 0 ...
  .. .. ..$ logFC   : num [1:2564] 2.27 1.94 1.42 1.24 1.05 ...
  .. .. ..$ pct.1   : num [1:2564] 1 0.993 0.999 0.764 0.769 0.941 0.71 0.906 0.72 0.669 ...
  .. .. ..$ pct.2   : num [1:2564] 0.679 0.469 0.875 0.118 0.126 0.432 0.06 0.274 0.095 0.101 ...
  ..@ dr            : list()
  ..@ options       :List of 1
  .. ..$ mode: chr "single"

And this is the code I used: 
data.input = as.data.frame(object@assays$RNA@data)
cells <- object@meta.data
cells <- cells[Cells(object),]
data.input <- data.input[,row.names(cells)]
meta = object@meta.data
cellchat2 <- createCellChat(object = as.matrix(data.input), meta = meta, group.by = "Identity")
CellChatDB <- CellChatDB.human
showDatabaseCategory(CellChatDB)
dplyr::glimpse(CellChatDB$interaction)
CellChatDB.use <- CellChatDB 
cellchat2@DB <- CellChatDB.use
cellchat2 <- subsetData(cellchat2)
future::plan("multiprocess", workers = 4) # do parallel
cellchat2 <- identifyOverExpressedGenes(cellchat2)
cellchat2 <- identifyOverExpressedInteractions(cellchat2)
cellchat2 <- projectData(cellchat2, PPI.human)

#Computation 
cellchat2 <- computeCommunProb(cellchat2, raw.use = TRUE)

SessionInfo() 
sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.2

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] patchwork_1.1.1     eulerr_6.1.0        CellChat_1.0.0      Biobase_2.50.0      BiocGenerics_0.36.0
 [6] igraph_1.2.6        forcats_0.5.1       stringr_1.4.0       dplyr_1.0.4         purrr_0.3.4        
[11] readr_1.4.0         tidyr_1.1.2         tibble_3.0.6        ggplot2_3.3.3       tidyverse_1.3.0    
[16] SeuratObject_4.0.0  Seurat_4.0.0       

loaded via a namespace (and not attached):
  [1] utf8_1.1.4           reticulate_1.18      tidyselect_1.1.0     htmlwidgets_1.5.3   
  [5] grid_4.0.3           Rtsne_0.15           devtools_2.3.2       munsell_0.5.0       
  [9] codetools_0.2-18     ica_1.0-2            future_1.21.0        miniUI_0.1.1.1      
 [13] withr_2.4.1          colorspace_2.0-0     ggalluvial_0.12.3    rstudioapi_0.13     
 [17] stats4_4.0.3         ROCR_1.0-11          tensor_1.5           listenv_0.8.0       
 [21] NMF_0.23.0           labeling_0.4.2       polyclip_1.10-0      farver_2.0.3        
 [25] pheatmap_1.0.12      rprojroot_2.0.2      coda_0.19-4          parallelly_1.23.0   
 [29] vctrs_0.3.6          generics_0.1.0       xfun_0.21            R6_2.5.0            
 [33] doParallel_1.0.16    clue_0.3-58          gg.gap_1.3           spatstat.utils_2.0-0
 [37] cachem_1.0.4         assertthat_0.2.1     promises_1.2.0.1     scales_1.1.1        
 [41] gtable_0.3.0         Cairo_1.5-12.2       globals_0.14.0       processx_3.4.5      
 [45] goftest_1.2-2        rlang_0.4.10         systemfonts_1.0.1    GlobalOptions_0.1.2 
 [49] splines_4.0.3        lazyeval_0.2.2       broom_0.7.5          BiocManager_1.30.10 
 [53] reshape2_1.4.4       abind_1.4-5          modelr_0.1.8         backports_1.2.1     
 [57] httpuv_1.5.5         tools_4.0.3          usethis_2.0.1        gridBase_0.4-7      
 [61] statnet.common_4.4.1 ellipsis_0.3.1       RColorBrewer_1.1-2   sessioninfo_1.1.1   
 [65] ggridges_0.5.3       Rcpp_1.0.6           plyr_1.8.6           ps_1.5.0            
 [69] prettyunits_1.1.1    rpart_4.1-15         deldir_0.2-10        pbapply_1.4-3       
 [73] GetoptLong_1.0.5     cowplot_1.1.1        S4Vectors_0.28.1     zoo_1.8-8           
 [77] haven_2.3.1          ggrepel_0.9.1        cluster_2.1.1        fs_1.5.0            
 [81] tinytex_0.29         magrittr_2.0.1       sna_2.6              RSpectra_0.16-0     
 [85] data.table_1.14.0    scattermore_0.7      circlize_0.4.13.1001 lmtest_0.9-38       
 [89] reprex_1.0.0         RANN_2.6.1           fitdistrplus_1.1-3   matrixStats_0.58.0  
 [93] pkgload_1.2.0        hms_1.0.0            mime_0.10            xtable_1.8-4        
 [97] readxl_1.3.1         IRanges_2.24.1       gridExtra_2.3        shape_1.4.5         
[101] testthat_3.0.2       compiler_4.0.3       KernSmooth_2.23-18   crayon_1.4.1        
[105] htmltools_0.5.1.1    mgcv_1.8-34          later_1.1.0.1        lubridate_1.7.10    
[109] DBI_1.1.1            dbplyr_2.1.0         ComplexHeatmap_2.6.2 MASS_7.3-53.1       
[113] Matrix_1.3-2         cli_2.3.1            pkgconfig_2.0.3      registry_0.5-1      
[117] plotly_4.9.3         xml2_1.3.2           foreach_1.5.1        svglite_1.2.3.2     
[121] rngtools_1.5         pkgmaker_0.32.2      rvest_0.3.6          callr_3.5.1         
[125] digest_0.6.27        rle_0.9.2            sctransform_0.3.2    RcppAnnoy_0.0.18    
[129] spatstat.data_2.0-0  cellranger_1.1.0     leiden_0.3.7         uwot_0.1.10         
[133] gdtools_0.2.3        shiny_1.6.0          rjson_0.2.20         lifecycle_1.0.0     
[137] nlme_3.1-152         jsonlite_1.7.2       network_1.16.1       desc_1.2.0          
[141] viridisLite_0.3.0    limma_3.46.0         fansi_0.4.2          pillar_1.5.0        
[145] lattice_0.20-41      fastmap_1.1.0        httr_1.4.2           pkgbuild_1.2.0      
[149] survival_3.2-7       glue_1.4.2           remotes_2.2.0        FNN_1.1.3           
[153] spatstat_1.64-1      png_0.1-7            iterators_1.0.13     stringi_1.5.3       
[157] memoise_2.0.0        irlba_2.3.3          future.apply_1.7.0

**Comment by sqjin** [comment]
@leawenger Can you check `unique(cellchat@idents)` to see if the factor level includes the cell type you removed? If so, you should drop this cell type from the factor level.

**Comment by leawenger** [comment]
@sqjin  thanks for the rapid response! I checked and the cell type is not present in there... However whilst it lists 13 levels it then mentions 15 levels... 

unique(cellchat2@idents)
 [1] Astrocytes 1             Immature neurons        
 [3] Upper Layer neurons      Interneurons            
 [5] Deep Layer neurons       Astrocytes 2            
 [7] Layer 4 neurons          Inner Radial Glia       
 [9] Oligodendrocytes/OPC     Truncate Radial Glia    
[11] Outer Radial Glia        Intermediate Progenitors
[13] Astrocytes 3            
15 Levels: Astrocytes 1 Astrocytes 2 ... Upper Layer neurons

**Comment by cswoboda** [comment]
Hi @leawenger,

Not an official member of the cellchat team or anything, but I think I can help you! The vignette has you subset meta data based on cells you want to use. Removing cells WILL NOT remove the levels embedded in your factor. For example, meta$labels may only have the 13 values contained within it you requested, but the levels of the factor will remain at 15 like in your data. To solve your issue, simply add this to your code:

meta = object@meta.data
meta$celltype <- dropLevels(meta$celltype, exclude = c("Your identity here, can include a character string of multiple cell types"))
cellchat2 <- createCellChat(object = as.matrix(data.input), meta = meta, group.by = "celltype")

This assumes you're using a seurat object with cell labels in the meta data as "celltype", but this could be done on any factored column of the metadata, so just perform this on the column you're grouping by.

Casey

**Comment by sqjin** [comment]
@cswoboda Thanks very much for sharing this.

**Comment by leawenger** [comment]
Hi Casey, 

That did the trick, it's all working well now. Thank you very much for your help!! 

Best, 

Léa

**Comment by Cooper36** [comment]
Hey all, I have a similar issue, but with a different error.

I am working with a merged spatial Seurat object (11 capture areas) and following this [vignette](https://rdrr.io/github/sqjin/CellChat/f/tutorial/CellChat_analysis_of_spatial_imaging_data.Rmd).

I was able to run through the entire pipeline successfully by subsetting the Seurat object to a single capture area (the first capture area). However, when I subset the Seurat object to any other capture area  it fails when running computeCommunProbe() giving the error:

"Error in if (xx != 0) xx/10 else z/10 : argument is of length zero"

Here is the code:
_______v_____________________v________________________v____________
  dataObj = Datasets
  idents = "AnnoCluster"
  section = "1B"
  slidefolder = "2396_Sim"
  
  Idents(object = dataObj) <- "Sec.ident"

  data <- subset(x = dataObj, ident = section, invert = FALSE)
  
  Idents(object = data) <- idents
  
  data.input = GetAssayData(data, slot = "data", assay = "Spatial") # normalized data matrix
  meta = data.frame(labels = Idents(data), row.names = names(Idents(data))) # manually create a dataframe consisting of the cell labels

  
  spatial.locs <- GetTissueCoordinates(data, scale = NULL, cols = c("imagerow", "imagecol"))
  
  scale.factors = jsonlite::fromJSON(txt = paste(getwd(),"/Slides/",slidefolder, "/", section,"_count_out/outs/spatial/scalefactors_json.json",sep = ""))
  scale.factors = list(spot.diameter = 65, spot = scale.factors$spot_diameter_fullres, # these two information are required
                       fiducial = scale.factors$fiducial_diameter_fullres, hires = scale.factors$tissue_hires_scalef, lowres = scale.factors$tissue_lowres_scalef # these three information are not required
  )


  cellchat <- createCellChat(object = data.input, meta = meta, group.by = "labels",
                             datatype = "spatial", coordinates = spatial.locs, scale.factors = scale.factors)


  CellChatDB <- CellChatDB.human # use CellChatDB.human if running on human data
  
  CellChatDB.use <- CellChatDB # simply use the default CellChatDB
  
  # set the used database in the object
  cellchat@DB <- CellChatDB.use
  
  
  # subset the expression data of signaling genes for saving computation cost
  cellchat <- subsetData(cellchat) # This step is necessary even if using the whole database
  future::plan("multisession", workers = 1) # do parallel
  cellchat <- identifyOverExpressedGenes(cellchat)
  cellchat <- identifyOverExpressedInteractions(cellchat)
  

  cellchat <- computeCommunProb(cellchat, type = "truncatedMean", trim = 0.1, 
                                 distance.use = TRUE, interaction.length = 200, scale.distance = 0.01)
  
  # Filter out the cell-cell communication if there are only few number of cells in certain cell groups
  cellchat <- filterCommunication(cellchat, min.cells = 10)
  
  cellchat <- computeCommunProbPathway(cellchat)
  
  cellchat <- aggregateNet(cellchat)
  
  groupSize <- as.numeric(table(cellchat@idents))
  par(mfrow = c(1,2), xpd=TRUE)
  netVisual_circle(cellchat@net$count, vertex.weight = rowSums(cellchat@net$count), weight.scale = T, label.edge= F, title.name = "Number of interactions")
  netVisual_circle(cellchat@net$weight, vertex.weight = rowSums(cellchat@net$weight), weight.scale = T, label.edge= F, title.name = "Interaction weights/strength")

_______^_____________________^________________________^____________


unique(cellchat@idents) on the CellChat object yields the expect:
[1] dGM         inCtx       outCtx      Other       Lesion      LesionAdj   WM          Vent        LesionAdjGM
Levels: Other inCtx Vent outCtx dGM WM LesionAdjGM LesionAdj Lesion

I have also included my cellchat objects, both the first capture area (working) and the second (not working).

Any help would be greatly appreciated!
[CellChatObjects.zip](https://github.com/sqjin/CellChat/files/11160561/CellChatObjects.zip)
