### ISSUE TITLE
How do you know interaction pairs between the two cell identities from a CellChat object?

### ISSUE THREAD

**Issue by BeyondMyPast228** [sqjin/CellChat#157]
Hi,
Thanks for this user-friendly tool. When i  perform cell interaction analysis on a scRNA-seq dataset, how do i know the ligand-receptor pairs and pathways between the two cellular identities?

**Comment by sqjin** [comment]
@BeyondMyPast228 Please check the function `subsetCommunication`, where you can define the sources.use and targets.use
