### ISSUE TITLE
Error in runUMAP(Similarity, min.dist = 0.3, n.neighbors = k)

### ISSUE THREAD

**Issue by Emily-Y21** [sqjin/CellChat#158]
I have a problem when running:

> cellchat <- netEmbedding(cellchat, type = "functional")

Manifold learning of the signaling networks for a single dataset 
Error in runUMAP(Similarity, min.dist = 0.3, n.neighbors = k) : 
  Cannot find UMAP, please install through pip (e.g. pip install umap-learn or reticulate::py_install(packages = 'umap-learn')).

I have used reticulate::py_install(packages = 'umap-learn') to install 'umap-learn',but it can't help. 
I tried to library(umap-learn) after installation, but it shows: Error in library(umap - learn) : The length of 'package' must be one 

Can you kindly help me with this problem? Thank you very much!

**Comment by sqjin** [comment]
@Emily-Y21 You might need to specify the python version, e.g., 
`reticulate::use_python("/Users/USERS/opt/miniconda3/bin/python", required=T)`

**Comment by Emily-Y21** [comment]
Thanks for your answer.But it still has something wrong.
I use the following code to install 'umap-learn'.


remotes::install_github("hafen/rminiconda")
py <- rminiconda::find_miniconda_python("my_python")
reticulate::use_python(py, required = TRUE)
reticulate::py_install(packages = 'umap-learn')


but when I run&nbsp;&gt; cellchat <- netEmbedding(cellchat, type = "functional")
it still returns an error









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sqjin/CellChat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月18日(星期四) 上午6:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sqjin/CellChat] Error in runUMAP(Similarity, min.dist = 0.3, n.neighbors = k) (#158)





 
@Emily-Y21 You might need to specify the python version, e.g.,
 reticulate::use_python("/Users/USERS/opt/miniconda3/bin/python", required=T)

**Comment by sqjin** [comment]
@Emily-Y21 Can you please check https://github.com/lmcinnes/umap to see how to run umap in R?

**Comment by apal6** [comment]
Hi,

Thank you for the wonderful package. I wonder if this problem was solved as I encountered the same error.

Best,
Aastha
