### ISSUE TITLE
rankSimilarity multiple datasets

### ISSUE THREAD

**Issue by hmbaghdassarian** [sqjin/CellChat#160]
I am running into a problem when trying to incorporate more than 2 datasets and compare across them. Specifically, I run into an error with the rankSimilarity function. From my understanding of the description for the "comparison2" parameter, this should be a pairwise comparison between any of the two datasets in the merged CellChat object, but for some of the comparisons, I get the error "Error in (position[comparison2[2]] + 1):position[comparison2[2] + 1]: NA/NaN argument".  

This is caused by the last line of code here, from the rankSimilarity function: 

`Y <- methods::slot(object, slot.name)$similarity[[type]]$dr[[comparison.name]]
data1 <- Y[(position[comparison2[1]]+1):position[comparison2[1]+1], ]
data2 <- Y[(position[comparison2[2]]+1):position[comparison2[2]+1], ]`

I believe this may be due to hardcoding the indices for position from comparison2, even if comparison2 != c(1,2). This causes `position[comparison2[2]+1]` to be NaN. For example, the position vector for c(1,2) and c(1,3) is the same, but for c(1,3), there is no index 4, so `position[comparison2[2]+1]` is NaN. 

If this is causing the error, could you please tell me what should be changed to fix it? Otherwise, if I'm totally wrong, could you point me in the right direction? I've attached a screenshot of part of my code to further clarify. 

Thanks so much!

<img width="752" alt="Screen Shot 2021-03-19 at 11 57 37 AM" src="https://user-images.githubusercontent.com/40876664/111808372-5366dc80-88aa-11eb-9ad7-a572ecb086d9.png">

**Comment by sqjin** [comment]
@hmbaghdassarian It looks like this is an issue. I think I need to refresh some data structure so that this part is easier for coding. Currently it is indeed not easy to get correct index. Will try to fix it in next few days.

**Comment by hmbaghdassarian** [comment]
@sqjin is there any update on this?

**Comment by sqjin** [comment]
@hmbaghdassarian I think I have fixed it. Can you try to reinstall the package

**Comment by hmbaghdassarian** [comment]
@sqjin yes, it looks like it works now. thank you!
