### ISSUE TITLE
"Compare the major sources and targets in 2D space" Question rather than issue

### ISSUE THREAD

**Issue by khomicsk** [sqjin/CellChat#161]
I really like the comparison in 2D space. However, is there a way to set the y axis fixed at the same (higher) range?

I could not find a way to do that. As its scales y axis for each conditions the comparison of changes is more difficult to visually compare.

**Comment by sqjin** [comment]
@khomicsk This should be easily done by adjusting the ggplot2 theme. e.g., use 'scale_y_continuous' or `coord_cartesian`. Here is one example https://stackoverflow.com/questions/41768273/create-ggplots-with-the-same-scale-in-r
