### ISSUE TITLE
some issue about computecommunpathway

### ISSUE THREAD

**Issue by wyvern114** [sqjin/CellChat#163]
Hello, this is my code:
p<-readRDS(file = "F:/bioinfor_work/ctrl.rds")

data.input <- GetAssayData(p, assay = "RNA", slot = "data") # normalized data matrix

labels <- Idents(p)

meta <- data.frame(labels = labels, row.names = names(labels)) # create a dataframe of the cell labels

cellchat <- createCellChat(object = data.input, meta = meta, group.by = "labels")

cellchat

cellchat <- addMeta(cellchat, meta = meta)

cellchat <- setIdent(cellchat, ident.use = "labels") # set "labels" as default cell identity

levels(cellchat@idents)

groupSize <- as.numeric(table(cellchat@idents)) # number of cells in each cell group

CellChatDB <- CellChatDB.mouse 

showDatabaseCategory(CellChatDB)

dplyr::glimpse(CellChatDB$interaction)

CellChatDB.use <- subsetDB(CellChatDB, search = "Secreted Signaling") # use Secreted Signaling

CellChatDB.use <- CellChatDB # simply use the default CellChatDB

cellchat@DB <- CellChatDB.use

colnames(CellChatDB$interaction)

CellChatDB.use <- subsetDB(CellChatDB, search = "Secreted Signaling") 

cellchat@DB <- CellChatDB.use # set the used database in the object

unique(CellChatDB$interaction$annotation)

cellchat <- subsetData(cellchat) # subset the expression data of signaling genes for saving computation cost
future::plan("multiprocess", workers = 4) 
cellchat <- identifyOverExpressedGenes(cellchat)
cellchat <- identifyOverExpressedInteractions(cellchat)
cellchat <- projectData(cellchat, PPI.mouse)  

cellchat <- computeCommunProb(cellchat,raw.use = TRUE,population.size = T)

cellchat <- mycomputeCommunProb(cellchat)

cellchat <- computeCommunProbPathway(cellchat)

and I using computecommunprobpathway and there is an error :Error in apply(prob, c(1, 2), by, group, sum) :
dim(X) must have a positive length, how can i solve that ?

PS: By the way, I didn't use: cellchat<-computecommunprob(cellchat), because it take too many time for me, may be an hour, and i pass that and use computecommmunprobpathway, and some how it works, i forgot to save the previous code, so please tell me the reason.

**Comment by sqjin** [comment]
@wyvern114 Hi, you should run computeCommunProb before running computeCommunProbPathway. I am trying to provide a faster version now.
