### ISSUE TITLE
liftCellChat error

### ISSUE THREAD

**Issue by s849** [sqjin/CellChat#164]
Hi,

When I try to use liftCellChat, I get the following error:

Update slots object@net, object@netP, object@idents in a single dataset... 
Error in values.new[group.existing.index, group.existing.index, ] <- values : 
  number of items to replace is not a multiple of replacement length

How to fix this?

**Comment by s849** [comment]
Ok, I think I fixed it by changing the identity names. But now after liftCellChat, I get this:

cellchat <- mergeCellChat(object.list, add.names = names(object.list), cell.prefix = TRUE)
Error in match.names(clabs, names(xi)) : 
  names do not match previous names

**Comment by sqjin** [comment]
@s849 I am sorry I have no idea on this except for testing it. Can you run the source codes of the function `mergeCellChat` or you can share the object with me to test it?

**Comment by ycao6928** [comment]
I got the same error. 
In my case data 1 has 90 cell types, data 2 has 95 cell types, but together they have 96 cell types, ie, some of the cell types are in data 1 only and some in data 2 only.
I was able to solve this as suggested by funpys: 
merged   <- mergeCellChat( _typical merging code_ )
merged  <- liftCellChat(merged , group.new = levels( merged@idents$joint) )

**Comment by sqjin** [comment]
@ycao6928 Thanks Yue! You can also define `group.new` using any char vector.

**Comment by decodebiology** [comment]
> I got the same error. And I solved it using liftCellChat after mergeCellChat.

You saved my day.
