### ISSUE TITLE
No significant interactions in CellChat results

### ISSUE THREAD

**Issue by JKarmanAbbVie** [sqjin/CellChat#166]
Hello Authors of CellChat,

First of all, thank you for the fantastic R package. I have a question. I am using the code below on GSE153760 (10x data) and getting a df_net output with 308546 lines, p values ranging 0-0.05 and prob values ranging 1.686783e-18 to 3.691215e-03. I start from a Seurat v3 object I built from the data as deposited in GEO (gse153760_combined_ad). Yet, when I try to run the last line of code, I get no significant signaling for any pathway. Is this expected based on the df_net file as I explained? Or am I missing something?

Your help is appreciated in advance!

Best,

JK

library(CellChat)
library(patchwork)
options(stringsAsFactors = F)
cellchat_gse153760_ad <- createCellChat(object = gse153760_combined_ad, group.by = "celltypenew")
groupSize <- as.numeric(table(cellchat_gse153760_ad@idents)) # number of cells in each cell group
CellChatDB.use <- CellChatDB_refined

# set the used database in the object
cellchat_gse153760_ad@DB <- CellChatDB.use

cellchat_gse153760_ad <- subsetData(cellchat_gse153760_ad)
cellchat_gse153760_ad <- identifyOverExpressedGenes(cellchat_gse153760_ad)
cellchat_gse153760_ad <- identifyOverExpressedInteractions(cellchat_gse153760_ad)
cellchat_gse153760_ad <- projectData(cellchat_gse153760_ad, PPI.human)

cellchat_gse153760_ad <- computeCommunProb(cellchat_gse153760_ad, raw.use = FALSE, population.size = TRUE, type = 'truncatedMean', trim = 0)
# Filter out the cell-cell communication if there are only few number of cells in certain cell groups
cellchat_gse153760_ad <- filterCommunication(cellchat_gse153760_ad, min.cells = 10)
save(cellchat_gse153760_ad, file = 'cellchat_gse153760_ad_032521_truncatedmean_0.RData')
df_net_ad <- subsetCommunication(cellchat_gse153760_ad)
cellchat_gse153760_ad <- computeCommunProbPathway(cellchat_gse153760_ad)

pairLR.use <- extractEnrichedLR(cellchat_gse153760_ad, signaling = unique(df_net_ad$pathway_name))
# a data frame of 0 rows produced

**Comment by sqjin** [comment]
Hi @JKarmanAbbVie , this is unexpected. I have no idea except for testing your data. You can also run the source codes line by line to figure out the reason.

**Comment by JKarmanAbbVie** [comment]
I figured out what my issue was. I was trying to use my own version of CellChatDB and it was not formatted correctly.

**Comment by yansongtongji** [comment]
Have you solved it? I have the same problem on mine work……
