### ISSUE TITLE
sources.use causes error in hierarchy plots with netVisual_aggregate 

### ISSUE THREAD

**Issue by hooperj** [sqjin/CellChat#169]
Similar to the issue closed last week, I want to only see a subset of all my cell types in these hierarchy plots.
This works perfectly:
>netVisual_aggregate(noseChat, signaling = "NOTCH",  vertex.receiver =c(12,13,14,3,4,5,21,22))

But when I add a sources.use argument, I get an error message
>netVisual_aggregate(noseChat, signaling = "NOTCH",  vertex.receiver =c(12,13,14,3,4,5,21,22), sources.use = c(1:14,21,22))
>               Error in levels(object@idents) : object 'object' not found

I just re-installed the package, but the new version did not fix this.
joan
[Notch2OEC.HierPlot.pdf](https://github.com/sqjin/CellChat/files/6233038/Notch2OEC.HierPlot.pdf)

**Comment by sqjin** [comment]
@hooperj Can you set `remove.isolate = TRUE` and try it again?

**Comment by hooperj** [comment]
Still generates the same error message…

> netVisual_aggregate(noseChat, signaling = "NOTCH",  vertex.receiver =c(12,13,14,3,4,5,21,22), sources.use = c(1:14,21,22), remove.isolate = TRUE)
Error in ***@***.***) : object 'object' not found

From: sqjin ***@***.***>
Reply-To: sqjin/CellChat ***@***.***>
Date: Wednesday, March 31, 2021 at 1:15 AM
To: sqjin/CellChat ***@***.***>
Cc: "Hooper, Joan" <JOAN.HOOPER@CUANSCHUTZ.EDU>, Mention ***@***.***>
Subject: Re: [sqjin/CellChat] sources.use causes error in hierarchy plots with netVisual_aggregate (#169)


@hooperj<https://github.com/hooperj> Can you set remove.isolate = TRUE and try it again?

**Comment by sqjin** [comment]
@hooperj Sorry about it. Can you reinstall the package and try it again? I just fixed this issue.

**Comment by hooperj** [comment]
I’m not sure if I am re-installing the latest version., I used
>devtools::install_github("sqjin/CellChat")
And got back


I reinstalled the package and it still has problems. I dug into the code and found two issues in the netVisual_hierarchy1 sub-function.

  1.  It does NOT pass ‘object’, so if I try to pass numeric sources.use, it errors out on to line 22

if (is.numeric(sources.use)) {

    sources.use <- ***@***.******@***.***)[sources.use>]
                If I make a new netVisual_hierarchy1 function , adding ‘object = object’ to the input arguments I, it corrects the problem. Or if I by-pass the need for this by using ‘levels(noseChat)[c(1:14,21,22)]’ in the original function call, it also works.

  1.  It does not properly process the reduced-size ‘net’ matrix if ‘remove.isolate = TRUE’. The problem shows up around line 55
net2 <- net

reorder.row <- c(vertex.receiver, setdiff(1:nrow(net), vertex.receiver))
net2 <- net2[reorder.row, vertex.receiver]

“Error in net2[reorder.row, vertex.receiver] : subscript out of bounds” because the original indices used in ‘vertex.receiver’ no longer fit the reduced size of the ‘net’ matrix – which ‘remove.isolate=T’ reduced from 22x22  to 22x9.

I can fix this for me locally, but thought you might want to fix it in the package



From: sqjin ***@***.***>
Reply-To: sqjin/CellChat ***@***.***>
Date: Thursday, April 1, 2021 at 11:44 PM
To: sqjin/CellChat ***@***.***>
Cc: "Hooper, Joan" <JOAN.HOOPER@CUANSCHUTZ.EDU>, Mention ***@***.***>
Subject: Re: [sqjin/CellChat] sources.use causes error in hierarchy plots with netVisual_aggregate (#169)


@hooperj<https://github.com/hooperj> Sorry about it. Can you reinstall the package and try it again? I just fixed this issue.

**Comment by hooperj** [comment]
Sorry-I hit SENT instead of PASTE. This is the dialog I get reinstalling and I wanted to be sure this includes the updates.
>   checking for file ‘/private/var/folders/b_/cx1l8cl53bx4m718hb1nh5g00000gn/T/Rtmpz1wj9s/remotes47af602f2e4c/sqjin-CellChat->a52e182/DESCRIPTION’ ...✓  checking for file >‘/private/var/folders/b_/cx1l8cl53bx4m718hb1nh5g00000gn/T/Rtmpz1wj9s/remotes47af602f2e4c/sqjin-CellChat-a52e182/DESCRIPTION’
>─  preparing ‘CellChat’:
>✓  checking DESCRIPTION meta-information ...
>─  cleaning src
>─  checking for LF line-endings in source and make files and shell scripts
>─  checking for empty or unneeded directories
>─  building ‘CellChat_1.0.0.tar.gz’

If this version does include the update, then the  message below is relevant ..

From: "Hooper, Joan" <JOAN.HOOPER@CUANSCHUTZ.EDU>
Date: Monday, April 5, 2021 at 1:14 PM
To: sqjin/CellChat ***@***.***>
Subject: Re: [sqjin/CellChat] sources.use causes error in hierarchy plots with netVisual_aggregate (#169)

I’m not sure if I am re-installing the latest version., I used
>devtools::install_github("sqjin/CellChat")
And got back


I reinstalled the package and it still has problems. I dug into the code and found two issues in the netVisual_hierarchy1 sub-function.

  1.  It does NOT pass ‘object’, so if I try to pass numeric sources.use, it errors out on to line 22

if (is.numeric(sources.use)) {

    sources.use <- ***@***.******@***.***)[sources.use>]
                If I make a new netVisual_hierarchy1 function , adding ‘object = object’ to the input arguments I, it corrects the problem. Or if I by-pass the need for this by using ‘levels(noseChat)[c(1:14,21,22)]’ in the original function call, it also works.

  1.  It does not properly process the reduced-size ‘net’ matrix if ‘remove.isolate = TRUE’. The problem shows up around line 55
net2 <- net

reorder.row <- c(vertex.receiver, setdiff(1:nrow(net), vertex.receiver))
net2 <- net2[reorder.row, vertex.receiver]

“Error in net2[reorder.row, vertex.receiver] : subscript out of bounds” because the original indices used in ‘vertex.receiver’ no longer fit the reduced size of the ‘net’ matrix – which ‘remove.isolate=T’ reduced from 22x22  to 22x9.

I can fix this for me locally, but thought you might want to fix it in the package



From: sqjin ***@***.***>
Reply-To: sqjin/CellChat ***@***.***>
Date: Thursday, April 1, 2021 at 11:44 PM
To: sqjin/CellChat ***@***.***>
Cc: "Hooper, Joan" <JOAN.HOOPER@CUANSCHUTZ.EDU>, Mention ***@***.***>
Subject: Re: [sqjin/CellChat] sources.use causes error in hierarchy plots with netVisual_aggregate (#169)


@hooperj<https://github.com/hooperj> Sorry about it. Can you reinstall the package and try it again? I just fixed this issue.

**Comment by sqjin** [comment]
@hooperj I checked `‘object ` in `netVisual_hierarchy1`, but I did not find it.  For the index issue, it seems not easy to solve it.  Can you use other type of plots such as circle?
