### ISSUE TITLE
A problem with install CellChat

### ISSUE THREAD

**Issue by Zechuan-Chen** [sqjin/CellChat#17]
Hello, when I install the CellChat R packages, something wrong with the CellChat.so file. The error messages are as follows:

** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘CellChat’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/czc/anaconda3/envs/scvi/lib/R/library/00LOCK-CellChat-master/00new/CellChat/libs/CellChat.so':
  /home/czc/anaconda3/envs/scvi/lib/R/library/00LOCK-CellChat-master/00new/CellChat/libs/CellChat.so: invalid ELF header
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/czc/anaconda3/envs/scvi/lib/R/library/CellChat’
Warning message:
In install.packages("./CellChat-master.tar.gz") :
  installation of package ‘./CellChat-master.tar.gz’ had non-zero exit status

**It seems that there was a problem with the CellChat.so file, which make me unable to install.**

-----------

And I can't open this file, with the same ERROR messages:  invalid ELF header

(scvi) [czc@covid libs]$ readelf -d CellChat.so
readelf: CellChat.so: Error: Not an ELF file - it has the wrong magic bytes at the start

Additional, It's difficult for me to install this packages from github by devtools, so I download and install this package from local.

Looking forward to your reply！Thank you very much!

**Comment by sqjin** [comment]
@Zechuan-Chen Please check the previous [issue#5](https://github.com/sqjin/CellChat/issues/5) to see if it can helps.

**Comment by sqjin** [comment]
@Zechuan-Chen You might need to install the source codes by `install.packages(path_to_file, type = 'source', rep = NULL)`

**Comment by Zechuan-Chen** [comment]
Thank you very much! I make it!
My server system is Centos7. I also delete the *.o and *.so file in the src directory. I don't know whether these two files are extra.

**Comment by genecell** [comment]
@sqjin @Zechuan-Chen I met the same error, and it only works after removing all the *.o and *.so files in the src directory. Thanks for the nice tool!

**Comment by chen-zhan** [comment]
> Thank you very much! I make it! My server system is Centos7. I also delete the *.o and *.so file in the src directory. I don't know whether these two files are extra.

Hi, I meet the same problem. But I have find the src directory. Where you find it? 
```
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘CellChat’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/public/home/niuxy/Software/miniconda3/envs/R4/lib/R/library/00LOCK-CellChat-master/00new/CellChat/libs/CellChat.so':
  /public/home/niuxy/Software/miniconda3/envs/R4/lib/R/library/00LOCK-CellChat-master/00new/CellChat/libs/CellChat.so: invalid ELF header
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/public/home/niuxy/Software/miniconda3/envs/R4/lib/R/library/CellChat’
Warning message:
In i.p(...) :
  installation of package ‘/public/home/niuxy/tmp//Rtmpr0b0sM/remotes1295152c57c2/CellChat-master’ had non-zero exit status

```
