### ISSUE TITLE
Interaction between distant organs?

### ISSUE THREAD

**Issue by HyacintViolet** [sqjin/CellChat#171]
Hi, I wonder if I could do analysis for cell cell communication between distant organs? A related issue might be #53 

Specifically, I think I would reduce the ligand-receptor database to only secreted proteins and their cognate receptors, and run CellChat on two organs, for example an organ secreting endocrines, such as pancreas, and another organ receiving the endocrine signal, such as liver.

For the permutation test, I may have to permute group labels within each organ separately, and look for interaction pairs between cells from different organs.

Do you think I could use CellTalk to do that? Many biologists may be interested in such analysis, especially for people who work on secreted proteins. Thanks!

**Comment by sqjin** [comment]
@HyacintViolet This is indeed an important application. From what I understand, endocrines provide a way to send signals from one place to another. Thus we can infer cell-cell communication based on the expression of ligands and receptors, and CellChat is applicable to such case. I think the communication happens within and between organs. So you can pull together all cell groups from different organs and then extract the interactions between organs from the cellchat analysis.
