### ISSUE TITLE
Population size use

### ISSUE THREAD

**Issue by cswoboda** [sqjin/CellChat#172]
You mention in the documentation of computecommunprob that:

"whether consider the proportion of cells in each group across all sequenced cells. Set population.size = FALSE if analyzing sorting-enriched single cells, to remove the potential artifact of population size. Set population.size = TRUE if analyzing unsorted single-cell transcriptomes, with the reason that abundant cell populations tend to send collectively stronger signals than the rare cell populations."

So, my tissue is unsorted, however, there's one celltype that is way overly abundant compared to the rest. Is it wrong to set population size to false here, if I want to highlight the interactions between the other smaller celltypes where I have evidence to suggest they are playing a crucial role in signaling within this dataset? I don't necessarily know whether or not in this specific tissue the more abundant cell population is sending the "strongest" signals per say.

Thanks,

Casey

**Comment by sqjin** [comment]
@cswoboda I am sorry I missed your question. In this case, you can set population.size = FALSE to avoid the potential artifacts.

**Comment by cswoboda** [comment]
Thank you!
