### ISSUE TITLE
Chord diagram diameter

### ISSUE THREAD

**Issue by camerongw** [sqjin/CellChat#175]
Hi, thanks for developing such a great tool. I find it really useful. I have a question about chord diagrams - is there any way to directly control the diameter?
When I run:
```R
par(mfrow=c(1,2))
netVisual_aggregate(
  naive, signaling = pathway, layout = "chord", cell.order = naive_order,
  vertex.label.cex = 0.9, scale = T)
netVisual_aggregate(
  infected, signaling = pathway, layout = "chord", cell.order = infected_order,
  vertex.label.cex = 0.9, scale = T)
```

I get this output:
![image](https://user-images.githubusercontent.com/65387606/114665921-f5120a00-9d40-11eb-84c8-8e54b17cbfc9.png)

I'm a bit unclear on why the sizes are so different, and I don't want to change/shrink the labels on one plot because I'd prefer the styles to be consistent.

**Comment by sqjin** [comment]
Hi @camerongw , sorry for the late reply.  Such issue is caused by the longer cell group names in your second plot. One way is to plot the graph separately.

**Comment by pormr** [comment]
It can be circumvented by using a monkey patch that override R function
`strwidth <- function(x) {0.02}`

**Comment by Kadd-L** [comment]
> It can be circumvented by using a monkey patch that overrides the original R function `strwidth <- function(x) {0.02}`

 This is amazing! Thank you @pormr !
