### ISSUE TITLE
netVisual_embedding error

### ISSUE THREAD

**Issue by jv-20** [sqjin/CellChat#176]
Hi @sqjin 

I am trying to generate a new figure based on cellchat analysis RData completed in early February. The analysis was performed in a single dataset.

When re-running this function, I receive error now. When I did the analysis in February, I was able to generate figures without any problem. Could you please advise?

```
netVisual_embedding(cellchat_obj, type = "functional")

Error in methods::slot(object, slot.name)$similarity[[type]]$dr[[comparison.name]] : 
  subscript out of bounds
```
I also tried updating updateCellChat(cellchat_obj), still the same error.

Thank you in advance

**Comment by sqjin** [comment]
@jv-20 Can you rerun the analysis from the function `computeNetSimilarity` to `netVisual_embedding`
