### ISSUE TITLE
About the method of Inference of intercellular communications in paper

### ISSUE THREAD

**Issue by gsq-gsq** [sqjin/CellChat#177]
Hi @sqjin 
First of all, thank you very much for providing such a great cell communication analysis tool. I was reading your paper recently, but I have some questions about the cell communication inference method described in the article.

a）Identification of differentially expressed signaling genes. 
Is the rank sum test used to identify differentially expressed signal genes between **_two cell groups_**? I don’t quite understand the meaning of "**_across all cell groups_**" in the text

b) Calculation of intercellular communication probability. 
I don't quite understand the relationship between the "random walk" mentioned in the article and the formula for calculating the communication probability; "Based on the projected ligand and receptor profiles.." makes me very confused.
![image](https://user-images.githubusercontent.com/59217784/114892900-c0d14300-9e3f-11eb-95c8-9d521524acf3.png)
I sincerely hope that you can take time to reply when you see the question, thank you again！

**Comment by sqjin** [comment]
@gsq-gsq Yes, the rank test was used to test the expression difference between cells in one cell group and cells in all other cell groups. Genes showing differential expression in at least one cell group were considered. 

Random walk was used to smooth the gene expression and the smoothed expression was called projected data. Using such projected data, one can compute the communication probabilities.

**Comment by gsq-gsq** [comment]
Thank you very much for your reply！
For question b), I found some source code about "projected" in the source code you uploaded. Can I understand it as an "Imputation" process for improving the quality of single-cell data?

**Comment by sqjin** [comment]
@gsq-gsq Yes, it is kind of imputation.

**Comment by gsq-gsq** [comment]
Okay, I understand, thanks again for your reply!
