### ISSUE TITLE
computeCommunProb: Error in P1 * P2 * P3 * P4 : non-conformable arrays

### ISSUE THREAD

**Issue by cnhaines01** [sqjin/CellChat#179]
Hi sqjin,

Thank you so much for an amazing program. I've run CellChat on several datasets now and have had so much success. In a recent run-through though I ran into an error after computeCommunProb that said "Error in P1 * P2 * P3 * P4 : non-conformable arrays." I have split a single seurat object into two based on treatment group and then ran the cellchat pipeline individually for each treatment group. The first treatment group I was able to run computeCommunProb without issue. They have the same cluster identities. I've tried re-installing CellChat and restarting my R session but have not had any luck. Any advice would be appreciated. 

Thank you,
Corinne Haines

Code: 

library(CellChat)
library(circlize)
library(ComplexHeatmap)
library(NMF)
library(ggplot2)                  
library(patchwork)
library(igraph)
library(dplyr)
library(ggalluvial)
library(Seurat)
options(stringsAsFactors = FALSE)

iBP <- readRDS("~/Documents/UNC_analysis/UNC Transfer 1 Objects/Melanoma/sc.list.allIntegration.afterUMAP.rds")

Idents(iBP) <- "seurat_clusters"
iBP_sub <- subset(iBP, idents = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29"))
Idents(iBP_sub) <- "orig.ident"
E2.Veh <- subset(iBP_sub, idents = "E2")
P.Veh <- subset(iBP_sub, idents = "Placebo")

cellchat_E2.Veh <- createCellChat(object = E2.Veh, group.by = "seurat_clusters")
cellchat_P.Veh <- createCellChat(object = P.Veh, group.by = "seurat_clusters")

CellChatDB <- CellChatDB.mouse # use CellChatDB.human if running on human data
showDatabaseCategory(CellChatDB)

CellChatDB.use <- CellChatDB
cellchat_E2.Veh@DB <- CellChatDB.use
cellchat_P.Veh@DB <- CellChatDB.use

cellchat_E2.Veh <- subsetData(cellchat_E2.Veh)
cellchat_E2.Veh <- identifyOverExpressedGenes(cellchat_E2.Veh)
cellchat_E2.Veh <- identifyOverExpressedInteractions(cellchat_E2.Veh)

cellchat_P.Veh <- subsetData(cellchat_P.Veh)
cellchat_P.Veh <- identifyOverExpressedGenes(cellchat_P.Veh)
cellchat_P.Veh <- identifyOverExpressedInteractions(cellchat_P.Veh)

cellchat_E2.Veh <- computeCommunProb(cellchat_E2.Veh, raw.use = TRUE, population.size = FALSE)
cellchat_E2.Veh <- filterCommunication(cellchat_E2.Veh, min.cells = 10)

cellchat_P.Veh <- computeCommunProb(cellchat_P.Veh, raw.use = TRUE, population.size = FALSE)

**Error in P1 * P2 * P3 * P4 : non-conformable arrays.

**Comment by sqjin** [comment]
@cnhaines01 Can you check your data, including object@data.signaling and object@idents, to see if they look ok? Please make sure the number of levels in the factor variable `object@idents` is the same as the number of cell groups.

**Comment by cnhaines01** [comment]
Upon investigation object@idents has included the cell group I had removed from my Seurat object. I was able to fix it using:

cellchat_P.Veh <- setIdent(cellchat_P.Veh, ident.use = "seurat_clusters", levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29"))

Thank you so much for your help!
