### ISSUE TITLE
Quick question: Support for SCTransform or alternative normalizations

### ISSUE THREAD

**Issue by ColeKeenum** [sqjin/CellChat#180]
I see that the input to CellChat needs to be a normalized matrix. 

This makes sense to me, but I was wondering if alternative normalizations, particularly [SCTransform](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1874-1), which is a popular normalization method would also be supported. 

In #64, I saw that the user was using SCTransform normalizations, and it seems like there was implicit permission to use such data, but I wanted to check explicitly. Considering that this normalization seems to remove technical artifacts in the data, I expect that other users may be interested an official answer.

**Comment by ColeKeenum** [comment]
Yes, something like this you mean?

input <- GetAssayData(object = seuratObj, assay = 'SCT', slot = "data")

**Comment by sqjin** [comment]
@ColeKeenum Missed your message. Yes, use `input <- GetAssayData(object = seuratObj, assay = 'SCT', slot = "data")`

**Comment by ColeKeenum** [comment]
@sqjin No problem. Thanks! This has worked for me.
