### ISSUE TITLE
Access to intermediate results

### ISSUE THREAD

**Issue by HyacintViolet** [sqjin/CellChat#181]
Hi, thanks for providing this wonderful tool!
I'm interested in a particular L-R pair within a dataset. 
After running the pipeline, the L-R pair I'm interested in did not show up in the df.net result.
I'm wondering if I could access the intermediate results and check for reasons why the L-R pair was missing, for example, one cell type involved in the L-R pair may have too few cells.

Thanks!

**Comment by sqjin** [comment]
@HyacintViolet The methods for computing the average expression per cell group will clearly produce different number of interactions. Thus you can check the average expression using different methods.  For example, you can play with the following codes by adjusting the `trim` parameter. 

data.input = cellchat@data.signaling
data.use.avg1 <- aggregate(t(data.input), list(cellchat@idents), FUN = function(x) mean(x, trim = 0.10, na.rm = TRUE))
data.use.avg1[,"WNT4"]
data.use.avg1[,"LRP6"]

**Comment by HyacintViolet** [comment]
Thank you @sqjin!
