### ISSUE TITLE
Interaction strength and probability values

### ISSUE THREAD

**Issue by cswoboda** [sqjin/CellChat#182]
Hi again @sqjin! 

In using your package across a few different datasets I've noticed two technical concerns I wanted to run by you for clarification

1. When you map to a PPI instead of using raw values, the cumulative "interaction strength" and probability of my interactions seems to reduce drastically (under a value of 1 for example)
2. I use mostly nuclear instead of single cell data, which often suffers from less sequencing depth of unique genes and ambient mRNA contamination. It's unclear to me whether we could consider this data of "high sequencing depth", as there's different field standards comparative to single cell rna seq. However, raw values tend to give me higher interaction strength (depends on the dataset, but lets say raw data gives me a cumulative interaction strength of 16 in one dataset, while using ppi gives me 0.5.

I'm essentially just reaching out for insight into how important the value of this number is (it seems like cellchat does analysis by compared relative changes rather than having a standard of "sufficient interaction strength". 

thanks,

Casey

**Comment by sqjin** [comment]
@cswoboda Yes, all values are relative and there is no sufficiently small values.  You can use the raw values as it often produces more clean interactions. You can take a look at the updated tutorial, where you may want to change the methods for computing average expression if some important signaling genes only express in a small portion of cells.
