### ISSUE TITLE
Pathways of River Plot missing

### ISSUE THREAD

**Issue by yjgeno** [sqjin/CellChat#183]
Hi, thanks for your package!

My issue was that after I computed netAnalysis_river(cellchat, pattern = "outgoing"), some of the significant pathways did not show in the river plot. 

The heatmap computed by identifyCommunicationPatterns(cellchat) gave me the complete list of pathways. 

I presumed the pathways shown on the river plot, after NMF, should be identical for 'outgoing' and 'incoming'. Also, the river plot should give me the same pathway list as the heatmap.

I was wondering if you set any filter in the river plot? Are pathways on the river plot the significant pathways in subsetCommunication(cellchat)?

May you let me know if anything I was missing? Thank you.

**Comment by sqjin** [comment]
@yjgeno There is a `cutoff` parameter when using netAnalysis_river. You can try to decrease it.

**Comment by yjgeno** [comment]
Hi @sqjin thanks for your info. I was initially wondering if it was a bug of the function or something I did wrong?
I had about more than 30 pathways to show
