### ISSUE TITLE
How to calculate the Interaction weights/strength

### ISSUE THREAD

**Issue by miaomiaotan** [sqjin/CellChat#184]
Hi, 
Thank you for this user-friendly package!
You mentioned two ways to display the aggregated cell-cell communication network, the "Number of interactions" and the "Interaction weights/strength". Can you talk about how the Interaction weights was calculated? Thank you!

**Comment by sqjin** [comment]
@miaomiaotan It is the communication probability defined in our paper. The matrix is cellchat@net$prob or cellchat@netP$prob

**Comment by miaomiaotan** [comment]
@sqjin Get it. Thank you!

**Comment by Kiven-zero-Li** [comment]
Hello, thank you for this package!
I have some confusions when using it. After I created the cellchat object, I have seen two matrix: cellchat@net$prob and cellchat@net$weight, and they are different. If the former one is used to describe the interaction weights/strength, what about the latter one: cellchat@net$weight? What is it used to?
Looking forward to your reply! This is very important for me. Thank you!

**Comment by mumdark** [comment]
> Hello, thank you for this package! I have some confusions when using it. After I created the cellchat object, I have seen two matrix: cellchat@net$prob and cellchat@net$weight, and they are different. If the former one is used to describe the interaction weights/strength, what about the latter one: cellchat@net$weight? What is it used to? Looking forward to your reply! This is very important for me. Thank you!

@Kiven-zero-Li I'm not certain if I have understood correctly, but cellchat@net$weight might be the sum of cellchat@net$prob.
