### ISSUE TITLE
Error thrown during the subsetData(cellchat)

### ISSUE THREAD

**Issue by BuddySphinx** [sqjin/CellChat#185]
Hi, I am new to cellchat and I have encountered an issue when running to the step subsetData(cellchat), which threw an error Error in UseMethod("select") : no applicable method for 'select' applied to an object of class "NULL". I created the cellchat object from a Seurat object. Here is my code:
load("lung_dat.Robj")
lung<-NormalizeData(lung_dat)
#Preprocess and create a Cell chat object
data.input<-GetAssayData(lung,assay = "RNA",slot = "data")
meta<-lung_dat@meta.data
cellchat <- createCellChat(object = data.input,meta=meta,group.by = "cell.type.ident")
I am wondering what caused this error?

**Comment by sqjin** [comment]
@BuddySphinx The codes you showed look ok. Can you show me all your codes before running subsetData?

**Comment by BuddySphinx** [comment]
@sqjin Here is the full code I have:
library(CellChat)
library(Seurat)
options(stringsAsFactors = FALSE)
load("ligand_receptor.RData")
load("lung_dat.Robj")
lung<-NormalizeData(lung_dat)
#Preprocess and create a Cell chat object
data.input<-GetAssayData(lung,assay = "RNA",slot = "data")
meta<-lung_dat@meta.data
cellchat <- createCellChat(object = data.input,meta=meta,group.by = "cell.type.ident")
#Define a database
CellChatDB1.use<-data.frame(ligand_receptor[[1]])
cellchat@DB<-CellChatDB1.use
cellchat <- subsetData(cellchat)

**Comment by sqjin** [comment]
@BuddySphinx Can you check the difference of CellChatDB1.use with our database CellChatDB.human/mouse? You should make sure they have similar columns. This is the only potential issue I can see.

**Comment by BuddySphinx** [comment]
@sqjin thank you for your reply. That's the part I had issue with. Because the database only includes two columns, ligand and receptor pairs and I wasn't sure if it will work. Any suggestions if this format does not work?

**Comment by sqjin** [comment]
@BuddySphinx I suggest to have the same columns as in CellChatDB.mouse even if they are empty in certain columns.
