### ISSUE TITLE
error with netAnalysis_computeCentrality using mergeCellChat object

### ISSUE THREAD

**Issue by mcap91** [sqjin/CellChat#187]
Thank you for this amazing package. 

I have a merged cellchat object (2 individual cellchat runs using Cellchat 1.1.0). 

I am getting the following error when trying to produce this figure from netAnalysis_signalingChanges_scatter:

![image](https://user-images.githubusercontent.com/36866996/116945730-42411780-ac2d-11eb-856a-747fdb4dbbd1.png)

```Please run `netAnalysis_computeCentrality` to compute the network centrality scores!```

then I run 

```cellchat <- netAnalysis_computeCentrality(cellchat)```

but receive the following error

``` Error in if (nrow(adjmatrix) != ncol(adjmatrix)) { :  argument is of length zero```

I am not sure how to fix this because when I run 

```
gg <- list()
for (i in 1:length(object.list)) {
  object.list[[i]] <- netAnalysis_computeCentrality(object.list[[i]])
  gg[[i]] <- netAnalysis_signalingRole_scatter(object.list.sub[[i]], title = names(object.list)[i], weight.MinMax = weight.MinMax)
}
patchwork::wrap_plots(plots = gg)
```

from the tutorial to generate another plot it works. 

thank you

**Comment by mcap91** [comment]
I got this to work by running ```netAnalysis_computeCentrality``` on each cellchat object in the ```object.list``` separately and then using ```mergeCellChat```.

**Comment by BatLaB-cell** [comment]
@mcap91 Do you mean you run the following code for each cell chat object before merging them in the object.list?

cellchat.dataset1<-netAnalysis_computeCentrality(cellchat.dataset1)

When I tried on each individual cell chat objects, I also get the error:

Error in if (nrow(adjmatrix) != ncol(adjmatrix)) { : argument is of length zero

@sqjin Any suggestion about this error?

**Comment by Tycooner** [comment]
same problem, please help!!!

**Comment by sqjin** [comment]
@zpingfeng @Tycooner Can you guys share me your CellChat object for further checking?

**Comment by zpingfeng** [comment]
Thanks Suoqin!
How do I send the cellchat obj? The file is >26MB. I tried to drag it to here, but was not allowed

**Comment by zpingfeng** [comment]
str(cellchat)
Formal class 'CellChat' [package "CellChat"] with 14 slots
  ..@ data.raw      : num[0 , 0 ] 
  ..@ data          :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. ..@ i       : int [1:3310998] 0 2 15 18 19 22 55 56 70 76 ...
  .. .. ..@ p       : int [1:1892] 0 1458 2676 4277 5999 7762 9394 10444 12907 14078 ...
  .. .. ..@ Dim     : int [1:2] 14494 1891
  .. .. ..@ Dimnames:List of 2
  .. .. .. ..$ : chr [1:14494] "Mrpl15" "Lypla1" "Tcea1" "Atp6v1h" ...
  .. .. .. ..$ : chr [1:1891] "AAACCTGAGCGACGTA-1_4" "AAACCTGAGCTAAACA-1_4" "AAACCTGGTTGTACAC-1_4" "AAACCTGTCTAACCGA-1_4" ...
  .. .. ..@ x       : num [1:3310998] 1 2 1 1 1 3 1 5 1 3 ...
  .. .. ..@ factors : list()
  ..@ data.signaling:Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. ..@ i       : int [1:3310998] 0 2 15 18 19 22 55 56 70 76 ...
  .. .. ..@ p       : int [1:1892] 0 1458 2676 4277 5999 7762 9394 10444 12907 14078 ...
  .. .. ..@ Dim     : int [1:2] 14494 1891
  .. .. ..@ Dimnames:List of 2
  .. .. .. ..$ : chr [1:14494] "Mrpl15" "Lypla1" "Tcea1" "Atp6v1h" ...
  .. .. .. ..$ : chr [1:1891] "AAACCTGAGCGACGTA-1_4" "AAACCTGAGCTAAACA-1_4" "AAACCTGGTTGTACAC-1_4" "AAACCTGTCTAACCGA-1_4" ...
  .. .. ..@ x       : num [1:3310998] 1 2 1 1 1 3 1 5 1 3 ...
  .. .. ..@ factors : list()
  ..@ data.scale    : num[0 , 0 ] 
  ..@ data.project  : num [1:14494, 1:1891] 1 0 2 0 0 0 0 0 0 0 ...
  .. ..- attr(*, "dimnames")=List of 2
  .. .. ..$ : chr [1:14494] "Mrpl15" "Lypla1" "Tcea1" "Atp6v1h" ...
  .. .. ..$ : chr [1:1891] "AAACCTGAGCGACGTA-1_4" "AAACCTGAGCTAAACA-1_4" "AAACCTGGTTGTACAC-1_4" "AAACCTGTCTAACCGA-1_4" ...
  ..@ net           :List of 2
  .. ..$ prob: num [1:4, 1:4, 1:18] 0 0 0 0 0 0 0 0 0 0 ...
  .. .. ..- attr(*, "dimnames")=List of 3
  .. .. .. ..$ : chr [1:4] "Conventional Treg" "IL17-producing" "Naive Treg" "Ikzf1+"
  .. .. .. ..$ : chr [1:4] "Conventional Treg" "IL17-producing" "Naive Treg" "Ikzf1+"
  .. .. .. ..$ : chr [1:18] "APP_CD74" "CD200_CD200R4" "CD40LG_CD40" "CD86_CD28" ...
  .. ..$ pval: num [1:4, 1:4, 1:18] 1 1 1 1 1 1 1 1 1 1 ...
  .. .. ..- attr(*, "dimnames")=List of 3
  .. .. .. ..$ : chr [1:4] "Conventional Treg" "IL17-producing" "Naive Treg" "Ikzf1+"
  .. .. .. ..$ : chr [1:4] "Conventional Treg" "IL17-producing" "Naive Treg" "Ikzf1+"
  .. .. .. ..$ : chr [1:18] "APP_CD74" "CD200_CD200R4" "CD40LG_CD40" "CD86_CD28" ...
  ..@ netP          :List of 2
  .. ..$ pathways: chr(0) 
  .. ..$ prob    : num[1:4, 1:4, 0 ] 
  .. .. ..- attr(*, "dimnames")=List of 3
  .. .. .. ..$ : chr [1:4] "Conventional Treg" "IL17-producing" "Naive Treg" "Ikzf1+"
  .. .. .. ..$ : chr [1:4] "Conventional Treg" "IL17-producing" "Naive Treg" "Ikzf1+"
  .. .. .. ..$ : NULL
  ..@ meta          :'data.frame':	1891 obs. of  16 variables:
  .. ..$ orig.ident         : chr [1:1891] "BM.s31" "BM.s31" "BM.s31" "BM.s31" ...
  .. ..$ nCount_RNA         : num [1:1891] 2817 1964 3014 3922 4102 ...
  .. ..$ nFeature_RNA       : int [1:1891] 1458 1218 1601 1722 1763 1632 1050 2463 1171 1168 ...
  .. ..$ percent.mt         : num [1:1891] 1.77 3.92 2.35 1.96 1.02 ...
  .. ..$ RNA_snn_res.0.3    : chr [1:1891] "1" "1" "1" "0" ...
  .. ..$ seurat_clusters.old: Factor w/ 6 levels "0","1","2","3",..: 1 2 1 2 1 1 1 1 1 1 ...
  .. ..$ sample             : chr [1:1891] "BM.Treg.HOM" "BM.Treg.HOM" "BM.Treg.HOM" "BM.Treg.HOM" ...
  .. ..$ nCount_SCT         : num [1:1891] 3283 3086 3332 3805 3874 ...
  .. ..$ nFeature_SCT       : int [1:1891] 1458 1250 1601 1722 1763 1632 1070 2357 1180 1171 ...
  .. ..$ SCT_snn_res.0.1    : Factor w/ 5 levels "0","1","2","3",..: 1 1 1 1 1 1 1 1 1 1 ...
  .. ..$ group              : chr [1:1891] "BM.Treg" "BM.Treg" "BM.Treg" "BM.Treg" ...
  .. ..$ SCT_snn_res.0.09   : Factor w/ 5 levels "0","1","2","3",..: 1 1 1 1 1 1 1 1 1 1 ...
  .. ..$ SCT_snn_res.0.06   : Factor w/ 4 levels "0","1","2","3": 1 1 1 1 1 1 1 1 1 1 ...
  .. ..$ SCT_snn_res.0.2    : Factor w/ 6 levels "0","1","2","3",..: 1 2 1 2 1 1 1 1 1 1 ...
  .. ..$ SCT_snn_res.0.3    : Factor w/ 9 levels "0","1","2","3",..: 1 6 1 2 1 1 1 1 1 1 ...
  .. ..$ seurat_clusters    : Factor w/ 4 levels "Conventional Treg",..: 1 2 1 2 1 1 1 1 1 1 ...
  ..@ idents        : Factor w/ 4 levels "Conventional Treg",..: 1 2 1 2 1 1 1 1 1 1 ...
  ..@ DB            :List of 4
  .. ..$ interaction:'data.frame':	378 obs. of  11 variables:
  .. .. ..$ interaction_name  : chr [1:378] "ADGRE5_CD55B" "ALCAM_CD6" "ANXA1_FPR2_LXA4" "APP_CD74" ...
  .. .. ..$ pathway_name      : chr [1:378] "ADGRE5" "ALCAM" "ANXA1" "APP" ...
  .. .. ..$ ligand            : chr [1:378] "Adgre5" "Alcam" "Anxa1" "App" ...
  .. .. ..$ receptor          : chr [1:378] "Cd55b" "Cd6" "FPR2_LXA4" "Cd74" ...
  .. .. ..$ agonist           : chr [1:378] "" "" "" "" ...
  .. .. ..$ antagonist        : chr [1:378] "" "" "" "" ...
  .. .. ..$ co_A_receptor     : chr [1:378] "" "" "" "" ...
  .. .. ..$ co_I_receptor     : chr [1:378] "" "" "" "" ...
  .. .. ..$ evidence          : chr [1:378] "PMID: 11297558" "KEGG: mmu04514" "PMID: 22610094" "PMID: 19849849" ...
  .. .. ..$ annotation        : chr [1:378] "Cell-Cell Contact" "Cell-Cell Contact" "Cell-Cell Contact" "Cell-Cell Contact" ...
  .. .. ..$ interaction_name_2: chr [1:378] "Adgre5  - Cd55b" "Alcam  - Cd6" "Anxa1  - (Fpr2+Lxa4)" "App  - Cd74" ...
  .. ..$ complex    :'data.frame':	155 obs. of  4 variables:
  .. .. ..$ subunit_1: chr [1:155] "Inhba" "Inha" "Inha" "Il12a" ...
  .. .. ..$ subunit_2: chr [1:155] "Inhbb" "Inhba" "Inhbb" "Il12b" ...
  .. .. ..$ subunit_3: chr [1:155] "" "" "" "" ...
  .. .. ..$ subunit_4: chr [1:155] "" "" "" "" ...
  .. ..$ cofactor   :'data.frame':	31 obs. of  16 variables:
  .. .. ..$ cofactor1 : chr [1:31] "Fst" "Bambi" "Tie1" "Ptprb" ...
  .. .. ..$ cofactor2 : chr [1:31] "" "" "" "" ...
  .. .. ..$ cofactor3 : chr [1:31] "" "" "" "" ...
  .. .. ..$ cofactor4 : chr [1:31] "" "" "" "" ...
  .. .. ..$ cofactor5 : chr [1:31] "" "" "" "" ...
  .. .. ..$ cofactor6 : chr [1:31] "" "" "" "" ...
  .. .. ..$ cofactor7 : chr [1:31] "" "" "" "" ...
  .. .. ..$ cofactor8 : chr [1:31] "" "" "" "" ...
  .. .. ..$ cofactor9 : chr [1:31] "" "" "" "" ...
  .. .. ..$ cofactor10: chr [1:31] "" "" "" "" ...
  .. .. ..$ cofactor11: chr [1:31] "" "" "" "" ...
  .. .. ..$ cofactor12: chr [1:31] "" "" "" "" ...
  .. .. ..$ cofactor13: chr [1:31] "" "" "" "" ...
  .. .. ..$ cofactor14: chr [1:31] "" "" "" "" ...
  .. .. ..$ cofactor15: chr [1:31] "" "" "" "" ...
  .. .. ..$ cofactor16: chr [1:31] "" "" "" "" ...
  .. ..$ geneInfo   :'data.frame':	45544 obs. of  6 variables:
  .. .. ..$ Symbol         : chr [1:45544] "a" "Pzp" "Abl1" "Abl2" ...
  .. .. ..$ Name           : chr [1:45544] "nonagouti" "PZP, alpha-2-macroglobulin like" "c-abl oncogene 1, non-receptor tyrosine kinase" "v-abl Abelson murine leukemia viral oncogene 2 (arg, Abelson-related gene)" ...
  .. .. ..$ EntrezGene.ID  : chr [1:45544] "50518" "11287" "11350" "11352" ...
  .. .. ..$ Ensembl.Gene.ID: chr [1:45544] "ENSMUSG00000027596" "ENSMUSG00000030359" "ENSMUSG00000026842" "ENSMUSG00000026596" ...
  .. .. ..$ HomoloGene.ID  : chr [1:45544] "1264" "104112" "3783" "5278" ...
  .. .. ..$ HGNC.ID        : chr [1:45544] "HGNC:745" "null" "HGNC:76" "HGNC:77" ...
  ..@ LR            :List of 1
  .. ..$ LRsig:'data.frame':	18 obs. of  11 variables:
  .. .. ..$ interaction_name  : chr [1:18] "APP_CD74" "CD200_CD200R4" "CD40LG_CD40" "CD86_CD28" ...
  .. .. ..$ pathway_name      : chr [1:18] "APP" "CD200" "CD40" "CD86" ...
  .. .. ..$ ligand            : chr [1:18] "App" "Cd200" "Cd40lg" "Cd86" ...
  .. .. ..$ receptor          : chr [1:18] "Cd74" "Cd200r4" "Cd40" "Cd28" ...
  .. .. ..$ agonist           : chr [1:18] "" "" "" "" ...
  .. .. ..$ antagonist        : chr [1:18] "" "" "" "" ...
  .. .. ..$ co_A_receptor     : chr [1:18] "" "" "" "" ...
  .. .. ..$ co_I_receptor     : chr [1:18] "" "" "" "" ...
  .. .. ..$ evidence          : chr [1:18] "PMID: 19849849" "KEGG: mmu04514" "KEGG: mmu04514" "PMID: 23954143" ...
  .. .. ..$ annotation        : chr [1:18] "Cell-Cell Contact" "Cell-Cell Contact" "Cell-Cell Contact" "Cell-Cell Contact" ...
  .. .. ..$ interaction_name_2: chr [1:18] "App  - Cd74" "Cd200  - Cd200r4" "Cd40lg  - Cd40" "Cd86  - Cd28" ...
  ..@ var.features  :List of 2
  .. ..$ features     : chr [1:2913] "Crip1" "Tmsb4x" "S100a4" "Vim" ...
  .. ..$ features.info:'data.frame':	2913 obs. of  7 variables:
  .. .. ..$ clusters   : chr [1:2913] "Conventional Treg" "Conventional Treg" "Conventional Treg" "Conventional Treg" ...
  .. .. ..$ features   : chr [1:2913] "Crip1" "Tmsb4x" "S100a4" "Vim" ...
  .. .. ..$ pvalues    : num [1:2913] 1.04e-23 1.18e-21 8.83e-19 9.34e-19 5.34e-15 ...
  .. .. ..$ logFC      : num [1:2913] 28.9534 73.8502 17.0437 18.7932 0.0326 ...
  .. .. ..$ pct.1      : num [1:2913] 0.903 0.999 0.756 0.85 0.939 0.819 0.919 0.895 0.818 0.943 ...
  .. .. ..$ pct.2      : num [1:2913] 0.758 0.982 0.567 0.725 0.833 0.677 0.833 0.835 0.695 0.875 ...
  .. .. ..$ pvalues.adj: num [1:2913] 1.50e-19 1.71e-17 1.28e-14 1.35e-14 7.74e-11 ...
  ..@ dr            : list()
  ..@ options       :List of 3
  .. ..$ mode     : chr "single"
  .. ..$ run.time : num 2758
  .. ..$ parameter:List of 8
  .. .. ..$ type.mean      : chr "triMean"
  .. .. ..$ trim           : NULL
  .. .. ..$ raw.use        : logi TRUE
  .. .. ..$ population.size: logi FALSE
  .. .. ..$ nboot          : num 100
  .. .. ..$ seed.use       : int 1
  .. .. ..$ Kh             : num 0.5
  .. .. ..$ n              : num 1

**Comment by zpingfeng** [comment]
the problem start from here for this data set
> cellchat <- computeCommunProbPathway(cellchat)
Error in apply(prob.pathways.sig, 3, sum) : 
  'MARGIN' does not match dim(X)

I have several sets of data. Each had problems at different steps.

**Comment by zpingfeng** [comment]
probably no signal to match?

**Comment by Roeply** [comment]
> 这个数据集的问题从这里开始
> 
> > cellchat <- computeCommunProbPathway(cellchat)
> > 错误应用(prob.pathways.sig, 3, sum) : 
> > 'MARGIN' 不匹配dim(X)
> 
> 我有几组数据。每个人在不同的步骤都有问题。

I also have same problem

**Comment by PeggySze** [comment]
I also have the same problem. Dose anyone know how to solve it ? Thanks!

**Comment by XiaohanLuDuke** [comment]
> the problem starts from here for this data set
> 
> > cellchat <- computeCommunProbPathway(cellchat)
> > Error in apply(prob.pathways.sig, 3, sum) :
> > 'MARGIN' does not match dim(X)
> 
> I have several sets of data. Each had problems at different steps.

I have similar problem. Have you fix it? Could you please share your solution?

**Comment by XiaohanLuDuke** [comment]
> > 这个数据集的问题从这里开始
> > > cellchat <- computeCommunProbPathway(cellchat)
> > > 错误应用(prob.pathways.sig, 3, sum) :
> > > 'MARGIN' 不匹配dim(X)
> > 
> > 
> > 我有几组数据。每个人在不同的步骤都有问题。
> 
> I also have same problem

Have you find out the solution?

**Comment by fouerghi** [comment]
> 

I am also running into this error. Any solutions?

**Comment by cherrie-g** [comment]
I also met the same error, does anyone solute it?

**Comment by XiaohanLuDuke** [comment]
Thank you so much!

Hannah
________________________________

**Comment by Rhacki** [comment]
whenI had this error:
if (nrow(adjmatrix) != ncol(adjmatrix)) { :  argument is of length zero
after running cellchat <- netAnalysis_computeCentrality(cellchat, slot.name = "netP") 
I had to run the following code again and it fixed the problem:  
cellchat <- computeCommunProbPathway(cellchat)
