### ISSUE TITLE
Interaction weights/strength from tutorial different

### ISSUE THREAD

**Issue by erikagucciardo** [sqjin/CellChat#188]
Hi! Thanks for this useful tool!
I am running through the tutorial, but the graph with title "Interaction weights/strength" turns out different in the plot window.
What could be the cause?
Notably, when I run par(mfrow = c(3,4), xpd=TRUE), I get a fatal error and the R session aborts. This doesn't happen when I remove "xpd=TRUE". Is this change the reason why the plot looks different?

**Comment by sqjin** [comment]
@erikagucciardo Can you show me the plot? Is it very different or minor different?

**Comment by erikagucciardo** [comment]
![Troubleshoot](https://user-images.githubusercontent.com/51324470/117437878-7e2ff180-af39-11eb-9c49-ed20020cee93.png)
This is how it looks in the plot window. When I save it, it looks just fine. It might be something to do with the parameter "xpd", but my R session aborts if I set this parameter to TRUE.

**Comment by sqjin** [comment]
@erikagucciardo Interesting. I never have such issue.
