### ISSUE TITLE
How can I get Information flow figure in your paper？

### ISSUE THREAD

**Issue by MMriran** [sqjin/CellChat#189]
Hi，thank you for your great tool！ It works well and helps a lot. And I have a question about information flow figure in your paper.  When I try to get the  Information flow figure (eg.Fig 5k) and run the codes in your tutorials, then, I found I only got a barplot  with all pathways in one direction.    So How  can I get the information flow figure with pathways in both sides and order the pathway by their P values ( same as Fig 5k in your paper)?

![image](https://user-images.githubusercontent.com/51091889/117230723-400ad300-ae50-11eb-91ad-9996ef95bae5.png)

**Comment by MMriran** [comment]
![image](https://user-images.githubusercontent.com/51091889/117230690-31242080-ae50-11eb-9e5b-96e4ef7f200f.png)

**Comment by sqjin** [comment]
@MMriran  it is deprecated now as it can not be extended to three datasets. You can try the codes below (I think it looks nice)
`rankNet(cellchat, mode = "comparison", stacked = T, do.stat = TRUE)`
