### ISSUE TITLE
computeCommunProb Error: there is no package called 'CellChat'

### ISSUE THREAD

**Issue by Margaret-jo** [sqjin/CellChat#192]
Hi @sqjin 

I got an error when calling the computeCommunProb function after updated the CellChat version to 1.1.0 :
Error: there is no package called 'CellChat'.

The previous steps including CellChat object creation and ligand-receptor interaction database setting were all went well, till the computeCommunProb function was called.

May I have your kind suggestions?
Many thanks!

**Comment by sqjin** [comment]
@Margaret-jo This is interesting. Can you run the source codes of this function to see where is the error coming from?

**Comment by superman2412** [comment]
> Hi @sqjin
> 
> I got an error when calling the computeCommunProb function after updated the CellChat version to 1.1.0 :
> Error: there is no package called 'CellChat'.
> 
> The previous steps including CellChat object creation and ligand-receptor interaction database setting were all went well, till the computeCommunProb function was called.
> 
> May I have your kind suggestions?
> Many thanks!

@Margaret-jo Double check if you have updated R to (R 4.0>), I get the same error when I update R.

**Comment by Margaret-jo** [comment]
> @Margaret-jo Double check if you have updated R to (R 4.0>), I get the same error when I update R

Thanks for your suggestion, I have re-installed the Cellchat and then solved this problem.

**Comment by Margaret-jo** [comment]
> @Margaret-jo This is interesting. Can you run the source codes of this function to see where is the error coming from?

Many thanks for your reply. The issue was solved by re-installation of the package. THX again for the support.
