### ISSUE TITLE
error when calling identifyOverExpressedGenes function

### ISSUE THREAD

**Issue by xiaozhutou789** [sqjin/CellChat#193]
I used the test dataset data_humanSkin and ran the programe as follow. However, there was an mistake like cellchat <- identifyOverExpressedGenes(cellchat)
**Error in genes.de[[i]] : subscript out of bounds**
How to fix it ?
Many thanks~
# subset the expression data of signaling genes for saving computation cost
cellchat <- subsetData(cellchat) # This step is necessary even if using the whole database
future::plan("multiprocess", workers = 4) # do parallel
#> Warning: [ONE-TIME WARNING] Forked processing ('multicore') is disabled
#> in future (>= 1.13.0) when running R from RStudio, because it is
#> considered unstable. Because of this, plan("multicore") will fall
#> back to plan("sequential"), and plan("multiprocess") will fall back to
#> plan("multisession") - not plan("multicore") as in the past. For more details,
#> how to control forked processing or not, and how to silence this warning in
#> future R sessions, see ?future::supportsMulticore
cellchat <- identifyOverExpressedGenes(cellchat)
cellchat <- identifyOverExpressedInteractions(cellchat)
# project gene expression data onto PPI network (optional)
cellchat <- projectData(cellchat, PPI.human)

**Comment by xiaozhutou789** [comment]
and I ran the program on the linux R

**Comment by sqjin** [comment]
@xiaozhutou789 For such errors, I have to say I have no idea. I suggest you to run the sources codes line by line or send me the codes and data that I can replicate your error.
