### ISSUE TITLE
Vertex Receiver

### ISSUE THREAD

**Issue by vim15** [sqjin/CellChat#198]
I'm sorry, but I am very confused about how to set the vertex.receiver and what it means as it's numeric. 

I run the below : 
```
vertex.receiver = seq(1,1) # a numeric vector. 
netVisual_aggregate(cellchatHF1, signaling = pathways.show,  vertex.receiver = vertex.receiver)
```
and obviously when I change the numbers at the vertex.receiver slot the plots change, but I have no idea what each of the 2 numbers relates to, or how to find out which of my clusters (which are named) are what number. 

If you could let me know how I can find out in my object which of the clusters corresponds to what number, or give more info about this field I would greatly appreciate it. 

Also, it only allows you to input 2 numbers i.e 2 populations (?), what happens if you're only interested in 1 population being the sender? I've tried putting (1, ) or (1, 0) with no avail. Your help would be much appreciated, Thank you.

**Comment by sqjin** [comment]
@vim15 You can check the order of cell groups in cellchat object using `levels(cellchat@idents)`, which corresponds to 1,2,3,...

You can set vertex.receiver = c(1,2,5,7), which will put these cell groups at the most left side in the plot. Assuming these groups represent immune cells and the remaining groups are fibrobalsts, such plot is very useful to study the interactions between immune cells and firbroblasts.

**Comment by vim15** [comment]
Hello!

Thank you for the help and the quick response, works like a charm. 
Is there a way to just have 1 population as the sender? Based on the above I've tried both : 

vertex.receiver = c(1) & vertex.receiver = 1 and both of these fail with the following error : 
Error in matrix(0, m1, m1) : non-numeric matrix extent

Thanks again :)

**Comment by wajm** [comment]
same issue with me.
any option for this?

**Comment by sqjin** [comment]
@wajm @vim15 This function will not work if there is only one element defined in `vertex.receiver`. In this case, you can use the circle plot.
