### ISSUE TITLE
there is no package called ‘CellChat’ 

### ISSUE THREAD

**Issue by zh-Bian** [sqjin/CellChat#2]
Hello, when I used the function computeCommunProb(), it always reported an error:  there is no package called ‘CellChat’. Could you give  me some advice to solve the problem? Thank you! @sqjin

**Comment by sqjin** [comment]
@zh-Bian Can you show me several lines of codes before you run this function and how you run this function?

**Comment by zh-Bian** [comment]
I followed the process of 'Walkthrough - CellChat analysis of cell-cell communication in mouse skin wounds'. Here are my codes.

cellchat <- subsetData(cellchat) # subset the expression data of signaling genes for saving computation cost
future::plan("multiprocess", workers = 15) # do parallel
cellchat <- identifyOverExpressedGenes(cellchat)
cellchat <- identifyOverExpressedInteractions(cellchat)
cellchat <- projectData(cellchat, PPI.mouse) #human/mouse

library(CellChat)

cellchat <- computeCommunProb(cellchat)  
cellchat <- computeCommunProbPathway(cellchat)
cellchat <- aggregateNet(cellchat)

When it run to 'cellchat <- computeCommunProb(cellchat) ', it failed with " 'there is no package called ‘CellChat’ ". Then I used to source code to test and I found the error occured in function computeExpr_complex().

data.complex = my.sapply(
    X = 1:nrow(Rsubunits),
    FUN = function(x) {
      RsubunitsV <- unlist(Rsubunits[x,], use.names = F)
      RsubunitsV <- RsubunitsV[RsubunitsV != ""]
      return(geometricMean(data.use[RsubunitsV,]))
    }
  )

**Comment by sqjin** [comment]
@zh-Bian I have no idea on this error for now. I searched the similar issue online, and you might can try  `library.path <- .libPaths()
library("cellchat", lib.loc = library.path)`. Please check [here](https://stackoverflow.com/questions/27673000/rscript-there-is-no-package-called). If it does not work, can you share your cellchat object with me or your colleague?

**Comment by sqjin** [comment]
@zh-Bian library.path <- .libPaths(); library("CellChat", lib.loc = library.path)

**Comment by zh-Bian** [comment]
Hello, Thank you for your advice. I tried your method but it didn't work. And I noticed an interesting detail: when I first open my Rstudio, 'cellchat <- computeCommunProb(cellchat)' works fine,  however the second is the same wrong. I think whether the function needs to access some resources online, so it sometimes works and sometimes not. @sqjin

**Comment by sqjin** [comment]
@zh-Bian I will take a look and fix this issue. For now, please just run this function only one time.

**Comment by zh-Bian** [comment]
OK. The way for me to use the package is interesting, and the package is useful. Thank you very much for answering my questions.

**Comment by sqjin** [comment]
@zh-Bian Hello, just let you know that I have no issue to rerun `cellchat <- computeCommunProb(cellchat)` in the same Rstudio.
