### ISSUE TITLE
One KEGG not found in database

### ISSUE THREAD

**Issue by ruohuchengxhe** [sqjin/CellChat#20]
Hi,
Is there a way to customise the database? I'm using the mouse database and looking specifically for KEGG: mmu04620. However, I didn't find this  in it. So I wonder if it is possible to add this one? And if yes, could you please provide how to do it? Thanks!

**Comment by sqjin** [comment]
Hi @ruohuchengxhe , yes, you can add new L-R pairs. First, you need to save three files based on the information in CellChatDB, including 'interaction_input_CellChat.csv', 'complex_input_CellChat.csv', 'and cofactor_input_CellChat.csv'. Second, you can add your curated information in these files. Third, run the following codes `options(stringsAsFactors = FALSE) 
interaction_input <- read.csv(file = 'interaction_input_CellChat.csv')
row.names(interaction_input) <- interaction_input[,1]
complex_input <- read.csv(file = 'complex_input_CellChat.csv', row.names = 1)
cofactor_input <- read.csv(file = 'cofactor_input_CellChat.csv', row.names = 1)
CellChatDB <- list()
CellChatDB$interaction <- interaction_input
CellChatDB$complex <- complex_input
CellChatDB$cofactor <- cofactor_input
CellChatDB$geneInfo <- geneIfo
CellChatDB.mouse <- CellChatDB`. Fourth (optional), you can re-build CellChat package by updating the database as follows `devtools::use_data(CellChatDB.mouse, overwrite = TRUE)`

**Comment by ruohuchengxhe** [comment]
> Hi @ruohuchengxhe , yes, you can add new L-R pairs. First, you need to save three files based on the information in CellChatDB, including 'interaction_input_CellChat.csv', 'complex_input_CellChat.csv', 'and cofactor_input_CellChat.csv'. Second, you can add your curated information in these files. Third, run the following codes `options(stringsAsFactors = FALSE) interaction_input <- read.csv(file = 'interaction_input_CellChat.csv') row.names(interaction_input) <- interaction_input[,1] complex_input <- read.csv(file = 'complex_input_CellChat.csv', row.names = 1) cofactor_input <- read.csv(file = 'cofactor_input_CellChat.csv', row.names = 1) CellChatDB <- list() CellChatDB$interaction <- interaction_input CellChatDB$complex <- complex_input CellChatDB$cofactor <- cofactor_input CellChatDB$geneInfo <- geneIfo CellChatDB.mouse <- CellChatDB`. Fourth (optional), you can re-build CellChat package by updating the database as follows `devtools::use_data(CellChatDB.mouse, overwrite = TRUE)`

Yes! Is there a good way to find the ligand, receptors, agonist, antagonist, subunits, cofactor, etc. from a certain pathway? Or is there a tool for that? Please bear with me that I haven't done this before. Finding from KEGG map and click on each gene box doesn't seem like the right approach. 
Besides, I suppose the rownames of complex_input should check with the receptor column in the interaction dataset, and the rownames of cofactor should be the same with either the co_A_receptor or co_I_receptor in the interaction dataset. Please add if there is any rule I should follow to keep the consistency of this dataset instead of messing it up.
Thank you in advance!

**Comment by sqjin** [comment]
Hi @ruohuchengxhe,  we indeed manually examine each signaling pathway and curate the detailed information for the L-R interaction. As you noted, we click each gene box to include all the members. Since we include all the factors contributed to the L-R interaction, our manual curation ensures the accuracy of the database.  Your understanding of the rule is totally correct. The core file is the interaction_input and then we use other files to provide detailed information of some complexes and co-factors.

**Comment by ruohuchengxhe** [comment]
> Hi @ruohuchengxhe, we indeed manually examine each signaling pathway and curate the detailed information for the L-R interaction. As you noted, we click each gene box to include all the members. Since we include all the factors contributed to the L-R interaction, our manual curation ensures the accuracy of the database. Your understanding of the rule is totally correct. The core file is the interaction_input and then we use other files to provide detailed information of some complexes and co-factors.

Hi, thanks for you kind reply! Looks like there's a lot to do for adding a pathway! Thanks for providing other pathways!
