### ISSUE TITLE
projectOnNetwork function cause integer overflow error when running on a large dataset

### ISSUE THREAD

**Issue by YukuanHuang** [sqjin/CellChat#205]
Hi, I used a large dataset and ran the program. However, there was a mistake when I used the command `cellchat <- projectData(cellchat, PPI.human)`. 
![image](https://user-images.githubusercontent.com/68011792/119217533-6ba6e200-bb0d-11eb-9a76-bf79d6723ecc.png)
It seems this mistake caused by too large my input data since my dim(gene_expression)[2] > 500000

Can you please help me troubleshoot this?
Thank you very much!

**Comment by sqjin** [comment]
@YukuanHuang I suggest to skip this step since it is not required if setting raw.use = TRUE in computeCommunProb.

**Comment by YukuanHuang** [comment]
@sqjin Thank you for your reply. I just replace `data_in_new_space = matrix(rep(0, length(new_features)*dim(gene_expression)[2]),nrow=length(new_features))` in function "projectOnNetwork" with `data_in_new_space <- sparseMatrix(dims=c(length(new_features),ncol=dim(gene_expression)[2]),i={},j={})
  data_in_new_space <- as(data_in_new_space,"dgCMatrix")` and use `Matrix::solve` in function "randomWalkBySolve". I did not saw the error again.
