### ISSUE TITLE
Is there a way to not consider autocrine signaling?

### ISSUE THREAD

**Issue by MarvinDo** [sqjin/CellChat#209]
Hello @sqjin 

first of all thank you very much for the awesome package!

I am currently working on a dataset where I am only interested in the signaling between two different cell types. As some of the visualizations are influenced by the autocrine interactions I would like to remove those from the cellchat object or maybe do not calculate them in the first place. Is there a way to do this?

I am very much looking forward to your answer.

**Comment by sqjin** [comment]
Hi @MarvinDo After the calculation, you can change the computed communication matrix object@net$prob.  Please try the following codes and let me know if it works. 
object@net$prob[1,1, ] <- 0
object@net$prob[2,2, ] <- 0

**Comment by MarvinDo** [comment]
Thank you very much!  Worked perfectly fine for me. I inserted your code snippet after the computeCommunProb() call.

Keep up the great work!
