### ISSUE TITLE
problem when generating graphs

### ISSUE THREAD

**Issue by yjlee0331** [sqjin/CellChat#21]
Hello, 

Thank you for developing this wonderful tool!

I have two questions - 

The first is, when I got the hierarchical plot to work, it worked beautifully. Then all of a sudden, despite the fact that I'm running the same code (after I've changed pathways.show to a different pathway), the graph looks like this and no longer plots the lines.

![image](https://user-images.githubusercontent.com/59858525/90078268-57a69800-dcd2-11ea-9388-0a695daa52da.png)

The second is, I'd like to specify the clusters used as vertex.receiver. 

I've tried vertex.receiver = c(0, 1, 3, 5, 6, 11). I've also tried vertex.receiver = as.integer(c(0, 1, 3, 5, 6, 11)), and specifying this in the code for netVisual_aggregate as well like this: netVisual_aggregate(cell, signaling = pathways.show,  vertex.receiver = c(0, 1, 3, 6, 11), vertex.size = groupSize)

However, I always get this error: 
Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent

The only way I do not get this error is if I follow the vignette exactly and say vertex.receiver = seq(1, 9).

How do I fix this? Thank you!

**Comment by sqjin** [comment]
@yjlee0331 I feel sorry you have such issues. However, there is no issue when I tested the two cases you mentioned. For example, I can specify the vector by `vertex.receiver = c(1,2,5,9,10,12)`. Can you re-install the package and restart the RStudio?

**Comment by yjlee0331** [comment]
@sqjin thank you so much for your response. The vertex.receiver works now (I didn't realize that cluster 0 actually should be "1"); however, I still have a problem with the graphs. Sometimes, if I reload the package, it works, but most of the time it doesn't work and I continue getting graphs like the one I showed above, even if I reinstall the package. The circle graph also looks like this: 

![image](https://user-images.githubusercontent.com/59858525/90211621-38396900-ddbf-11ea-9821-4eacfbb4b153.png)

**Comment by sqjin** [comment]
@yjlee0331 Not sure if this issue is due to the fact that the cluster index starts from 0. You might can re-name your cell clusters. If this still does not work, you can either share your CellChat object with me or ask your colleagues to test it.

**Comment by cswoboda** [comment]
Any updates on this by chance? Having the exact same problem. Attempting to supply the factored labels to the object to replace them to see if it helps at all, I'm wondering if its an issue that comes from creating a cellchat object directly from a seurat object.

**Comment by sqjin** [comment]
@cswoboda When assigning new cell labels, you should use the `addMeta` and `setIdent` functions. Please check the last section in the tutorial on the interface with other tools.

**Comment by cswoboda** [comment]
Thank you!
