### ISSUE TITLE
plotGeneExpression function error message

### ISSUE THREAD

**Issue by jojob123** [sqjin/CellChat#212]
Thanks for creating such an awesome tool!
When I run the command:  plotGeneExpression(cellchat, signaling = "CXCL", split.by = "datasets", colors.ggplot = T)

I get following error:
 *** caught segfault ***
address 0x14226, cause 'memory not mapped'

Traceback:
 1: dyn.load(file, DLLpath = DLLpath, ...)
 2: library.dynam(lib, package, package.lib)
 3: loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])
 4: asNamespace(ns)
 5: namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,     .libPaths()), versionCheck = vI[[j]]), i[[2L]], from = package)
 6: loadNamespace(name)
 7: getNamespace(ns)
 8: asNamespace(ns)
 9: getExportedValue(pkg, name)
10: Seurat::CreateSeuratObject
11: plotGeneExpression(cellchat, signaling = "CXCL", split.by = "datasets",     colors.ggplot = T)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace

The data I'm using was extracted from Seurat object. Not sure how to fix this.

**Comment by sqjin** [comment]
@jojob123 Can you run the source codes to dig into the error?  Based on the information you provided, I have no idea on the error.
