### ISSUE TITLE
Trouble importing data

### ISSUE THREAD

**Issue by VUbels** [sqjin/CellChat#213]
Hi, brilliant paper/tool. Thanks so much for this!

After reading through the publication I was immediately exciting to use the CellChat tool. However, as a complete R novice I've had some struggles with trying to recreate an acceptable dataset that can be used in CellChat. I went through the entire tutorial with the tutorial data without a problem but am currently a bit stuck. Prior to generating my own sc-RNA dataset I thought I'd try the tool out with a sc-RNA dataset from a different paper. This dataset consists of gene expression levels in ~20 different hair follicle compartments. I thought it would be possible to use this dataset to infer the latent pathways between these compartments by using the CellChat tool. But I have no idea how to set up the data such that it can be used in the CellChat tool. Would you perhaps mind having a look at the dataset and tell me how to alter it such that its CellChat compatible? Apologies for the insanely easy question. 

[TRD.xlsx](https://github.com/sqjin/CellChat/files/6577053/TRD.xlsx)

**Comment by sqjin** [comment]
@VUbels It seems that the data you shared is the average expression per cell population. CellChat requires a data matrix and cell group information.
