### ISSUE TITLE
subsetCommunication results

### ISSUE THREAD

**Issue by jv-20** [sqjin/CellChat#214]
Hi @sqjin 

Quick question. There seems to be discrepancy in number of interactions returned when running subsetCommunication and net$count

I receive two different numbers as shown below. These two numbers should be the same isn't it? Or am I missing something- would appreciate if you give some advice? 
```
df.net<- subsetCommunication(cellchat.obj)
nrow(df.net)
[1] 54853

sum(cellchat.obj@net$count)
[1] 51902
```

Also, how to interpret zero pvalues? Is it still significant?

Thank you

**Comment by sqjin** [comment]
@jv-20 Yes, they should be the same. Can you please look into this issue in detail? 

Pvalues with zeros are very significant.

**Comment by jv-20** [comment]
Hi @sqjin  the discrepancy seems to be filter on whether pval<=0.5 or pval<0.05

```
df.net<- subsetCommunication(cellchat.obj)
nrow(df.net)
[1] 54853

df.net1=subset(df.net,pval<0.05)
nrow(df.net1)
[1] 51902

Applying the filter in pvalue column returns the same number as returned from sum on cellchat.obj@net$count shown below

sum(cellchat.obj@net$count)
[1] 51902

```
It would be good to fix this for the adjacency matrix of (cellchat.obj@net$count) so we get the same number. 

Thank you again for this beautiful package and your prompt replies.

**Comment by sqjin** [comment]
@jv-20 Thanks! Will fix it.
