### ISSUE TITLE
Can I use 2 different dataset(seurat) for CellChat analysis?

### ISSUE THREAD

**Issue by dmsalsgh97** [sqjin/CellChat#215]
Hi, thanks for developing wonderful DB and many visualizations!

I want to know that merging 2 different sources of datasets(Seurat) and, use it as CellChat input is valid.

In my case, I have 2 datasets: A. is containing only immune cells ( mine ) , and B. is containing surroundings ( GEO )

I want to know that my immune cell types have any crosstalk on specific tissue conditions,
But unfortunately, my dataset A has a few surrounding celltypes...

If I can use public datasets together, it would be wonderful!
Thanks.

**Comment by sqjin** [comment]
@dmsalsgh97 Yes, you can merged two datasets together and use a single data matrix as an input of CELLCHAT

**Comment by dmsalsgh97** [comment]
Thanks! I'll try this

**Comment by ParGol544** [comment]
Hi,
Thanks a lot for developing such a wonderful package.
Can I merge two CellChat databases with the same cell population but with different cell number? Is it important the number of cells in each database (e.g I have two Seurat objects one with 3000 cells and another one with 4000 cells with the same cell population)?

**Comment by sqjin** [comment]
@ParGol544  it is ok, you can merge it.

**Comment by ParGol544** [comment]
Thanks for your reply. Does it affect on the number of interactions when I compare two databases with different cell number?

**Comment by sqjin** [comment]
@ParGol544 No, our method is based on cell group, independent on the cell number.
