### ISSUE TITLE
Allocating labels to cell groups of SEURAT objects.

### ISSUE THREAD

**Issue by VUbels** [sqjin/CellChat#216]
Hi!

Once again asking for help in a (hopefully) tiny matter this time. After a bit of an idiotic question previously I managed to basically get the entire CellChat script working! The only problem I had is that due to importing a SEURAT object, and using label-free mode, I'm currently seeing all my results in groups (1-10) as expected. However, I'd now like to name each group according to their most differentially expressed genes which is the following list:

list('KRT15-CXCL14', 'KRT1-KRTDAP', 'KRT16-S100A2', 'KRT31', 'MLANA-CD74', 'SPRR1A-CST6', 'NUSAP1-STMN1', 'KRT27-TCHH', 'DCD', 'ANGPTL7-SELENOP', 'SPARC-PPIAP19').

Would you be so kind to explain how I should go about to match each group with each string in the list? Again, major thanks for all the help and the amazing tool. So far having a lot of fun with it.

Kind regards.

**Comment by sqjin** [comment]
@VUbels I suggest you to name a cell group in Seurat object before running CellChat. If you really want to do it in CellChat, you can check `addMeta` and `setIdent` functions. But you need to re-run all the functions and analysis after the function `computeCommunProb`.
