### ISSUE TITLE
Customize Bubble Plot

### ISSUE THREAD

**Issue by MariaRosariaNucera** [sqjin/CellChat#217]
Hello,
let's say I have 5 cell groups, but I want a bubble plot with the interaction of only some precise couples of them, for example 
group1->group1, group2->group3, group4->group5. Is there a way to have all of them in the same plot?
I am able to get one of them using:
netVisual_bubble(cellchat, sources.use = 1, targets.use = 1)
But if I try selecting more like this:
netVisual_bubble(cellchat, sources.use = c(1,2,4), targets.use = c(1,3,5))
I also obtain unwanted couples like group1->group5
How can I solve this problem?
Alternatively, how can I access the matrix used to plot the bubble plot, so I can use it to make my own plots?

**Comment by sqjin** [comment]
Hi @MariaRosariaNucera You can try another version of this function, which defines the corresponding sources and targets by `from` and `to`. Please see below. If you want to use the current version, one way you can try is as follows. 
1) Use `subsetCommunication` to find the related L-R pairs. 
    df.net <- subsetCommunication(object, slot.name = "net",
                                  sources.use = sources.use, targets.use = targets.use,
                                  thresh = thresh)

2) Subset the L-R pairs in `df.net `

3) Run `netVisual_bubble(cellchat,  pairLR.use = df.net.subset)`

If you set `return.data = TRUE`, you can return the data frame for re-plotting.

**Comment by MariaRosariaNucera** [comment]
Thank you for you answer! I tried the your 3 steps:
in step2 I created df.net.subset keeping only the rows of df.net with my couples of groups of interest,
but then in step3 I got a dimension error
 Error in `$<-.data.frame`(`*tmp*`, "interaction_name_2", value = character(0)) : 
  replacement has 0 rows, data has 32 ,
so I had to do netVisual_bubble(cellchat, pairLR.use = df.net.subset['interaction:name']) but in this way I can only select the ligand-receptor pairs present in the couples of groups that I am interested in, but if a L-R pair is also present in the couples I don't care about, these couples still appear in the plot.

Where can I get the new function?I tried updating or uninstalling and reinstalling CellChat but if I use from and to I get this error:
Error in netVisual_bubble(cellchat, from = c(1, 2), to = (3)) : 
  unused arguments (from = c(1, 2), to = (3))

**Comment by sqjin** [comment]
@MariaRosariaNucera Sorry, I suppose to attach the codes. But it is too long. Anyway, here is the [code](https://www.dropbox.com/s/h8w9z9njtu87afv/netVisual_bubble_old?dl=0)

**Comment by MariaRosariaNucera** [comment]
Thanks you @sqjin

**Comment by jiangsiao** [comment]
Hello, I  have a similar question.
I want to specify the sending cell type and the receiving cell type like group1 -> group2,3; group2 -> group4,5. Is there a way to have all of them in the same plot? 
I tried it with the above method and the following error was shown:
`netVisual_bubble(cellchat, from = 1,to = c(6,7), bidirection = FALSE, pairLR.use = pairLR.use, comparison = c(1, 2), group = NULL, remove.empty = FALSE)`

> Comparing communications on a merged object

> Error in netVisual_bubble(cellchat, from = 1, to = c(6, 7), bidirection = FALSE,  :

  The length of 'from' and 'to' must be the same!

But there has a error when I change the length of 'from' and 'to':
`netVisual_bubble(cellchat, from = c(1,2),to = c(6,7), bidirection = FALSE, pairLR.use = pairLR.use, comparison = c(1, 2), group = NULL, remove.empty = FALSE)`

> Comparing communications on a merged object

> Error in seq.default(1.5, length(unique(df$Var1)) - 0.5, 1) :

  wrong sign in 'by' argument

I think this is a type of problem, but no good solution has been found. Please help me~~

**Comment by SSSJe** [comment]
@sqjin

**Comment by yingyonghui** [comment]
> Hello, let's say I have 5 cell groups, but I want a bubble plot with the interaction of only some precise couples of them, for example group1->group1, group2->group3, group4->group5. Is there a way to have all of them in the same plot? I am able to get one of them using: netVisual_bubble(cellchat, sources.use = 1, targets.use = 1) But if I try selecting more like this: netVisual_bubble(cellchat, sources.use = c(1,2,4), targets.use = c(1,3,5)) I also obtain unwanted couples like group1->group5 How can I solve this problem? Alternatively, how can I access the matrix used to plot the bubble plot, so I can use it to make my own plots?

Hi all,
I've just encountered the same error.
Is there any updating on this problem?
Any suggestions would be appreciated!
Thx!

@sqjin @MariaRosariaNucera

**Comment by sqjin** [comment]
@SSSJe The current version does not have the arguments "from" and "to".  Indeed, `netVisual_bubble` does not allow you to do in this way. One solution you can try is to modify the dataframe for generating the bubble plot in the codes.

**Comment by SSSJe** [comment]
> 

@sqjin Fine. I will try it. Thx.
