### ISSUE TITLE
subscript out of bounds error in computeCommunProbPathway(cellchat)

### ISSUE THREAD

**Issue by franciscogrisanti** [sqjin/CellChat#22]
Hi @sqjin! Hope you're doing good. I'm having an issue and I was hoping you can help me

While running 

`cellchat <- computeCommunProbPathway(cellchat)`

I get this error!

```
Error in prob.pathways[, , pathways.sig]: subscript out of bounds
Traceback:

1. computeCommunProbPathway(cellchat)

```

Do you know what could it be?

Here is the complete code

```
data.input <- GetAssayData(LAPV.integrated, assay = "integrated", slot = "data") # normalized data matrix
Idents(object = LAPV.integrated) <- 'Named'
labels <- Idents(LAPV.integrated)
identity <- data.frame(group = labels, row.names = names(labels)) # create a dataframe of the cell labels
cellchat <- createCellChat(data = data.input)
cellchat <- addMeta(cellchat, meta = identity, meta.name = "labels")
cellchat <- setIdent(cellchat, ident.use = "labels") # set "labels" as default cell identity
CellChatDB <- CellChatDB.mouse # use CellChatDB.human if running on human data
CellChatDB.use <- subsetDB(CellChatDB, search = "Secreted Signaling")
cellchat@DB <- CellChatDB.use # set the used database in the object
cellchat <- subsetData(cellchat) # subset the expression data of signaling genes for saving computation cost
future::plan("multiprocess", workers = 8) # do parallel
cellchat <- identifyOverExpressedGenes(cellchat)
cellchat <- identifyOverExpressedInteractions(cellchat)
cellchat <- projectData(cellchat, PPI.mouse)
groupSize <- as.numeric(table(cellchat@idents))
cellchat <- computeCommunProb(cellchat)
cellchat <- computeCommunProbPathway(cellchat)
```

**Comment by sqjin** [comment]
Hi @franciscogrisanti, your data.input contains negative values, which is not suitable as input of CellChat. CellChat requires the normalized data.  `data.input <- GetAssayData(LAPV.integrated, assay = "RNA", slot = "data")`

**Comment by franciscogrisanti** [comment]
Thanks for the reply! It's working now. 💯

**Comment by caiquanyou** [comment]
Hi @sqjin!  I'm having the same issue and don't know what todo,hoping you can help me
I running the code below:
data.input <- GetAssayData(scdata, assay = "RNA", slot = "data")
identity = data.frame(group =scdata@meta.data$Predicted_labels,
                      row.names = names(scdata@meta.data$Predicted_labels))
unique(identity$group)
cellchat <- createCellChat(data = data.input)
# add meta data
cellchat <- addMeta(cellchat, meta = identity, meta.name = "labels")
cellchat <- setIdent(cellchat, ident.use = "labels")
identity
levels(cellchat@idents) # show factor levels of the cell labels
groupSize <- as.numeric(table(cellchat@idents)) # number of cells in each cell group
CellChatDB <- CellChatDB.mnouse
CellChatDB.use <- subsetDB(CellChatDB, search = "Secreted Signaling") # use Secreted Signaling for cell-cell communication analysis
cellchat@DB <- CellChatDB.use # set the used database in the object
cellchat <- subsetData(cellchat)
future::plan("multiprocess", workers = 4)
cellchat <- identifyOverExpressedGenes(cellchat)
cellchat <- identifyOverExpressedInteractions(cellchat)
cellchat <- projectData(cellchat, PPI.mouse)
# Compute the communication probability and infer cellular communication network
cellchat <- computeCommunProb(cellchat)

And get the error :
Error in data.use[RsubunitsV, ]: subscript out of bounds

**Comment by weihuaguo** [comment]
Hi @sqjin I have the same question as @caiquanyou mentioned. Could you help us with this? Thanks!

**Comment by sqjin** [comment]
@weihuaguo Can you please make sure you have correctly done the following?  (1) Use the correct CellChatDB: either 'CellChatDB <- CellChatDB.mouse' or 'CellChatDB <- CellChatDB.human'; (2) Have the correct cell group information by checking 'unique(cellchat@idents)'; (3) Have the correct data matrix for cell-cell communication analysis: please check `cellchat@data` and 'cellchat@data.signaling'

**Comment by geosen** [comment]
Hi @sqjin ! Thank you for this tool! Seems excellent. 

I'm also having a subscript out of bounds error. Let me describe the situation below. My samples are Human Bulk RNA-Seq from isolated populations of HSCs (15 samples) and MSCs (7 samples). My gene identifiers are ENSEMBL gene ids with no version number.

library(CellChat)
library(patchwork)
library(edgeR)
options(stringsAsFactors = FALSE)
setwd("~/Desktop/MariaProject/Interactome Analysis/HSCs-MSCs/CellChat/")
#read expression data
exprData <- read.table('~/Desktop/MariaProject/Interactome Analysis/HSCs-MSCs/expr_data_MariaProject.txt', header=TRUE, row.names = 1)
#normalize
exprDataN <- log2(cpm(exprData) + 1)

#read sample metadata
metadata <- read.table('~/Desktop/MariaProject/Interactome Analysis/HSCs-MSCs/metafile_MariaProject.txt', header = TRUE)
cellChat1 <- createCellChat(object = exprDataN, meta = metadata, group.by = "CellType")
cellChat1 <- setIdent(cellChat1, ident.use = "CellType") # set "labels" as default cell identity
levels(cellChat1@idents) # show factor levels of the cell labels
CellChatDB <- CellChatDB.human 
# use all CellChatDB for cell-cell communication analysis
CellChatDB.use <- CellChatDB # simply use the default CellChatDB
# set the used database in the object
cellChat1@DB <- CellChatDB.use
# subset the expression data of signaling genes for saving computation cost
cellChat1 <- subsetData(cellChat1, features = CellChatDB.human$geneInfo$Ensembl.Gene.ID) # end up with 36845 x22 matrix from an initial 58767 x 22 matrix
#cellChat1 <- subsetData(cellChat1) # !!!!! when using this command cellChat1@data.signaling ends up blank. Using Ensembl IDs (see above) fixed this.
#check subset results
cellChat1@data.signaling
dim(cellChat1@data.signaling)

#do parallel
future::plan("multiprocess", workers = 4) #normal warning will pop-up probably
cellChat1 <- identifyOverExpressedGenes(cellChat1)
cellChat1 <- identifyOverExpressedInteractions(cellChat1)
cellChat1 <- projectData(cellChat1, PPI.human)
cellChat1 <- computeCommunProb(cellChat1, raw.use = TRUE)

The result is:

>cellChat1 <- computeCommunProb(cellChat1, raw.use = TRUE)
Error in data.use[RsubunitsV, ] : subscript out of bounds



Any suggestions? I will continue to troubleshoot this and return here if I find a solution.

Thank you in advance for your time!

**Comment by sqjin** [comment]
@geosen Hi, you should convert ensembl gene id to official gene name before running CellChat.

**Comment by geosen** [comment]
@sqjin Thank you so much for taking the time to answer me! That was the issue!

**Comment by hejincan** [comment]
> @sqjin Thank you so much for taking the time to answer me! That was the issue!

@geosen  Hi, I get the same error while analyzing bulk RNA-seq. And my gene identifiers are gene symbols.  Could you please tell me How you fixed this error in more detail?

**Comment by sqjin** [comment]
@1221li You should change your cell labels, which cannot be `0`. It should be at least starting from 1, e..g., 1,2,3,..

**Comment by 1221li** [comment]
Thank you very much for answering my question. I seem to have solved this problem. I have increased the number of seurat_clusters and there is no longer this mistake.However, at the step of NetAnalysis_ComputeCentrality, we have the following error
> future::plan("multiprocess", workers = 4) 
> cellchat <- identifyOverExpressedGenes(cellchat)
> cellchat <- identifyOverExpressedInteractions(cellchat)
> cellchat <- projectData(cellchat, PPI.human)
> cellchat <- computeCommunProb(cellchat)

> 
> cellchat < -  filterCommunication（cellchat，min.cells =  10）
Error: unexpected input in "cellchat < -  filterCommunication（"
> cellchat <-filterCommunication(cellchat，min.cells =  10)
Error: unexpected input in "cellchat <-filterCommunication(cellchat，"
> cellchat <-filterCommunication(cellchat,min.cells =  10)
> cellchat <- computeCommunProbPathway(cellchat)
> cellchat <- aggregateNet(cellchat)
> cellchat <- netAnalysis_computeCentrality(cellchat, slot.name = "netP")
Fortran runtime error: Insufficient number of elements in TARRAY.
Fortran runtime error: Insufficient number of elements in TARRAY.
Fortran runtime error: Insufficient number of elements in TARRAY.
Error: Failed to retrieve the result of MulticoreFuture (future_sapply-1) from the forked worker (on localhost; PID 42646). Post-mortem diagnostic: No process exists with this PID, i.e. the forked localhost worker is no longer alive.
In addition: Warning message:
In mccollect(jobs = jobs, wait = TRUE) :
  1 parallel job did not deliver a result
> Fortran runtime error: Insufficient number of elements in TARRAY.


I don't know what caused this mistake, could you please help me solve it?

**Comment by sqjin** [comment]
@1221li I have no idea on this. Can you run the source codes of this function to figure out the reason?

**Comment by Josephinedh** [comment]
@1221li Did you figure out the problem with NetAnalysis_ComputeCentrality? I'm experiencing the same issue now.

**Comment by libingnan11** [comment]
@1221li Did you figure out the problem with NetAnalysis_ComputeCentrality? I'm experiencing the same issue now.

**Comment by sqjin** [comment]
@libingnan11 (1) Run the source codes by yourself and check the reason (2) if you can share your object and I can run the source code.

**Comment by jiey1996** [comment]
Hi   @sqjin ! Hope you're doing good. I'm having an issue and I was hoping you can help me. After running the netAnalysis_computeCentrality function, it turns off R directly and displays Fortran runtime error: Insufficient number of elements in TARRAY.
What is the reason for this?

**Comment by dyinboisry4u** [comment]
On my case, `Fortran runtime error: Insufficient number of elements in TARRAY.` seems cause by `igraph`. When `netAnalysis_computeCentrality()` call `igraph`, the R session crash immediately. Downgrade my R version 4.2.2 to 4.0.3 could fix this problem.

**Comment by 1989ANSS** [comment]
Hi Sqjin, I have a similar error, could you kindly help?

My cellchat@data has been standardized and no negative number exists. The gene name is the official gene name.
for example:

Xkr4    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
Gm1992  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
Gm37381 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
Rp1     . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
Sox17   . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
Gm37323 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
              
Xkr4    ......
Gm1992  ......
Gm37381 ......
Rp1     ......
Sox17   ......
Gm37323 ......

cellchat <- computeCommunProbPathway(cellchat)
Error in prob.pathways[, , pathways.sig, drop = FALSE] : 
  subscript out of bounds
> traceback()
1: computeCommunProbPathway(cellchat)

**Comment by sqjin** [comment]
@1989ANSS Can you show your `unique(cellchat@idents)`?

**Comment by 1989ANSS** [comment]
Thank you for responding

unique(cellchat@idents)
 [1] T_Cells     Neutrophils NK_Cells    Macrophages DCs         B_Cells     Fibroblast  Cancer      Basophils  
[10] MCs         Endo_Cells 
Levels: B_Cells Basophils Cancer DCs Endo_Cells Fibroblast Macrophages MCs Neutrophils NK_Cells T_Cells

**Comment by sqjin** [comment]
@1989ANSS It looks good. Could you share your cellchat object so that I can replicate your error.  If your file is too big, you can set `cellchat@data = cellchat@data[1:2, ]` as I only need the `cellchat@data.signaling`

**Comment by 1989ANSS** [comment]
Dear Professor Suoqin  Jin

Please Attached cellchat object file,

Kindest Regards

Arnaldo

**Comment by koelschnj** [comment]
Hi @sqjin, thank you for making this great tool! I have also been experiencing issues related to this, but only arises when I try to run computeCommunProbPathway() on analyses that I have ran computeCommunProb() with a truncatedMean option (error on both 5 and 10% thresholds so far). However, when I run computeCommunProb() with default settings, everything works perfectly fine.

This is all of the code and the resultant error message:

```
library(Seurat)
library(CellChat)
library(future)
library(patchwork)
options(stringsAsFactors = FALSE)

HCCp1.cells <- readRDS(file = "~/HCCp1.cells.sorted.new.labels.RDS")

Idents(HCCp1.cells) <- HCCp1.cells@meta.data$group
table(HCCp1.cells@meta.data$group)

new.group.levels <- c("CD", "PreT", "MWD.T", "MRD.T", "MRD.NT")
HCCp1.cells@meta.data$group <- factor(x = HCCp1.cells@meta.data$group, levels = new.group.levels)
table(HCCp1.cells@meta.data$group)

new.cell.type.levels <- c("Bcell", "Tcell", "DC", "NKT", "NK", "Neutrophil", "Monocyte", "Macrophage", "Endothelial", "LSEC", "Stromal", "HSC", "Fibroblast", "Myofibroblast", "Cholangiocyte",  "Hepatocyte", "Cancer")

CD.cells <- subset(HCCp1.cells, idents = "CD", invert = FALSE)
table(CD.cells@meta.data$group)
CD.cells@meta.data$Cell.Type <- factor(x = CD.cells@meta.data$Cell.Type, levels = new.cell.type.levels)
table(CD.cells@meta.data$Cell.Type)
Idents(CD.cells) <- CD.cells@meta.data$Cell.Type

cellchat.CD <- createCellChat(object = CD.cells, group.by = "Cell.Type", assay = "RNA")

CellChatDB <- CellChatDB.mouse
showDatabaseCategory(CellChatDB)

dplyr::glimpse(CellChatDB$interaction)

CellChatDB.use <- subsetDB(CellChatDB, search = c("Secreted Signaling", "Cell-Cell Adhesion", "ECM-Receptor", "Non-protein Signaling"))

cellchat.CD@DB <- CellChatDB.use

cellchat.CD <- subsetData(cellchat.CD)
future::plan("multisession", workers = 2)

cellchat.CD <- identifyOverExpressedGenes(cellchat.CD)
cellchat.CD <- identifyOverExpressedInteractions(cellchat.CD)

unique(cellchat.CD@idents)

cellchat.CD@idents = droplevels(cellchat.CD@idents, exclude = setdiff(levels(cellchat.CD@idents),unique(cellchat.CD@idents)))

##cellchat.CD <- computeCommunProb(cellchat.CD)
cellchat.CD <- computeCommunProb(cellchat.CD, type = "truncatedMean", trim = 0.05)

cellchat.CD <- filterCommunication(cellchat.CD, min.cells = 2)

cellchat.CD <- computeCommunProbPathway(cellchat.CD)

Error in prob.pathways[, , pathways.sig, drop = FALSE] : 
  subscript out of bounds

```
I have checked that I have used normalized data, and I have used two different sets of cell type labels, but the error keeps occurring only when I add the "truncatedMean" argument to look at more lowly expressed interactions.  I would greatly appreciate any insight you may be able to offer, and I could send you my cellchat object file if needed.
