### ISSUE TITLE
How to keep only some interaction in cellchat object

### ISSUE THREAD

**Issue by MariaRosariaNucera** [sqjin/CellChat#221]
Hi @sqjin
I am working on a dataset with 16 clusters.
I only care about the following interactions pairs:
1-1, 2-3, 3-2, 4-4
5-5, 6-7, 7-6, 8-8
9-9, 10-11, 11-10, 12-12
13-13, 14-15, 15-14, 16-16
how to I delete the other couples of interactions from the cellchat object? Can I totally avoid to calculate them from the beginning?
I am very much looking forward to your answer.

**Comment by MariaRosariaNucera** [comment]
Now I am doing like this:
cellchat@net$prob[1,2, ] <- 0
cellchat@net$prob[1,3, ] <- 0
cellchat@net$prob[1,4, ] <- 0
cellchat@net$prob[1,5, ] <- 0
cellchat@net$prob[1,6, ] <- 0
cellchat@net$prob[1,7, ] <- 0
cellchat@net$prob[1,8, ] <- 0
cellchat@net$prob[1,9, ] <- 0
cellchat@net$prob[1,10, ] <- 0
cellchat@net$prob[1,11, ] <- 0
cellchat@net$prob[1,12, ] <- 0
cellchat@net$prob[1,13, ] <- 0
cellchat@net$prob[1,14, ] <- 0
cellchat@net$prob[1,15, ] <- 0
cellchat@net$prob[1,16, ] <- 0
cellchat@net$prob[2,1, ] <- 0
cellchat@net$prob[2,2, ] <- 0
cellchat@net$prob[2,4, ] <- 0
cellchat@net$prob[2,5, ] <- 0
cellchat@net$prob[2,6, ] <- 0
cellchat@net$prob[2,7, ] <- 0
cellchat@net$prob[2,8, ] <- 0
cellchat@net$prob[2,9, ] <- 0
cellchat@net$prob[2,10, ] <- 0
cellchat@net$prob[2,11, ] <- 0
cellchat@net$prob[2,12, ] <- 0
cellchat@net$prob[2,13, ] <- 0
cellchat@net$prob[2,14, ] <- 0
cellchat@net$prob[2,15, ] <- 0
cellchat@net$prob[2,16, ] <- 0
cellchat@net$prob[3,1, ] <- 0
cellchat@net$prob[3,3, ] <- 0
cellchat@net$prob[3,4, ] <- 0
cellchat@net$prob[3,5, ] <- 0
cellchat@net$prob[3,6, ] <- 0
cellchat@net$prob[3,7, ] <- 0
cellchat@net$prob[3,8, ] <- 0
cellchat@net$prob[3,9, ] <- 0
cellchat@net$prob[3,10, ] <- 0
cellchat@net$prob[3,11, ] <- 0
cellchat@net$prob[3,12, ] <- 0
cellchat@net$prob[3,13, ] <- 0
cellchat@net$prob[3,14, ] <- 0
cellchat@net$prob[3,15, ] <- 0
cellchat@net$prob[3,16, ] <- 0
cellchat@net$prob[4,1, ] <- 0
cellchat@net$prob[4,2, ] <- 0
cellchat@net$prob[4,3, ] <- 0
cellchat@net$prob[4,5, ] <- 0
cellchat@net$prob[4,6, ] <- 0
cellchat@net$prob[4,7, ] <- 0
cellchat@net$prob[4,8, ] <- 0
cellchat@net$prob[4,9, ] <- 0
cellchat@net$prob[4,10, ] <- 0
cellchat@net$prob[4,11, ] <- 0
cellchat@net$prob[4,12, ] <- 0
cellchat@net$prob[4,13, ] <- 0
cellchat@net$prob[4,14, ] <- 0
cellchat@net$prob[4,15, ] <- 0
cellchat@net$prob[4,16, ] <- 0 and so on 
But I am sure there is a better way to do so.............

**Comment by sqjin** [comment]
@MariaRosariaNucera Generally, you can do it by using the `subsetCellChat` function or defining the `sources.use` and 'targets.use' parameter in some related functions. However, your case looks complicated, which seems impossible to write a general codes.  For you case, instead of setting other elements to be zero, you can only assign values to the pairs you selected because you have very few number of pairs to be used.
