### ISSUE TITLE
Question in comparing two dataset

### ISSUE THREAD

**Issue by phoebee-h** [sqjin/CellChat#222]
Hi,

I saw your tutorial for merging two datasets (object1 and object2), but I got three questions not quite specified in the documents.

(1) Can I apply `netVisual_individual` after merging two cellchat objects together? I would like to see whether the certain L-R pair distinguished among merging datasets.

(2) The `liftCellChat` solves the problem in different composition when combining two data. However, some of the plotting functions seem to use `object.list[[i]]` instead, meaning the object1 and object2 were merely stored in the list? In this case, can I just specify the idents (by factorizing) to make both object1 and object2 stay with the same levels? When I look at my results, it shows no differences, but don't know whether I might take the consequences.

Some like this:
```
cellchat.E13@idents <-  factor(as.vector(cellchat.E13@idents), levels = c("FIB-A", "FIB-B", "FIB-P", "DC", "Pericyte", "MYL", "Immune", "ENDO", "Muscle", "MELA", "Basal-P", "Basal", "Spinious"))
cellchat.E14@idents <-  factor(as.vector(cellchat.E14@idents), levels = c("FIB-A", "FIB-B", "FIB-P", "DC", "Pericyte", "MYL", "Immune", "ENDO", "Muscle", "MELA", "Basal-P", "Basal", "Spinious"))
object.list <- list(E13= cellchat.E13, E14 = cellchat.E14)
cellchat <- mergeCellChat(object.list, add.names = names(object.list))
```

(3) How do I reorder the dot in `netVisual_aggregate` when parameter set to `layout = "circle"`, or` layout = "hierarchy"`? The parameter `cell.order` only works in chord plot, but failed in these two layout. (I would like to order cell clusters sequentially by number.)
![image](https://user-images.githubusercontent.com/28743573/122181087-9ccfc380-cebb-11eb-8744-2590e75dee2b.png)

Thank you for your great work.
Phoebe

**Comment by sqjin** [comment]
@phoebee-h 
(1) it should work, as you can see in our tutorial
pathways.show <- c("WNT") 
weight.max <- getMaxWeight(object.list, slot.name = c("netP"), attribute = pathways.show) # control the edge weights across different datasets
par(mfrow = c(1,2), xpd=TRUE)
for (i in 1:length(object.list)) {
  netVisual_aggregate(object.list[[i]], signaling = pathways.show, layout = "circle", edge.weight.max = weight.max[1], edge.width.max = 10, signaling.name = paste(pathways.show, names(object.list)[i]))
}

(2) You cannot manually lift up the factor levels. you should do it using `liftCellChat`. 

(3) You can re-order all the cell groups without recomputing communication probability by using 'setIdent' or `updateClusterLabels` by defining the `new.order` parameter. The latter one will be likely added this weekend.

**Comment by phoebee-h** [comment]
Hi, 
Thank you for your quick response! 

I think my first question you've already demonstrated in single object condition (visualize cell-cell communication mediated by a single ligand-receptor pair), but I'm confused by this: 
Apart from structural/ functional analysis, does it make any differences in plotting chord diagram (shared same cell population compositions)? For example, in these chord plots: (A) object1 (B) object2 (C) `mergeCellChat `(object1 and object2), will (A) and (B) plots unlike in (C)?
If no differences, then I have no problem.


Thanks again, especially for my third question. 
Phoebe.

**Comment by sqjin** [comment]
@phoebee-h No difference. They represent the same network.

**Comment by phoebee-h** [comment]
OK, got it. Thanks a lot.
