### ISSUE TITLE
How to transfer metadata group from v3Seurat object to CellChat and how to use it properly?

### ISSUE THREAD

**Issue by BatLaB-cell** [sqjin/CellChat#223]
Hello, 
Using your nice tutorial, I successfully created a CellChat object from my previous v3 Seurat object named "allbiopsies.integrated" using the following codes:

DefaultAssay(allbiopsies.integrated) <- 'RNA'

#Extract the CellChat input files from a Seurat object
#The normalized count data and cell group information can be obtained from the Seurat object by

data.input <- GetAssayData(allbiopsies.integrated, assay = "RNA", slot = "data") # normalized data matrix
labels <- Idents(allbiopsies.integrated)
meta <- data.frame(group = labels, row.names = names(labels)) # create a dataframe of the cell labels
cellchat <- createCellChat(object = data.input, meta = meta, group.by = "group")

CellChatDB <- CellChatDB.human # use CellChatDB.mouse if running on mouse data
showDatabaseCategory(CellChatDB)
dplyr::glimpse(CellChatDB$interaction)

# use a subset of CellChatDB for cell-cell communication analysis
CellChatDB.use <- subsetDB(CellChatDB, search = "Secreted Signaling") # use Secreted Signaling
# use all CellChatDB for cell-cell communication analysis
# CellChatDB.use <- CellChatDB # simply use the default CellChatDB

# set the used database in the object
cellchat@DB <- CellChatDB.use

# subset the expression data of signaling genes for saving computation cost
cellchat <- subsetData(cellchat) # This step is necessary even if using the whole database

cellchat <- identifyOverExpressedGenes(cellchat)

cellchat <- identifyOverExpressedInteractions(cellchat)
# project gene expression data onto PPI network (optional)
cellchat <- projectData(cellchat, PPI.human)
cellchat <- computeCommunProb(cellchat)

saveRDS(cellchat, file = "cellchat_16.06.21.rds")

I am just concerned because in the metadata of my Seurat object which consists in merged seurat objects from different patients , I added a patient group. I can't find it anymore in the cellChat object (or I don't know where is it).

How to be sure that this information is present in the CellChat object? And how can I use it afterward for CellChat comparisons?

Thank you very much!

**Comment by sqjin** [comment]
@BatLaB-cell When performing comparison analysis, you should run cellchat for each condition/dataset individually, and then use the mergeCellChat fucntion to perform the comparison analysis. 

If your inout meta have multiple columns, you will see all information in cellchat object
