### ISSUE TITLE
netAnalysis_signalingChanges_scatter

### ISSUE THREAD

**Issue by ParGol544** [sqjin/CellChat#224]
Thank you for developing such a wonderful package.
what does negative value mean in netAnalysis_signalingChanges_scatter?

**Comment by sqjin** [comment]
@ParGol544 Positive values mean increased signaling in the second condition, and negative values mane increased signaling in the first condition

**Comment by sqjin** [comment]
@ParGol544 'bonferroni' is used for correcting p-values. It is ok to decrease logfc.threshold to 0.2 or 0.1

**Comment by ParGol544** [comment]
Thank you very much for your useful information.

**Comment by ParGol544** [comment]
Hello,
Thank you for developing such a wonderful package.

I have a question concerning the FindAllMarkers function in Seurat.
I used logfc.threshold = 0.2 when I wanted to detect protein-coding genes, and I used logfc.threshold = 0.1 to find low-expressed genes (long non-coding RNA).
Now the reviewer is telling me that both 0.2 and 0.1 are very low. You need to use at least logfc.threshold = 1. I think he is comparing scRNA-seq with bulk RNA. How can I convince her/him? Do you have any arguments for using 0.25? Why are we using such a low fold change in FindAllMarkers?
Best
Parisa
