### ISSUE TITLE
liftCellChat issue

### ISSUE THREAD

**Issue by ylxing001** [sqjin/CellChat#225]
Hi, 
I get the following error after using liftCellChat function:

> levels(db1_cellchat@idents)
[1] "0" "1" "2" "3"
> levels(db2_cellchat@idents)
[1] "0" "1" "2"
> levels(db3_cellchat@idents)
[1] "0" "1" "2"
> group.new = levels(db1_cellchat@idents)
> db2_cellchat <- liftCellChat(db2_cellchat, group.new)
The CellChat object will be lifted up using the cell labels 0, 1, 2, 3
Update slots object@net, object@netP, object@idents in a single dataset... 
> levels(db2_cellchat@idents)
[1] "0" "1" "2" "3"
> db3_cellchat <- liftCellChat(db3_cellchat, group.new)
The CellChat object will be lifted up using the cell labels 0, 1, 2, 3
Update slots object@net, object@netP, object@idents in a single dataset... 
**Error in dimnames(values)[[3]] : subscript out of bounds**

How to fix this?
Thank you

**Comment by sqjin** [comment]
@ylxing001 The cell identify can not start from "0". You should assign a new label.

**Comment by ylxing001** [comment]
@sqjin Thank you Suoqin. It worked. Now I've encountered another problem: 
> object.list <- list(db1 = db1_cellchat, db2 = db2_cellchat, db3=db3_cellchat)
> merged.cellchat <- mergeCellChat(object.list, add.names = names(object.list), cell.prefix=TRUE)
Error in match.names(clabs, names(xi)) : 
  names do not match previous names

Thanks!

**Comment by ylxing001** [comment]
I checked that I've got different column names in object.list$db@meta between datasets, so I changed their names and it worked! Thank you!
