### ISSUE TITLE
How to map the total cellular interaction network?

### ISSUE THREAD

**Issue by Rui-Jing** [sqjin/CellChat#23]
Hi,
Thanks for developing this user-friendly tool. I have a problem about mapping total cellular interaction network. （This is a representation of the entire data set rather than a single pathway）Just like the following picture shown:(url
![image](https://user-images.githubusercontent.com/59251760/90304847-784b3980-deee-11ea-90fc-e1922fcbc9df.png)
)
Different circles represent different cell types. The size of the cell circle represents more cellular interaction.(It means that certain cells are involved in more cellular communication )   The thickness of the lines is positively correlated with the number of ligand-receptor interaction events.

I sincerely hope to get your kind reply.

ps:感谢您今天在哔哩哔哩直播中的分享，因为实验错过了前面部分，很遗憾。希望金老师以后还能继续开课。期待！

**Comment by sqjin** [comment]
Hi @Rui-Jing , thanks! Hope our tool will be helpful for your research. Is your question the same as your previous one [#8](https://github.com/sqjin/CellChat/issues/8)
