### ISSUE TITLE
Error in netAnalysis_computeCentrality

### ISSUE THREAD

**Issue by bharatm26** [sqjin/CellChat#231]
Hi,
I am getting errors while computing and visualize the network centrality scores on in-house data. 

Code:
```{r}
# Compute the network centrality scores
cellchat <- netAnalysis_computeCentrality(cellchat, slot.name = "netP")#, net = net, net.name = NULL) # the slot 'netP' means the inferred intercellular communication network of signaling pathways
# Visualize the computed centrality scores using heatmap, allowing ready identification of major signaling roles of cell groups
netAnalysis_signalingRole_network(cellchat, signaling = pathways.show, width = 8, height = 2.5, font.size = 10)
```
The error is:
Error in igraph::betweenness(G) : At centrality.c:1604 : Weight vector must be positive, Invalid value

Please help me fix the issue.

Thanks

**Comment by sqjin** [comment]
@bharatm26 I guess this error happens because there are negative values in your input data. Please check cellchat@data. 

When extracting data from seurat object, you should do it by `data.input = GetAssayData(w10x, assay = "RNA")`

**Comment by bharatm26** [comment]
Thanks for the reply. It worked by selecting RNA as an assay.
