### ISSUE TITLE
Issue with computeCommunProb function

### ISSUE THREAD

**Issue by ylxing001** [sqjin/CellChat#232]
Hi Suoqin,

After updating CellChat, I found the computeCommunProb function is not working anymore. 

> db1_cellchat1 <- readRDS("db1_cellchat_rawdata.rds")
> db2_cellchat1 <- readRDS("db2_cellchat_rawdata.rds")
> db3_cellchat1 <- readRDS("db3_cellchat_rawdata.rds")
> db1_cellchat1@DB <- CellChatDB.use
> db2_cellchat1@DB <-CellChatDB.use
> db3_cellchat1@DB <-CellChatDB.use
> db1_cellchat1 <- subsetData(db1_cellchat1)
> db1_cellchat1<- identifyOverExpressedGenes(db1_cellchat1,thresh.p = 0.05)
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=00s  
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=00s  
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=00s  
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=00s  
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=00s  
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=00s  
> db1_cellchat1 <- identifyOverExpressedInteractions(db1_cellchat1)
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=00s  
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=00s  
> db1_cellchat1 <- projectData(db1_cellchat1, PPI.mouse)
> db1_cellchat1 <- computeCommunProb(db1_cellchat1)
**Error in rep(yes, length.out = len) : 
  attempt to replicate an object of type 'closure'**

 I also got another earlier error like this. 
> db1_cellchat1 <- computeCommunProb(db1_cellchat1)
**Error in computeCommunProb(db1_cellchat1) : 
  Please check your input data matrix and ensure that you use the normalized data instead of count data!**

My dataset is already normalized so not quite sure why it happened. 

Thanks for your help.

**Comment by sqjin** [comment]
@ylxing001 Now I removed such information. You should be OK now.

**Comment by ylxing001** [comment]
@sqjin Sorry, could you please provide more information? I still couldn't get it worked. Would it be possible to provide the older version of source code for computeCommunProb function?

**Comment by BatLaB-cell** [comment]
@ylxing001 Is your cell chat objects derived from a Seurat object? 

I had the same error because my Seurat object was normalized with the function SCTransform and not with the classical normalization. Since I change the way I normalize my Seurat object, I don't have this error anymore

**Comment by ylxing001** [comment]
@BatLaB-cell Yes, my Cellchat objects were normalized with SCTransform. But they definitely worked until I updated CellChat. How did you change the normalization approach, by using ScaleData?

**Comment by BatLaB-cell** [comment]
@ylxing001 Yes I gave SCT up and used the "classical" way of Seurat normalization and since Cellchat perfectly works. Hope it could solve your issue.

**Comment by sqjin** [comment]
@ylxing001 @BatLaB-cell Thanks for reporting this issue. I will address this issue tomorrow.

**Comment by ylxing001** [comment]
@sqjin It would be great if you can solve the issue with SCT normalised data. I cannot use scale.data normalised data because all the other analyses (GO enrichment, DEG, pseudotime) were performed using SCT normalised data. Besides, I've generated a lot of CellChat plots from the SCT normalised data, which is not working after updating CellChat.

**Comment by sqjin** [comment]
@ylxing001 Yes, I will do it. But another way to do it is 

data.input = GetAssayData(w10x, slot = "data", assay = "SCT")
meta = w10x@meta.data
meta$labels = meta$final.clusters
cellchat <- createCellChat(data.input, meta = meta, group.by = "labels", do.sparse = F)

**Comment by sqjin** [comment]
@ylxing001 It now works for SCT normalised data.
