### ISSUE TITLE
Error in as(data, "dgCMatrix") :    no method or default for coercing “data.frame” to “dgCMatrix”

### ISSUE THREAD

**Issue by SohaibRU** [sqjin/CellChat#234]
I am trying to create a cellchat object from a seurat file but I keep getting this error. I have transformed my own scanpy h5ad files to serurat files so maybe its stemming from that but I'm unsure. I tried to add this line of code to fix it

object<- as (as(object, "matrix"), "dgCMatrix")
 
but that did not solve it. Any help is greatly appreciated!

**Comment by sqjin** [comment]
@SohaibRU Have you checked the suggestions in the tutorial `Interface with other single-cell analysis toolkits (e.g., Seurat, SingleCellExperiment, Scanpy)`. You may can try different methods to convert the scanpy object to seurat? 

You can also directly extract the data matrix and meta data information from scanpy, and then use them as input of cellchat.

**Comment by SohaibRU** [comment]
@sqjin thank you, i have ran the code to extract the cellchat input from my scanpy file but now I am getting this error. 

Error in py_module_import(module, convert = convert) : 
  ModuleNotFoundError: No module named 'anndata'

I see online this could be due to my python environment not being up to date but I'm unsure of how to fix this.

**Comment by qffighting** [comment]
I also meet the same problem that the error is as followed:
Error in as(data, "dgCMatrix") : 
  no method or default for coercing “function” to “dgCMatrix”

**Comment by qffighting** [comment]
I have solved my problem and I think that the help in R is very helpful. My input data is seurat  object and I didn't extract the cellchat input from my seurat file and I just followed the package help and use my seurat object as my input data :cellchat <- createCellChat(object = seurat.obj, group.by = "seurat.clusters"). no error occurred.
I found that there were some example in the R help and maybe it can help you

Examples
## Not run: 
# Input is a data matrix
## create a dataframe consisting of the cell labels
meta = data.frame(labels = cell.labels, row.names = names(cell.labels))
cellchat <- createCellChat(object = data.input, meta = meta, group.by = "labels")

# input is a Seurat object
## use the default cell identities of Seurat object
# cellchat <- createCellChat(object = seurat.obj, group.by = "ident")
## use other meta information as cell groups
# cellchat <- createCellChat(object = seurat.obj, group.by = "seurat.clusters")

# input is a SingleCellExperiment object
# cellchat <- createCellChat(object = sce.obj, group.by = "sce.clusters")

## End(Not run)

**Comment by SohaibRU** [comment]
I solved the problem by using my scanpy anndata instead following the cellchat tutorial. thanks for all the help everyone!

**Comment by codecant1** [comment]
Hello @sqjin and others -- I am running into the same error:
_Error in as(data, "dgCMatrix") :
no method or default for coercing “function” to “dgCMatrix”_

Attemping to run the following code, where loadedData is a log2(TPM+1) bulk RNAseq data matrix and meta is a 61x1 data matrix consisting of a column named "Diagnosis," rownames equal to colnames of loadedData and all cell values reading "Melanoma." In other words, I am working with a single group of data that is all bulk RNA-seq.
_cellchat <- createCellChat(object = loadedData, meta = meta)_

Per https://github.com/sqjin/CellChat/issues/137, sqjin previously indicated that CellChat could be used with a bulk RNA seq data despite CellChat's original intentions to be used on single cell objects.
