### ISSUE TITLE
Question about Part II of "comparing datasets" - up- and downregulated pathways based on differential gene expression

### ISSUE THREAD

**Issue by bieniu777** [sqjin/CellChat#238]
Hello,

I am following you tutorial for "Comparison analysis of multiple datasets using CellChat" and I would like to understand one part a bit better: "Identify dysfunctional signaling by using differential expression analysis". 

I have three datasets in my analysis. When I want to find upregulated genes in just the first dataset (WH), I run this code:
```
pos.dataset = "WH"
features.name = pos.dataset
cellchat <- identifyOverExpressedGenes(cellchat, group.dataset = "datasets", pos.dataset = pos.dataset, features.name = features.name, only.pos = FALSE, thresh.pc = 0.1, thresh.fc = 0.1, thresh.p = 1)
net.up <- subsetCommunication(cellchat, net = net, datasets = "WH", ligand.logFC = 0.2, receptor.logFC = NULL)
```

This works fine, but I don't know whether the above code calculates the upregulated genes in my WH dataset as compared to the other two datasets (IFNL, NL) that I have or whether it compares them to just the next dataset (IFNL), ommiting the third dataset (NL)? That is my first question.

Same goes for downregulated genes:
`net.down <- subsetCommunication(cellchat, net = net, datasets = c("IFNL", NL"), ligand.logFC = -0.1, receptor.logFC = -0.1)`

It doesn't let me subset two datasets, I can only use one in the above code.  But I guess that is okay if I can only compare two datasets at a time.
But if that is the case, and the code for finding upregulated genes only looks at two datasets at a time - I would like to know how do I subset the upregulated genes from my WH as compared to the third dataset (NL), and not second dataset (INFL) - as I assume is the way the code works. That is my second question.

I hope that makes sense. I would appreciate any help.

Thanks

**Comment by sqjin** [comment]
@bieniu777 In identifyOverExpressedGenes, the differetial expression analysis is performed by comparing one dataset/clusters vs. all others. 

For subsetCommunication, i will consider all the support the of two datasets. But you can also get one each time and then combine them together. 

If you want to compare the first with the third by omitting the second one, this means that you will not use any information in the second dataset. I would suggest to just merge the two cellchat objects or might use the subsetCellChat to get the data from the two datasets and then perform comparison analysis

**Comment by bieniu777** [comment]
@sqjin Thank you very much. 

The fact that it compares one dataset to all others is great. 

Sorry, but in that case I'd like to double-check that visualise downregulated pathways in my first dataset as compared to all other datasets correctly.

With the upreulated pathways it seems pretty straightforwad, basically what I already pasted earlier:


```
pos.dataset = "WH"
features.name = pos.dataset
cellchat <- identifyOverExpressedGenes(cellchat, group.dataset = "datasets", pos.dataset = pos.dataset, features.name = features.name, only.pos = FALSE, thresh.pc = 0.1, thresh.fc = 0.1, thresh.p = 1)
net <- netMappingDEG(cellchat, features.name = features.name)
net.up <- subsetCommunication(cellchat, net = net, datasets = "WH",ligand.logFC = 0.2, receptor.logFC = NULL)

gene.up <- extractGeneSubsetFromPair(net.up, cellchat)
pairLR.use.up = net.up[, "interaction_name", drop = F]
gg1 <- netVisual_bubble(cellchat, pairLR.use = pairLR.use.up, sources.use = 2, targets.use = c(1,3:5), comparison = c(1,2,3),  angle.x = 90, remove.isolate = T,title.name = paste0("Up-regulated signaling in ", names(object.list)[1]))
```


But then, the turioral says that in order to find downregulated genes in the first dataset, you look at which are upregulated in the other datasets. 
So this comes back to my trying to use the other two datasets to get the downregulated genes in the first dataset. Since I can't include two datasets in the code at once, I could just combine the results.
```
net.down1 <- subsetCommunication(cellchat, net = net, datasets = "IFNL",  ligand.logFC = -0.1, receptor.logFC = -0.1)
net.down2 <- subsetCommunication(cellchat, net = net, datasets = "NL",  ligand.logFC = -0.1, receptor.logFC = -0.1)

net.down <- rbind(net.down1, net.down2)

pairLR.use.down = net.down[, "interaction_name", drop = F]
gg2 <- netVisual_bubble(cellchat, pairLR.use = pairLR.use.down, sources.use = 1, targets.use = c(2:5), comparison = c(1,2,3),  angle.x = 90, remove.isolate = T,title.name = paste0("Down-regulated signaling in ", names(object.list)[1]))
```

Does it look like a correct approach (the code runs without problems)?

**Comment by sqjin** [comment]
@bieniu777 It looks good to me. You may can also consider the requirement of percent of expressing cells.  Below is an example

  net.up <- subsetCommunication(object.merged, net = net, datasets = names(object.list)[i+1],ligand.logFC = 0.25, receptor.logFC = 0.25,ligand.pvalues = 0.05, receptor.pvalues = 0.05, ligand.pct.1 = 0.25, receptor.pct.1 = 0.25)
  net.down <- subsetCommunication(object.merged, net = net, datasets = names(object.list)[i],ligand.logFC = -0.25, receptor.logFC = -0.25, ligand.pvalues = 0.05, receptor.pvalues = 0.05, ligand.pct.2 = 0.25, receptor.pct.2 = 0.25)

**Comment by bieniu777** [comment]
Thank you very much

**Comment by Manikgarg** [comment]
Thanks @sqjin ! I am in a similar situation and I have decided to merge two cellchat objects at a time to do the analysis. I noticed that in identifying the upregulated pathways, `receptor.logFC` is marked as `NULL` but wouldn't the signaling be reduced if the receptor has negative LFC? Sorry if I am missing something! 
With this assumption, I was thinking of modify the code to:
```
net.up <- subsetCommunication(cellchat, net = net, datasets = "WH",ligand.logFC = 0.2, receptor.logFC = 0.2)
net.up_down <- subsetCommunication(cellchat, net = net, datasets = "WH",  ligand.logFC = 0.2, receptor.logFC = -0.1)
net.down1 <- subsetCommunication(cellchat, net = net, datasets = "IFNL",  ligand.logFC = -0.1, receptor.logFC = -0.1)
net.down<-rbind(net.up_down, net.down1)
```
Do you think this makes sense? 
I am also a bit confused about when we want to calculate the downregulated pathways in "WH", why don't we simply flip the signs for logFC while keeping the dataset same:
`net.down <- subsetCommunication(cellchat, net = net, datasets = "WH",ligand.logFC = -0.1, receptor.logFC = -0.1)`
or change the dataset but shortlist at the upregulated pathways in IFNL (i.e. with positive logFC):
`net.down <- subsetCommunication(cellchat, net = net, datasets = "IFNL",ligand.logFC = 0.1, receptor.logFC = 0.1)`
Why do we switch to non-positive dataset as well as invert the sign to negative?:
`net.down <- subsetCommunication(cellchat, net = net, datasets = "IFNL",ligand.logFC = -0.1, receptor.logFC = -0.1)`
 Wouldn't it shortlist the downregulated pathways in IFNL that would ideally be upregulated in WH?

Hope I managed to explain it propely. Any help much appreciated!! Thanks!
