### ISSUE TITLE
Font category error in netVisual_aggregate

### ISSUE THREAD

**Issue by liangyuan-njmu** [sqjin/CellChat#24]
Hi,
Thanks for developing this user-friendly tool.
I have one problem that I can't go through when running:

```
netVisual_aggregate(cellchat, signaling = pathways.show, layout = "circle", vertex.size =groupSize)

Error in text.default(x, y, labels = labels, col = label.color, family = label.family,  :
  字体类别出错
```
Can you kindly help me with this problem? thank you very much!

**Comment by sqjin** [comment]
@liangyuan-njmu Please try `install.packages("extrafont")`

**Comment by liangyuan-njmu** [comment]
Sorry, I still haven't solved the problem.
```
> library(extrafont)
> netVisual_aggregate(cellchat, signaling = pathways.show, layout = "circle", vertex.size = groupSize)
Error in text.default(x, y, labels = labels, col = label.color, family = label.family,  :
  字体类别出错
```
I would like to ask what is the font of the label. Thank you very much~

**Comment by liangyuan-njmu** [comment]
I already know the font for plotting is Arial. I need to add this font to R.
Thank you very much~
