### ISSUE TITLE
Limiting to certain cell types in netVisual_embeddingPairwise 

### ISSUE THREAD

**Issue by jv-20** [sqjin/CellChat#249]
Hi @sqjin 

I have a quick question. Is it possible to limit to certain celltypes when doing functional or structural similarity grouping analysis  with netVisual_embeddingPairwise?

I like how we could specify source/target cell types in rankNet to identify pathways that change the information flow in context of those celltypes. Just wondering if it is possible to do this in the functional/structural similarity grouping analysis. 

Another small thing, would you be able to advise how to increase the arrow size in circle plot?

Thanks again for this amazing tool. You are a star.

**Comment by sqjin** [comment]
@jv-20 For the first question, if you want to subset cell groups, you can use the subsetCellChat function to get a small CellChat object. 

I have no idea on how to change the arrow size. But it definitely can be changed if you check how to do it using 'igraph'.  Note that the edge colors are consistent with the source nodes.

**Comment by jv-20** [comment]
Thank you @sqjin that's grand.
