### ISSUE TITLE
Heatmap of cell cluster on one axis and signaling pathway on the other axis

### ISSUE THREAD

**Issue by LooLipin** [sqjin/CellChat#25]
Hi there,

I was wondering if there's a way to combine the plots below into a single plot, ie have clusters on one axis and the signaling pathways on the other.
![image](https://user-images.githubusercontent.com/57159632/90350235-cb082b00-e07f-11ea-95f9-175b16ca66ac.png)

If there is no way to do it with the existing code, maybe there is a slot in which I can obtain this data to plot separately.

Thanks,
Lipin

**Comment by sqjin** [comment]
Hi @LooLipin, CellChat provides two functions to connect cell groups with signaling pathways, including `netAnalysis_river` and `netAnalysis_dot`. We demonstrate this in the tutorial. You can also check the method details of our preprint to see how we achieve such aim.
