### ISSUE TITLE
trim parameter not passed to mean func

### ISSUE THREAD

**Issue by dbdimitrov** [sqjin/CellChat#254]
Hi Suoqin,

I was looking through the different means code and noticed that the `trim` parameter is not appropriately passed to the `thresholdedMean` function and it simply returns the non-truncated mean.

https://github.com/sqjin/CellChat/blob/0c1134066be7f731466c15a6b2c0114881864432/R/modeling.R#L897

I will do my best to come back to you about the linux parallelization soon - apologies for the delay, I've been swamped lately.

I hope you are well.

Best wishes,
Daniel

**Comment by sqjin** [comment]
Hi Daniel @dbdimitrov 

Thanks for looking into this. The truncated mean is actually pass via `"truncatedMean"` when running `computeCommunProb`.  The `thresholdedMean` is a different one and is not accessed by the users. 

Hope all is going well with you too!

Best,
Suoqin
