### ISSUE TITLE
differential comunication in a control vs disease dataset.

### ISSUE THREAD

**Issue by pedriniedoardo** [sqjin/CellChat#256]
Hello, thank you for developing this wonderful tool.
I have an integrated dataset composed of control and diseased cells. At the moment I am using your tool running the analysis on the control cells and then on the diseased cells, highlighting the new pathways/pairs appearing or disappearing.
I was wondering whether there is a more straightforward approach, maybe specifying the experimental design in the metadata table. Also, what would you recommend to use as metrics to gauge whether a specific pathway is differently "expressed/regulated" in the comparison control vs diseased design?

**Comment by sqjin** [comment]
@pedriniedoardo Our current strategy is use run cellchat on each dataset and then perform comparison analysis.  In the tutorial, we provide an example how to combine differential expression analysis with cell-cell communication network. Please check the section `Identify dysfunctional signaling by using differential expression analysis`

**Comment by pedriniedoardo** [comment]
thank you for the explanation!
