### ISSUE TITLE
Error in V(g) <- `*vtmp*` : could not find function "V<-"

### ISSUE THREAD

**Issue by charlesgwellem** [sqjin/CellChat#261]
Please is what could be the reason why I am not able to make hierarchy plots with the **netVisual_aggregate** function? I am howver able to use the same function on the same data to successfully make a circle or chord plot.

```
netVisual_aggregate(cellchat, signaling = pathways.show,  vertex.receiver = vertex.receiver, layout = "hierarchy")
Error in V(g) <- `*vtmp*` : could not find function "V<-"
```
But the following line of code works

`netVisual_aggregate(cellchat, signaling = pathways.show,  vertex.receiver = vertex.receiver, layout = "circle")`

Thanks in advance.

**Comment by sqjin** [comment]
@charlesgwellem It looks like it can not find the function from the igraph package.  can you do `library(igraph)`?

**Comment by charlesgwellem** [comment]
@sqjin  You are right. Loading igraph worlks
