### ISSUE TITLE
Interpreting netAnalysis_signalingChanges_scatter plots

### ISSUE THREAD

**Issue by tjbencomo** [sqjin/CellChat#262]
Hi. I'm trying to interpret a figure generated by `netAnalysis_signalingChanges_scatter` comparing NK cell signaling in two stages of cancer
<img width="638" alt="Screen Shot 2021-08-10 at 12 32 16 PM" src="https://user-images.githubusercontent.com/26121995/128923440-635f7260-6d3d-4250-8c0d-862b20f5a808.png">

I had a few questions:

1. Why is EGF/PARs a square when the strength only changes for outgoing interactions? Should these be triangles since no change in incoming interaction suggests they are "Outgoing specific"? The same issue happens for Laminin although the shape is flipped. Is this a bug or am I reading the plot wrong?
2. How is "Shared" different than "Incoming & Outgoing Specific"

Thanks!

**Comment by sqjin** [comment]
@tjbencomo I noticed the first issue you mentioned. It should be a bug. Will address it in next few days. 

Shared means both conditions have the outgoing and incoming signaling of this pathway associated with this population. You can visualize the inferred network to further check.

**Comment by tjbencomo** [comment]
Thanks for answering both of those questions!

**Comment by iheartfoosball** [comment]
Hi guys,

@sqjin , thanks for the great package! 

I am still a little confused regarding @tjbencomo 's 2nd question about the direction labels. What I understand is:
Incoming specific = in both conditions (eg cSCC and pSCC in this case), the pathway was identified as a significant communication pathway in this cell population but in the incoming direction only
Outoging specific = pathway is identified in both conditions in this cell population but in the outgoing direction only
Shared = pathway is identified in both conditions in this cell population in both directions
Incoming and outgoing specific = ?

I originally thought these labels are instead referring to whether the **difference** between the 2 conditions is significant in the incoming vs outgoing vs both directions, but your previous response suggests that I was wrong about that.

Any thoughts appreciated - thank you!

**Comment by sqjin** [comment]
@iheartfoosball @tjbencomo Please update the Package because I have fixed the bug when generating this plot. 

@iheartfoosball Unfortunately, your original understanding is not correct. The word 'specific' here means whether it is specific to one condition. For example, if there is one pathway that only has outgoing signaling in cSCC but not in pSCC, then we claim it as outgoing specific in cSCC.

**Comment by iheartfoosball** [comment]
@sqjin Thanks! I will update now.

I see, thank you for the explanation. So all pathways that are specific to 1 condition will have both a non-gray color to indicate which condition + a non-circle shape to indicate which direction (incoming, outgoing, or both), and all the gray-colored points must be circles since they are not specific to a condition. Am I understanding correctly now?

**Comment by iheartfoosball** [comment]
Hi @sqjin , I updated to v1.1.3 and I still notice the issue that @tjbencomo pointed out. I've pasted a screenshot below and highlighted the points in question. These two pathways are labeled "Outgoing specific" but the strength is only changing for incoming interactions.

![image](https://user-images.githubusercontent.com/8459225/129652561-c9c77299-f107-4825-a309-dde46537c875.png)

**Comment by sqjin** [comment]
@iheartfoosball， please visualize this signaling and you will find there is no issue because they have very small outgoing interaction strength.

**Comment by iheartfoosball** [comment]
@sqjin , thanks, maybe I am still misunderstanding. A pathway colored red means it was **only** detected in the "CE" condition, correct? And if it is a triangle, it is **only** detected in the outgoing direction? How is it possible for such a pathway to have a differential incoming strength of around 0.2 (y-axis value on this plot) if there is no incoming interaction?

Sure, let's assume it's true that they have very small outgoing interaction strength. But they are still labeled as outgoing specific, so the incoming interaction should be non-existent, no?
