### ISSUE TITLE
Issue with weight/strength 

### ISSUE THREAD

**Issue by GBeattie** [sqjin/CellChat#267]
Hey, 

I've managed to run a merged analysis and generate some plots, the plots showing the interaction counts look good, however when showing weights there's some issues. Firstly the weights don't plot on the compareInteractions plot, and when plotting the weights using netVisual_diffInteractions the differential goes the opposite way from the counts. I'm thinking this could be because I've used population.size = T within computeCommunProb to mitigate the highly variable size of my clusters. Maybe my instinct to set population.size = T was incorrect?

My script and plots are below, any advice would be greatly appreciated!

```
cc.list <- list()
cc.list[["Control"]] <- createCellChat(object = subset(seu.int, subset = Treatment == "Control"), group.by = "cluster.id")
cc.list[["aCD25"]] <- createCellChat(object = subset(seu.int, subset = Treatment == "aCD25"), group.by = "cluster.id")

cc.list$Control@DB <- CellChatDB.mouse ; cc.list$aCD25@DB <- CellChatDB.mouse
cc.list <- lapply(cc.list, function(x) subsetData(x))

future::plan("multiprocess", workers = 2) 
cc.list <- lapply(cc.list, function(x) identifyOverExpressedGenes(x))
cc.list <- lapply(cc.list, function(x) identifyOverExpressedInteractions(x))
cc.list <- lapply(cc.list, function(x) computeCommunProb(x, population.size = T, type =  "truncatedMean", trim = 0.1))
cc.list <- lapply(cc.list, function(x) filterCommunication(x, min.cells = 10))
cc.list <- lapply(cc.list, function(x) computeCommunProbPathway(x))
cc.list <- lapply(cc.list, function(x) aggregateNet(x))

cc <- mergeCellChat(cc.list, add.names = names(cc.list))
cc <- subsetCellChat(cc, idents.use = c(lymph.clust, myelo.clust))

plot_grid(
compareInteractions(cc, show.legend = F, group = c(1,2)),
compareInteractions(cc, show.legend = F, group = c(1,2), measure = "weight"))

netVisual_diffInteraction(cc, weight.scale = T)
netVisual_diffInteraction(cc, weight.scale = T, measure = "weight")
```

![image](https://user-images.githubusercontent.com/11555832/129582466-afa6dfc8-a94c-427b-8584-bacbb34ae5d5.png)

![image](https://user-images.githubusercontent.com/11555832/129584468-d8391152-92a2-4fdd-85ee-cc0a1928494b.png)
![image](https://user-images.githubusercontent.com/11555832/129584500-dbdf78fa-dfa1-4324-9ea5-f85451ac261d.png)

**Comment by sqjin** [comment]
@GBeattie You can try `population.size = FALSE` as this parameter is not used to regress out the effect of population size. You can check the tutorial for detailed explanation.  

It looks like there is some issue when generating the bar plot for interaction weight. However, I have no issue for my own datasets. 

In some cases, the results from interaction number and interaction strength might be different as they have different meaning and are computed from different methods.

**Comment by GBeattie** [comment]
@sqjin Thank you for the speedy response!

I've run the analysis again using `population.size = FALSE ` and the weighted compareInteractions plot is now working. The values however are very low, and the differential between the two samples is still inverted when compared to the count plots (not shown below but similar to the network and differential heatmap plots shown before with `population.size = TRUE `).

I'm not sure what could have gone wrong for the interaction strength values to be so low, is there anything I should check in the data? If these values are genuine, would it be fair to say the differential counts are likely a better representation of the biology since the values are too low to be reliable?

![image](https://user-images.githubusercontent.com/11555832/129730216-c227ebb5-b73d-4604-93ff-5f8cc9f2ede4.png)

**Comment by sqjin** [comment]
@GBeattie It is ok to have low values here because all the values are relative small based on the measure used in CellChat. We cannot say 0.05 is very small here, but we know a link with 0.06 is stronger than 0.05. 

In terms of which one could better represent the biology,  I know some people prefer the number of interactions in the published papers. In your case, it showed that although there are few number of interactions  in aCD25, they are highly activated in aDC25. I expect to see many upregulated signaling in aCD25.

**Comment by GBeattie** [comment]
@sqjin Thanks for the response, I'm guessing there's some normalising that goes on that might generate these values. If it was possible to introduce some kind of p-value to comparative plots like compareInteractions that might be useful for determining real changes over small background level changes. 

Good to know the interaction number is preferred, the outputs from the count plots agree with a separate analysis I've done using CellPhoneDB.

**Comment by acihanckr** [comment]
I was having the same issue with the barplot and it was due to rounding. If the total weights are smaller than 10^-3, it is rounded to 0 since the default digits parameter in the function is 3. Changing digits parameter to a larger number like 10 or 15 fixes the issue.
