### ISSUE TITLE
Question about the netMappingDEG function; NA values generated

### ISSUE THREAD

**Issue by bieniu777** [sqjin/CellChat#268]
Hello,

I have a question about the part of the tutorial that looks for ligand-receptor pairs based on differential gene expression between different datasets.

I noticed that that code:

`net <- netMappingDEG(cellchat, features.name = features.name)`

generates quite a lot of NA values. Then, I can further subset ligand-receptor pairs based on logFC of ligands, logFC of receptors etc. This is great, but why do some ligand receptor pairs have missing values? Sometimes I can only see the stats for a ligand, sometimes only for a receptor, and sometimes for neither - just NA values. So obviously when I subset my pairs based on log FC values, some are not included because of the missing values. What does it mean if NA values are generated here? Does it mean that one of the datasets didn't express a ligand (or a receptor) at all? If yes, does that mean that I don't see dataset-specific ligand-receptor pairs in DEG analysis? Only those that are expressed in both?

Best wishes

**Comment by sqjin** [comment]
@bieniu777 NA means that the ligand or receptor is not differentially expressed in that cluster.  You can check the DEGs by `DEG <- object.merged@var.features[[paste0(features.name, ".info")]]`

**Comment by bieniu777** [comment]
@sqjin Thank you
