### ISSUE TITLE
Question about communication probabilities

### ISSUE THREAD

**Issue by tjbencomo** [sqjin/CellChat#269]
Hi @sqjin,

Thanks for creating this really useful software. I am comparing signaling in a control and tumor condition. After merging control and tumor CellChat objects and following the tutorial, I run

```
rankNet(cellchat, mode = "comparison", stacked = T, do.stat = TRUE)
```

and the top tumor specific signaling pathways (only present in the tumor and absent in the control) are PTN and ANXA1. When I examine the tumor pathway probabilities and p-values with `subsetCommunication(cellchat, slot.name = "netP")`, the strongest PTN interaction has a `prob = 0.0306359166` and `pval = 0`. Other tumor-specific pathways have similar `prob` scores (between 1e-3 to 1e-2) and p-values of 0. Overall, the minimum probabilities for any pathway identified by CellChat is 8.325975e-06 and the maximum is 2.041313. 

1. 2.041313 is greater than 1. Should `prob` be between 0 and 1, or is it an unbounded measure of signaling strength?
2. Do you have any experience validating pathways with smaller `prob` scores? In your CellChat paper some of the lesion-specific pathways you show in Figure 7 (IL4, TNF) have similar probabilities to my results, but `prob` scores around 1e-3 seems rather small. I am comforted that CellChat identified PTN as PTN has already been implicated in my disease via other methods, but any thoughts on the `prob` score strengths would be appreciated.

**Comment by sqjin** [comment]
@tjbencomo The values of `prob` are relative. That is, we cannot say 0.8 is large or not, but we can say 0.8 is greater than 0.7. Therefore, this is no need to be worry about the specific values. Based on my experience, once CellChat indicates an either increased or decreased signaling that is interesting to you, you should check the inferred signaling network and the expression levels. This will give you a confident result for further validation.  You can also check the section involved in differential expression analysis in the tutorial of comparison analysis.

**Comment by tjbencomo** [comment]
Thanks for commenting on this @sqjin
