### ISSUE TITLE
CellChat_Rcpp.o: file not recognized: File format not recognized collect2.exe: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by simon910** [sqjin/CellChat#28]

**Comment by simon910** [comment]
CellChat_installation_error
Installing package into ‘C:/Users/Simon-PC/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'CellChat' ...
** using staged installation
** libs
C:\Rtools\mingw_64\bin\nm.exe: CellChat_Rcpp.o: File format not recognized
C:\Rtools\mingw_64\bin\nm.exe: RcppExports.o: File format not recognized
c:/Rtools/mingw_64/bin/g++ -std=gnu++11 -shared -s -static-libgcc -o CellChat.dll tmp.def CellChat_Rcpp.o RcppExports.o -LC:/PROGRA~1/R/R-36~1.2/bin/x64 -lR
CellChat_Rcpp.o: file not recognized: File format not recognized
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'CellChat'
* removing 'C:/Users/Simon-PC/Documents/R/win-library/3.6/CellChat'

**Comment by sqjin** [comment]
@simon910 Please check the issue #6
