### ISSUE TITLE
A question about function of circleplot

### ISSUE THREAD

**Issue by BeyondMyPast228** [sqjin/CellChat#3]
Hi,
Thanks for developing CellChat, which is very user-friendly and convenient. But I don't know what to do when I want to draw a circleplot of all the functional pathways.  
The code is **netVisual_aggregate(cellchat, signaling = pathways.show, layout = "circle", vertex.size = groupSize)**. So,  Should I enter all the pathways manually? After I manually enter all the pathways, the title of circleplot got farraginous.
I sincerely hope to get your reply.

**Comment by sqjin** [comment]
@BeyondMyPast228 Hello, you can use for..loop to save all the plots from all the signaling pathways. Please check the tutorial [here](https://htmlpreview.github.io/?https://github.com/sqjin/CellChat/blob/master/vignettes/example_streamline_for_quick_analysis_and_exploration.html).
