### ISSUE TITLE
Error in do.call(getGeneric("seed"), c(list(x = x, model = init, method = seed.method),  :    'what' must be a function or character string

### ISSUE THREAD

**Issue by kzxkzx** [sqjin/CellChat#30]
hi~sorry to bother,perfect R toolkit,but I get trouble when I want to use the function _identifyCommunicationPatterns_(cellchat, pattern = "incoming", k = nPatterns), are there some solution?

**Comment by sqjin** [comment]
@kzxkzx Please install the NMF package by `devtools::install_github("sqjin/NMF")`

**Comment by kzxkzx** [comment]
@sqjin seems still not work

**Comment by sqjin** [comment]
@kzxkzx Please check the solution in the issue #16

**Comment by wu-yc** [comment]
Hi, @kzxkzx @sqjin. #16 did not solve anything. 
I restart my R, reload the library(CellChat), and this bug disappears. It seems that this bug is caused by clashes of different packages. 
Cheers
