### ISSUE TITLE
netClustering Error

### ISSUE THREAD

**Issue by akui113** [sqjin/CellChat#31]
it's a wonderful R toolkit, but I had got this error when using the function netClustering

cellchat <- netClustering(cellchat, type = "functional") 
 
Error in as.vector(data): no method for coercing this S4 class to a vector.

how could I fix this trouble? thank you very much.
--

**Comment by sqjin** [comment]
Hi @akui113 , I think the issue is due to certain incorrect data you obtained when running netClustering. I suggest you to debug the code. For example, you can run each line in the [code](https://github.com/sqjin/CellChat/blob/master/R/analysis.R) to figure out the reason.

**Comment by akui113** [comment]
OK, thank you for your suggestion, I will try it and find the main reason.

**Comment by akui113** [comment]
OK, thank you for your suggestion, I will try it and find the main reason.

**Comment by akui113** [comment]
OK, thank you for your suggestion, I will try it and find the main reason.
