### ISSUE TITLE
How to explain the pathway distance？

### ISSUE THREAD

**Issue by Rui-Jing** [sqjin/CellChat#32]
Hi，
CellChat does pioneering work comparing multiple databases about cell-cell communication. But I still have confused about the results of comparing multiple data sets. Just like the picture below:
[
![image](https://user-images.githubusercontent.com/59251760/90842530-1c6f2d80-e392-11ea-8f37-b4aa94792743.png)
](url)
Larger distance implies larger difference of the communication networks between Database1 and Database2. So for this graph, can you explain whether database 1 is more enriched or database 2 is more enriched on some signaling pathways(eg WNT). In other words, **Could it be said that dataset 1 enriched more on the WNT pathway and dataset 2 enriched less.**

Another problem is that when I compare **multiple datasets(>2)**, **rankSimilarity** and **rankNet** cannot show the differences from multiple datasets.

Looking forward to your kind reply.

**Comment by sqjin** [comment]
Hi @Rui-Jing , the pathway distance is computed based on the 2D-space. Thus it can indicate whether the same signaling between two datasets are similar or not. It cannot suggest whether it is enriched in one dataset.  Based on the definition in rankSimilarity and ranNet, they definitely can only work for two datasets. But we provide a parameter in these two functions to allow for comparing any two pairs.

**Comment by Rui-Jing** [comment]
@sqjin Hi, for a comparison of ligand-receptor pairs in two datasets, does it means a descending order of all different ligand-receptor pairs, or does it means a comparison of one of the ligand-receptor pairs in two datasets?  Can you give me a demonstration ?(an example of comparison for L-R pairs).

**Comment by sqjin** [comment]
@Rui-Jing Sorry, I cannot well understand you.

**Comment by Rui-Jing** [comment]
@sqjin I'm sorry I didn't explain my question clearly. I was wondering if I could find the differences in specific L-R pairs when comparing cell communication between two databases. Or an overview of the difference in L-R pairs expression.

**Comment by sqjin** [comment]
@Rui-Jing If you follow the [tutorial](https://htmlpreview.github.io/?https://github.com/sqjin/CellChat/blob/master/vignettes/example_streamline_for_quick_analysis_and_exploration.html), you will find the generated cell-cell communication network for both signaling pathway and its associated L-R pairs. Then you can check the difference between specific L-R pairs.  For the overall differences, please check our tutorial on comparison analysis. For the L-R expression, you can simply do it in Seurat.
