### ISSUE TITLE
empty columns occur when using netVisual_bubble

### ISSUE THREAD

**Issue by esroom** [sqjin/CellChat#324]
Thank you for this wonderful tool!

I have a small problem when using **netVisual_bubble**. It works well when I didn't select some targets or sources, but once I selected,  empty columns were not removed. Here is my code

`netVisual_bubble(cellchat,  pairLR.use = myLR,  sources.use = c(2:8), targets.use = c(2:8))`

and the picture
![image](https://user-images.githubusercontent.com/44914876/142576320-16fa698a-8994-4a14-a679-a42abb19d75e.png)

It could be done by removing NAs before plotting. In my case, I add some code in the **netVisual_bubble** function at line 243-244. I am using **version 1.1.3**. Hope this helps.

![image](https://user-images.githubusercontent.com/44914876/142577335-987ba4b1-2daa-4efa-afcd-acfea9213bc9.png)

**Comment by sqjin** [comment]
@esroom Can you also try set `remove.isolate = TRUE`？ It should also work.

**Comment by esroom** [comment]
Thanks, it works!
