### ISSUE TITLE
when I run mergeCellChat,  an error was found

### ISSUE THREAD

**Issue by lawrenceczj** [sqjin/CellChat#344]
Dear，
       thank you for your useful package，
      then when I run mergeCellChat,  an error was found:
The cell barcodes in merged 'meta' is   
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length
In addition: Warning message:
In mergeCellChat(chol, add.names = names(chol)) :
  The cell barcodes in merged 'meta' is different from those in the used data matrix.
              We now simply assign the colnames in the data matrix to the rownames of merged 'mata'!
looking forward to your help!

**Comment by maqingyue** [comment]
Have you solved this problem? I have the same problem.

**Comment by maqingyue** [comment]
Hello, I also have the same problem.  I ran object. list [[i]]@meta on the tutorial data and my data respectively.  The data in the tutorial are different prefixes, and my data are also different prefixes.  Why does my data have this error?  Figure 1 is the data in the tutorial, and Figure 2 is my data. I don't know if this is the reason for reporting errors.

FIg.1
![图1](https://user-images.githubusercontent.com/113956599/223633278-e60230d0-9639-4456-8f58-627e819a969f.png)

Fig.2
![图2](https://user-images.githubusercontent.com/113956599/223633295-4d9562f0-c797-4415-85a1-b5ff74f868b0.png)

**Comment by maqingyue** [comment]
How did you solve this problem? I have the same problem.

**Comment by pwmellors** [comment]
I have the same problem
