### ISSUE TITLE
Is CellChat suitable for research of the interaction between neurons?

### ISSUE THREAD

**Issue by grimwoo** [sqjin/CellChat#345]
Thanks for development of such fabulous package for cell-cell interaction. Here, I wonder if CellChat is suitable for research of the interaction between neurons. Because the crosstalk among neurons was usually modulated by synapse and electricity. 
Look forward to your reply! Best wishes!

**Comment by sqjin** [comment]
@grimwoo In principle, I think it can be applied to your case. CellChat infers cell cell communication based on the expression levels of ligands and receptors.  When applying to neuron signaling, you may need to check if your interested signaling pathways are included in CellChatDB. If not, I am happy to update the database if you can provide me a list of newly added L-R pairs.

**Comment by grimwoo** [comment]
@sqjin thanks for your quick reply! The genes involved in synapse are complicated (for example, the [glutamatergic synapse](http://amigo.geneontology.org/amigo/term/GO:0098978) concluded by [SynGO](https://www.cell.com/neuron/pdfExtended/S0896-6273(19)30427-1)). I have to commit that I didn't recognize those interactions between neurons in L-R pairs levels. Hence, I closed this issue. But if any other experts in this field please feel free to give a conclusion on the performance of CellChat on synaptic crosstalk.
