### ISSUE TITLE
Merging two datasets with different sample size

### ISSUE THREAD

**Issue by artemisiat** [sqjin/CellChat#346]
Hello and thank you so much for this all around wonderful package.
I have a question concerning merging datasets in order to perform differential analysis. 
I would like to compare two conditions from my dataset that have different sample size which results in differences in the number of cells per cluster. As far as I understand your approach focuses on cell groups rather than numbers of cells but is there any additional steps I should consider pre- or post-merging?
Additionally, would increased gene expression in one of the two conditions result in false differential comparisons of pathways?
Thank you!

**Comment by sqjin** [comment]
@artemisiat Since CellChat computes the average expression of ligands and receptors per cell group, you do not need to be worry about the cell numbers when running 'cellchat <- computeCommunProb(cellchat)'

I am not very clear about your second question.

**Comment by artemisiat** [comment]
@sqjin thanks!
Yes sorry about that. Ignore for now and might return to the thread when I work out my results.
