### ISSUE TITLE
computeCommunProb

### ISSUE THREAD

**Issue by callaL** [sqjin/CellChat#36]
Hello, Mr. Jin，
        I encountered the following error when using cellchat.When I executed this command, the software reported an error:cellchat <- computeCommunProb(cellchat)
        

![11](https://user-images.githubusercontent.com/52152132/91839176-39084100-ec81-11ea-8409-23fad84fea53.png)

  Hope to get your help

**Comment by sqjin** [comment]
@callaL I am sorry I have no idea on this error. Make sure you are using the normalized data without negative values as input. I suggest you to run each line of the codes in computeCommunProb.
