### ISSUE TITLE
Turning off differential plots when using merged object

### ISSUE THREAD

**Issue by GBeattie** [sqjin/CellChat#366]
Hey,

I'm producing some nice plots showing differences between samples, but there doesn't seem to be a way of turning the differential  off and visualising the raw number/strength of interactions.

For example, I have two samples, and `netVisual_heatmap(cc, cluster.rows = T, cluster.cols = T)  ` produces differential numbers of interactions, but I would like to see just the raw number of interactions, treating both samples as one.

It's possible the only way to do this is to generate another CellChat object where the samples are merged into one, but would be really helpful if there was an easier way!

All the best,
Gordon

**Comment by sqjin** [comment]
@GBeattie If you do `netVisual_heatmap(object.list[[1]])`, it will only produce the number of interactions for the first sample.

**Comment by GBeattie** [comment]
Thanks, this will work pretty nicely!
