### ISSUE TITLE
Hierarchical plot shows inconsistent result compared to circle plot and network centrality heatmap

### ISSUE THREAD

**Issue by YiqunCao** [sqjin/CellChat#37]
Hi,
Thanks for the great tool. I notice that for some of the signaling pathways, the hierarchical plot is inconsistent with the circle plot or the network centrality heatmap. 
Below is one of the example, both circle plot and network centrality heatmap show strong cell communication between cell type "Epithelial_M" and "Epithelial_P", but the hierarchical plot (the first plot) does not show such cell communication. What could be the reason? Thanks!
<img width="848" alt="Screen Shot 2020-09-01 at 10 11 06 PM" src="https://user-images.githubusercontent.com/12710658/91863296-8b595a00-eca1-11ea-8925-e08489005722.png">
![Screen Shot 2020-09-01 at 10 13 19 PM](https://user-images.githubusercontent.com/12710658/91863318-90b6a480-eca1-11ea-8569-76ca019e3599.png)
![Screen Shot 2020-09-01 at 10 47 37 PM](https://user-images.githubusercontent.com/12710658/91866491-2a338580-eca5-11ea-8c1c-78affd453fac.png)

**Comment by sqjin** [comment]
@YiqunCao I just fixed this bug when generating Hierarchy plot. Please re-install the package.
