### ISSUE TITLE
What is meant by cell composition - cell type or proportion?

### ISSUE THREAD

**Issue by Hrovatin** [sqjin/CellChat#372]
I would like to compare multiple datasets with CellChat. They have the same cell types, but in different proportions. Do I need to use lift function in this case or not? - I was not sure what exactly you mean by cell composition in different parts of tutorials - e.g. different sets of cell types or different cell type proportions.

**Comment by sqjin** [comment]
@Hrovatin It means the different sets of cell types. Thus you not need to use the lift function.

**Comment by Hrovatin** [comment]
Thank you for the explanation.
