### ISSUE TITLE
Is the intercellular communications p-value a raw or corrected p-value?

### ISSUE THREAD

**Issue by LucaTucciarone** [sqjin/CellChat#382]
Hello!

I have one question about the step:
cellchat <- computeCommunProb(cellchat)
In the paper you explain how you calculate statistically significant interactions:

`The significant interactions between two cell groups are identified using a permutation test by randomly permuting the group labels of cells, and then recalculating the communication probability Pi,j between cell group i and cell group j through a pair of ligand L and receptor R. The p-value of each Pi,j is computed by a specific formula.`

 but then you do not specify whether the pvalue is a corrected pvalue or not. Could you please explain? 
 I am using the raw communication probabilities out of cell chat and I wanted to better understand if I should correct the p-values or not. 

If I should do that I don't thin is even possible as most of them are just 0s.
Let me know, 

Thanks!

**Comment by LucaTucciarone** [comment]
And also, what does "communication probability" really is? What is the maximum it can go up to? 
up to1 ?

**Comment by EvelynZav** [comment]
Hi, I also have this question.

**Comment by sqjin** [comment]
The communication probability is the interaction score we defined and computed in cellchat. In most cases, the values are very small due to the way how we compute it. But you still can compare values across different pathways and datasets.  

The p-value is not corrected.  We permute the cell labels 100 times.
