### ISSUE TITLE
Interpreting netAnalysis_signalingChanges_scatter

### ISSUE THREAD

**Issue by simonmfr** [sqjin/CellChat#391]
I wonder how a singnalling class (e.g. GALECTIN) can be differentially active between the datasets (KO vs WT), when it is KO-specific? Wouldn't it have to be active in both datasets to be able to detect changes between conditions? Appreciate any help!

![grafik](https://user-images.githubusercontent.com/70199914/158989411-7c8e3bde-45d1-443d-baab-07631b4e3a62.png)

**Comment by sqjin** [comment]
@simonmfr You can use the circle plot to visualize the inferred signaling network and you are expected to see that there is only outgoing GALECTIN signaling in KO condition instead of WT.

**Comment by simonmfr** [comment]
I see, makes sense. Thanks for the quick reply.
