### ISSUE TITLE
ranknet figure

### ISSUE THREAD

**Issue by jv-20** [sqjin/CellChat#395]
Hello @sqjin 

Quick question. 

I am trying to use rankNet function to draw the stacked barchart for top 20 altered pathways based on the information flow.  
When I use the return.data function, I can't seem to find the column with values that have the relative information flow (ranges between 0 to 1)?.  Could you please advise which column is that?

```
test=rankNet(cellchat_merged.obj, mode = "comparison", stacked = T,return.data = T,do.stat = T)
test=test$signaling.contribution
```

Also, could you please advise, if it is possible to generate ranknet figure for a list of user input signaling pathways?

Thank you

**Comment by sqjin** [comment]
@jv-20 You can check the column called "contribution" and stacked bar plot uses this information to show the relative proportion. 
It looks like rankNet does not support the input of signaling pathways, you can do it by filter the 'test' data from the ggplot object and then replot it based on the some codes in rankNet.

**Comment by jv-20** [comment]
Thanks @sqjin
