### ISSUE TITLE
How to distinguish the secreted signaling pattern——paracrine/autocrine signaling interactions

### ISSUE THREAD

**Issue by BeyondMyPast228** [sqjin/CellChat#4]
Hi，
Thanks for your answer to my previous question. As I was running CellChat, I became aware of a problem. Can I know if the type of interactions in my single-cell data is autocrine or paracrine? How can I tell them apart?
I sincerely hope to get your reply.

**Comment by sqjin** [comment]
@BeyondMyPast228 First, our customized hierarchical plot allows easy-to-identified paracrine vs. autocrine signaling links; second, the signaling role plot also can tell you based on the sender and receiver measures; third, you can also access the communication probability matrix via `cellchat@netP$prob` or `cellchat@net$prob`, where the non-zero elements in the diagonal indicate the autocrine signaling.

**Comment by BeyondMyPast228** [comment]
Thanks your answer.

**Comment by guokai8** [comment]
So in the hierarchical plot, the left part is autocrine or the right part is autocrine?

**Comment by sqjin** [comment]
@guokai8 I am not very clear what you are referring to. But the link from one solid circle (source) with one open circle (target) with the same colors is the autocrine signaling.
