### ISSUE TITLE
Multiple Graphs Overlay On Top of One Another

### ISSUE THREAD

**Issue by troks27** [sqjin/CellChat#401]
Hello,

When working through your vignette with my data, it seems that when I try to generate one graph after another, the previous graph still reminds, resulting in two graphs being overlayed onto of one another. How do I clear the previous graph before generating the next one? Other packages do this automatically. 

![Screen Shot 2022-04-07 at 12 14 38 PM](https://user-images.githubusercontent.com/52392398/162249567-167d3b0a-c11d-4a7d-bd9e-8c881b16c3fa.png)
 
Ran 1st:
netAnalysis_contribution(cellchat_seurat_integrated_02, signaling = pathways.show)

Ran later on:
nPatterns = 2
cellchat_seurat_integrated_02 <- identifyCommunicationPatterns(cellchat_seurat_integrated_02, pattern = "outgoing", k = nPatterns,width=12,height=22)

**Comment by giovanegt** [comment]
dev.off()
Or 
graphics.off()
