### ISSUE TITLE
error when doing netVisual_heatmap

### ISSUE THREAD

**Issue by sadiexiaoyu** [sqjin/CellChat#413]
Hi, 
When I run netVisual_heatmap(cellchat, signaling=pathways.show,color.heatmap="Reds")
It gives the following error report:
Do heatmap based on a single object
Error in if (n<=length(colorSpace)) : argument is of length zero.
Could you give any suggestion?

**Comment by sadiexiaoyu** [comment]
sorry, it is my system error.

**Comment by fffyan33** [comment]
Hi! How did you fix it? Thanks a lot!

**Comment by hyjforesight** [comment]
Same issue here. How did u fix it? Thanks!

**Comment by sqjin** [comment]
@hyjforesight @fffyan33 Did you set `remove.isolate = T`?  If not, it is weird.

**Comment by hyjforesight** [comment]
hi @sqjin, I restart my PC and rerun the codes. It works fine.
