### ISSUE TITLE
Integrate data as input files, run cellchat

### ISSUE THREAD

**Issue by chuhan1314** [sqjin/CellChat#42]
Hello, Mr. Jin，

I used seurat (cca) to integrate the data, and the input matrix is as follows:

![image](https://user-images.githubusercontent.com/56568877/92352996-e7910380-f111-11ea-921c-98272e060f94.png)
![image](https://user-images.githubusercontent.com/56568877/92353237-6dad4a00-f112-11ea-87bc-b6f239067baa.png)

However, when I run "computeCommunProb()", there are some warnings.

 
![image](https://user-images.githubusercontent.com/56568877/92353342-a9481400-f112-11ea-99a5-a230f49ca46c.png)

next, when I run "computeCommunProbPathway()", errored.

![image](https://user-images.githubusercontent.com/56568877/92353375-bfee6b00-f112-11ea-90a1-571750049944.png)

I want to know if this error is related to negative values in the matrix?
In addition, can Cellchat run the integrated data, and if so, what should be done?

Hope to get your help！

**Comment by chuhan1314** [comment]
In my understanding, the gene expression in The "RNA" assay is just the “cbind” of several samples after normalization. If I am concerned about the interaction of certain two types of cells in different samples (for example T-reg in sample A and T cell in sample B), can accurate results be obtained using such gene expression values?

**Comment by sqjin** [comment]
@chuhan1314 It is OK to use such normalized data. But you can also find a better way to remove the batch between different datasets.

**Comment by chuhan1314** [comment]
Excellent 👏Thank you again for your kind reply 🙏In addition, I would like to ask you, do you have a recommended method for batch removal? If so, what is it?

**Comment by sqjin** [comment]
@chuhan1314 You can check the benchmarking paper for batch correction. As far as I know, the corrected matrix from almost all the batch removal methods are only suitable for dimension reduction, and NOT suitable for CellChat.

**Comment by chuhan1314** [comment]
> @ chuhan1314您可以检查基准纸以进行批次校正。据我所知，几乎所有批次去除方法中的校正矩阵仅适用于缩小尺寸，不适用于CellChat。

Thank you again for your kind reply 🙏
