### ISSUE TITLE
Using residuals instead of counts as CellChat Object input?

### ISSUE THREAD

**Issue by artemisiat** [sqjin/CellChat#420]
Have you tried loading residuals of corrected counts for various covariates (i.e. age, sex, etc.) instead of the normalized counts? Would the code perform similarly or do you see clear reasons that it wouldn't provide accurate results?
Thanks!
Artemis

**Comment by sqjin** [comment]
@artemisiat please try the solution here (https://github.com/HenrikBengtsson/future/issues/624#issuecomment-1131916204)

**Comment by sqjin** [comment]
@artemisiat I have not done it in this way yet.  Does this data have many negative values? How did you use this data for downstream analysis such as differential expression analysis

**Comment by artemisiat** [comment]
Ended up using counts instead due to issues that come up when i use the negative values indeed. Thank you!
