### ISSUE TITLE
can we use CellChat for user-specific custom interactions?

### ISSUE THREAD

**Issue by jv-20** [sqjin/CellChat#43]
Hi Suoqin,

Thanks for this really nice tool. I was wondering if you can give some advice on if it is possible to use CellChat for custom interactions specified by the user. 

Thank you,
Janaki

**Comment by sqjin** [comment]
Hi @jv-20 , here is an example for inferring interactions for TGFb signaling `signaling.show <- c("TGFb")
pairLR <- searchPair(signaling = signaling.show, pairLR.use = cellchat@LR$LRsig, key = "pathway_name", matching.exact = T, pair.only = F)
cellchat <- computeCommunProb(cellchat, LR.use = pairLR)
`

**Comment by jv-20** [comment]
Thanks so much for the reply. That's helpful. I have another question. For example, if we know hypothetically there are other potential receptors for a specific ligand but it is not reported in the cellchatDB, is it possible to add these interactions to the database and run the pipeline?

Thank you,
Janaki

**Comment by sqjin** [comment]
@jv-20 Please check the previous issues #20 and #38 to see how to update the database.

**Comment by jv-20** [comment]
Excellent 👏 thanks for the links. I will follow the instructions to update the database. Thank you again for your kind reply 🙏
