### ISSUE TITLE
Normalized data

### ISSUE THREAD

**Issue by nicholascwho** [sqjin/CellChat#44]
Hi Jin,

Thank you for this resource.

I have a question about the data normalization. Is it possible to proceed with TPM instead of using the normalization method you used in the paper?

Thank you!

Warmest regards,
Nicholas Ho

**Comment by nicholascwho** [comment]
Sorry, I meant log2(TPM+1)

**Comment by sqjin** [comment]
@nicholascwho Yes, you can use it.

**Comment by nicholascwho** [comment]
Thank you!
