### ISSUE TITLE
Change Communication Probability's Scale in Bubble Plots?

### ISSUE THREAD

**Issue by ManuelMoradiellos** [sqjin/CellChat#452]
Hi!

First of all, thanks for the package! I'm still getting into it but it has a lot of cool features that are useful for analysis I'm currently doing.

In my experiment I have three datasets with different conditions but with the same type of cells from which I want to compare the differences.

I've merged the datasets two-by-two and when using netVisual_Bubble() I noticed that the scale of the Communication Probability from the comparison goes from min. to max. probability instead of 0 to 1 as I'm used to. I also saw that the original probability undergoes a scaling/transformation of -1/log(original_prob); why is it so?

I've been taking a look at the function to see if I could modify that behavior because I'm interested in comparing various bubble plots and I think that having the scale from 0 to 1 would be useful. Do you know of any good way to do alter this scale in the bubble plots??

**Comment by sqjin** [comment]
@ManuelMoradiellos You can consider to modify two pieces of codes. 
` g <- g + scale_radius(range = c(min(df$pval), max(df$pval)), breaks = sort(unique(df$pval)),labels = names(values)[values %in% sort(unique(df$pval))], name = "p-value")`
`g <- g + scale_colour_gradientn(colors = colorRampPalette(color.use)(99), na.value = "white", limits=c(quantile(df$prob, 0,na.rm= T), quantile(df$prob, 1,na.rm= T)),
                                    breaks = c(quantile(df$prob, 0,na.rm= T), quantile(df$prob, 1,na.rm= T)), labels = c("min","max"))`

By setting a unified range for the `range` and `limits`, you can compare different plots. 

The reason why I do the transformation is to avoid certain values that are super large. The same transformation was applied in the rankNet function.

**Comment by ManuelMoradiellos** [comment]
Thanks for the help and the quick response!

I still need to tinker a bit with the visualization as when setting the unified range of the probability from 0 to 1 the resulting plot is not as good as I expected.

**Default version of** `netVisual_bubble()` :
![default_visualization](https://user-images.githubusercontent.com/53752249/184175814-fbb077ad-600e-46fe-864a-b37152072cae.png)

**Modified version of** `netVisual_bubble()` :
![modified_visualization](https://user-images.githubusercontent.com/53752249/184175963-6a23500d-3fa6-41ba-a950-0074be02a645.png)

Maybe my data does indeed have really low probability of cell-cell communication but I believe I may be missing something in the probability transformation, maybe I need to update something else to represent it correctly.

Anyways thanks for the help and I'll keep on working to achieve my objective!

**Comment by sqjin** [comment]
@ManuelMoradiellos Here are my suggestions. 1) Increase the dot size;  2) No need to set the range as [0,1], but the range based on your data. You can easily compute the min and max probabilities in your inferred network.

**Comment by ManuelMoradiellos** [comment]
Thanks for all the help @sqjin~ 
I'll follow your suggestions as at first I wanted to fix the rate of probability so the heatmap's coloring wouldn't be misleading to my peers, but not modifying the range and including the min and max values will do the trick!
