### ISSUE TITLE
Re-create Hierarchical Plot in Paper

### ISSUE THREAD

**Issue by h1hui** [sqjin/CellChat#456]
Hello,

First of all I want to thank you guys for such great package.

But I can't seem to find sample code for the hierarchical plots you showed in your paper. Would you mind letting me know where you have the code?
![Screen Shot 2022-08-10 at 12 35 48 PM](https://user-images.githubusercontent.com/33336127/184013752-80b57de6-e530-4517-acc6-58f3b758e738.png)

Thanks,
Ashley

**Comment by sqjin** [comment]
@h1hui Can you point out the difference/feature compared to the one in the tutorial?

**Comment by h1hui** [comment]
So I am looking at these two tutorials right now, and the hierarchical plotting is not included somehow. Did I miss something?
https://htmlpreview.github.io/?https://github.com/sqjin/CellChat/blob/master/tutorial/CellChat-vignette.html#visualize-each-signaling-pathway-using-hierarchy-plot-circle-plot-or-chord-diagram
https://htmlpreview.github.io/?https://github.com/sqjin/CellChat/blob/master/tutorial/Comparison_analysis_of_multiple_datasets.html

**Comment by sqjin** [comment]
@h1hui 
`netVisual_aggregate(cellchat, signaling = pathways.show,  vertex.receiver = vertex.receiver)` this one should produce the hierarchical plotting.

**Comment by h1hui** [comment]
Thanks! I get it now.
