### ISSUE TITLE
Create a Ligand-Receptor DB without complexes and cofactors

### ISSUE THREAD

**Issue by earmingol** [sqjin/CellChat#459]
Hi @sqjin 

I'm wondering if it's possible to use CellChat with a list of LR pairs that does not contain complexes and cofactors (it's from another organism too). I tried passing empty matrices for ```CellChatDB$complex``` and ```CellChatDB$cofactor``` but I looks like that it doesn't work.

I would really appreciate your help!

**Comment by sqjin** [comment]
Hi Erick @earmingol ,

You should modify the related columns in CellChatDB$interaction. To avoid complex, then you should not have complexes in the columns of ligand and receptor. To avoid cofactors, you should set the columns of agonist, antagonist, co_A_receptor and  co_I_receptor to be empty. Please let me know if this does not work. 

Best,
Suoqin

**Comment by earmingol** [comment]
Thanks, @sqjin! It looks like it worked. So, as long I  keep empty those columns in CellChatDB$interaction, it doesn't matter what info I have in CellChatDB$complex and CellChatDB$cofactor?

**Comment by sqjin** [comment]
@earmingol Exactly!

**Comment by earmingol** [comment]
Thank you! It worked perfectly! :)
