### ISSUE TITLE
subscript out of bounds error in identifyOverExpressedGenes(cellchat)

### ISSUE THREAD

**Issue by wuzhigui** [sqjin/CellChat#46]
Hi @sqjin! Hope you're doing good. I'm having an issue and I was hoping you can help me

While running

cellchat <- identifyOverExpressedGenes(cellchat)

I get this error!
```
 |                                                  | 0 % ~calculating  Error in data1[x, ] : subscript out of bounds
```
Do you know what could it be?

Here is the complete code

```
DefaultAssay(seuratObj) <- 'integrated'
Idents(seuratObj) <- seuratObj$group
seuratObj$group=factor(seuratObj$group)


data.input <- seuratObj@assays$integrated@data # normalized data matrix


groups <- levels(seuratObj$group)
group <- groups[1]
subcells <- WhichCells(object = seuratObj, idents = group)
data.sub <- data.input[,subcells]

labels <- seuratObj$finalCluster[subcells]


identity <- data.frame(group = labels, row.names = names(labels)) # create a dataframe of the cell labels
cellchat <- createCellChat(data = data.sub)
cellchat <- addMeta(cellchat, meta = identity, meta.name = "labels")
cellchat <- setIdent(cellchat, ident.use = "labels") # set "labels" as default cell identity
levels(cellchat@idents) # show factor levels of the cell labels
#####################################################################################################

#####################################################################################################
CellChatDB <- CellChatDB.mouse # use CellChatDB.mouse if running on mouse data
showDatabaseCategory(CellChatDB)
# Show the structure of the database
dplyr::glimpse(CellChatDB$interaction)#选取列操作

CellChatDB.use <- subsetDB(CellChatDB, search = "Secreted Signaling") # use Secreted Signaling for cell-cell communication analysis
cellchat@DB <- CellChatDB.use # set the used database in the object# ####################
cellchat <- subsetData(cellchat) # subset the expression data of signaling genes for saving computation cost

#####################################保存cellchatDatabase######################



###CellChatDBfuture::plan("multiprocess", workers = 6) # do parallel
cellchat <- identifyOverExpressedGenes(cellchat)#不行
cellchat <- identifyOverExpressedInteractions(cellchat)#可以
cellchat <- projectData(cellchat, PPI.mouse)

cellchat <- computeCommunProb(cellchat)
cellchat <- computeCommunProbPathway(cellchat)
cellchat <- aggregateNet(cellchat)

```

**Comment by sqjin** [comment]
@wuzhigui You should use the log-transformed data from the `RNA` assay. The `seuratObj@assays$integrated@data` contains negative values.

**Comment by wuzhigui** [comment]
Hello ! thanks for your response ! Though  I have changed the assay and tried  to normalize the count with this comment `data.input=normalizeData(data.input)` ,  this error was still return .So ,I checked the source code and found that  lack of  `sketchData()`  ,maybe that is reason why i got this error ? And maybe R calculation is easy to overflow ?

**Comment by sqjin** [comment]
@wuzhigui Did you extract the data using `GetAssayData(seuratObj, assay = "RNA")`?  If yes, can you run each line of the identifyOverExpressedGenes to figure out the issue?  This error is not related with `sketchData` because it does not use it.

**Comment by wuzhigui** [comment]
Thanks for your response ! I have figured out this error ! But .I got another error .While running ` cellchat <- computeCommunProb(cellchat)`  ,the problem comes up 
``` Error in Prob[, , i] <- Pnull : 
  number of items to replace is not a multiple of replacement length  ```
I have no idea now .I am looking forward to your reply

**Comment by wuzhigui** [comment]
Thanks for your response ! I have figured out this error ! But .I got another error .While running cellchat <- computeCommunProb(cellchat) ,the problem comes up
`Error in Prob[, , i] <- Pnull : 
  number of items to replace is not a multiple of replacement length`
I have no idea now .I am looking forward to your reply !

**Comment by sqjin** [comment]
Hi @wuzhigui , I have no idea about this error. If you want, you can share me a subset the data for test.

**Comment by wuzhigui** [comment]
Thanks very much ! I have figured out this error ! Thanks again !

**Comment by lyuguol** [comment]
> Thanks very much ! I have figured out this error ! Thanks again !

@wuzhigui Hi, I encountered the same issue. Could you show me how you solved the problem?

Thank you in advance.

Best,

Guoliang

**Comment by akramdi** [comment]
Hello, 

I am also interested in the solution.
For me `identifyOverExpressedGenes` only worked when it's precedented by  `subsetData`, otherwise I get the same error:

```
> cellchat <- identifyOverExpressedGenes(cellchat)
Error in data.use[features, cell.use1, drop = FALSE] : 
  subscript out of bounds
```

Do we always have to subset before ?

Thanks for the help, 
Cheers

**Comment by sqjin** [comment]
@akramdi Yes, you need to run `subsetData` because it returns a slot called '@data.signaling' that will be used for all the analysis.  This function just extract the expression data of signaling genes that are used to infer the cell-cell communication network.  You can also use all genes by defining 'features' in this function.

**Comment by akramdi** [comment]
Got it, thank you for the quick reply !

**Comment by Kevinhokahey** [comment]
> Thanks for your response ! I have figured out this error ! But .I got another error .While running cellchat <- computeCommunProb(cellchat) ,the problem comes up `Error in Prob[, , i] <- Pnull : number of items to replace is not a multiple of replacement length` I have no idea now .I am looking forward to your reply !

Hi I met the same problem when I was testing the cellChat using seurat data pbmc3k. Could you tell me how to solve this problem. subscript out of bounds error in identifyOverExpressedGenes(cellchat)
