### ISSUE TITLE
Extract cells interact with another cell type via barcode

### ISSUE THREAD

**Issue by hiiiyilingzhang** [sqjin/CellChat#466]
Hi Prof. Jin,

Thanks for the nice package!
May I know if it is possible to extract cells that interact with another specific cell type? For example, extracting a subset of T cells that interact with fibroblast, based on cellchat@net$count or cellchat@net$weight. It would be great if you can provide some hints about how to correspond interaction info to the cell barcode. 

Bests!

**Comment by sqjin** [comment]
@hiiiyilingzhang I afraid you can not do it in this way. But you can pre-cluster T cells and re-run the cell cell communication analysis.

**Comment by hiiiyilingzhang** [comment]
Got it. Thanks for your reply~
