### ISSUE TITLE
Extract specific ligands/receptors and imputation

### ISSUE THREAD

**Issue by s849** [sqjin/CellChat#47]
Hello,

I have three questions;

1. Is there an easy way to extract all ligands/receptors for a pathway that is significant (other than looking at the bar chart for all pathways that show as significant)?
2. If I do not want to run the imputation step, is it possible to run this pipeline?

Thank you very much

**Comment by sqjin** [comment]
@s849 I just update and add some functions to address your two questions. Please re-install the package and try it. `netAnalysis_contribution` now return the L-R pairs.
