### ISSUE TITLE
Getting this plot

### ISSUE THREAD

**Issue by s849** [sqjin/CellChat#48]
Hi, 

I noticed the following plot being generated at the beginning of the program. Can we generate such a plot for the significant signaling pathways?
<img width="909" alt="Screen Shot 2020-09-13 at 3 50 05 PM" src="https://user-images.githubusercontent.com/47041278/93030656-823d8680-f5d9-11ea-81f3-7aa972618779.png">

**Comment by sqjin** [comment]
Hi @s849 , one way is to generate a temporal variable giving the subset of CellChatDB, and then you can plot such graph using our function. All you need is to generate a subset of CellChatDB$interaction. You can get the L-R pairs of a signaling pathway by ` pairLR <- searchPair(signaling = c("TGFb"), pairLR.use = CellChatDB$interaction, key = "pathway_name", matching.exact = T, pair.only = F)`
