### ISSUE TITLE
cellchat <- netClustering(cellchat, type = "structural")

### ISSUE THREAD

**Issue by LianaLiu** [sqjin/CellChat#49]
Good tools to analyze cell-cell communication,  and i have an error when i did
cellchat <- netClustering(cellchat, type = "structural"), and the error was that Error in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  :   'data'的种类必需为矢量，但现在是'NULL', but i have got all the results before,  and i don't know what went wrong. Can you help me ?Thank you very much.Best wishes.

**Comment by sqjin** [comment]
Hi @LianaLiu , NO worry about this 'NULL'. The merge function just merge the cell-cell communication information, and thus the 'data' slot is NULL.

**Comment by LianaLiu** [comment]
@sqjin Thank you very much!
