### ISSUE TITLE
 "subsetData" is not working properly.

### ISSUE THREAD

**Issue by ysuzuki1978** [sqjin/CellChat#495]
When I asked for data to run cellchat from the vendor who did the primary scRNA-seq analysis, they just gave me EXPRESSION and METADATA and said they would not support me, so I am trying to do the analysis on my own.

We believe that this is probably because the ”subsetData” is not working well and therefore object@data.signaling is not created in the correct format. The source code is as follows.

************************
meta <- read.table("All_metadata.txt", header = TRUE, sep = '\t', row.names = 1, stringsAsFactors = FALSE)
cell.use = rownames(meta)[meta$group == "G1"] # extract the cell names from disease data
exp_all <- read.table("All_exp_data.txt", header = TRUE, sep = '\t', row.names = 1, stringsAsFactors = FALSE)
exp_all <- t(exp_all)
seurat_object <- CreateSeuratObject(exp_all, mini.cells = 3, mini.genes = 200, project ="mouse")
data.input<-GetAssayData(seurat_object,assay = "RNA",slot = "data")
cellchat <- createCellChat(object = data.input)
cellchat <- createCellChat(object = data.input, group.by = "orig.ident")
cellchat <- addMeta(cellchat, meta = meta)
cellchat <- setIdent(cellchat, ident.use = "cell_type") 
levels(cellchat@idents)
groupSize <- as.numeric(table(cellchat@idents)) 
CellChatDB <- CellChatDB.mouse
showDatabaseCategory(CellChatDB)
dplyr::glimpse(CellChatDB$interaction)
CellChatDB.use <- subsetDB(CellChatDB, search = "Secreted Signaling") # use Secreted Signaling
cellchat@DB <- CellChatDB.use
cellchat <- subsetData(cellchat) # This step is necessary even if using the whole database
future::plan("multisession", workers = 4)
cellchat <- identifyOverExpressedGenes(cellchat)

****************
identifyOverExpressedGenes(cellchat)  error: 
  Please check `object@data.signaling` and ensure that you have run `subsetData` and that the data matrix `object@data.signaling` looks OK.

![スクリーンショット 2022-10-24 16 00 22](https://user-images.githubusercontent.com/42367694/197467271-ab6b1680-d2e3-43af-86cd-ed9c0ca9dee8.png)
![スクリーンショット 2022-10-24 16 00 10](https://user-images.githubusercontent.com/42367694/197467302-24a1ba74-41e3-4aae-aa90-54f6bd26e7bb.png)
![スクリーンショット 2022-10-24 17 06 07](https://user-images.githubusercontent.com/42367694/197478084-31bac121-fcc1-44e4-bfda-653256a69804.png)

**Comment by JohnChristin** [comment]
I'm also having this issue.

**Comment by sqjin** [comment]
@ysuzuki1978 Your input data is not correct. Rows should be genes and columns should be cells.

**Comment by sqjin** [comment]
@TheBorgy @JohnChristin  Can you share your cellchat object and your codes that can replicate the error? You can find my email in the Description file.

**Comment by ysuzuki1978** [comment]
@sqjin

Thank you for your comment.
As you point out, the rows and columns are incorrect.
We then solved the problem by adding the meta information with ADDMETA in the following script.


 
meta <- read.table("G2_metadata.txt", header = TRUE, sep = '\t', row.names = 1, stringsAsFactors = FALSE)
exp_all <- read.table("G2_exp_data.txt", sep = '\t', row.names = 1)
seurat_object <- CreateSeuratObject(exp_all, mini.cells = 3, mini.genes = 200, project ="mouse")
data.input<-GetAssayData(seurat_object,assay = "RNA",slot = "data")
cellchat <- createCellChat(object = data.input)
cellchat <- addMeta(cellchat, meta = meta)
cellchat <- setIdent(cellchat, ident.use = "cell_type")

**Comment by wdg118** [comment]
@sqjin I also get this problem. However my cellchat object has genes in rows and cells(samples) as columns. 

![image](https://user-images.githubusercontent.com/63317650/221827644-43c65ac1-7983-431a-9c99-b1441ccb5abf.png)
