### ISSUE TITLE
CellChat

### ISSUE THREAD

**Issue by MarcElosua** [sqjin/CellChat#496]
Hi @sqjin 

Thank you so much for such an amazing tool! I really enjoy using it and the documentation is incredible!

One quick question I have is if it is possible to filter out specific Sender - Receiver interactions once the CellChat object is already created? For example, removing the interactions between cell type A and B since they don't co-localize in space while keeping the interactions between A-C & B-C.

Thank you again so much for developing this tool!
Marc

**Comment by sqjin** [comment]
@MarcElosua Please check our new tutorial that can filter out the interactions beyond the interaction length.

**Comment by MarcElosua** [comment]
Hi @sqjin I will thank you!

In the meantime I did the following
```
Determine which clusters are close to each other
```{r}
tt <- with(se@meta.data, table(gem_id, sample_id))[]
im <- glue("X{colnames(tt)[tt[gem_param, ] > 0]}")
# position of each spot
pos <- se@images[[im]]@coordinates %>% select(row, col)
# Merge metadata and coordinates
pos_df <- merge(se@meta.data, pos, by = 0) %>%
  dplyr::select(hist_annotation, row, col)
```

Compute distances between all spots
```{r}
x <- dist(pos_df[, -1])
m <- as.matrix(x)
# Find the shortest distance between each set of clusters
an <- sort(unique(pos_df$hist_annotation))
dist_ls <- lapply(an, function(i) {
  idx_i <- which(pos_df$hist_annotation == i)
  
  min_dist <- lapply(an[an != i], function(ii) {
    idx_ii <- which(pos_df$hist_annotation == ii)
    min(m[idx_i, idx_ii])
  })
  names(min_dist) <- an[an != i]
  min_dist
})
names(dist_ls) <- an
```

Convert list to dataframe
```{r}
df <- purrr::map_df(dist_ls, dplyr::bind_rows) %>% data.frame(check.names = FALSE)
rownames(df) <- names(dist_ls)
dd <- df %>%
  tibble::rownames_to_column("region_1") %>%
  tidyr::pivot_longer(-region_1, names_to = "region_2", values_to = "distance") %>%
  dplyr::filter(distance < 1.5) %>%
  arrange(region_1, region_2)
```

Extract pairs to keep for non-autocrine signalling
```{r}
interact_ls <- lapply(unique(dd$region_1), function(i) {
  dd %>% dplyr::filter(region_1 == i) %>% pull(region_2)
})
names(interact_ls) <- unique(dd$region_1)
```

Remove all of those interactions that aren't "autocrine" within the tissue region or paracrine with neighboring regions
```{r}
table(CellChatDB.mouse$interaction$annotation)
physical_sign <- CellChatDB.mouse$interaction %>%
  dplyr::filter(annotation != "Secreted Signaling") %>%
  pull("interaction_name")
secreted_sign <- CellChatDB.mouse$interaction %>%
  dplyr::filter(annotation == "Secreted Signaling") %>%
  pull("interaction_name")
lr_vec <- dimnames(cellchat@net$prob)[[3]]
# Remove autocrine signaling predicted to be between different regions
for (i in intersect(lr_vec, physical_sign)) {  
  mask1 <- upper.tri(cellchat@net$prob[, , i]) | lower.tri(cellchat@net$prob[, , i])
  # Keep only autocrine signaling within each region
  cellchat@net$prob[, , i][mask1] <- 0
  # Assign P values to 1
  cellchat@net$pval[, , i][mask1] <- 1
}
# Keep secretory signaling within and between neighboring regions
# Iterate over all the secretory LR
for (i in intersect(lr_vec, secreted_sign)) {
  # Iterate over all the neighboring pairs
  for (ii in names(interact_ls)) {
    # Keep only autocrine signaling within each region
    mask <- ! names(cellchat@net$prob[ii, , i]) %in% c(interact_ls[[ii]], ii)
    cellchat@net$prob[ii, , i][mask] <- 0
    cellchat@net$pval[ii, , i][mask] <- 1
  }
}
```

Would it be a correct approach as well?

Thank you!

**Comment by MarcElosua** [comment]
Adding some comments that could be useful, when I ran CellChat in "sc" mode I then filtered interactions so that only Secreated Signaling could happen between different regions. For example: MHC-I which requires cell-cell interaction can only happen with signaling within a region while CXCL could happen between neighboring spots.

Does this make sense?

Thanks a lot for this great package!
Marc

**Comment by sqjin** [comment]
@MarcElosua Your codes look good I think. For cell-cell contact such as MHC-I, signaling could only happens between neighboring spots. For secreting signaling, it could diffuse to the nearby spots within certain distance.
