### ISSUE TITLE
Error in abs(igraph::E(g)$weight) :    non-numeric argument to mathematical function

### ISSUE THREAD

**Issue by top334** [sqjin/CellChat#503]
Hi, I met a problem when I draw the picture of  "netVisual_diffInteraction", error report is as below:
> netVisual_diffInteraction(cellchat, weight.scale = T,comparison = c(mygroup[1,1],mygroup[1,3]),title.name = paste0(mygroup[1,1],"_",mygroup[1,3],"_count"),measure = "count") 
Error in abs(igraph::E(g)$weight) : 
  non-numeric argument to mathematical function
> netVisual_diffInteraction(cellchat, weight.scale = T,comparison = c(mygroup[1,1],mygroup[1,3]),title.name = paste0(mygroup[1,1],"_",mygroup[1,3],"_weight"),measure = "weight") 
Error in abs(igraph::E(g)$weight) : 
  non-numeric argument to mathematical function
The detials of cellchat object are 4 groups data, and when I draw other 2 groups compare, it didn't have such error. However, it is important comparation which the 2 groups cannot draw the pciture, could anyone help me?

**Comment by laijen000** [comment]
hi @top334 , I am getting this same error, did you solve the issue?
