### ISSUE TITLE
error about netVisual_aggregate

### ISSUE THREAD

**Issue by zochzh** [sqjin/CellChat#51]
Hello, team CellChat.

I use pbmc3k data from [SeuratData](https://github.com/satijalab/seurat-data) to study your tutorial.

This was going well, but there was an error when I ran this function,

**netVisual_aggregate(cellchat, signaling = pathways.show,  vertex.receiver = vertex.receiver, vertex.size = groupSize)**

**Error in text.default(x, y, labels = labels, col = label.color, family = label.family,  :
  invalid font type**

This looks like a little bit of a conflict with the [igraph](https://github.com/igraph/igraph/issues/681)

I don't know how to solve it, so I come to ask for help.

Thank you for your excellent R package~

**Comment by sqjin** [comment]
Hi @zochzh , please check the previous issue #18  You need to install the 'Arial' font in R

**Comment by zochzh** [comment]
> Hi @zochzh , please check the previous issue #18 You need to install the 'Arial' font in R

Thank you very much for your answer!It was very helpful to me.
