### ISSUE TITLE
error about npattern

### ISSUE THREAD

**Issue by XudongGao66** [sqjin/CellChat#52]
hi，when i was runnning the code "cellchat <- identifyCommunicationPatterns(cellchat, pattern = "outgoing", k = nPatterns)", i got the result that Error in do.call(getGeneric("seed"), c(list(x = x, model = init, method = seed.method),  :  'what' must be a function or character string. Could you please tell me how to revise the code? Thank you a lot!

**Comment by sqjin** [comment]
Hi @XudongGao66 this is an issue related with the NMF package. Please see the installation suggestions in the README file.

**Comment by XudongGao66** [comment]
OK, the question has been solved by your suggestion. thank you! but i have one more question. How do I know which ligand and receptor mediate the interaction between the two types of cells?

**Comment by sqjin** [comment]
@XudongGao66 , Please check the previous issue #14  bubble plot is helpful.

**Comment by XudongGao66** [comment]
THANK YOU, MAN
