### ISSUE TITLE
mergeCellChat() Error in slot(object.list[[j]], slot.name[i]) :    no slot of name "images" for this object of class "CellChat"

### ISSUE THREAD

**Issue by jwiarda** [sqjin/CellChat#545]
Hello, I am trying to merge two cell chat objects derived from scRNA-seq (not spatial) data, but am running into the following error with the mergeCellChat() function: 

cellchat <- mergeCellChat(object.list, add.names = names(object.list))
Error in slot(object.list[[j]], slot.name[i]) : 
  no slot of name "images" for this object of class "CellChat"

My interpretation is that the "images" slot is only present for spatial data, which I am not using in this case. How might I be able to still merge these objects without image data? I am working with CellChat version (1.6.1).

All help appreciated!

**Comment by sqjin** [comment]
@jwiarda Can you update your cellchat object via `updateCellChat` and then try again?

**Comment by jwiarda** [comment]
@sqjin Magic...it worked! Thanks!

**Comment by EikoSAIJOU334** [comment]
I still have the same error and `updateCellChat` did't work. My data is also simple single cell transcriptome.
I use this useful cellchat tool from Singurality image and the version is CellChat_1.6.1.
How can I solve this problem?

**Comment by EikoSAIJOU334** [comment]
Thank you for replying to me, @sqjin !
My purpose was to regenerate older figures in the current environment.
Finally, I could complete it by using the older version of CellChat_1.1.3.
It has been solved. Anyway, thanks a lot.
