### ISSUE TITLE
netAnalysis_river error 

### ISSUE THREAD

**Issue by wuzhigui** [sqjin/CellChat#55]
Sorry to trouble you again .
When i  run this `netAnalysis_river(cellchat, pattern = "outgoing")`  
It will return
`Error in seq.default(1, nPatterns * 2, by = 2) : 
  wrong sign in 'by' argument`
The  same with above ,when i  run  `netAnalysis_river(cellchat, pattern = "incoming")` 
It will return
`Error in seq.default(2, nPatterns * 2, by = 2) : 
  wrong sign in 'by' argument`
Could you help me again ?Thanks  so much !

**Comment by QianZQ** [comment]
you need to run cellchat <- identifyCommunicationPatterns(cellchat, pattern = "incoming", k = nPatterns),than run netAnalysis_river

**Comment by sqjin** [comment]
Hi @wuzhigui , please do `library(ggalluvial)`.

**Comment by sqjin** [comment]
Hi @QianZQ , thanks for the help. But the main reason is somehow the package cannot automatically load `ggalluvial`.

**Comment by apal6** [comment]
Hi, 

It still gives the same error :
`library(ggalluvial)
> netAnalysis_river(cellchat_untreated, pattern = "outgoing")
Please make sure you have load `library(ggalluvial)` when running this function
Error in seq.default(1, nPatterns * 2, by = 2) : 
  wrong sign in 'by' argument`
