### ISSUE TITLE
Question about relabling the  cells and the cell number

### ISSUE THREAD

**Issue by lwlive** [sqjin/CellChat#550]
Cellchat  is really a useful tools with it's  short running time and beautiful graph.
there are two problems confused me: 
(1)I have  20  cell types including  NK_C1, NK_C2. For each cell types, I have downsampled 200 cells. Can I megre the  NK_C1 and NK_C2 to NK through changing the cellchat@idents information?

(2)After changing the labels,  the NK  cluster have 400 cells ,however, other celltypes only have 200 cells.Will the number of cells affect the interaction strength,making the interaction of NKs stronger than other celltypes?

Thanks!
Wei  Liu

**Comment by sqjin** [comment]
@lwlive The number of cells within each cell group does not affect the interaction strength.  
Yes, you can merge them together.

**Comment by lwlive** [comment]
Thanks  for you kind help!
