### ISSUE TITLE
How to draw Figure 3a and Figure 3b?

### ISSUE THREAD

**Issue by mengm5** [sqjin/CellChat#56]
Hi, 
Thank you for developing CellChat, it's a great work.
I'm interested in Figure 3a and Figure 3b called "Diffusion map" in your paper (show below), but I can't find the method to achieve it both in Methods and Vignettes (tutorials). Is it generated by CellChat or other tools? Could you please tell me how to draw it?
Thanks again!

![image](https://user-images.githubusercontent.com/31919733/94660793-c00c1000-0338-11eb-996e-cf0cab48f80e.png)

**Comment by sqjin** [comment]
Hi @mengm5 , sorry for the late reply. I used the function `RunDiffusion` from Seurat v2 to generate the diffusion map. But I think you can also use other similar function for diffusion map analysis from other package.

**Comment by mengm5** [comment]
Thank you @sqjin !
