### ISSUE TITLE
 identifyCommunicationPatterns error 

### ISSUE THREAD

**Issue by wuzhigui** [sqjin/CellChat#57]
When I run `cellchat <- identifyCommunicationPatterns(cellchat, pattern = "outgoing", k = nPatterns)`
It will return this error :
`Error in (new("standardGeneric", .Data = function (x)  : 
  unused arguments (model = list("NMFstd", 5, 0), method = "nndsvd")`
I hope someone can help me .please!

**Comment by wtj505531480** [comment]
I met the same error of data.use[, cell.use1, drop = FALSE] : subscript out of bounds, when i used  the function inidentifyOverExpressedGenes in cellchat, how did you slove this problem? thx

**Comment by xiangmingcai** [comment]
Hi, I met similar problem. It seems like a larger parameter "k" for identifyCommunicationPatterns was set. Try to use a k smaller than the number of pathway identified solved my problem.
