### ISSUE TITLE
Error in `.rowNamesDF<-`(x, value = value) : 'row.names'的长度不对

### ISSUE THREAD

**Issue by maqingyue** [sqjin/CellChat#572]
Hello, 
thank you very much for developing this software. I have encountered problems when applying. I hope to get your guidance. When I use mergeCellChat, I receive the following error:

Error in `.rowNamesDF<-`(x, value = value) : 'row.names'的长度不对
In addition: Warning messages:
1: In mergeCellChat(object.list, add.names = names(object.list), cell.prefix = TRUE) :
  Prefix cell names!
2: In mergeCellChat(object.list, add.names = names(object.list), cell.prefix = TRUE) :
  The cell barcodes in merged 'meta' is different from those in the used data matrix.
              We now simply assign the colnames in the data matrix to the rownames of merged 'mata'!

I don't know the reason for this error. I'm looking forward to your reply!

**Comment by pwmellors** [comment]
Have you been able to resolve this?  I have the same issue....

**Comment by maqingyue** [comment]
I observed my data (fig1) and the data in the tutorial (fig2), and found that there is no condition column in my data in object.list[[i]]@meta, so I added it to each sample. I don't know if this is correct, but I did not report any more mistakes.

cellchat_young@meta$Condition <- 'young'
cellchat_old@meta$Condition <- 'old'

fig1.my data
![image](https://user-images.githubusercontent.com/113956599/225483251-cf8e7a63-1380-47c7-b37c-5078ab70a5ef.png)

fig2. the data in the tutorial
![image](https://user-images.githubusercontent.com/113956599/225483300-e771970d-83f9-4a18-8cc2-ead2fe2f300c.png)

**Comment by pwmellors** [comment]
@maqingyue That worked! Can't thank you enough!
