### ISSUE TITLE
thresh parameter is useless in netVisual_bubble function

### ISSUE THREAD

**Issue by czlcaltech** [sqjin/CellChat#58]
Thanks for your inspiring package. However, when I try to lower the thresh parameter in netVisual_bubble function, the L-R relations plot in the figure don't seem to decrease, what happens? 

Here is my code. 

netVisual_bubble(cellchat, from = rep("M_CD55",25), to = levels(cellchat@idents), thresh = 1e-200) 
netVisual_bubble(cellchat, from = rep("M_CD55",25), to = levels(cellchat@idents), thresh = 1) 

Pictures generated by these two pieces of code are the same.

**Comment by sqjin** [comment]
Hi @czlcaltech , there should be some different in the list of significant L-R pairs. Can you check the calculated p-value? For example, object@net$pairwiseRank[[i]][[j]] will give the detailed information from cell group i to group j. You can also pull out the matrix via object@net$pval[i, , ,] to check the effect of the threshold.
