### ISSUE TITLE
Exposing implicit 'top' parameter in NetVisual_aggregate

### ISSUE THREAD

**Issue by Xethic** [sqjin/CellChat#59]
Hi,

I would like to make the following suggestion for an easy improvement of `netVisual_aggregate`:

Currently, the function hard-codes the `top` parameter for showing the top percentage of significant interactions equal to 1 when calling `netVisual_circle`: https://github.com/sqjin/CellChat/blob/70c7d0cee5520d1f0692894c723454ed57f3be8a/R/visualization.R#L233

It could be useful to expose this parameter the caller [of the above function](https://github.com/sqjin/CellChat/blob/70c7d0cee5520d1f0692894c723454ed57f3be8a/R/visualization.R#L183) as the layout can get complicated when the network is dense while it actually has many slightly significant interactions.

Thanks for this great package.

Best
Xethic

**Comment by sqjin** [comment]
Hi @Xethic , I just updated each visualization function to support the change of parameter `top`. You can reinstall the package and use it now. Thanks for the suggestions. 

Best,
Suoqin

**Comment by Xethic** [comment]
Hi @sqjin , Thanks for the quick resolve!

Best
Xethic
