### ISSUE TITLE
An error occurs when inferring structural similarity

### ISSUE THREAD

**Issue by BeyondMyPast228** [sqjin/CellChat#6]
Hi,
I'm sorry to bother you again. When I use CellChat to infer structural similarity, an error is generated. 
The code is : **cellchat <- netEmbedding(cellchat, type = "structural")**

The error is : **Error in py_call_impl(callable, dots$args, dots$keywords) : 
  SystemError: Bad call flags in PyCFunction_Call. METH_OLDARGS is no longer supported!**

I looked up the cause of this problem, which may be related to the python's version. Could you fixed it?
In additon, my python version is 3.6.

I'm looking forward to your reply.

**Comment by sqjin** [comment]
@BeyondMyPast228 This issue should be caused by improper installation of umap python package. It can be installed by ` pip install umap-learn`. Please check [here](https://github.com/lmcinnes/umap) if you encounter any issue.  Please make sure you can run umap in R after installation.

**Comment by BeyondMyPast228** [comment]
Thanks your answer. In your way, I finally solved the problem.
