### ISSUE TITLE
computeCommunProb

### ISSUE THREAD

**Issue by LianaLiu** [sqjin/CellChat#60]
hello, i followed your steps to run cellchat using seurat v3 data and when i use the function of computeCommunProb(cellchat <- computeCommunProb(cellchat)), there is an error:
Error in Prob[, , i] <- Pnull : 
  number of items to replace is not a multiple of replacement length
 Would you like to help me? Best wishes. Thank you very much.

**Comment by sqjin** [comment]
Hi @LianaLiu , can you show me how did you extract the data from Seurat v3 and use it as an input of CellChat? Please make sure the input data should not contain negative values.

**Comment by LianaLiu** [comment]
Thank you very much.  I used the 10X data and use normalized using 

 single_cell_analysis_2 <- log2(1 + sweep(single_cell_analysis, 2, median(colSums(single_cell_analysis))/colSums(single_cell_analysis), '*'))

 Then i got the pbmc data using the seurat and got the figure of different types of cells, then i extracted the specific stages cells of the data and saving rds.
Before using your cellchat, i read the rds and using 
data.input <- GetAssayData(pbmc, assay = "RNA", slot = "data")   to get the input data, and i am sure there were no NA values.  All the steps before computeCommunProb  can run successfully,  maybe i should using all the data and then run cellchat? Thank you very much! 
Best wished!

**Comment by LianaLiu** [comment]
thank you very much and i check the data and got the right results.
