### ISSUE TITLE
normalized data 

### ISSUE THREAD

**Issue by Imm123** [sqjin/CellChat#601]
Hi, 

I was wondering if I can normalized the data using log2(rawcounts +1). My input is bulk rna seq
I tried to use normalized data function but I got a matrix of all values = 0

**Comment by sqjin** [comment]
@Imm123 scRNA-seq data are usually normalized using ln(rawcounts +1). For bulk data , you can use this normalization method or quantile method.

**Comment by Imm123** [comment]
Thanks!
