### ISSUE TITLE
How to draw figure 5h ?

### ISSUE THREAD

**Issue by xzKristen** [sqjin/CellChat#61]
I want to know how to intergrate two dot plots  like figure 5h in your paper after merging two objects. What's more, whether  figure5e and figure5f (the two Hierarchy plots)  are obtained by merging  two datas or separately? And if it's an integrated analysis,can you tell me how it was done? Thank you so much!
![image](https://user-images.githubusercontent.com/59026235/95651282-e5a8ce80-0b1b-11eb-8718-92b622f30982.png)

![image](https://user-images.githubusercontent.com/59026235/95651293-fb1df880-0b1b-11eb-8b03-8e8ded790564.png)

**Comment by xzKristen** [comment]
Thank you for your answer. Sorry to bother you again,I wonder if there is a way to compare  communication signal strength among  cell groups  in a certain signaling pathway between two objects?

**Comment by sqjin** [comment]
Hi @xzKristen , rankNet provides an intuitive visualization of comparison of signaling strength between two objects. netVisual_bubble allows comparison of signaling strength among certain cell groups for one object. I can try to extend the bubble plot for multiple objects next week. If you have any other ideas for comparison, please let me know or you can make a contribution by sharing your codes on the github.
