### ISSUE TITLE
Install Package fail on linux

### ISSUE THREAD

**Issue by Aby-GGG** [sqjin/CellChat#62]
Trying to install cellchat.   I am getting an error on
![image](https://user-images.githubusercontent.com/58497378/95772998-3bce6b00-0cf0-11eb-8097-5f12749d6105.png)

Can you kindly help me with this problem? thank you very much!

**Comment by sqjin** [comment]
Hi @Aby-GGG , CellChat is neither on CRAN nor Bioconductor. So please follow the installation instruction in the README file. If you cannot use the install_github, you can check [here](https://kbroman.org/pkg_primer/pages/build.html) for more information on how to install R package from source.
