### ISSUE TITLE
Error in data.use[, cell.use1, drop = FALSE] : subscript out of bounds

### ISSUE THREAD

**Issue by wtj505531480** [sqjin/CellChat#64]
when i inputted seurat sctransform data into the cellchat function: identifyOverExpressedGenes(cellchat), it reported an error:Error in data.use[, cell.use1, drop = FALSE] : subscript out of bounds
how did you solve this problem? thx
input data like this
![image](https://user-images.githubusercontent.com/26889995/96139384-6824fa00-0f31-11eb-8aa5-e37e4ffbec5f.png)

**Comment by wtj505531480** [comment]
I saw the source code in identifyOverExpressedGenes function, the data in this function get from data.use <- object@data.signaling,  and i don't know where object@data.signaling come from,  i saw the codes before this step, it seems that there was not a function produced this slot, thx

**Comment by sqjin** [comment]
Hi @wtj505531480 , THE data.signaling is from the function `projectData`. For the issue you mentioned, I guess it is caused by the improper setting of cell labels. Can you show me your cell labels via `unique(cellchat@idents)`?

**Comment by wtj505531480** [comment]
Hi, @sqjin , the unique(cellchat@idents) like this:
![image](https://user-images.githubusercontent.com/26889995/96205241-a9042980-0f98-11eb-968d-5e969bc11ff7.png) 
and i cell the example codes in https://htmlpreview.github.io/?https://github.com/sqjin/CellChat/blob/master/vignettes/walkthrough_wound.html,the projectData function is under the identifyOverExpressedGenes function

**Comment by sqjin** [comment]
Hi @wtj505531480 , sorry, it comes from the subsetData function. Can you run the source code of the function line by line, which will help you figure out the specific reason. Particular, you can check if cell.use is empty when running certain step?

**Comment by wtj505531480** [comment]
Hi,@sqjin I run the example data and i tried to run the source code step by step, thx
