### ISSUE TITLE
Having problem generating image

### ISSUE THREAD

**Issue by ruohuchengxhe** [sqjin/CellChat#65]
Hi,
I was trying to draw the heatmap for the signaling role, however, the plot window was blank. I was able to do this before but not today. And because using ggsave() won't save this plot. So now I can't see if it was generated or not. Would you have any advice?
Thanks!

**Comment by sqjin** [comment]
Hi @ruohuchengxhe , the heatmap is created using ComplexHeatmap package and thus it will not return the ggplot object. Please just use the pdf()..dev.off() for saving figures.
