### ISSUE TITLE
save plot occurred error using pdf()...dev.off() on netVisual_aggregate

### ISSUE THREAD

**Issue by honghh2018** [sqjin/CellChat#69]
Hi @sqjin ,
     Thanks for the great tools,
      There are problem when saving the plot netVisual_aggregate using pdf()...dev.off base function,
       The error showing the wrong font type ,detail showing below,
       Error in text.default(x, y, labels = labels, col = label.color, family = label.family,  : 
       Font type error.
       The pdf showing no word on it like below,
      
![image](https://user-images.githubusercontent.com/41668708/97802020-9158c080-1c7b-11eb-9077-0d1907472e54.png)
       I try to using ggsave to save the plot generated by netVisual_aggregate however, it get empty .
       So how can i solved this problem ?
        Any advice would be appreciated.
        Best,

**Comment by sqjin** [comment]
Hi @honghh2018 , can you please check the previous issue #51  on the font issue? I also suggest to save the figure using `svglite` instead of 'pdf' because I found pdf cannot be edited in illustrator. You can also save it as png file for quick exploration.

**Comment by honghh2018** [comment]
Thanks @sqjin,
     It works, The netVisul plot can be save using svglite but pdf.
 Thanks again.

**Comment by honghh2018** [comment]
But i got another question when runing the cellchat in R script no Rstudio.
    the error occurred when it run on the netVisual_aggregate plot,  the error showing below.
![image](https://user-images.githubusercontent.com/41668708/99666948-a40a2c80-2aa6-11eb-8c13-0e570a8e6e80.png).
    Can you kindly help me to solve this issue? Thanks.
    the all code showing below,
    cellchat <- computeCommunProbPathway(cellchat)
cellchat <- aggregateNet(cellchat)
cellchat <- netAnalysis_signalingRole(cellchat, slot.name = "netP")
for(j in cellchat@netP$pathways){
  vertex.receiver = seq(1,8)
  pathways.show <- j
  svglite(paste0(j,'_network_line.svg'),width = 8,heigh = 8)
  netVisual_aggregate(cellchat, signaling = pathways.show,  vertex.receiver = vertex.receiver, vertex.size = groupSize)
  dev.off()
  svglite(paste0(j,'_networks_circle.svg'),width = 8,heigh = 8)
  netVisual_aggregate(cellchat, signaling = pathways.show, layout = "circle", vertex.size = groupSize,pt.title=20,vertex.label.cex = 1.7)
  dev.off()
  svglite(paste0(j,'_networks_contibution.svg'),width = 8,heigh = 8)
  netAnalysis_contribution(cellchat, signaling = pathways.show)
  dev.off()
  svglite(paste0(j,'_networks_signalingRole.svg'),width = 9,heigh = 8)
  netVisual_signalingRole(cellchat, signaling = pathways.show, width = 12, height = 2.5, font.size = 10)
  dev.off()
}

R version 3.6.0 (2019-04-26) -- "Planting of a Tree"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-redhat-linux-gnu (64-bit)

> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=zh_CN.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=zh_CN.UTF-8        LC_COLLATE=zh_CN.UTF-8    
 [5] LC_MONETARY=zh_CN.UTF-8    LC_MESSAGES=zh_CN.UTF-8   
 [7] LC_PAPER=zh_CN.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=zh_CN.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.0

**Comment by sqjin** [comment]
Hi @honghh2018 , I am sorry I missed your second question. Have you addressed it?  I always run it in Rstudio and thus I suggest you can also try it.
