### ISSUE TITLE
A problem when using netVisual_bubble

### ISSUE THREAD

**Issue by chuiqin** [sqjin/CellChat#70]
Thanks of your tools.It's easy to explore and show my data.
But when I try to run my code follow:
`netVisual_bubble(cellchat2, from = c(1,1,1,1), 
                 to = c(1,2,3,4),
                 bidirection = T,
                 color.heatmap = colorRampPalette(c("black", "blue", "yellow", "red"), alpha=TRUE)(n=399),
                 pairLR.use0 = "CXCL12 - ACKR3")`
the error occur follow: 
`Error in pairLR.use0[rowSums(is.na(prob)) != ncol(prob), , drop = FALSE] : incorrect number of dimensions`
Then ,I delete the parameter "pairLR.use0 " and the code are able to run successfully .
But it seems to show all the significant interactions in the picture.
I want to present some special ligand receptor pairs in the bubble plot instead of all pairs.
Can you help me solve with this probelm?Thanks!

**Comment by sqjin** [comment]
Hi @chuiqin, your input format of pairLR.use0 is not correct. You can run `pairLR <- searchPair(signaling = "CXCL",  key = "pathway_name", matching.exact = T, pair.only = T)` to check the format of pairLR

**Comment by akui113** [comment]
hello @sqjin 
I want to Subset the ligand-receptor interactions for given specific signals in bubble format. However, i also get the same Error like chuiqin. Then, i tested your suggestion "pairLR <- searchPair(signaling = c("WNT","BMP"), key = "pathway_name", matching.exact = T, pair.only = T)" and get the error as bellow:
Error in get(name, envir = env, inherits = FALSE) : 
  Identified global objects via static code inspection (function (x); {; if (!matching.exact) {; index <- grep(signaling[x], pairLR.use[[key]]); }; else {; ...; "\n")); }; }). argument "pairLR.use" is missing, with no default

Then, we added pairLR.use="WNT3A - (FZD5+LRP5)" :
pairLR <- searchPair(signaling = c("WNT","BMP"), key = "pathway_name",pairLR.use="WNT3A - (FZD5+LRP5)", matching.exact = T, pair.only = T)
and get the error :
Error in pairLR.use[[key]] : subscript out of bounds
could you help us solve this problem?
Thanks!

**Comment by sqjin** [comment]
Hi @akui113 @chuiqin  , both of you use an incorrect format of the variable `pairLR.use`. You cannot use pairLR.use="WNT3A - (FZD5+LRP5)".  It should be pairLR.use <- searchPair(signaling = c("WNT","BMP"), key = "pathway_name", matching.exact = T, pair.only = T). Then you should see how does the `pairLR.use` looks like now, which is a data.frame and contains one column named `ligand` and another column named `receptor`.

**Comment by akui113** [comment]
hello @sqjin I'm so sorry to disturb you again, I tried "pairLR.use <- searchPair(signaling = c("WNT","BMP"), key = "pathway_name", matching.exact = T, pair.only = T)" and get the error as follow:

Error in get(name, envir = env, inherits = FALSE) : 
  Identified global objects via static code inspection (function (x); {; if (!matching.exact) {; index <- grep(signaling[x], pairLR.use[[key]]); }; else {; ...; "\n")); }; }). argument "pairLR.use" is missing, with no default

Did I make a mistake with some parameters in searchPair function?

**Comment by sqjin** [comment]
Hi @akui113 Try `pairLR <- searchPair(signaling = c("WNT","BMP"), pairLR.use = object@LR$LRsig, key = "pathway_name", matching.exact = T, pair.only = T)`

**Comment by akui113** [comment]
hello @sqjin very exciting, it's working, thank you very much!
