### ISSUE TITLE
the error in calculating interaction probability

### ISSUE THREAD

**Issue by ChickenWangSY** [sqjin/CellChat#71]
thanks for your tools but I found some strange phenomomen in calculating interaction probability.
here is my data. 
```
data(cmt.right.cellchat)
```
firstly, I found that MIF signaling pathway was significantly active between cluster 2 and cluster 6 in mydata.
![image](https://user-images.githubusercontent.com/42604587/98645924-98fc2180-236d-11eb-8a05-1d104869e964.png)
but when I check expression of MIF, the ligand of MIF signaling pathway, I found that it hardly didn't express. there was just one cells expressed in 251 cells.
```
table(cmt.right.cellchat@data.signaling["MIF",which(cmt.right.cellchat@meta$labels == "cmt.right 2")])
               0 1.67386810881394 
             250                1 
```
![image](https://user-images.githubusercontent.com/42604587/98646411-4f600680-236e-11eb-97f7-068f378ef466.png)
morethan, I checked `data_signaling` in my data and found that MIF was one of 450 genes filtered by DEG testing. whatever, I read your preprint manuscript. the part `Calculation of ensemble average expression` said that a genes' average expression was calculated by three quantile. I just thought that MIF average expression in cluster 2 was exactly 0 and there shouldn't be interaction about MIF signaling pathway.

I was really confused. is there any advice?

regards

**Comment by sqjin** [comment]
Hi @ChickenWangSY , first, I think there is a bug for the DEG testing, where I can add in another filter to remove such genes. Second, can you check the the expression in cellchat@data.project that is used for inferring cell-cell communication? The `data.project` is returned from the function `projectData` that is used to enhance the expression through network propagation. This step is useful when your data is obtained in a low sequencing depth. In another word, you can skip this step if you think your data is in a good quality. Third, you may can also set population.size = FALSE if analyzing sorted single-cell transcriptomes. Please check the documentation of the function computeCommunProb for more details.
