### ISSUE TITLE
adding pathway information for L-R pairs not present in cellchatDB

### ISSUE THREAD

**Issue by jv-20** [sqjin/CellChat#72]
Hi @sqjin 

A quick question. I am working on human database. I created a database combining human LR pairs from celltalk + cellchatDB. This adds additional LR pairs from celltalk database. 

I am looking to add pathway information to the interaction input file for those additional LR pairs that are added from celltalk  and not present in cellchat,

Is it ok to use ligand names as pathway names? Would there be any issues with that? I just wanted to check with you and get your advice.  

Thank you

**Comment by sqjin** [comment]
Hi @jv-20 , yes, you can use any pathway name if you want. I think there should be no issue.

**Comment by jv-20** [comment]
Thank you @sqjin
