### ISSUE TITLE
Warning message when using future::plan("multiprocess")

### ISSUE THREAD

**Issue by jv-20** [sqjin/CellChat#74]
Hi @sqjin 

When I run cellchat with this code `future::plan("multiprocess",workers = 4) ` I received the following error message four times. Could you please advise? 

`Warning messages:
1: UNRELIABLE VALUE: Future (‘future_sapply-1’) unexpectedly generated random numbers without specifying argument '[future.]seed'. There is a risk that those random numbers are not statistically sound and the overall results might be invalid. To fix this, specify argument '[future.]seed', e.g. 'seed=TRUE'. This ensures that proper, parallel-safe random numbers are produced via the L'Ecuyer-CMRG method. To disable this check, use [future].seed=NULL, or set option 'future.rng.onMisuse' to "ignore". `

Thank you

**Comment by sqjin** [comment]
Hi @jv-20 , no worries! It is just a warning message from the `future` package.

**Comment by jv-20** [comment]
Thanks @sqjin
