### ISSUE TITLE
Error in runUMAP(Similarity, min.dist = 0.3, n.neighbors = k) :    Cannot find UMAP, please install through pip (e.g. pip install umap-learn or reticulate::py_install(packages = 'umap-learn'))

### ISSUE THREAD

**Issue by hahia** [sqjin/CellChat#75]
Hello, when I run
`cellchat <- netEmbedding(cellchat, type = "functional")`

There has error in runUMAP, but I had install the umap-learn use pip or use conda
How to solve this?

**Comment by hahia** [comment]
> Hello, when I run
> `cellchat <- netEmbedding(cellchat, type = "functional")`
> 
> There has error in runUMAP, but I had install the umap-learn use pip or use conda
> How to solve this?

I solve this, thanks.

**Comment by daisyyr** [comment]
> > Hello, when I run
> > `cellchat <- netEmbedding(cellchat, type = "functional")`
> > There has error in runUMAP, but I had install the umap-learn use pip or use conda
> > How to solve this?
> 
> I solve this, thanks.

Could you please tell me how you solve this? Many thanks!

**Comment by daisyyr** [comment]
> > > Hello, when I run
> > > `cellchat <- netEmbedding(cellchat, type = "functional")`
> > > There has error in runUMAP, but I had install the umap-learn use pip or use conda
> > > How to solve this?
> > 
> > 
> > I solve this, thanks.
> 
> Could you please tell me how you solve this? Many thanks!

It seems that restarting R environment after installing umap-learn could work!
