### ISSUE TITLE
Failed to install cellchat in r4.0.3 rtools40 win10

### ISSUE THREAD

**Issue by tn00992786** [sqjin/CellChat#76]
Dear Dr. Jin, 

I encountered the problem as title, and try to fix follow issue. 

Error: Failed to install 'CellChat' from GitHub:
  (converted from warning) installation of package ‘C:/Users/ADMINI~1/AppData/Local/Temp/RtmpuQUcMz/file3aa83d5f7dde/CellChat_0.0.2.tar.gz’ had non-zero exit status

Could you provide any solution to work it out?

**Comment by sqjin** [comment]
Hi @tn00992786 , you might can check the previous issue #5 to see if it is related with the Rcpp.

**Comment by tn00992786** [comment]
package ‘Rcpp’ successfully unpacked and MD5 sums checked

Error: Failed to install 'CellChat' from GitHub:
  (converted from warning) installation of package ‘C:/Users/ADMINI~1/AppData/Local/Temp/RtmpeU1w0h/file2a6c4ed13fab/CellChat_0.0.2.tar.gz’ had non-zero exit status
