### ISSUE TITLE
Error: $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by hahia** [sqjin/CellChat#78]
Data: tutorial skin wound data
Run
```
cellchat <- computeNetSimilarity(cellchat, type = "functional", thresh = 0.25)
cellchat <- netEmbedding(cellchat, type = "functional")
cellchat <- netClustering(cellchat, type = "functional", k = 4)
rankSimilarity(cellchat, type = "functional")
```
error
**Error: $ operator is invalid for atomic vectors**

**Comment by sqjin** [comment]
Hi @hahia , `rankSimilarity` only works for multiple dataset analysis.

**Comment by hahia** [comment]
> Hi @hahia , `rankSimilarity` only works for multiple dataset analysis.
Thank you!
