### ISSUE TITLE
Are there have vignettes about use latent trajectory to do communication analysis?

### ISSUE THREAD

**Issue by hahia** [sqjin/CellChat#79]
Are there have vignettes about use latent trajectory to do communication analysis?

**Comment by sqjin** [comment]
Hi @hahia , not yet! If you the cell clusters are also well grouped in the trajectory space in your data, you can also directly use the clustering results to perform the cell-cell communication analysis and then interpret the data based on the pseudotemporal ordering.

**Comment by hahia** [comment]
> Hi @hahia , not yet! If you the cell clusters are also well grouped in the trajectory space in your data, you can also directly use the clustering results to perform the cell-cell communication analysis and then interpret the data based on the pseudotemporal ordering.

ok, thanks for your reply.
