### ISSUE TITLE
A problem with running netAnalysis_river() and netAnalysis_dot() function

### ISSUE THREAD

**Issue by yangmean** [sqjin/CellChat#80]
Hi,
Thanks for your greatful tool.
I have a problem when I use the netAnalysis_river() and netAnalysis_dot() function to get the plot.
netAnalysis_river(U95.cellchat, pattern = "outgoing")
Error in seq.default(1, nPatterns * 2, by = 2) : wrong sign in 'by' argument

netAnalysis_dot(U95.cellchat, pattern = "outgoing")
Error in fix.by(by.x, x) : 'by' must specify a uniquely valid column

![image](https://user-images.githubusercontent.com/23022069/99477290-2b637d00-298d-11eb-9cbf-d70988ce7d29.png)
![image](https://user-images.githubusercontent.com/23022069/99477261-1b4b9d80-298d-11eb-9501-33b5692854ac.png)

Could you help me figure it out? Thank you very much!

**Comment by yangmean** [comment]
I have done library(ggalluvial), but also get the same error.
![image](https://user-images.githubusercontent.com/23022069/99491319-805fbd00-29a6-11eb-93af-387365f979d1.png)

**Comment by sqjin** [comment]
Hi @yangmean , it looks like there is an issue of the inferred patterns. Please check if your pattern looks normal: `  res.pattern <- methods::slot(object,  "netP")$pattern[[pattern]]
  data1 = res.pattern$pattern$cell
  data2 = res.pattern$pattern$signaling`

Otherwise, please debug the code in the function `netAnalysis_river` line by line.

**Comment by yangmean** [comment]
Hi, @sqjin, I got NULL result after executed `res.pattern <- methods::slot(object, "netP")$pattern[[pattern]]`. So I have found that I mistake the secreting patterns. I run the function `identifyCommunicationPatterns` with pattern "incoming", but run the `netAnalysis` function with "outgoing".. Thanks for your help!
