### ISSUE TITLE
A problem with netVisual_aggregate() and netVisual_aggregate function

### ISSUE THREAD

**Issue by weichen123hahah** [sqjin/CellChat#81]
Excuse me, can you tell me what the width of edge means and what calculation is used to obtain.Is the number of significant ligand and receptor pairs?
![image](https://user-images.githubusercontent.com/38218230/99548761-f3435500-29f3-11eb-84f0-b0b292264219.png)
![image](https://user-images.githubusercontent.com/38218230/99549150-50d7a180-29f4-11eb-94a1-f62e6daa95f0.png)

**Comment by sqjin** [comment]
Hi @weichen123hahah , edge width represents the communication probability (i.e., interaction strength).

**Comment by yangmean** [comment]
> Hi @weichen123hahah , edge width represents the communication probability (i.e., interaction strength).
Could you please tell me how to get the value of communication probability (i.e., interaction strength) in the cellchat object? Thanks~

**Comment by yangmean** [comment]
Hi, @sqjin , could you please tell me how to get the value of communication probability (i.e., interaction strength) in the cellchat object?

**Comment by sqjin** [comment]
Hi @yangmean , you can access the data of signaling pathway via cellchat@netP$prob and the data of L-R pair via cellchat@net$prob
