### ISSUE TITLE
How to use all 3 "Secreted Signaling" "Cell-Cell contact" and "ECM-Receptor" in CellChatDB.use?

### ISSUE THREAD

**Issue by EAC-T** [sqjin/CellChat#82]
Hi everyone,
I'm so happy to have found this amazing package!
I'm interested in exploring all 3 different types of signaling between my cells. 
Is there a way I can do all 3 at the same time? Do I need to subset the DB before adding it to the object?

Thank you a lot!

**Comment by sqjin** [comment]
Hi @EAC-T , you can simply skip the `subsetDB` step and set `CellChatDB.use <- CellChatDB`.
