### ISSUE TITLE
rankNet(cellchat, mode = "comparison") Interpretation and Stats

### ISSUE THREAD

**Issue by EAC-T** [sqjin/CellChat#83]
Hi everyone,

I have 2 Seurat objects, I followed the tutorial and I got to the 
rankNet(cellchat, mode = "comparison")
On the y-axis of the figure, the pathways are labeled either in red, blue or black. the red belongs to KO and the blue toCTL in my case. I'm wondering what is the meaning of the labels on the y-axis? is it associated with some significance-value from a statistical test? The one written in red are upregulated in the red group, written in black are the same between groups and blue are upregulated in the blue group? is there a p-value that I can find or use? 

Thank you

**Comment by sqjin** [comment]
Hi @EAC-T , the one colored in red are upregulated in the red group, written in black are the same between groups and blue are upregulated in the blue group. It is determined based on the relative information flow of each pathway between two conditions. The information flow is defined by summarizing the communication probability in the inferred signaling network. You can access the data by setting the parameter `return.data = TRUE`.  It is a good suggestion to also associate them with certain statistical test. I will give a try.

**Comment by EAC-T** [comment]
Hi @sqjin , thank you for taking the time to explain. Yes please, statistics are very important when it comes to publishing. I hope you give it a try!

**Comment by EAC-T** [comment]
Hello sqjin, I was just wondering if you have any updates on the statistics? 
Thank you a lot
