### ISSUE TITLE
computeCommunProb source code with computeExpr_complex not found

### ISSUE THREAD

**Issue by Wulin-Tan** [sqjin/CellChat#84]
Hi, Jin

CellChat is a great tool to my project.

when I tried to run computeComunProb
> cellchat <- computeCommunProb(cellchat)  
Error in Prob[, , i] <- Pnull : 
  number of items to replace is not a multiple of replacement length

then I tried the source code line by line, but got this error
> data.complex <- computeExpr_complex(complex_input, data.use, complex)
Error in computeExpr_complex(complex_input, data.use, complex) : 
  could not find function "computeExpr_complex"

any suggestions?

thank you.

**Comment by onegoodguy-tnt** [comment]
i face the same problem. Is there any solution?
