### ISSUE TITLE
install cellchat problem

### ISSUE THREAD

**Issue by ChipsXu** [sqjin/CellChat#85]
Hello, I tried to install this package with R studio on windows7, but failed with the following message:
##########
Error: package or namespace load failed for 'CellChat' in namespaceExport(ns, exports):
 undefined exports: netVisual_aggregate
installation of package ‘C:/Users/ADMINI~1/AppData/Local/Temp/RtmpKuEYDK/file12347f7f6868/CellChat_0.0.2.tar.gz’ had non-zero exit status
##########
my R version is 4.0.3.

In addition, I have tried to install it in the sever (ubuntu 1604), R studio sever, I also failed. It said:
########
Error: package or namespace load failed for ‘CellChat’ in namespaceExport(ns, exports):
 undefined exports: netVisual_aggregate
Error: loading failed
Execution halted
ERROR: loading failed

Error: Failed to install 'CellChat' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpMSGmD0/file1b3672f176cb6/CellChat_0.0.2.tar.gz’ had non-zero exit status
In addition: Warning message:
In fun(libname, pkgname) : couldn't connect to display ":0"
########

So how can I solved this problem ?
Any advice would be appreciated.
Best,

**Comment by ltosti** [comment]
Hi there,

I got the same error 10 minutes ago.

**Comment by sqjin** [comment]
Hi @ltosti and @ChipsXu , I am very sorry that I deleted the netVisual_aggregate function by mistake when updating the netVisual function in last commit. I just corrected it and please re-install the package. Thanks!
