### ISSUE TITLE
Heatmap - outgoing communication pattern

### ISSUE THREAD

**Issue by ltosti** [sqjin/CellChat#86]
In the vignette [here](https://htmlpreview.github.io/?https://github.com/sqjin/CellChat/blob/master/vignettes/example_streamline_for_quick_analysis_and_exploration.html) in the paragraphs "Identify outgoing communication pattern of secreting cells" and "Identify incoming communication pattern of target cells" you save a heatmap with the following command:

```
pdf(file = paste0("CommunicationPatterns_receiver_heatmap.pdf"))
cellchat <- identifyCommunicationPatterns(cellchat, pattern = "incoming", k = nPatterns)
dev.off()
```

but is there a way to output the heatmap without the need to generate the pdf output? Indeed by doing

```cellchat <- identifyCommunicationPatterns(cellchat, pattern = "incoming", k = nPatterns)``` 

you get just a new Cellchat object, but not the supposed heatmap.

**Comment by sqjin** [comment]
Hi @ltosti , if you just do `cellchat <- identifyCommunicationPatterns(cellchat, pattern = "incoming", k = nPatterns)`, a heatmap should be generated in the RStudio window.  In addition, the data matrix for generating the heatmap is also stored in `object,@netP$pattern[["incoming"]]`.

**Comment by ltosti** [comment]
Thank you, @sqjin , I think my problem was that I was using CellChat in a Jupyter Notebook - but the pdf output is indeed generated.
