### ISSUE TITLE
netVisual_bubble Error: Breaks and labels are different lengths

### ISSUE THREAD

**Issue by akui113** [sqjin/CellChat#87]
Hi, @sqjin 
I encountered this problem for the first time and run other data normally, but just only one data get such an error as follows.
netVisual_bubble(cellchat, from = c("A"), to = c("B"))
Error: Breaks and labels are different lengths
Run `rlang::last_error()` to see where the error occurred.

but I still unknow where the error occurred, could you help me.
Thank you very much!

**Comment by sqjin** [comment]
Hi @akui113 , I am sorry I have no idea on it. Can you run the source codes line by line to figure out the reason? Thanks!

**Comment by akui113** [comment]
OK, @sqjin, Thank you for your generous help!
