### ISSUE TITLE
Rstudio break down when run netAnalysis_river command

### ISSUE THREAD

**Issue by snow55** [sqjin/CellChat#88]
Hello, when I run netAnalysis_river, my Rstudio would break down without any error information, just like the below image. 
I have load ggalluvial, and have done identifyCommunicationPatterns.
Can you help me ? Thank you very much!
<img width="276" alt="netAnalysis_river question" src="https://user-images.githubusercontent.com/39936155/101307166-cca16d00-3881-11eb-804d-2d7ca40bfab1.png">

**Comment by sqjin** [comment]
Hi @snow55 , I am sorry I have no idea on this. This is the first time I hear about this issue. Can you please run the source codes line by line to figure out the reason?
