### ISSUE TITLE
CellAtlas Explorer

### ISSUE THREAD

**Issue by ltosti** [sqjin/CellChat#89]
Hi @sqjin ,

Are you planning to release a version of CellChat Explorer to enable users to upload and explore locally their own datasets?

**Comment by sqjin** [comment]
@ltosti Yes, we are actually working on it now and will add a function to enable interactive exploration. It should be done within next two weeks.

**Comment by ltosti** [comment]
Hello @sqjin 

Any news on this? :)

**Comment by sqjin** [comment]
Hi @ltosti , thanks for your interest. I am so sorry that my collaborator, who was helping on developing a CellChat app, was very busy for a while.  He has done some work, but need additional two days' work.  Thanks for your patience.

**Comment by sqjin** [comment]
Hi @ltosti Thanks for your patience.  Our CellChat shiny app is finally out now. You can check it here: https://github.com/sqjin/CellChatShiny

Our CellChat paper is also officially published today: https://www.nature.com/articles/s41467-021-21246-9
