### ISSUE TITLE
How to use the "ECM-Receptor"    and   "Cell-Cell Contact" in the database?

### ISSUE THREAD

**Issue by guokai8** [sqjin/CellChat#9]
Hi @sqjin, I just wonder how to use the "ECM-Receptor" and "Cell-Cell Contact" annotation in the package? Could you give a quick example of these two part?
Thanks!

**Comment by sqjin** [comment]
Hi @guokai8, you can use all the interactions by `CellChatDB.use = CellChatDB.mouse` , and only ECM-Receptor interactions by `CellChatDB.use <- subsetDB(CellChatDB.mouse, search = "ECM-Receptor", key = "annotation")`. Our tutorial also shows the example for using Secreted Signaling.
