### ISSUE TITLE
missing value where TRUE/FALSE in netVisual_aggregate

### ISSUE THREAD

**Issue by gt7901b** [sqjin/CellChat#90]
Hi, Suoqin:

Thanks for developing this nice tool!

I was trying out this command 

pathways.show <- c("TGFb") 
vertex.receiver = seq(1,9) # a numeric vector
netVisual_aggregate(cellchat, signaling = pathways.show,  vertex.receiver = vertex.receiver, vertex.size = groupSize)

but go the following error. What might be the cause?

thanks for your time

Error in if (vr[1] == vr[2]) {: missing value where TRUE/FALSE needed
Traceback:

1. netVisual_aggregate(cellchat, signaling = pathways.show, vertex.receiver = vertex.receiver, 
 .     vertex.size = groupSize)
2. netVisual_hierarchy1(prob.sum, vertex.receiver = vertex.receiver, 
 .     top = top, color.use = color.use, vertex.size = vertex.size, 
 .     signaling.name = NULL, vertex.label.cex = vertex.label.cex)
3. plot(g, edge.curved = edge.curved, layout = coords_scale, margin = margin, 
 .     rescale = T, vertex.shape = "fcircle", vertex.frame.width = c(rep(1, 
 .         m1), rep(2, nrow(net3) - m1)), vertex.label.degree = label.locs, 
 .     vertex.label.dist = label.dist, vertex.label.family = "Arial")
4. plot.igraph(g, edge.curved = edge.curved, layout = coords_scale, 
 .     margin = margin, rescale = T, vertex.shape = "fcircle", vertex.frame.width = c(rep(1, 
 .         m1), rep(2, nrow(net3) - m1)), vertex.label.degree = label.locs, 
 .     vertex.label.dist = label.dist, vertex.label.family = "Arial")
5. norm_coords(layout, -1, 1, -1, 1)
6. .layout.norm.col(layout[, 2], ymin, ymax)

**Comment by sqjin** [comment]
Hi @gt7901b , are you using the example wound data?

**Comment by gt7901b** [comment]
No.I was using my own data.
I tried use example wound data today with walk through example. It was fine with the netVisual_aggregate command.
but when I did 
nPatterns = 5 
cellchat <- identifyCommunicationPatterns(cellchat, pattern = "outgoing", k = nPatterns)

I got this error.

Error in do.call(getGeneric("seed"), c(list(x = x, model = init, method = seed.method), : 'what' must be a function or character string
Traceback:

1. identifyCommunicationPatterns(cellchat, pattern = "outgoing", 
 .     k = nPatterns)
2. NMF::nmf(data, rank = k, method = "lee", seed = "nndsvd")
3. NMF::nmf(data, rank = k, method = "lee", seed = "nndsvd")
4. nmf(x, rank, method = strategy, ...)
5. nmf(x, rank, method = strategy, ...)
6. .local(x, rank, method, ...)
7. do.call(getGeneric("seed"), c(list(x = x, model = init, method = seed.method), 
 .     parameters.seed))

**Comment by sqjin** [comment]
Hi @gt7901b , you can plot Fig. 5G using `rankNet` function. You can check the tutorial on comparison analysis. It is based on the total communication probabilities instead of interaction number. object@netP$prob contains the interaction probabilities.  

The density plot was made using Matlab code. I do not have R codes for now. But you can plot the gene expression using violin plot such as in Seurat package. 

For the NMF-related errors, please check previous issue #16

**Comment by gt7901b** [comment]
thanks, Suoqin, this is very helpful. If I want to check for specific L-R pair, e.g., PDCD1-CD274,is there a way to do that?
Also, how to overlay the numbers in the circle plot like Fg.4B in the paper?    thanks for your time

**Comment by sqjin** [comment]
Hi @gt7901b , you can do it by object@net$prob[,,"PDCD1-CD274"].

computeNetSimilarityPairwise is for the comparison analysis of multiple datasets, and the 'functional' only works when the two datasets have the identical cell types. 

You can check previous issue #8 for the plot
