### ISSUE TITLE
Question about object@netP$prob

### ISSUE THREAD

**Issue by franciscogrisanti** [sqjin/CellChat#91]
Hey @sqjin  👍  Thanks for making this package, it's pretty good and interesting!

I'm wondering about object@netP$prob, I have two genotypes (two diff cellchat objects) and just want to calculate a ratio of change between a specific celltype population across different pathways. 

When I try to extract **object@netP$prob**, I see this -->

<img width="971" alt="image" src="https://user-images.githubusercontent.com/35009018/101684889-b552b300-3a2c-11eb-95f6-db798216617f.png">
 
I want to extract the average prob of CM using for example the TGFB pathway, but I'm not sure if I should grab the entire row or column? 

Best,

Francisco

**Comment by sqjin** [comment]
Hi @franciscogrisanti , prob is a three-dimensional array, where the first dimension represents sources, the second dimension represent targets and the third dimension represent signaling pathways. For each signaling pathway, it can be either sent or received by certain population, and thus you might want to summarize both sending and receiving signaling.  object@netP$prob['CM', ,'TGFb'] gives the sending signaling from CM and object@netP$prob[ , 'CM', 'TGFb'] gives the receiving signaling from CM.    You might can also consider to reshape the array into data frame for easier subsetting by `      df.net <- reshape2::melt(prob, value.name = "prob")
      colnames(df.net)[1:3] <- c("source","target","pathway_name")`

**Comment by franciscogrisanti** [comment]
Thank you @sqjin! That was exactly what I needed. 

I notice that the probabilities are always quite low, the max is around 0.002 for both genotypes. 

Do you doing directly a ratio of change would make sense? Or would you think that first I need to scale them?

**Comment by sqjin** [comment]
Hi @franciscogrisanti , all the values are relative although they look small. You cannot scale them again when comparing with different datasets or networks.

**Comment by franciscogrisanti** [comment]
Thanks @sqjin 

They are relative to what? 

Best,

Francisco
