### ISSUE TITLE
question on netAnalysis_river() options

### ISSUE THREAD

**Issue by conradlab** [sqjin/CellChat#92]
Hello - thanks for the wonderful package. We've found that it seems to work well for our biological system, and identifies most of the known signaling relationships among our cell types, as well as plenty of interesting novel signaling relationships.

I have two questions on the netAnalysis_river plots. First, if we leave do.order=F, how is the signaling pathway order determined?

Second, I can see that the "cutoff" option is a useful way of trimming the pathways that are displayed, based on signaling "strength". Can you suggest a way to make a river plot that would only display the pathways that named by the user; for instance just show "MK" and "IL2" regardless of the strength?

Thanks!

**Comment by sqjin** [comment]
Hi @conradlab , thanks for your interest in our tool.  If setting do.order = F, the signaling pathways are ordered based on the order in our database. 

The current function does not support the subsetting of pathways. I can add such a control parameter next week. Thanks for your patience.

**Comment by conradlab** [comment]
thank you @sqjin! Another suggestion for future development would be a function that would allow the user to summarize the results from rankNet(..,mode="comparison") in terms of cell types. For instance, in some situations it could be useful to make a statement like, "we observed that the biggest changes in information flow were in signaling between cell type X and cell type Y".

**Comment by sqjin** [comment]
Thanks @conradlab for the great suggestion. I might can create another function for plotting the interactions changes between any two cell types.  Will do it during this holiday break. Please let me know if you have any other suggestions/comments.

**Comment by sqjin** [comment]
Hi @conradlab , we have significantly updated the tutorial on comparison analysis. For some other suggestions, I will take care later. Thanks!
