### ISSUE TITLE
why the step with function netEmbedding error occurred 

### ISSUE THREAD

**Issue by honghh2018** [sqjin/CellChat#94]
Hi @sqjin ,
 I also follow you vignette to install the cellchat and umap-learn with pip install using python where lcoate in /usr/local/bin/python.
 Nevertheless, it occurred error like below: 
cellchat = netEmbedding(cellchat, type = "structural")
Error in runUMAP(Similarity, min.dist = 0.3, n.neighbors = k) : 
  Cannot find UMAP, please install through pip (e.g. pip install umap-learn or reticulate::py_install(packages = 'umap-learn')).
 So, what should i do for this issue, any kindly help would be appreciated.
 Best,
 Hanshuihong

**Comment by honghh2018** [comment]
I use the reticulate::py_install(packages = 'umap-learn') to install the umap-learn,but it get error like below:
![image](https://user-images.githubusercontent.com/41668708/102217094-0d028a00-3f17-11eb-9c0d-af87712f0fea.png)
It had me lots of time wasted, and make me crazy.

**Comment by sqjin** [comment]
Hi @honghh2018 , you can install the umap by `pip install umap-learn` in the terminal. Please check the original package documentation if you have any issues.  After you install it, if you still cannot find umap in R, then you can try use_python to specify your python version.
