### ISSUE TITLE
Error in netAnalysis_signalingRole()

### ISSUE THREAD

**Issue by aditisk** [sqjin/CellChat#95]
Hi @sqjin,

I am trying to follow the steps from the vignette on my own data. I successfully completed all the steps prior to the error message received below:

`cellchat <- netAnalysis_signalingRole(cellchat, slot.name = "netP") # the slot 'netP' means the inferred intercellular communication network of signaling pathways
Error in if (nrow(adjmatrix) != ncol(adjmatrix)) { : 
  argument is of length zero`

How can I fix this ? Thanks.

**Comment by sqjin** [comment]
Hi @aditisk , I am sorry I have no idea on this error. Can you run the source codes to check the potential issues?

**Comment by aditisk** [comment]
Hi @sqjin, thank you for the prompt response. I re-ran the steps and it works okay for me now. I think I was missing the line mentioned below.

`cellchat <- computeCommunProbPathway(cellchat)`
