### ISSUE TITLE
Retrieve info about enrich pathways

### ISSUE THREAD

**Issue by EAC-T** [sqjin/CellChat#97]
Hello,

I did the joint analysis and ended up with enriched pathway like PDL1, I was wondering how can I get the info about what ligands and receptors are involved in the pathway and where is it coming from. I have around 12 cell types, can I find which cell type is contributing to the pathway being enriched?

Also, how can I get the info on what is in the pathways here?
netVisual_circle(ctlchat@net$count,vertex.size = groupSize, weight.scale = T, label.edge= T, 
                 edge.label.cex = 0.8, vertex.label.cex = 1)
I can see that there are 10 pathways between 2 different cell types and I'm wondering how to find what they are?

One more thing please, If I want to do the netVisual_circle but between a smaller subsets of cell types, like between only 2 of them?

Thank you a lot,

**Comment by sqjin** [comment]
Hi @EAC-T , you can simply plot the PDL1 network to show the involved cell types. You can also extract the network by cellchat@netP$prob[ , , "PDL1"], which gives a matrix with row being sources and columns being targets. 

For the second question, I suggest to use the netVisual_bubble to check the enriched pathways between different cell types at this moment. I will update CellChat with more detailed documentation and more functions for useful searching in next week. Please stay tuned! 

Please check the parameter in the function netVisual_circle, where you can control the sources and targets.

**Comment by EAC-T** [comment]
Hi @sqjin ,

I was just wondering if you got the chance to update the documentation? 
We are almost done with the paper and we want to use cellchat for our analysis.

Thank you a lot,

**Comment by sqjin** [comment]
Hi @EAC-T , we have significantly updated our tutorial recently. Please check it out.
