### ISSUE TITLE
question about the the summary of cell-cell communications

### ISSUE THREAD

**Issue by MMriran** [sqjin/CellChat#99]
Hi, sqjin, thank you for your cellchat which I had applied in my work. Now I had another questions about the cellchat.Can I get the summary cell-cell communications in cellchat?  For example, I want to measure the relationship between the T cells and B cells based on the ligand-receptor pairs and then get a value which stand for the strength of correlation coefficients.  Just like the following picture shown:
![image](https://user-images.githubusercontent.com/51091889/103165691-d7826880-4855-11eb-9c3c-c17be48e1981.png)
![image](https://user-images.githubusercontent.com/51091889/103165693-df420d00-4855-11eb-8988-80ac201816d4.png)

**Comment by sqjin** [comment]
Hi @MMriran , there might be different ways to measure the relationship between different cell types. Can you please provide a reference of the above figure?

**Comment by MMriran** [comment]
thank you for your replay. [https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3541365](url)  This is the link.

**Comment by sqjin** [comment]
@MMriran Thanks. I will look into it and get back to you this week.

**Comment by sqjin** [comment]
Hi @MMriran , I have significantly updated the documentation and tutorial although I have not got chance to look at the paper you mentioned.
